import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import fs from 'node:fs';
const require=createRequire(import.meta.url),ts=require('typescript');
require.extensions['.ts']=(module,file)=>module._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,file);
const {resolveBomDrawingMetadata: resolve}=require('../lib/production-drawing-metadata.ts');
const row=(id,parentId,recordId='doc',extra={})=>({id,recordId,bom:{parentId,itemDescription:id,drawingNumber:'BOM-'+id,componentRevision:'R02'},...extra});
test('metadata comes together from the document BOM root',()=>assert.deepEqual(resolve([row('root',null),row('child','root')],'doc'),{title:'root',drawingNumber:'BOM-root',revisionLabel:'R02'}));
test('project parent does not hide document root',()=>assert.equal(resolve([row('root','project')],'doc').title,'root'));
test('source linkage supports shared occurrences',()=>assert.equal(resolve([row('root',null,'other',{sourceRecordIds:['doc']})],'doc').title,'root'));
test('unrelated document cannot provide metadata',()=>assert.equal(resolve([row('root',null,'other')],'doc').title,''));
test('ambiguous roots remain unresolved',()=>assert.equal(resolve([row('a',null),row('b',null)],'doc').title,''));
