import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import fs from 'node:fs';
const require=createRequire(import.meta.url),ts=require('typescript');
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(module,file)=>module._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText,file);
require.extensions['.css']=()=>{};
// A small hook harness exercises table interactions without a browser runtime.
const state=[];let cursor=0;
const Module=require('node:module'),originalLoad=Module._load;
Module._load=function(id,...args){const value=originalLoad.call(this,id,...args);return id==='react'?{...value,useState(initial){const index=cursor++;if(!(index in state))state[index]=initial;return [state[index],next=>{state[index]=typeof next==='function'?next(state[index]):next}];}}:value};
const Component=require('../app/v2/trr-review-details.tsx').default;
Module._load=originalLoad;
const render=props=>{cursor=0;return Component(props)};
const {renderToStaticMarkup}=require('react-dom/server');
const draft={documentType:'report',summary:'',uncertainties:[],drawingNumber:'',revisionLabel:'',items:[{id:'one',recordId:'doc',area:'trr',title:'조립 주의사항',detail:'원본 조건',source:'p.1',trrSection:'조립',trrKind:'current'}]};
const nodes=root=>!root||typeof root!=='object'?[]:Array.isArray(root)?root.flatMap(nodes):[root,...nodes(root.props?.children)];
test('TRR reuses shared selection controls and keeps the table read only',()=>{
 let applied,cancelled=false;
 const props={draft,version:2,disabled:false,dirty:false,confirmedCount:1,documentName:'원본.pdf',onApply:ids=>{applied=ids},onCancel:()=>{cancelled=true}};
 const tree=render(props),html=renderToStaticMarkup(tree);
 assert.match(html,/전체 검토/);assert.match(html,/선택 0개 확정/);assert.match(html,/확정 취소 반영/);
 assert.doesNotMatch(html,/textarea|전체 수정|조회 모드|p\.1/);
 const actions=tree=>nodes(tree).find(n=>n.props?.areaLabel==='TRR');
 assert.equal(actions(tree).props.confirmDisabled,true);
 actions(tree).props.onSelectAll(true);
 actions(render(props)).props.onConfirm();assert.deepEqual(applied,['one']);
 actions(render(props)).props.onCancel();assert.equal(cancelled,true);
 assert.equal(actions(render({...props,dirty:true})).props.confirmDisabled,true);
 nodes(render(props)).find(n=>n.props?.label==='반영 목차').props.onChange(JSON.stringify('1. 일반 기술정보'));
 assert.equal(actions(render(props)).props.selectedCount,0);
 assert.match(renderToStaticMarkup(render(props)),/필터 조건에 맞는 항목이 없습니다/);
});
