import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import fs from 'node:fs';
const require=createRequire(import.meta.url),ts=require('typescript');
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(module,file)=>module._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText,file);
require.extensions['.css']=()=>{};
// A small hook harness exercises table interactions without a browser runtime.
const state=[];let cursor=0;
const Module=require('node:module'),originalLoad=Module._load;
Module._load=function(id,...args){const value=originalLoad.call(this,id,...args);return id==='react'?{...value,useState(initial){const index=cursor++;if(!(index in state))state[index]=initial;return [state[index],next=>{state[index]=typeof next==='function'?next(state[index]):next}];}}:value};
const Component=require('../app/v2/trr-review-details.tsx').default;
Module._load=originalLoad;
const render=props=>{cursor=0;return Component(props)};
const {renderToStaticMarkup}=require('react-dom/server');
const draft={documentType:'report',summary:'',uncertainties:[],drawingNumber:'',revisionLabel:'',items:[{id:'one',recordId:'doc',area:'trr',title:'조립 주의사항',detail:'원본 조건',source:'p.1',trrSection:'조립',trrKind:'current'}]};
const nodes=root=>!root||typeof root!=='object'?[]:Array.isArray(root)?root.flatMap(nodes):[root,...nodes(root.props?.children)];
test('review editor exposes numbered destinations and blocks reflection until changes are saved',()=>{
 let changed;const props={draft,version:2,disabled:false,dirty:false,onChange:d=>{changed=d},onApply:()=>{}};
 const tree=render(props),html=renderToStaticMarkup(tree);assert.match(html,/5. 조립/);assert.match(html,/검토 대기/);assert.doesNotMatch(html,/출처|p\.1/);assert.equal(nodes(tree).filter(n=>n.type==='textarea').length,0);
 nodes(tree).find(n=>n.type==='button'&&n.props.className==='production-edit-all').props.onClick();
 const editable=render(props);
 nodes(editable).find(n=>n.props?.['aria-label']==='1번 본문').props.onChange({target:{value:'보완한 조건'}});
 assert.equal(changed.items[0].detail,'보완한 조건');assert.equal(draft.items[0].detail,'원본 조건');
 assert.equal(changed.items[0].source,'p.1');
 const applyButton=tree=>nodes(tree).filter(n=>n.type==='button').at(-1);
 const edited=render({...props,draft:changed,dirty:true});assert.equal(applyButton(edited).props.disabled,true);
 const applied=render({...props,appliedVersion:2,wordVersion:3});assert.match(renderToStaticMarkup(applied),/V003.*반영 완료/);assert.equal(applyButton(applied).props.disabled,true);
 nodes(applied).find(n=>n.props?.label==='반영 목차').props.onChange(JSON.stringify('1. 일반 기술정보'));
 assert.match(renderToStaticMarkup(render(props)),/필터 조건에 맞는 항목이 없습니다/);
 nodes(render(props)).find(n=>n.type==='button'&&n.props.children==='필터 초기화').props.onClick();
 assert.match(renderToStaticMarkup(render(props)),/조립 주의사항/);
});
