"use client";
import {useEffect,useState} from 'react';
import {readApiJson} from '../../lib/read-api-json';
import {suppliedDecision,type SuppliedData,type SuppliedFact,type SuppliedChoice} from '../../lib/customer-supplied-contract';
import CustomerSuppliedTable from './customer-supplied-table';
import './customer-supplied.css';
export default function CustomerSuppliedReview({projectId,recordId,version,facts,area,disabled,onApplied}:{projectId:string;recordId:string;version:number;facts:SuppliedFact[];area:'summary'|'supplied'|'bom';disabled:boolean;onApplied:()=>void}){
 const [data,setData]=useState<SuppliedData|null>(null),[selected,setSelected]=useState<string[]>([]),[choices,setChoices]=useState<Record<string,SuppliedChoice>>({}),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[reload,setReload]=useState(0);
 useEffect(()=>{const c=new AbortController();setSelected([]);setConfirmed(false);setError('');setData(null);fetch(`/api/projects/${projectId}/customer-supplied`,{signal:c.signal,cache:'no-store'}).then(async r=>{const d=await readApiJson(r) as SuppliedData&{error?:string};if(!r.ok)throw Error(d.error);setData(d);const values:Record<string,SuppliedChoice>={};for(const f of facts){const target=f.replacementChain.at(-1)||f.itemNumber,entry=d.entries.find(e=>e.section===f.section&&e.itemNumber===target),parents=d.assemblies.filter(a=>a.customerNumbers.includes(f.section)),parts=d.parts.filter(p=>p.customerNumbers.includes(target));values[f.id]={itemId:f.id,parentPartId:entry?.parentPartId??(parents.length===1?parents[0].id:''),partId:entry?.partId??(parts.length===1?parts[0].id:''),unit:''};}setChoices(values)}).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[projectId,recordId,version,reload,area]);
 const apply=async()=>{if(!data||area==='summary'||busy)return;setBusy(true);setError('');try{const r=await fetch(`/api/projects/${projectId}/customer-supplied`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({recordId,version,area,customerConfirmed:confirmed,fingerprint:data.fingerprint,choices:selected.map(id=>choices[id])})}),d=await readApiJson(r);if(!r.ok)throw Error(d.error);setSelected([]);setConfirmed(false);onApplied();setReload(n=>n+1);setNotice(`${d.changed}건 반영했습니다.`)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const change=(id:string,patch:Partial<SuppliedChoice>)=>{setChoices(c=>({...c,[id]:{...c[id],...patch}}));setConfirmed(false)};
 const rows=facts.map(f=>({...f,changeLabel:data?suppliedDecision(f,data.entries):'조회 중'}));
 const locked=disabled||busy||!data?.canReview;
 return <section className="supplied-review">
 {error&&<p role="alert" className="wv2-form-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {area==='summary'?<p>추출 {facts.length}건 · 원본 추가 {facts.filter(f=>f.change==='added').length}건 · 삭제 {facts.filter(f=>f.change==='removed').length}건 · 대체 {facts.filter(f=>f.change==='replaced').length}건. 변경 내용을 고객에게 확인한 뒤 각 탭에서 확정하세요.</p>:<div className="review-decision review-confirm-actions"><label><input type="checkbox" disabled={locked} checked={selected.length===facts.length&&facts.length>0} onChange={e=>{setSelected(e.target.checked?facts.map(f=>f.id):[]);setConfirmed(false)}}/>전체 선택</label><label><input type="checkbox" disabled={locked||!selected.length} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>고객 확인 완료</label><button disabled={locked||!selected.length||!confirmed} onClick={()=>void apply()}>선택 {selected.length}개 {area==='bom'?'BOM 반영':'확정'}</button></div>}
 <CustomerSuppliedTable rows={rows} selected={selected} onSelect={area==='summary'?undefined:ids=>{setSelected(ids);setConfirmed(false)}} disabled={locked}
 extraHeader={area==='bom'?<><th>연결 SECTION ASSY</th><th>연결 PART</th><th>수량·단위 확인</th><th>반영 상태</th></>:undefined}
 extraCell={area==='bom'?r=>{const choice=choices[r.id],fact=facts.find(f=>f.id===r.id)!,target=fact.replacementChain.at(-1)||fact.itemNumber,entry=data?.entries.find(e=>e.section===r.section&&e.itemNumber===target),part=data?.parts.find(p=>p.id===choice?.partId),edge=data?.edges.find(e=>e.parentPartId===choice?.parentPartId&&e.childPartId===choice?.partId);return <><td><select aria-label={`${r.itemNumber} 연결 ASSY`} value={choice?.parentPartId??''} disabled={locked} onChange={e=>change(r.id,{parentPartId:e.target.value})}><option value="">SECTION 확인 필요</option>{data?.assemblies.map(a=><option key={a.id} value={a.id}>{a.partNumber} · {a.name}</option>)}</select></td><td>{fact.change==='replaced'&&<span>대체 대상: {target}</span>}<select aria-label={`${r.itemNumber} 연결 PART`} value={choice?.partId??''} disabled={locked} onChange={e=>change(r.id,{partId:e.target.value})}><option value="">고객번호 검색 / 신규 생성</option>{data?.parts.map(p=><option key={p.id} value={p.id}>{p.partNumber} · {p.name}</option>)}</select></td><td><span>{edge?`기존 ${edge.quantity??'미확인'} ${edge.unit}`:'기존 연결 없음'} → {fact.change==='removed'?'삭제':r.quantity}</span>{!part&&!edge&&fact.change!=='removed'&&<input aria-label={`${r.itemNumber} 확인한 수량 단위`} placeholder="단위 확인 후 입력" value={choice?.unit??''} disabled={locked} onChange={e=>change(r.id,{unit:e.target.value})}/>}</td><td>{entry?.recordId===recordId&&entry.version===version?entry.bomApplied?'반영 완료':'BOM 미반영':'사급품 확정 필요'}</td></>}:undefined}/>
 </section>;
}
