"use client";

import {useEffect,useMemo,useState} from "react";
import {Check,ChevronRight,Clock3,ShieldCheck} from "lucide-react";
import "./gate-work-panel.css";

type Project={id:string;name:string};
type Task={id:string;wbsCode:string;name:string;taskType:string;assigneeName?:string;roleCode?:string};
type GateDecision="PASS"|"CONDITIONAL_PASS"|"REJECT"|"DEFER"|null;
type Gate={taskId:string;gateCode:string;name:string;plannedDate?:string;status:string;progress:number;decision?:GateDecision;note?:string;decidedAt?:number;decidedBy?:string;activityCount:number;completedActivityCount:number;missingRequiredDeliverables:number;openGateIssues:number};
type GateWarnings={message?:string;incompleteTasks?:unknown[];missingDeliverables?:unknown[]}|null;

const gateCompleted=(decision?:GateDecision)=>decision==="PASS"||decision==="CONDITIONAL_PASS";
const decisionLabel=(decision?:GateDecision,status?:string)=>decision==="PASS"?"승인 완료":decision==="CONDITIONAL_PASS"?"조건부 승인":decision==="REJECT"?"반려":decision==="DEFER"?"보류":status==="review"?"검토 중":"예정";
const decisionClass=(decision?:GateDecision,status?:string)=>decision==="PASS"?"passed":decision==="CONDITIONAL_PASS"?"conditional":decision==="REJECT"?"rejected":decision==="DEFER"?"deferred":status==="review"?"current":"planned";
const gateOrder=["G1","G2","G3","G4","G5","G6"];

export function GateWorkPanel({project,tasks,onOpenTask}:{project:Project|null;tasks:Task[];onOpenTask:(taskId:string)=>void}){
  const [gates,setGates]=useState<Gate[]>([]),[expanded,setExpanded]=useState(""),[note,setNote]=useState(""),[saving,setSaving]=useState(false),[notice,setNotice]=useState("");
  const load=async()=>{if(!project){setGates([]);return}try{const response=await fetch(`/api/projects/${project.id}/gates`,{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"Gate 정보를 불러오지 못했습니다.");const next=(data.gates??[]) as Gate[];setGates(next);const current=gateOrder.find(code=>!gateCompleted(next.find(item=>item.gateCode===code)?.decision))||"G6";setExpanded(value=>value||current)}catch(reason){setNotice(reason instanceof Error?reason.message:"Gate 정보를 불러오지 못했습니다.")}};
  useEffect(()=>{setExpanded("");setNote("");setNotice("");void load()},[project?.id]);
  const items=useMemo(()=>gateOrder.map(code=>gates.find(item=>item.gateCode===code)).filter((item):item is Gate=>Boolean(item)),[gates]);
  const currentCode=gateOrder.find(code=>!gateCompleted(items.find(item=>item.gateCode===code)?.decision))||"COMPLETE";
  const decide=async(gate:Gate,decision:Exclude<GateDecision,null>)=>{if(!project||saving)return;if(decision!=="PASS"&&!note.trim()){setNotice("PASS 이외 결정에는 검토 의견을 입력해 주세요.");return}setSaving(true);setNotice("");try{const response=await fetch(`/api/projects/${project.id}/gates`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({taskId:gate.taskId,decision,note:note.trim()})});const result=await response.json() as {error?:string;warnings?:GateWarnings};if(!response.ok)throw new Error(result.error||"Gate 결정을 저장하지 못했습니다.");setNote("");setNotice(decision==="PASS"?(result.warnings?.message?`${gate.gateCode} 승인 완료 · ${result.warnings.message}`:`${gate.gateCode} 승인 완료`):decision==="CONDITIONAL_PASS"?`${gate.gateCode} 조건부 승인 완료`:`${gate.gateCode} 결정을 저장했습니다.`);await load();window.dispatchEvent(new CustomEvent("v2-project-data-updated",{detail:{projectId:project.id}}))}catch(reason){setNotice(reason instanceof Error?reason.message:"Gate 결정을 저장하지 못했습니다.")}finally{setSaving(false)}};
  if(!project)return <div className="wv2-gate-panel-empty"><ShieldCheck size={26}/><b>프로젝트를 선택해 주세요.</b></div>;
  return <div className="wv2-gate-panel"><header><div><small>STAGE · GATE</small><h3>Gate 진행·승인</h3></div><span>{currentCode==="COMPLETE"?"G1~G6 승인 완료":`현재 ${currentCode}`}</span></header><div className="wv2-gate-steps">{items.map((gate,index)=>{const open=expanded===gate.gateCode,current=gate.gateCode===currentCode,completed=gateCompleted(gate.decision),task=tasks.find(item=>item.id===gate.taskId),approvalOwner=task?.assigneeName||task?.roleCode||gate.decidedBy||"미지정";return <article className={`${decisionClass(gate.decision,gate.status)} ${current?"is-current":""}`} key={gate.taskId}><div className="wv2-gate-step-line"><i>{completed?<Check size={14}/>:current?<Clock3 size={14}/>:index+1}</i><button onClick={()=>setExpanded(open?"":gate.gateCode)}><span><b>{gate.gateCode}</b><em>{decisionLabel(gate.decision,gate.status)}</em></span><small>승인 담당 {approvalOwner}{gate.plannedDate?` · 계획 ${gate.plannedDate}`:""}</small></button><button className="detail" title="Gate Task 상세" onClick={()=>onOpenTask(gate.taskId)}><ChevronRight size={17}/></button></div>{open&&<section className="wv2-gate-step-detail"><dl><div><dt>활동</dt><dd>{gate.completedActivityCount}/{gate.activityCount}</dd></div><div><dt>필수 산출물 미충족</dt><dd>{gate.missingRequiredDeliverables}</dd></div><div><dt>열린 이슈</dt><dd>{gate.openGateIssues}</dd></div><div><dt>최근 승인자</dt><dd>{gate.decidedBy||"—"}</dd></div></dl>{gate.note&&<p className="wv2-gate-last-note">최근 의견 · {gate.note}</p>}{current&&!completed&&<><textarea rows={3} value={note} onChange={event=>setNote(event.target.value)} placeholder="조건부 승인·반려·보류 시 검토 의견을 입력하세요."/><div className="wv2-gate-actions"><button disabled={saving} onClick={()=>decide(gate,"DEFER")}>보류</button><button disabled={saving} onClick={()=>decide(gate,"REJECT")}>반려</button><button disabled={saving} onClick={()=>decide(gate,"CONDITIONAL_PASS")}>조건부</button><button className="primary" disabled={saving} onClick={()=>decide(gate,"PASS")}>PASS</button></div></>}</section>}</article>})}</div>{!items.length&&<div className="wv2-gate-panel-empty"><ShieldCheck size={26}/><b>등록된 Gate Task가 없습니다.</b></div>}{notice&&<p className="wv2-gate-panel-notice">{notice}</p>}</div>;
}
