"use client";

import {useState} from "react";
import {AlertTriangle,ChevronRight,FileStack,GanttChartSquare,LayoutDashboard,MessageSquareText,Pencil,Sparkles,Table2} from "lucide-react";
import {useSharedDashboard} from "./dashboard-data-store";
import {useSharedProjectDashboard} from "./project-dashboard-data-store";
import "./gate-dashboard-patch.css";

type Project={id:string;code:string;name:string;customerName?:string;partnerId?:string;projectTypeName?:string;startDate:string;endDate:string;status:string};
type Task={id:string;wbsCode:string;name:string;kind:string;status:string;progress:number;plannedEnd?:string;assigneeName?:string};
type Gate={taskId:string;gateCode:string;name:string;plannedDate?:string;status:string;progress:number;decision?:string|null;activityCount:number;completedActivityCount:number;missingRequiredDeliverables:number;openGateIssues:number;delayRate?:number;healthScore?:number};
type ProjectMetric={id:string;progress:number;taskCount:number;completedCount:number;reviewCount:number;delayedCount:number;missingDeliverables:number;openIssues:number;issueCount?:number;riskCount?:number;collaborationCount?:number;gateSummary?:{currentGate:string;decision?:string|null;passedCount:number;nextReviewDate?:string|null};gates?:Gate[]};
type GateHealthItem={gateCode:string;projectCount:number;healthScore:number;averageDelayRate:number;distribution:{normal:number;under5:number;under10:number;under20:number;under30:number;over30:number};normalCount?:number;delayedCount?:number;activityProgress:number;missingDeliverables:number;openIssues:number;conditional:number;rejected:number;deferred:number};
type GatePortfolio={customers:Array<{customerName:string;total:number;stages:Array<{gateCode:string;count:number}>;healthy?:number;delayed:number}>;gateHealth:GateHealthItem[]};
type ContextItem={id:string;kind:"프로젝트"|"WBS";title:string;meta:string};
type AiRequest={source:string;prompt:string;contextItems:ContextItem[]};
export type PortfolioProjectPreset={statuses?:string[];partnerIds?:string[];passedGates?:string[];attention?:""|"healthy"|"delayed"|"issues"};

const decisionLabel=(value?:string|null)=>value==="PASS"?"승인 완료":value==="CONDITIONAL_PASS"?"조건부 승인":value==="REJECT"?"반려":value==="DEFER"?"보류":value==="review"||value==="REVIEW"?"검토 중":value==="COMPLETE"?"G6 승인 완료":"예정";
const decisionClass=(value?:string|null)=>value==="PASS"?"passed":value==="CONDITIONAL_PASS"?"conditional":value==="REJECT"?"rejected":value==="DEFER"?"deferred":value==="review"||value==="REVIEW"?"review":"planned";
const severityLabel=(value?:string)=>value==="critical"?"심각":value==="high"?"높음":value==="medium"?"보통":"낮음";
const delayedTask=(task:Task)=>task.status!=="completed"&&Boolean(task.plannedEnd)&&task.plannedEnd!<new Date().toISOString().slice(0,10);

function GateFlow({gates,onOpen}:{gates:Gate[];onOpen?:(taskId:string)=>void}){
  const items=["G1","G2","G3","G4","G5","G6"].map(code=>gates.find(item=>item.gateCode===code)||{taskId:code,gateCode:code,name:code+" Gate",status:"planned",progress:0,decision:null,activityCount:0,completedActivityCount:0,missingRequiredDeliverables:0,openGateIssues:0});
  return <div className="wv2-gate-flow">{items.map((gate,index)=><div className="wv2-gate-node-wrap" key={gate.gateCode}><button className={decisionClass(gate.decision||gate.status)} onClick={()=>onOpen?.(gate.taskId)} disabled={!onOpen}><b>{gate.gateCode}</b><span>{decisionLabel(gate.decision||gate.status)}</span><small>{gate.completedActivityCount}/{gate.activityCount} 활동 · 산출물 미흡 {gate.missingRequiredDeliverables}</small></button>{index<items.length-1&&<i/>}</div>)}</div>;
}

export function GatePortfolioDashboard({projects,onOpenProject,onOpenProjectList}:{projects:Project[];onOpenProject:(project:Project)=>void;onOpenProjectList:(preset:PortfolioProjectPreset)=>void}){
  const dashboard=useSharedDashboard<{projects?:ProjectMetric[];gatePortfolio?:GatePortfolio}>();
  const metrics=dashboard?.projects??[],portfolio=dashboard?.gatePortfolio??null,[customer,setCustomer]=useState("");
  const customerOptions=Array.from(new Set(projects.map(item=>item.customerName||"거래처 미지정"))).sort(),visible=customer?projects.filter(item=>(item.customerName||"거래처 미지정")===customer):projects,metricFor=(id:string)=>metrics.find(item=>item.id===id);
  const active=visible.filter(item=>item.status==="active"),completed=visible.filter(item=>item.status==="completed"),preparing=visible.filter(item=>item.status==="preparing"),delayed=visible.filter(item=>(metricFor(item.id)?.delayedCount||0)>0),healthy=active.filter(item=>(metricFor(item.id)?.delayedCount||0)===0),openIssues=visible.reduce((sum,item)=>sum+(metricFor(item.id)?.openIssues||0),0),issueRiskProjects=[...visible].sort((a,b)=>((metricFor(b.id)?.issueCount||0)+(metricFor(b.id)?.riskCount||0)+(metricFor(b.id)?.collaborationCount||0))-((metricFor(a.id)?.issueCount||0)+(metricFor(a.id)?.riskCount||0)+(metricFor(a.id)?.collaborationCount||0))||(metricFor(b.id)?.openIssues||0)-(metricFor(a.id)?.openIssues||0)).slice(0,10);
  const issueRiskMax=Math.max(1,...issueRiskProjects.flatMap(item=>{const metric=metricFor(item.id);return [metric?.issueCount||0,metric?.riskCount||0,metric?.collaborationCount||0]}));
  const gateCodes=["G1","G2","G3","G4","G5","G6"],cumulative=gateCodes.map(gateCode=>({gateCode,count:visible.filter(item=>metricFor(item.id)?.gates?.some(gate=>gate.gateCode===gateCode&&gate.decision==="PASS")).length})),maxGate=Math.max(1,...cumulative.map(item=>item.count)),distribution=[...gateCodes,"COMPLETE"].map(gateCode=>({gateCode,count:visible.filter(item=>metricFor(item.id)?.gateSummary?.currentGate===gateCode).length})),maxDistribution=Math.max(1,...distribution.map(item=>item.count));
  const visibleGateHealth=gateCodes.map(gateCode=>{const passed=visible.flatMap(project=>(metricFor(project.id)?.gates??[]).filter(gate=>gate.gateCode===gateCode&&gate.decision==="PASS"));const scores=passed.map(gate=>Number(gate.healthScore??100));const normalCount=passed.filter(gate=>(Number(gate.delayRate)||0)<=0).length;return {gateCode,projectCount:passed.length,healthScore:passed.length?Math.round(scores.reduce((sum,value)=>sum+value,0)/passed.length):100,normalCount,delayedCount:passed.length-normalCount}});
  const presetBase:PortfolioProjectPreset=customer?{partnerIds:Array.from(new Set(visible.map(item=>item.partnerId).filter((id):id is string=>Boolean(id))))}:{};
  return <section className="wv2-portfolio-dashboard"><header><div><small>EXECUTIVE PROJECT PORTFOLIO</small><h1>전사 프로젝트 대시보드</h1><p>Gate 승인·현재 단계·고객사별 지연과 이슈를 실제 저장 데이터로 확인합니다.</p></div><label className="wv2-gate-customer-filter"><span>거래처</span><select value={customer} onChange={event=>setCustomer(event.target.value)}><option value="">전체 거래처</option>{customerOptions.map(name=><option value={name} key={name}>{name}</option>)}</select></label></header>
    <div className="summary"><button type="button" onClick={()=>onOpenProjectList(presetBase)}><span>전체 프로젝트</span><b>{visible.length}</b><small>진행 {active.length} · 준비 {preparing.length}</small></button><button type="button" className="healthy" onClick={()=>onOpenProjectList({...presetBase,statuses:["active"],attention:"healthy"})}><span>정상 프로젝트</span><b>{healthy.length}</b><small>진행 프로젝트 중 지연 없음</small></button><button type="button" className={delayed.length?"risk":""} onClick={()=>onOpenProjectList({...presetBase,attention:"delayed"})}><span>지연 프로젝트</span><b>{delayed.length}</b><small>즉시 확인 필요</small></button><button type="button" onClick={()=>onOpenProjectList({...presetBase,passedGates:["G6"]})}><span>G6 승인 완료</span><b>{cumulative.find(item=>item.gateCode==="G6")?.count||0}</b><small>프로젝트 완료 {completed.length}</small></button><button type="button" className={openIssues?"warn":""} onClick={()=>onOpenProjectList({...presetBase,attention:"issues"})}><span>열린 이슈·리스크</span><b>{openIssues}</b><small>{visible.filter(item=>(metricFor(item.id)?.openIssues||0)>0).length}개 프로젝트</small></button></div>
    <div className="wv2-gate-portfolio"><section><header><b>Gate별 누적 통과</b><span>PASS 결정 기준</span></header><div className="wv2-gate-bars">{cumulative.map(item=><div key={item.gateCode}><b>{item.gateCode}</b><i><span style={{width:(item.count/maxGate*100)+"%"}}/></i><strong>{item.count}건</strong></div>)}</div></section><section><header><b>현재 Gate 분포</b><span>프로젝트당 1개 단계</span></header><div className="wv2-gate-distribution" aria-label="현재 Gate별 프로젝트 분포">{distribution.map(item=>{const height=item.count?Math.max(4,item.count/maxDistribution*100):0;return <article key={item.gateCode} aria-label={(item.gateCode==="COMPLETE"?"완료":item.gateCode)+" "+item.count+"개 프로젝트"}><strong>{item.count}</strong><i><span style={{height:height+"%"}}/></i><b>{item.gateCode==="COMPLETE"?"완료":item.gateCode}</b></article>})}</div></section></div>
    <div className="charts"><section className="wv2-gate-operations"><header><b>Gate별 지연 건강도</b><span className="wv2-gate-health-guide" title="건강도는 각 Gate를 실제 PASS한 프로젝트의 지연율 점수를 평균합니다. 지연율 = 지연일수 ÷ 계획기간."><b>건강도 기준 :</b> 지연 없음 100 · 5%미만 90 · 10%미만 80 · 20%미만 60 · 30%미만 40 · 30%이상 20</span></header><div className="wv2-gate-health">{visibleGateHealth.map(item=><div key={item.gateCode} role="button" tabIndex={0} title={`${item.gateCode} 통과 프로젝트 ${item.projectCount}개 보기`} style={{cursor:"pointer"}} onClick={()=>onOpenProjectList({...presetBase,passedGates:[item.gateCode]})} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();onOpenProjectList({...presetBase,passedGates:[item.gateCode]})}}}><div className="health-score"><b>{item.gateCode}</b><strong>{item.healthScore}점</strong></div><div className="health-meter"><span style={{width:`${Math.max(0,Math.min(100,item.healthScore))}%`}}/></div><small>통과 {item.projectCount}개 · 정상 {item.normalCount} · 지연 {item.delayedCount}</small></div>)}</div></section><section className="wv2-issue-risk-chart-section"><header><b>프로젝트 이슈·리스크·협조 현황</b><span>Worst TOP 10 · 열린 항목 합계 순</span></header><div className="wv2-issue-risk-histogram" role="img" aria-label="프로젝트별 이슈 리스크 협조 건수 Worst Top 10">{issueRiskProjects.map(project=>{const metric=metricFor(project.id),issueCount=metric?.issueCount||0,riskCount=metric?.riskCount||0,collaborationCount=metric?.collaborationCount||0,totalCount=issueCount+riskCount+collaborationCount;const bars=[{key:"issue",label:"이슈",value:issueCount},{key:"risk",label:"리스크",value:riskCount},{key:"collaboration",label:"협조",value:collaborationCount}];return <button type="button" className="wv2-issue-risk-histogram-item" data-total={totalCount} key={project.id} onClick={()=>onOpenProject(project)} title={`${project.name} · 총 ${totalCount} · 이슈 ${issueCount} · 리스크 ${riskCount} · 협조 ${collaborationCount}`}><div className="wv2-issue-risk-bar-group">{bars.map(bar=><div className={`wv2-issue-risk-bar ${bar.key}`} key={bar.key}><strong>{bar.value}</strong><i><span style={{height:bar.value?`${Math.max(7,bar.value/issueRiskMax*100)}%`:"0%"}}/></i><small>{bar.label}</small></div>)}</div><b>{project.name}</b></button>})}</div></section></div>
    <section className="wv2-gate-customer-matrix"><header><b>거래처 × 현재 Gate</b><span>각 Gate 안에 정상/지연 프로젝트를 함께 표시</span></header><div className="wv2-gate-matrix-table"><header><span>거래처</span>{gateCodes.map(code=><span key={code}>{code}</span>)}<span>G6 승인완료</span></header>{(portfolio?.customers??[]).filter(item=>!customer||item.customerName===customer).map(item=>{const stageMap=new Map(item.stages.map(stage=>[stage.gateCode,stage.count]));const customerProjects=visible.filter(project=>(project.customerName||"거래처 미지정")===item.customerName);return <div className="row" key={item.customerName}><b>{item.customerName}</b>{gateCodes.map(code=>{const gateProjects=customerProjects.filter(project=>metricFor(project.id)?.gateSummary?.currentGate===code),normal=gateProjects.filter(project=>(metricFor(project.id)?.delayedCount||0)===0).length,late=gateProjects.length-normal;return <span className="wv2-gate-status-cell" key={code}>{gateProjects.length?<><b>{gateProjects.length}</b><small><em>{normal} 정상</em><em className={late?"risk":""}>{late} 지연</em></small></>:"-"}</span>})}<span>{stageMap.get("COMPLETE")||"-"}</span></div>})}</div></section>
  </section>;
}

export function GateProjectDashboard({project,tasks,onOpenTask,onNavigate,onEdit,onAi}:{project:Project|null;tasks:Task[];onOpenTask:(taskId:string,tab?:"detail"|"deliverable"|"issue")=>void;onNavigate:(destination:"gantt"|"wbs"|"documents"|"issues"|"reports")=>void;onEdit:()=>void;onAi:(request:AiRequest)=>void}){
  type ProjectDashboardData={issues:Array<{id:string;taskId?:string;issueType?:string;title:string;status:string;severity?:string;ownerName?:string;dueDate?:string}>;deliverables:Array<{id:string;taskId?:string;taskCode?:string;taskName?:string;name:string;status:string;required?:boolean|number;revisionCount?:number|string}>;gates:Gate[]};
  const dashboard=useSharedProjectDashboard<ProjectDashboardData>(project?.id),issues=dashboard?.issues??[],deliverables=dashboard?.deliverables??[],gates=dashboard?.gates??[];
  if(!project)return <div className="wv2-project-empty"><LayoutDashboard size={34}/><h2>프로젝트를 선택해 주세요.</h2></div>;
  const leaf=tasks.filter(task=>task.kind==="task"),completed=leaf.filter(task=>task.status==="completed").length,progress=Math.round(leaf.reduce((sum,task)=>sum+task.progress,0)/Math.max(1,leaf.length)),delayed=leaf.filter(delayedTask),openIssues=issues.filter(issue=>!["resolved","closed","completed"].includes(issue.status)),registered=deliverables.filter(item=>Number(item.revisionCount||0)>0),missingRequired=deliverables.filter(item=>Boolean(item.required)&&Number(item.revisionCount||0)===0),approvalPending=registered.filter(item=>!["approved","completed"].includes(String(item.status||"").toLowerCase())),upcoming=leaf.filter(task=>task.status!=="completed"&&task.plannedEnd).sort((a,b)=>(a.plannedEnd||"").localeCompare(b.plannedEnd||"")).slice(0,6),currentGate=gates.find(gate=>gate.decision!=="PASS")||gates.at(-1),passedCount=gates.filter(gate=>gate.decision==="PASS").length;
  const priorityTasks=(delayed.length?delayed:upcoming).slice(0,5),severityRank:Record<string,number>={critical:0,high:1,medium:2,low:3},priorityIssues=[...openIssues].filter(issue=>issue.issueType!=="collaboration").sort((a,b)=>(severityRank[a.severity||"low"]??4)-(severityRank[b.severity||"low"]??4)||(a.dueDate||"9999-12-31").localeCompare(b.dueDate||"9999-12-31")).slice(0,5),priorityDeliverables=[...missingRequired].sort((a,b)=>(a.taskCode||"").localeCompare(b.taskCode||"",undefined,{numeric:true})).slice(0,5);
  const contextItems:ContextItem[]=[{id:project.id,kind:"프로젝트",title:project.name,meta:"진척률 "+progress+"% · Gate 통과 "+passedCount+"/6 · 현재 "+(currentGate?.gateCode||"미지정")+" · 지연 "+delayed.length+" · 열린 이슈 "+openIssues.length+" · 필수 미등록 "+missingRequired.length}];
  return <section className="wv2-project-dashboard"><header><div><small>PROJECT DASHBOARD</small><h1>{project.name}</h1><p>{project.code} · {project.customerName||"거래처 미지정"} · {project.startDate} — {project.endDate}</p></div><div className="wv2-dashboard-actions"><button onClick={onEdit}><Pencil size={18}/>프로젝트 정보 수정</button><button onClick={()=>onAi({source:"프로젝트 대시보드",prompt:"현재 프로젝트의 Gate 통과 현황, 지연 Task, 시험 이슈와 필수 산출물을 기준으로 경영진 브리핑을 작성해줘.",contextItems})}><Sparkles size={18}/>AI 프로젝트 브리핑</button></div></header>
    <div className="summary"><article><span>전체 진척률</span><b>{progress}%</b></article><article><span>Gate 통과</span><b>{passedCount}/6</b></article><article className={currentGate&&currentGate.decision!=="PASS"?"warn":""}><span>현재 Gate</span><b>{currentGate?.gateCode||"—"}</b><small>{decisionLabel(currentGate?.decision||currentGate?.status)}</small></article><article className={delayed.length?"risk":""}><span>지연 Task</span><b>{delayed.length}</b></article><article className={missingRequired.length?"warn":""}><span>등록 산출물</span><b>{registered.length}/{deliverables.length}</b><small>필수 미등록 {missingRequired.length} · 승인 대기 {approvalPending.length}</small></article><article><span>열린 이슈</span><b>{openIssues.length}</b></article></div>
    <section className="wv2-project-gate-panel"><header><div><b>G1~G6 Stage-Gate 진행 현황</b><span>Gate는 진행 단계의 검토·승인 기록으로 운영합니다.</span></div><em>{currentGate?.plannedDate?"다음 Review "+currentGate.plannedDate:"Review 일정 확인 필요"}</em></header><GateFlow gates={gates} onOpen={taskId=>onOpenTask(taskId,"detail")}/></section>
    <nav className="wv2-project-shortcuts" aria-label="프로젝트 바로가기"><button onClick={()=>onNavigate("gantt")}><GanttChartSquare size={18}/><span><b>프로젝트 간트</b><small>일정 흐름 확인</small></span></button><button onClick={()=>onNavigate("wbs")}><Table2 size={18}/><span><b>WBS·실적</b><small>지연 {delayed.length}</small></span></button><button onClick={()=>onNavigate("documents")}><FileStack size={18}/><span><b>문서·산출물</b><small>필수 미등록 {missingRequired.length}</small></span></button><button onClick={()=>onNavigate("issues")}><AlertTriangle size={18}/><span><b>이슈·리스크</b><small>열린 항목 {openIssues.length}</small></span></button><button onClick={()=>onNavigate("reports")}><MessageSquareText size={18}/><span><b>보고·회의</b><small>보고자료 확인</small></span></button></nav>
    <div className="body dashboard-action-grid"><section><header><b>확인 필요한 일정</b><span>{delayed.length?delayed.length+"건 지연":"다가오는 일정 "+upcoming.length+"건"}</span></header>{priorityTasks.map(task=><button key={task.id} onClick={()=>onOpenTask(task.id,"detail")}><span><b>{task.wbsCode} {task.name}</b><small>{task.assigneeName||"미배정"} · 종료 {task.plannedEnd||"미정"}</small></span><em>{task.progress}%</em></button>)}{!priorityTasks.length&&<p className="wv2-dashboard-empty">확인 필요한 일정이 없습니다.</p>}<footer><button onClick={()=>onNavigate("wbs")}>전체 일정 보기 <ChevronRight size={18}/></button></footer></section>
      <section><header><b>열린 이슈·리스크</b><span>{openIssues.length}건</span></header>{priorityIssues.map(issue=><button key={issue.id} onClick={()=>issue.taskId?onOpenTask(issue.taskId,"issue"):onNavigate("issues")}><span><b>{issue.title}</b><small>{issue.ownerName||"담당자 미지정"}{issue.dueDate?" · 기한 "+issue.dueDate:""}</small></span><em className={issue.severity==="critical"||issue.severity==="high"?"risk":""}>{severityLabel(issue.severity)}</em></button>)}{!priorityIssues.length&&<p className="wv2-dashboard-empty">열린 이슈·리스크가 없습니다.</p>}<footer><button onClick={()=>onNavigate("issues")}>전체 이슈 보기 <ChevronRight size={18}/></button></footer></section>
      <section><header><b>미등록 필수 산출물</b><span>{missingRequired.length}건</span></header>{priorityDeliverables.map(item=><button key={item.id} onClick={()=>item.taskId?onOpenTask(item.taskId,"deliverable"):onNavigate("documents")}><span><b>{item.name}</b><small>{item.taskCode||"Task 미연결"}{item.taskName?" · "+item.taskName:""}</small></span><em className="warn">미등록</em></button>)}{!priorityDeliverables.length&&<p className="wv2-dashboard-empty">미등록 필수 산출물이 없습니다.</p>}<footer><button onClick={()=>onNavigate("documents")}>전체 산출물 보기 <ChevronRight size={18}/></button></footer></section></div>
  </section>;
}