"use client";

import {useEffect,useMemo,useState} from "react";
import {Box,FileText,GitCompareArrows,Layers3,Link2,Save,Sparkles,Trash2,X} from "lucide-react";
import {ConnectedAiPanel,type ContextItem} from "./connected-ai-workspaces";
import {setBomCompareSeed} from "./bom-compare-launch";
import "./part-detail-panel.css";

type Part={id:string;partNumber:string;name:string;partType:string;spec?:string;unit:string;revision:string;status:string;standardCost?:number;rollupCost?:number};
type BomRow={id:string;parentPartId:string;parentNumber:string;parentName:string;childPartId:string;childNumber:string;childName:string;quantity:number;unit:string;sortOrder:number;note?:string};
type Category={id:string;code:string;name:string;isActive:number;sortOrder:number};
type CategoryLink={partId:string;categoryId:string};
type Revision={revisionSeq:number;revision:string;changeNote?:string;createdBy?:string;createdAt?:number};
type DeleteCheck={canDelete?:boolean;reason?:string};
type Tab="info"|"bom"|"revision"|"relation"|"ai";
type OpenDetail={partId:string;tab?:Tab;context?:ContextItem};

const roleLabel=(value:string)=>value==="TOP_ITEM"||value==="PRODUCT"?"Top Item":value==="ASSEMBLY"||value==="SUB_ASSEMBLY"?"Assembly":"Part";
const normalizeRole=(value:string)=>value==="TOP_ITEM"||value==="PRODUCT"?"TOP_ITEM":value==="ASSEMBLY"||value==="SUB_ASSEMBLY"?"ASSEMBLY":"PART";
const when=(value?:number)=>value?new Date(value*1000).toLocaleString("ko-KR",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}):"—";
const partAiContext=(part:Part,structured:boolean):ContextItem=>({id:part.id,kind:structured?"BOM":"PART",title:`${part.partNumber} · ${part.name}`,meta:[`Item Role ${part.partType}`,`현재 Rev.${part.revision}`,part.spec?`사양 ${part.spec}`:"",structured?"BOM 구조 있음":"BOM 구조 없음"].filter(Boolean).join(" · ")});

export function PartDetailPanelHost({onOpenBomCompare}:{onOpenBomCompare?:(leftRootId:string,rightRootId?:string)=>void}={}){
  const [open,setOpen]=useState<OpenDetail|null>(null);
  useEffect(()=>{const handler=(event:Event)=>{const detail=(event as CustomEvent<OpenDetail>).detail;if(detail?.partId)setOpen(detail)};window.addEventListener("v2-open-part-detail",handler);return()=>window.removeEventListener("v2-open-part-detail",handler)},[]);
  if(!open)return null;
  return <PartDetailPanel request={open} onClose={()=>setOpen(null)} onOpenBomCompare={onOpenBomCompare}/>;
}

function PartDetailPanel({request,onClose,onOpenBomCompare}:{request:OpenDetail;onClose:()=>void;onOpenBomCompare?:(leftRootId:string,rightRootId?:string)=>void}){
  const [part,setPart]=useState<Part|null>(null),[bom,setBom]=useState<BomRow[]>([]),[categories,setCategories]=useState<Category[]>([]),[categoryId,setCategoryId]=useState(""),[revisions,setRevisions]=useState<Revision[]>([]);
  const [tab,setTab]=useState<Tab>(request.tab||"info"),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[deleting,setDeleting]=useState(false),[notice,setNotice]=useState("");
  const [name,setName]=useState(""),[itemRole,setItemRole]=useState("PART"),[spec,setSpec]=useState(""),[unit,setUnit]=useState("EA"),[status,setStatus]=useState("active");
  const [aiItems,setAiItems]=useState<ContextItem[]>(request.context?[request.context]:[]),[aiKey,setAiKey]=useState(Date.now()),[selectedRevisionSeqs,setSelectedRevisionSeqs]=useState<number[]>([]);
  const load=async()=>{setLoading(true);setNotice("");try{const [dataResponse,settingsResponse]=await Promise.all([fetch("/api/product-data",{cache:"no-store"}),fetch("/api/product-data/parts",{cache:"no-store"})]);const data=await dataResponse.json(),settings=await settingsResponse.json();if(!dataResponse.ok)throw new Error(data.error||"PART 정보를 불러오지 못했습니다.");if(!settingsResponse.ok)throw new Error(settings.error||"PART 기준정보를 불러오지 못했습니다.");const found=(data.parts??[]).find((row:Part)=>row.id===request.partId) as Part|undefined;if(!found)throw new Error("PART를 찾지 못했습니다.");setPart(found);setBom(data.bom??[]);setCategories((settings.categories??[]).filter((row:Category)=>Number(row.isActive)===1));setCategoryId((settings.categoryLinks??[]).find((row:CategoryLink)=>row.partId===request.partId)?.categoryId||"");setName(found.name||"");setItemRole(normalizeRole(found.partType));setSpec(found.spec||"");setUnit(found.unit||"EA");setStatus(found.status||"active");const structured=(data.bom??[]).some((row:BomRow)=>row.parentPartId===found.id);if(!request.context)setAiItems([partAiContext(found,structured)]);try{const revisionResponse=await fetch(`/api/product-data/bom-revisions?rootPartId=${encodeURIComponent(found.id)}`,{cache:"no-store"});const revisionData=await revisionResponse.json();setRevisions(revisionResponse.ok?(revisionData.revisions??[]):[])}catch{setRevisions([])}}catch(reason){setNotice(reason instanceof Error?reason.message:"PART 정보를 불러오지 못했습니다.")}finally{setLoading(false)}};
  useEffect(()=>{setTab(request.tab||"info");setAiItems(request.context?[request.context]:[]);setAiKey(Date.now());setSelectedRevisionSeqs([]);void load()},[request.partId,request.tab,request.context]);
  const children=useMemo(()=>bom.filter(row=>row.parentPartId===request.partId).sort((a,b)=>a.sortOrder-b.sortOrder),[bom,request.partId]);
  const parents=useMemo(()=>bom.filter(row=>row.childPartId===request.partId),[bom,request.partId]);
  const selectedRevisions=useMemo(()=>revisions.filter(revision=>selectedRevisionSeqs.includes(revision.revisionSeq)),[revisions,selectedRevisionSeqs]);
  const toggleRevision=(revisionSeq:number)=>setSelectedRevisionSeqs(current=>current.includes(revisionSeq)?current.filter(value=>value!==revisionSeq):[...current,revisionSeq]);
  const save=async()=>{if(!part||saving||!name.trim())return;setSaving(true);setNotice("");try{const response=await fetch("/api/product-data/parts",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({partId:part.id,name,itemRole,categoryId,spec,unit,status})});const result=await response.json();if(!response.ok)throw new Error(result.error||"PART 정보를 저장하지 못했습니다.");setNotice("PART 정보를 저장했습니다.");window.dispatchEvent(new CustomEvent("v2-part-updated",{detail:{partId:part.id}}));await load()}catch(reason){setNotice(reason instanceof Error?reason.message:"PART 정보를 저장하지 못했습니다.")}finally{setSaving(false)}};
  const removePart=async()=>{if(!part||deleting)return;setDeleting(true);setNotice("");try{const checkResponse=await fetch("/api/product-data/delete",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"check-part",partId:part.id})});const check=await checkResponse.json() as DeleteCheck;if(!checkResponse.ok||!check.canDelete)throw new Error(check.reason||"이 PART는 삭제할 수 없습니다.");if(!window.confirm(`${part.partNumber} · ${part.name}\n\nPART Master를 삭제할까요?\n삭제 후 복구할 수 없습니다.`))return;const response=await fetch("/api/product-data/delete",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"delete-part",partId:part.id})});const result=await response.json() as DeleteCheck;if(!response.ok)throw new Error(result.reason||"PART를 삭제하지 못했습니다.");window.dispatchEvent(new CustomEvent("v2-part-updated",{detail:{partId:part.id,deleted:true}}));window.dispatchEvent(new CustomEvent("jsolution:product-data-refresh"));onClose()}catch(reason){setNotice(reason instanceof Error?reason.message:"PART를 삭제하지 못했습니다.")}finally{setDeleting(false)}};
  const openBom=()=>{if(!part)return;window.dispatchEvent(new CustomEvent("v2-open-part-bom",{detail:{partId:part.id}}));onClose()};
  const openRevisionAi=()=>{if(!part||!selectedRevisions.length)return;const items:ContextItem[]=selectedRevisions.map(revision=>({id:`${part.id}:${revision.revisionSeq}`,kind:"BOM Revision",title:`${part.partNumber} / Rev.${revision.revision}`,meta:[part.name,part.spec?`사양 ${part.spec}`:"",revision.changeNote||"BOM 구조 저장",revision.createdBy||"등록자 미상",when(revision.createdAt)].filter(Boolean).join(" · ")}));setAiItems(items);setAiKey(Date.now());setTab("ai")};
  const openRevisionCompare=()=>{if(!part||selectedRevisions.length!==2||!onOpenBomCompare)return;const ordered=[...selectedRevisions].sort((a,b)=>a.revisionSeq-b.revisionSeq);setBomCompareSeed({rootPartId:part.id,leftRevisionSeq:ordered[0].revisionSeq,rightRevisionSeq:ordered[1].revisionSeq});onOpenBomCompare(part.id);onClose()};
  const tabs:[Tab,string][]=[["info","기본정보"],["bom","BOM"],["revision","Revision"],["relation","연관정보"],["ai","AI 대화"]];
  return <aside className="wv2-panel wide wv2-part-detail-panel">
    <div className="wv2-resize"/>
    <header><div><small>PART MASTER</small><h2>{part?`${part.partNumber} · ${part.name}`:"PART 상세"}</h2><span>{part?`${roleLabel(part.partType)} · Rev.${part.revision}`:"PART 정보를 불러오는 중입니다."}</span></div><div><button onClick={onClose} aria-label="PART 상세 닫기"><X size={19}/></button></div></header>
    <nav>{tabs.map(([key,label])=><button key={key} className={tab===key?"active":""} onClick={()=>setTab(key)}>{label}</button>)}</nav>
    <section className="wv2-panel-body wv2-part-detail-body">{loading?<div className="wv2-part-detail-empty"><Box size={28}/><b>PART 정보를 불러오는 중…</b></div>:!part?<div className="wv2-part-detail-empty"><Box size={28}/><b>{notice||"PART를 찾을 수 없습니다."}</b></div>:<>
      {notice&&<p className="wv2-part-detail-notice">{notice}</p>}
      {tab==="info"&&<div className="wv2-part-info-tab"><section className="summary"><div><span>PART Code</span><b>{part.partNumber}</b></div><div><span>Revision</span><b>Rev.{part.revision}</b></div><div><span>BOM</span><b>{children.length?`구조 있음 · ${children.length}개 직하위`:"구조 없음"}</b></div></section><label><span>품명 *</span><input value={name} onChange={event=>setName(event.target.value)}/></label><div className="two"><label><span>Item Role</span><select value={itemRole} onChange={event=>setItemRole(event.target.value)}><option value="TOP_ITEM">Top Item</option><option value="ASSEMBLY">Assembly</option><option value="PART">Part</option></select></label><label><span>부품 유형</span><select value={categoryId} onChange={event=>setCategoryId(event.target.value)}><option value="">선택 안 함</option>{categories.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></label></div><label><span>사양</span><input value={spec} onChange={event=>setSpec(event.target.value)} placeholder="규격 · 재질 · 사양"/></label><div className="two"><label><span>단위</span><input value={unit} onChange={event=>setUnit(event.target.value)}/></label><label><span>상태</span><select value={status} onChange={event=>setStatus(event.target.value)}><option value="active">사용</option><option value="inactive">사용 안 함</option></select></label></div><div className="wv2-part-info-actions"><button className="danger" disabled={deleting} onClick={()=>void removePart()}><Trash2 size={16}/>{deleting?"확인 중…":"PART 삭제"}</button><button className="save" disabled={saving||deleting||!name.trim()} onClick={()=>void save()}><Save size={16}/>{saving?"저장 중…":"변경사항 저장"}</button></div></div>}
      {tab==="bom"&&<div className="wv2-part-bom-tab"><section className="summary"><article><Layers3 size={20}/><div><span>직하위 구성</span><b>{children.length}개</b></div></article><article><Link2 size={20}/><div><span>상위 사용처</span><b>{parents.length}개</b></div></article></section><button className="open-bom" onClick={openBom}><Layers3 size={17}/>BOM 편집기에서 열기</button><h3>하위 구성</h3>{children.length?children.map(row=><article className="row" key={row.id}><div><b>{row.childNumber}</b><span>{row.childName}</span></div><em>{row.quantity} {row.unit}</em></article>):<p className="empty">아직 하위 BOM 구조가 없습니다.</p>}<h3>상위 사용처</h3>{parents.length?parents.map(row=><article className="row" key={row.id}><div><b>{row.parentNumber}</b><span>{row.parentName}</span></div><em>사용 중</em></article>):<p className="empty">이 PART를 사용하는 상위 BOM이 없습니다.</p>}</div>}
      {tab==="revision"&&<div className="wv2-part-revision-tab"><header><div><GitCompareArrows size={19}/><span><b>BOM Revision History</b><small>AI 대화 또는 BOM 비교에 사용할 Revision을 선택합니다.</small></span></div></header>{revisions.length?revisions.map((revision,index)=><article key={`${revision.revisionSeq}-${revision.revision}`} className={selectedRevisionSeqs.includes(revision.revisionSeq)?"selected":""}><input type="checkbox" checked={selectedRevisionSeqs.includes(revision.revisionSeq)} onChange={()=>toggleRevision(revision.revisionSeq)}/><strong>Rev.{revision.revision}</strong><div><b>{revision.changeNote||(index===revisions.length-1?"Initial BOM baseline":"BOM 구조 저장")}</b><small>{revision.createdBy||"등록자 미상"} · {when(revision.createdAt)}</small></div></article>):<p className="empty">저장된 BOM Revision 이력이 없습니다.</p>}{selectedRevisionSeqs.length>0&&<div className="wv2-part-revision-actions"><span>{selectedRevisionSeqs.length}개 Revision 선택</span><button onClick={openRevisionAi}><Sparkles size={16}/>AI 대화</button><button disabled={selectedRevisionSeqs.length!==2||!onOpenBomCompare} onClick={openRevisionCompare}><GitCompareArrows size={16}/>BOM 비교</button></div>}</div>}
      {tab==="relation"&&<div className="wv2-part-relation-tab"><section><FileText size={21}/><div><b>연관 도면</b><span>Primary Drawing 및 참조 도면 연결 영역</span></div><em>준비 중</em></section><section><Layers3 size={21}/><div><b>BOM 사용 관계</b><span>상위 {parents.length}개 · 하위 {children.length}개</span></div><em>연결됨</em></section><section><Link2 size={21}/><div><b>설계변경 · 품질 · Workflow</b><span>PART 기준 연관 객체를 한곳에서 확인합니다.</span></div><em>확장 예정</em></section></div>}
      {tab==="ai"&&<div className="wv2-part-ai-tab">{aiItems.length?<ConnectedAiPanel project={null} draftRequest={{key:aiKey,source:"PART · BOM 상세",prompt:aiItems.length>1?"선택한 BOM Revision들의 핵심 변경점과 영향, 검토 필요사항을 비교해줘":"",contextItems:aiItems}}/>:<div className="wv2-part-detail-empty"><Sparkles size={26}/><b>AI 문맥을 준비하는 중…</b></div>}</div>}
    </>}</section>
  </aside>;
}
