"use client";

import {useEffect,useState,type FormEvent} from "react";
import {Plus,RefreshCw,Settings,Trash2,X} from "lucide-react";
import "./part-bom-settings-workspace.css";

type Category={id:string;code:string;name:string;isActive:number;sortOrder:number};
type NumberSetting={prefix:string;separator:string;digits:number;nextSequence:number;allowManual:number};
type Data={categories:Category[];numberSetting:NumberSetting};
const emptySetting:NumberSetting={prefix:"P",separator:"-",digits:6,nextSequence:1,allowManual:1};

export function PartBomSettingsWorkspace(){
  const [data,setData]=useState<Data>({categories:[],numberSetting:emptySetting});
  const [loading,setLoading]=useState(false),[notice,setNotice]=useState(""),[editing,setEditing]=useState<Partial<Category>|null>(null),[savingNumber,setSavingNumber]=useState(false);
  const load=async()=>{setLoading(true);try{const response=await fetch("/api/product-data/settings",{cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.error||"PART/BOM 기준정보를 불러오지 못했습니다.");setData({categories:result.categories??[],numberSetting:result.numberSetting??emptySetting});setNotice("")}catch(reason){setNotice(reason instanceof Error?reason.message:"PART/BOM 기준정보를 불러오지 못했습니다.")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const saveCategory=async(event:FormEvent)=>{event.preventDefault();if(!editing)return;const response=await fetch("/api/product-data/settings",{method:editing.id?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(editing)});const result=await response.json();if(!response.ok){setNotice(result.error||"부품 유형을 저장하지 못했습니다.");return}setEditing(null);await load();setNotice("부품 유형을 저장했습니다.")};
  const remove=async(row:Category)=>{if(!window.confirm(`'${row.name}' 부품 유형을 삭제할까요?\n사용 중이면 삭제 대신 사용 안 함으로 변경됩니다.`))return;const response=await fetch("/api/product-data/settings",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id:row.id})});const result=await response.json();if(!response.ok){setNotice(result.error||"부품 유형을 삭제하지 못했습니다.");return}await load();setNotice(result.deactivated?"사용 중인 유형이라 사용 안 함으로 변경했습니다.":"부품 유형을 삭제했습니다.")};
  const saveNumber=async()=>{setSavingNumber(true);try{const response=await fetch("/api/product-data/settings",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({entity:"number-setting",...data.numberSetting})});const result=await response.json();if(!response.ok)throw new Error(result.error||"품번 설정을 저장하지 못했습니다.");await load();setNotice("품번 채번 설정을 저장했습니다.")}catch(reason){setNotice(reason instanceof Error?reason.message:"품번 설정을 저장하지 못했습니다.")}finally{setSavingNumber(false)}};
  const number=data.numberSetting;const preview=`${number.prefix}${number.separator}${String(Math.max(1,number.nextSequence||1)).padStart(Math.max(3,number.digits||6),"0")}`;
  return <section className="pbs-settings">
    <header><div><small>PART / BOM MASTER DATA</small><h2>PART · BOM 기준정보</h2><p>부품 유형과 회사 공통 품번 채번 규칙을 관리합니다.</p></div><button onClick={()=>void load()} disabled={loading}><RefreshCw size={17}/>{loading?"불러오는 중":"새로고침"}</button></header>
    {notice&&<p className="pbs-notice">{notice}</p>}
    <div className="pbs-grid">
      <section className="pbs-card"><header><div><small>REFERENCE DATA</small><h3>부품 유형</h3><p>PART 생성 시 참조정보로 선택합니다. BOM 구조와 Item Role에는 영향을 주지 않습니다.</p></div><button className="primary" onClick={()=>setEditing({code:"",name:"",isActive:1,sortOrder:data.categories.length})}><Plus size={16}/>부품 유형 추가</button></header><div className="pbs-table"><header><span>코드</span><span>이름</span><span>정렬</span><span>상태</span><span/></header>{data.categories.map(row=><article key={row.id}><b>{row.code}</b><span>{row.name}</span><span>{row.sortOrder}</span><i className={row.isActive?"active":"inactive"}>{row.isActive?"사용":"사용 안 함"}</i><div><button onClick={()=>setEditing({...row})}>수정</button><button className="danger" onClick={()=>void remove(row)}><Trash2 size={16}/></button></div></article>)}</div></section>
      <section className="pbs-card number"><header><div><small>NUMBERING</small><h3>품번 채번 설정</h3><p>Item Role·부품 유형·BOM Level·Revision과 분리된 회사 공통 순차번호입니다.</p></div></header><div className="pbs-number-form"><label><span>Prefix</span><input value={number.prefix} onChange={e=>setData(current=>({...current,numberSetting:{...current.numberSetting,prefix:e.target.value}}))}/></label><label><span>구분자</span><input value={number.separator} onChange={e=>setData(current=>({...current,numberSetting:{...current.numberSetting,separator:e.target.value}}))}/></label><label><span>자리수</span><input type="number" min={3} max={12} value={number.digits} onChange={e=>setData(current=>({...current,numberSetting:{...current.numberSetting,digits:Number(e.target.value)}}))}/></label><label><span>다음 번호</span><input type="number" min={1} value={number.nextSequence} onChange={e=>setData(current=>({...current,numberSetting:{...current.numberSetting,nextSequence:Number(e.target.value)}}))}/></label><label className="check"><input type="checkbox" checked={Boolean(number.allowManual)} onChange={e=>setData(current=>({...current,numberSetting:{...current.numberSetting,allowManual:e.target.checked?1:0}}))}/><span>품번 직접입력 허용</span></label><div className="pbs-preview"><small>다음 자동 품번</small><strong>{preview}</strong></div><button className="primary save" onClick={()=>void saveNumber()} disabled={savingNumber}>{savingNumber?"저장 중…":"채번 설정 저장"}</button></div></section>
    </div>
    {editing&&<div className="pbs-dialog-backdrop"><form className="pbs-dialog" onSubmit={saveCategory}><header><div><small>PART TYPE REFERENCE</small><h3>{editing.id?"부품 유형 수정":"부품 유형 추가"}</h3></div><button type="button" onClick={()=>setEditing(null)}><X size={18}/></button></header><label><span>코드 *</span><input required value={editing.code||""} onChange={e=>setEditing({...editing,code:e.target.value.toUpperCase().replace(/\s+/g,"_")})}/></label><label><span>이름 *</span><input required value={editing.name||""} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><div className="two"><label><span>정렬 순서</span><input type="number" min={0} value={editing.sortOrder??0} onChange={e=>setEditing({...editing,sortOrder:Number(e.target.value)})}/></label><label><span>사용 여부</span><select value={editing.isActive?"active":"inactive"} onChange={e=>setEditing({...editing,isActive:e.target.value==="active"?1:0})}><option value="active">사용</option><option value="inactive">사용 안 함</option></select></label></div><footer><button type="button" onClick={()=>setEditing(null)}>취소</button><button className="primary" type="submit">저장</button></footer></form></div>}
  </section>;
}
