"use client";
import {useState,type ReactNode} from 'react';
import {ChevronDown,ChevronRight,Layers3} from 'lucide-react';
import PbomEditDialog from './pbom-edit-dialog';
import {collapsedBomIdsAtDepth,type BomFact,type BomRow} from '../../lib/pbom-contract';
const show=(n:number|null)=>n===null?'미확인':Number(n.toFixed(6)).toLocaleString();
const labels={NEW:'NEW · 신규',EXISTING:'기존 부품',NEED_REVIEW:'확인 필요',MANUAL:'내부 추가'};
export default function PbomTable({rows,root,variant="full",editable=false,onEdit,onOpenEditor,renderSource}:{rows:BomRow[];renderSource?:(recordIds:string[])=>ReactNode;variant?:"full"|"review";root?:{id:string;partNumber:string;name:string}|null;editable?:boolean;onEdit?:(id:string,fact:BomFact)=>void|Promise<void>;onOpenEditor?:(id:string)=>void}){
 const [collapsed,setCollapsed]=useState<string[]>([]),[editing,setEditing]=useState(''),[rootCollapsed,setRootCollapsed]=useState(false);
 const hidden=(r:BomRow):boolean=>{let p=r.bom.parentId;const seen=new Set<string>();while(p&&!seen.has(p)){if(collapsed.includes(p))return true;seen.add(p);p=rows.find(x=>x.id===p)?.bom.parentId??null;}return false;};
 const review=variant==='review';
 const selected=rows.find(r=>r.id===editing);
 return <><div className="review-decision pbom-depth-actions" role="group" aria-label={review?"문서 BOM 표시 깊이":"프로젝트 BOM 표시 깊이"}><button type="button" disabled={!rows.length} onClick={()=>{setRootCollapsed(false);setCollapsed(collapsedBomIdsAtDepth(rows,1));}}>1레벨까지 보기</button><button type="button" disabled={!rows.length} onClick={()=>{setRootCollapsed(false);setCollapsed(collapsedBomIdsAtDepth(rows,2));}}>2레벨까지 보기</button><button type="button" disabled={!rows.length} onClick={()=>{setRootCollapsed(false);setCollapsed([]);}}>모두 펼치기</button></div><div className="pbom-table-scroll cswind-data-table"><table className="production-table pbom-tree-table"><thead><tr><th>품번</th><th>구분 / 변경</th>{!review&&<><th>Section</th><th>BOM Level</th></>}<th>{review?'품명 / ASSY 구조':'Item Description'}</th><th>Pos.</th><th>{review?'고객 Item No.':'Item No.'}</th><th>Drawing No.</th><th>CompRev</th><th>Qty Per Unit</th>{!review&&<th>Total Qty / Section</th>}<th>Weight</th>{!review&&<><th>Weight Source / Calculation Basis</th><th>Drawing Availability</th></>}{!review&&<th>출처 자료</th>}{editable&&<th>검토</th>}</tr></thead><tbody>
 {root&&!review&&<tr><td><span className="pbom-tree-label pbom-part-tree-label"><span className="pbom-toggle-slot"><button type="button" disabled={!rows.length} aria-expanded={!rootCollapsed} aria-label={`${root.name} ${rootCollapsed?'펼치기':'접기'}`} onClick={()=>setRootCollapsed(v=>!v)}>{rootCollapsed?<ChevronRight size={18}/>:<ChevronDown size={18}/>}</button></span><Layers3 size={18}/>{onOpenEditor?<button type="button" onClick={()=>onOpenEditor(root.id)}>{root.partNumber}</button>:<strong>{root.partNumber}</strong>}</span></td><td>프로젝트 TOP</td><td>—</td><td>0</td><td>{root.name}</td>{Array.from({length:10},(_,i)=><td key={i}>—</td>)}{editable&&<td/>}</tr>}
 {rows.filter(r=>!(root&&!review&&rootCollapsed)&&!hidden(r)).map(row=>{const b=row.bom,children=rows.some(r=>r.bom.parentId===row.id);return <tr key={row.id}><td>{review?onOpenEditor&&row.partId?<button onClick={()=>onOpenEditor(row.partId!)}>{row.internalPartNumber}</button>:<strong>{row.internalPartNumber||'확정 시 자동채번'}</strong>:<span className="pbom-tree-label pbom-part-tree-label" title={row.path} style={{paddingInlineStart:`${Math.max(0,row.level-(root?0:1))*20}px`}}><span className="pbom-toggle-slot">{children&&<button type="button" aria-expanded={!collapsed.includes(row.id)} aria-label={`${b.itemDescription} ${collapsed.includes(row.id)?'펼치기':'접기'}`} onClick={()=>setCollapsed(v=>v.includes(row.id)?v.filter(id=>id!==row.id):[...v,row.id])}>{collapsed.includes(row.id)?<ChevronRight size={18}/>:<ChevronDown size={18}/>}</button>}</span><span className={`pbom-part-dot ${b.partType==='ASSEMBLY'?'is-assembly':''}`} aria-hidden="true"/>{onOpenEditor&&row.partId?<button type="button" onClick={()=>onOpenEditor(row.partId!)}>{row.internalPartNumber}</button>:<strong>{row.internalPartNumber||'확정 시 자동채번'}</strong>}</span>}</td><td>{labels[row.match??'NEED_REVIEW']}{row.changed?` · ${row.changeLabel||'Revision 변경'}`:''}</td>{!review&&<><td>{b.section||'미확인'}</td><td>{row.level}</td></>}<td title={b.itemDescription}>{review?<span className="pbom-tree-label pbom-review-tree-label" style={{paddingInlineStart:`calc(${Math.max(0,row.level-1)} * var(--v2-action-height))`}}><span className="pbom-toggle-slot">{children&&<button type="button" aria-expanded={!collapsed.includes(row.id)} aria-label={`${b.itemDescription} ${collapsed.includes(row.id)?'펼치기':'접기'}`} onClick={()=>setCollapsed(v=>v.includes(row.id)?v.filter(id=>id!==row.id):[...v,row.id])}>{collapsed.includes(row.id)?<ChevronRight size={18}/>:<ChevronDown size={18}/>}</button>}</span><span className="pbom-node-name">{b.itemDescription}</span></span>:b.itemDescription}</td><td>{b.position||'—'}</td><td>{b.customerItemNumber||'—'}</td><td>{b.drawingNumber||'—'}</td><td>{b.componentRevision||'미확인'}</td><td>{show(b.quantity)} {b.unit}</td>{!review&&<td>{show(row.totalQuantity)} {b.unit}</td>}<td>{show(review?b.weight:row.calculatedWeight)} {b.weightUnit}</td>{!review&&<><td>{row.calculatedWeightSource}</td><td>{b.drawingAvailability}</td></>}{!review&&<td title={row.source}>{renderSource?.(row.sourceRecordIds??[row.recordId])??(row.sourceRecordIds??[row.recordId]).join(', ')}</td>}{editable&&<td><button onClick={()=>setEditing(editing===row.id?'':row.id)}>수정</button></td>}</tr>})}
 {!rows.length&&<tr><td colSpan={(review?9:15)+(editable?1:0)}>표시할 구조화 BOM이 없습니다.</td></tr>}
 </tbody></table></div>
 {selected&&onEdit&&<PbomEditDialog key={selected.id} row={selected} rows={rows} onSave={onEdit} onClose={()=>setEditing('')}/>}
 </>;
}
