"use client";
import {useState,type ReactNode} from 'react';
import {ChevronDown,ChevronRight} from 'lucide-react';
import PbomEditDialog from './pbom-edit-dialog';
import {type BomFact,type BomRow} from '../../lib/pbom-contract';
const show=(n:number|null)=>n===null?'미확인':Number(n.toFixed(6)).toLocaleString();
const labels={NEW:'NEW · 신규',EXISTING:'기존 부품',NEED_REVIEW:'확인 필요',MANUAL:'내부 추가'};
export default function PbomTable({rows,root,variant="full",editable=false,onEdit,onOpenEditor,renderSource}:{rows:BomRow[];renderSource?:(recordIds:string[])=>ReactNode;variant?:"full"|"review";root?:{id:string;partNumber:string;name:string}|null;editable?:boolean;onEdit?:(id:string,fact:BomFact)=>void|Promise<void>;onOpenEditor?:(id:string)=>void}){
 const [collapsed,setCollapsed]=useState<string[]>([]),[editing,setEditing]=useState('');
 const hidden=(r:BomRow):boolean=>{let p=r.bom.parentId;const seen=new Set<string>();while(p&&!seen.has(p)){if(collapsed.includes(p))return true;seen.add(p);p=rows.find(x=>x.id===p)?.bom.parentId??null;}return false;};
 const review=variant==='review';
 const selected=rows.find(r=>r.id===editing);
 return <><div className="pbom-table-scroll cswind-data-table"><table className="production-table pbom-tree-table"><thead><tr><th>내부 품번</th><th>구분 / 변경</th>{!review&&<><th>Section</th><th>BOM Level</th><th>Parent Item / BOM Path</th></>}<th>{review?'품명 / ASSY 구조':'Item Description'}</th><th>Pos.</th><th>{review?'고객 Item No.':'Item No.'}</th><th>Drawing No.</th><th>CompRev</th><th>Qty Per Unit</th>{!review&&<th>Total Qty / Section</th>}<th>Weight</th>{!review&&<><th>Weight Source / Calculation Basis</th><th>Drawing Availability</th></>}{!review&&<th>출처 자료 / 근거</th>}{editable&&<th>검토</th>}</tr></thead><tbody>
 {root&&<tr><td><strong>{root.partNumber}</strong></td><td>프로젝트 TOP</td><td>—</td><td>0</td><td>—</td><td>{root.name}</td><td colSpan={10}>확정한 문서 ASSY를 이 품목 바로 아래에 연결합니다.</td>{editable&&<td/>}</tr>}
 {rows.filter(r=>!hidden(r)).map(row=>{const b=row.bom,children=rows.some(r=>r.bom.parentId===row.id);return <tr key={row.id}><td>{review?onOpenEditor&&row.partId?<button onClick={()=>onOpenEditor(row.partId!)}>{row.internalPartNumber}</button>:<strong>{row.internalPartNumber||'확정 시 자동채번'}</strong>:<span className="pbom-tree-label" style={{paddingInlineStart:`${Math.min(row.level-1,12)*16}px`}}>{children&&<button aria-label={`${b.itemDescription} ${collapsed.includes(row.id)?'펼치기':'접기'}`} onClick={()=>setCollapsed(v=>v.includes(row.id)?v.filter(id=>id!==row.id):[...v,row.id])}>{collapsed.includes(row.id)?<ChevronRight size={18}/>:<ChevronDown size={18}/>}</button>}{onOpenEditor&&row.partId?<button onClick={()=>onOpenEditor(row.partId!)}>{row.internalPartNumber}</button>:<strong>{row.internalPartNumber||'확정 시 자동채번'}</strong>}</span>}</td><td>{labels[row.match??'NEED_REVIEW']}{row.changed?` · ${row.changeLabel||'Revision 변경'}`:''}</td>{!review&&<><td>{b.section||'미확인'}</td><td>{row.level}</td><td title={row.path}>{row.path}</td></>}<td title={b.itemDescription}>{review?<span className="pbom-tree-label" style={{paddingInlineStart:`${Math.min(row.level-1,12)*16}px`}}>{children&&<button aria-label={`${b.itemDescription} ${collapsed.includes(row.id)?'펼치기':'접기'}`} onClick={()=>setCollapsed(v=>v.includes(row.id)?v.filter(id=>id!==row.id):[...v,row.id])}>{collapsed.includes(row.id)?<ChevronRight size={18}/>:<ChevronDown size={18}/>}</button>}{b.itemDescription}</span>:b.itemDescription}</td><td>{b.position||'—'}</td><td>{b.customerItemNumber||'—'}</td><td>{b.drawingNumber||'—'}</td><td>{b.componentRevision||'미확인'}</td><td>{show(b.quantity)} {b.unit}</td>{!review&&<td>{show(row.totalQuantity)} {b.unit}</td>}<td>{show(review?b.weight:row.calculatedWeight)} {b.weightUnit}</td>{!review&&<><td>{row.calculatedWeightSource}</td><td>{b.drawingAvailability}</td></>}{!review&&<td title={row.source}>{renderSource?.(row.sourceRecordIds??[row.recordId])}<span>{row.source}</span></td>}{editable&&<td><button onClick={()=>setEditing(editing===row.id?'':row.id)}>수정</button></td>}</tr>})}
 {!rows.length&&<tr><td colSpan={(review?9:16)+(editable?1:0)}>표시할 구조화 BOM이 없습니다.</td></tr>}
 </tbody></table></div>
 {selected&&onEdit&&<PbomEditDialog key={selected.id} row={selected} rows={rows} onSave={onEdit} onClose={()=>setEditing('')}/>}
 </>;
}
