"use client";
import {useState,type ReactNode} from 'react';
import {ChevronDown,ChevronRight} from 'lucide-react';
import {DRAWING_AVAILABILITY,WEIGHT_SOURCES,type BomFact,type BomRow} from '../../lib/pbom-contract';
const show=(n:number|null)=>n===null?'미확인':Number(n.toFixed(6)).toLocaleString();
const labels={NEW:'NEW · 신규',EXISTING:'기존 부품',NEED_REVIEW:'확인 필요',MANUAL:'내부 추가'};
export default function PbomTable({rows,root,variant="full",editable=false,onEdit,onOpenEditor,renderSource}:{rows:BomRow[];renderSource?:(recordIds:string[])=>ReactNode;variant?:"full"|"review";root?:{id:string;partNumber:string;name:string}|null;editable?:boolean;onEdit?:(id:string,fact:BomFact)=>void;onOpenEditor?:(id:string)=>void}){
 const [collapsed,setCollapsed]=useState<string[]>([]),[editing,setEditing]=useState('');
 const hidden=(r:BomRow):boolean=>{let p=r.bom.parentId;const seen=new Set<string>();while(p&&!seen.has(p)){if(collapsed.includes(p))return true;seen.add(p);p=rows.find(x=>x.id===p)?.bom.parentId??null;}return false;};
 const review=variant==='review';
 const selected=rows.find(r=>r.id===editing);
 return <><div className="pbom-table-scroll cswind-data-table"><table className="production-table pbom-tree-table"><thead><tr><th>내부 품번</th><th>구분 / 변경</th>{!review&&<><th>Section</th><th>BOM Level</th><th>Parent Item / BOM Path</th></>}<th>{review?'품명 / ASSY 구조':'Item Description'}</th><th>Pos.</th><th>{review?'고객 Item No.':'Item No.'}</th><th>Drawing No.</th><th>CompRev</th><th>Qty Per Unit</th>{!review&&<th>Total Qty / Section</th>}<th>Weight</th>{!review&&<><th>Weight Source / Calculation Basis</th><th>Drawing Availability</th></>}<th>출처 자료 / 근거</th>{editable&&<th>검토</th>}</tr></thead><tbody>
 {root&&<tr><td><strong>{root.partNumber}</strong></td><td>프로젝트 TOP</td><td>—</td><td>0</td><td>—</td><td>{root.name}</td><td colSpan={10}>확정한 문서 ASSY를 이 품목 바로 아래에 연결합니다.</td>{editable&&<td/>}</tr>}
 {rows.filter(r=>!hidden(r)).map(row=>{const b=row.bom,children=rows.some(r=>r.bom.parentId===row.id);return <tr key={row.id}><td>{review?onOpenEditor&&row.partId?<button onClick={()=>onOpenEditor(row.partId!)}>{row.internalPartNumber}</button>:<strong>{row.internalPartNumber||'확정 시 자동채번'}</strong>:<span className="pbom-tree-label" style={{paddingInlineStart:`${Math.min(row.level-1,12)*16}px`}}>{children&&<button aria-label={`${b.itemDescription} ${collapsed.includes(row.id)?'펼치기':'접기'}`} onClick={()=>setCollapsed(v=>v.includes(row.id)?v.filter(id=>id!==row.id):[...v,row.id])}>{collapsed.includes(row.id)?<ChevronRight size={18}/>:<ChevronDown size={18}/>}</button>}{onOpenEditor&&row.partId?<button onClick={()=>onOpenEditor(row.partId!)}>{row.internalPartNumber}</button>:<strong>{row.internalPartNumber||'확정 시 자동채번'}</strong>}</span>}</td><td>{labels[row.match??'NEED_REVIEW']}{row.changed?` · ${row.changeLabel||'Revision 변경'}`:''}</td>{!review&&<><td>{b.section||'미확인'}</td><td>{row.level}</td><td title={row.path}>{row.path}</td></>}<td title={b.itemDescription}>{review?<span className="pbom-tree-label" style={{paddingInlineStart:`${Math.min(row.level-1,12)*16}px`}}>{children&&<button aria-label={`${b.itemDescription} ${collapsed.includes(row.id)?'펼치기':'접기'}`} onClick={()=>setCollapsed(v=>v.includes(row.id)?v.filter(id=>id!==row.id):[...v,row.id])}>{collapsed.includes(row.id)?<ChevronRight size={18}/>:<ChevronDown size={18}/>}</button>}{b.itemDescription}</span>:b.itemDescription}</td><td>{b.position||'—'}</td><td>{b.customerItemNumber||'—'}</td><td>{b.drawingNumber||'—'}</td><td>{b.componentRevision||'미확인'}</td><td>{show(b.quantity)} {b.unit}</td>{!review&&<td>{show(row.totalQuantity)} {b.unit}</td>}<td>{show(review?b.weight:row.calculatedWeight)} {b.weightUnit}</td>{!review&&<><td>{row.calculatedWeightSource}</td><td>{b.drawingAvailability}</td></>}<td title={row.source}>{renderSource?.(row.sourceRecordIds??[row.recordId])}<span>{row.source}</span></td>{editable&&<td><button onClick={()=>setEditing(editing===row.id?'':row.id)}>수정</button></td>}</tr>})}
 {!rows.length&&<tr><td colSpan={(review?10:16)+(editable?1:0)}>표시할 구조화 BOM이 없습니다.</td></tr>}
 </tbody></table></div>
 {editable&&selected&&onEdit&&<section className="pbom-fact-editor"><h3>{selected.bom.itemDescription} · 고객 정보 수정</h3><div>{(['section','itemDescription','position','customerItemNumber','drawingNumber','componentRevision','unit','weightUnit'] as const).map((key,index)=><label key={key}>{['Section','Item Description','Pos.','Customer Item No.','Drawing No.','CompRev','수량 단위','중량 단위'][index]}<input value={selected.bom[key]} onChange={e=>onEdit(selected.id,{...selected.bom,[key]:e.target.value})}/></label>)}
 <label>상위 ASSY<select value={selected.bom.parentId??''} onChange={e=>onEdit(selected.id,{...selected.bom,parentId:e.target.value||null})}><option value="">문서 최상위 ASSY</option>{rows.filter(r=>r.id!==selected.id&&r.bom.partType==='ASSEMBLY').map(r=><option key={r.id} value={r.id}>{r.bom.itemDescription}</option>)}</select></label>
 <label>품목 역할<select value={selected.bom.partType} onChange={e=>onEdit(selected.id,{...selected.bom,partType:e.target.value as BomFact['partType']})}><option value="ASSEMBLY">ASSY</option><option value="PART">부품</option></select></label>
 <label>Qty Per Unit<input type="number" min="0" step="any" value={selected.bom.quantity??''} onChange={e=>onEdit(selected.id,{...selected.bom,quantity:e.target.value===''?null:Number(e.target.value)})}/></label>
 <label>직접 표기 중량<input type="number" min="0" step="any" value={selected.bom.weight??''} onChange={e=>onEdit(selected.id,{...selected.bom,weight:e.target.value===''?null:Number(e.target.value)})}/></label>
 <label>중량 근거<select value={selected.bom.weightSource} onChange={e=>onEdit(selected.id,{...selected.bom,weightSource:e.target.value as BomFact['weightSource']})}>{WEIGHT_SOURCES.map(v=><option key={v}>{v}</option>)}</select></label>
 <label>도면 확보 상태<select value={selected.bom.drawingAvailability} onChange={e=>onEdit(selected.id,{...selected.bom,drawingAvailability:e.target.value as BomFact['drawingAvailability']})}>{DRAWING_AVAILABILITY.map(v=><option key={v}>{v}</option>)}</select></label>
 <label><input type="checkbox" checked={selected.bom.childrenComplete} onChange={e=>onEdit(selected.id,{...selected.bom,childrenComplete:e.target.checked})}/>하위 부품 목록 전체 확인</label></div><button onClick={()=>setEditing('')}>편집 접기</button></section>}
 </>;
}
