"use client";

import {useEffect,useMemo,useState} from "react";
import {ChevronRight,Coins,Layers3,Plus,RefreshCw,Search,TableProperties} from "lucide-react";
import "./product-data-workspace.css";

type Part={id:string;partNumber:string;name:string;partType:string;spec?:string;unit:string;revision:string;status:string;standardCost:number;rollupCost:number};
type BomRow={id:string;parentPartId:string;parentNumber:string;parentName:string;childPartId:string;childNumber:string;childName:string;quantity:number;unit:string;sortOrder:number;note?:string};
type CostSheet={id:string;partId:string;partNumber:string;partName:string;version:number;materialCost:number;laborCost:number;overheadCost:number;totalCost:number;note?:string;status:string;createdAt:number;createdBy?:string};
type Data={parts:Part[];bom:BomRow[];costSheets:CostSheet[];numberRule:string};
const money=(value:number)=>new Intl.NumberFormat("ko-KR",{maximumFractionDigits:0}).format(Number(value||0));
const typeLabel=(value:string)=>({ASSEMBLY:"ASSY",FABRIC:"원단",FOAM:"폼",FRAME:"프레임",TRIM:"부자재",PART:"부품"} as Record<string,string>)[value]||value;

function useProductData(){
  const [data,setData]=useState<Data>({parts:[],bom:[],costSheets:[],numberRule:"{TYPE}-{YYYY}-{SEQ4}"}),[loading,setLoading]=useState(true),[notice,setNotice]=useState("");
  const load=async()=>{setLoading(true);try{const response=await fetch("/api/product-data",{cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.error||"제품 데이터를 불러오지 못했습니다.");setData(result);setNotice("")}catch(reason){setNotice(reason instanceof Error?reason.message:"제품 데이터를 불러오지 못했습니다.")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);return {data,loading,notice,setNotice,load};
}

export function ProductDataWorkspace(){
  const {data,loading,notice,setNotice,load}=useProductData();const [tab,setTab]=useState<"part"|"bom">("part"),[query,setQuery]=useState(""),[adding,setAdding]=useState(false),[bomAdding,setBomAdding]=useState(false);
  const [name,setName]=useState(""),[partType,setPartType]=useState("PART"),[spec,setSpec]=useState(""),[unit,setUnit]=useState("EA"),[standardCost,setStandardCost]=useState(0);
  const [parentId,setParentId]=useState(""),[childId,setChildId]=useState(""),[quantity,setQuantity]=useState(1);
  const visible=useMemo(()=>{const q=query.trim().toLowerCase().replace(/\s+/g,"");return data.parts.filter(item=>!q||`${item.partNumber}${item.name}${item.partType}${item.spec||""}`.toLowerCase().replace(/\s+/g,"").includes(q))},[data.parts,query]);
  const parents=useMemo(()=>data.parts.filter(item=>data.bom.some(row=>row.parentPartId===item.id)||item.partType==="ASSEMBLY"),[data.parts,data.bom]);
  const selectedParent=parentId||parents[0]?.id||data.parts.find(item=>item.partType==="ASSEMBLY")?.id||"";
  const bomRows=data.bom.filter(row=>row.parentPartId===selectedParent);
  const createPart=async()=>{if(!name.trim())return;try{const response=await fetch("/api/product-data",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create-part",name,partType,spec,unit,standardCost})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Part를 등록하지 못했습니다.");setNotice(`${result.partNumber} 품번이 자동 생성되었습니다.`);setName("");setSpec("");setStandardCost(0);setAdding(false);await load()}catch(reason){setNotice(reason instanceof Error?reason.message:"Part를 등록하지 못했습니다.")}};
  const addBom=async()=>{if(!selectedParent||!childId)return;try{const response=await fetch("/api/product-data",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"add-bom",parentPartId:selectedParent,childPartId:childId,quantity,unit:data.parts.find(item=>item.id===childId)?.unit||"EA"})});const result=await response.json();if(!response.ok)throw new Error(result.error||"BOM을 등록하지 못했습니다.");setChildId("");setQuantity(1);setBomAdding(false);setNotice("BOM 하위 Part를 등록했습니다.");await load()}catch(reason){setNotice(reason instanceof Error?reason.message:"BOM을 등록하지 못했습니다.")}};
  return <section className="pdw-shell">
    <header className="pdw-head"><div><small>PRODUCT DATA · PART / BOM</small><h1>제품 데이터 관리</h1><p>Part Master와 제품 구조(BOM)를 하나의 기준 데이터로 관리합니다.</p></div><button onClick={()=>void load()}><RefreshCw size={17}/>새로고침</button></header>
    <div className="pdw-kpis"><article><span>전체 Part</span><b>{data.parts.length}</b><small>자동 품번 관리</small></article><article><span>ASSY</span><b>{data.parts.filter(p=>p.partType==="ASSEMBLY").length}</b><small>BOM 상위 품목</small></article><article><span>BOM 연결</span><b>{data.bom.length}</b><small>Parent → Child</small></article><article><span>채번 규칙</span><b className="rule">{data.numberRule}</b><small>중복 방지</small></article></div>
    <nav className="pdw-tabs"><button className={tab==="part"?"active":""} onClick={()=>setTab("part")}><TableProperties size={17}/>Part Master</button><button className={tab==="bom"?"active":""} onClick={()=>setTab("bom")}><Layers3 size={17}/>BOM 구조</button></nav>
    {notice&&<p className="pdw-notice">{notice}</p>}
    {tab==="part"&&<><div className="pdw-toolbar"><label><Search size={17}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="품번, 품명, 사양 검색"/></label><span>{visible.length}개 Part</span><button className="primary" onClick={()=>setAdding(value=>!value)}><Plus size={17}/>Part 등록</button></div>{adding&&<div className="pdw-editor"><div><label>품명 *<input value={name} onChange={e=>setName(e.target.value)} placeholder="예: 친환경 스웨이드 원단"/></label><label>Part 유형<select value={partType} onChange={e=>setPartType(e.target.value)}><option value="PART">부품</option><option value="ASSEMBLY">ASSY</option><option value="FABRIC">원단</option><option value="FOAM">폼</option><option value="FRAME">프레임</option><option value="TRIM">부자재</option></select></label><label>단위<input value={unit} onChange={e=>setUnit(e.target.value)}/></label><label>표준단가<input type="number" min="0" value={standardCost} onChange={e=>setStandardCost(Number(e.target.value))}/></label></div><label>사양<input value={spec} onChange={e=>setSpec(e.target.value)} placeholder="규격·재질·사양"/></label><footer><span>품번은 저장 시 자동 채번됩니다.</span><button onClick={()=>setAdding(false)}>취소</button><button className="primary" disabled={!name.trim()} onClick={createPart}>자동채번 · 등록</button></footer></div>}<div className="pdw-table"><table><thead><tr><th>품번</th><th>품명</th><th>구분</th><th>Revision</th><th>사양</th><th>단위</th><th>표준단가</th><th>BOM Roll-up</th><th>상태</th></tr></thead><tbody>{visible.map(item=><tr key={item.id}><td><b>{item.partNumber}</b></td><td>{item.name}</td><td><span className="kind">{typeLabel(item.partType)}</span></td><td>Rev.{item.revision}</td><td>{item.spec||"—"}</td><td>{item.unit}</td><td className="num">₩ {money(item.standardCost)}</td><td className="num strong">₩ {money(item.rollupCost)}</td><td><span className="status">사용중</span></td></tr>)}</tbody></table>{loading&&<p className="pdw-empty">제품 데이터를 불러오는 중…</p>}</div></>}
    {tab==="bom"&&<><div className="pdw-toolbar"><select value={selectedParent} onChange={e=>setParentId(e.target.value)}>{data.parts.filter(p=>p.partType==="ASSEMBLY"||data.bom.some(row=>row.parentPartId===p.id)).map(item=><option key={item.id} value={item.id}>{item.partNumber} · {item.name}</option>)}</select><span>하위 {bomRows.length}개</span><button className="primary" onClick={()=>setBomAdding(value=>!value)}><Plus size={17}/>하위 Part 추가</button></div>{bomAdding&&<div className="pdw-editor compact"><div><label>하위 Part<select value={childId} onChange={e=>setChildId(e.target.value)}><option value="">선택</option>{data.parts.filter(item=>item.id!==selectedParent&&!bomRows.some(row=>row.childPartId===item.id)).map(item=><option key={item.id} value={item.id}>{item.partNumber} · {item.name}</option>)}</select></label><label>수량<input type="number" min="0.001" step="0.1" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label></div><footer><button onClick={()=>setBomAdding(false)}>취소</button><button className="primary" disabled={!childId} onClick={addBom}>BOM 등록</button></footer></div>}<div className="pdw-bom"><header><div className="root"><Layers3 size={21}/><span><small>TOP ASSEMBLY</small><b>{data.parts.find(item=>item.id===selectedParent)?.partNumber} · {data.parts.find(item=>item.id===selectedParent)?.name}</b></span><strong>₩ {money(data.parts.find(item=>item.id===selectedParent)?.rollupCost||0)}</strong></div></header>{bomRows.map((row,index)=>{const child=data.parts.find(item=>item.id===row.childPartId);return <article key={row.id}><span className="line">{index===bomRows.length-1?"└":"├"}</span><ChevronRight size={17}/><div><b>{row.childNumber}</b><span>{row.childName}</span><small>{child?.spec||"사양 미등록"}</small></div><em>{row.quantity} {row.unit}</em><strong>₩ {money((child?.rollupCost||0)*row.quantity)}</strong></article>})}{!bomRows.length&&<p className="pdw-empty">등록된 BOM 하위 품목이 없습니다.</p>}</div></>}
  </section>
}

export function CostManagementWorkspace(){
  const {data,loading,notice,setNotice,load}=useProductData();const assy=data.parts.filter(item=>item.partType==="ASSEMBLY"||data.bom.some(row=>row.parentPartId===item.id));const [partId,setPartId]=useState(""),[labor,setLabor]=useState(0),[overhead,setOverhead]=useState(0),[note,setNote]=useState("");const activeId=partId||assy[0]?.id||"";const part=data.parts.find(item=>item.id===activeId);const material=Number(part?.rollupCost||part?.standardCost||0),total=material+labor+overhead;const sheets=data.costSheets.filter(item=>item.partId===activeId);
  const save=async()=>{if(!activeId)return;try{const response=await fetch("/api/product-data",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"save-cost",partId:activeId,materialCost:material,laborCost:labor,overheadCost:overhead,note})});const result=await response.json();if(!response.ok)throw new Error(result.error||"원가계산서를 저장하지 못했습니다.");setNotice(`원가계산서 V${result.version}을 저장했습니다.`);setNote("");await load()}catch(reason){setNotice(reason instanceof Error?reason.message:"원가계산서를 저장하지 못했습니다.")}};
  return <section className="pdw-shell cost"><header className="pdw-head"><div><small>COST MANAGEMENT · BOM ROLL-UP</small><h1>원가 관리</h1><p>BOM 기준 재료비를 자동 Roll-up하고 원가계산서 버전을 관리합니다.</p></div><button onClick={()=>void load()}><RefreshCw size={17}/>새로고침</button></header>{notice&&<p className="pdw-notice">{notice}</p>}<div className="pdw-cost-grid"><section><header><b>원가계산 대상</b><select value={activeId} onChange={e=>setPartId(e.target.value)}>{assy.map(item=><option key={item.id} value={item.id}>{item.partNumber} · {item.name}</option>)}</select></header><div className="cost-summary"><article><span>BOM 재료비</span><b>₩ {money(material)}</b><small>BOM 자동 Roll-up</small></article><article><span>가공/노무비</span><b>₩ {money(labor)}</b><input type="number" min="0" value={labor} onChange={e=>setLabor(Number(e.target.value))}/></article><article><span>경비/간접비</span><b>₩ {money(overhead)}</b><input type="number" min="0" value={overhead} onChange={e=>setOverhead(Number(e.target.value))}/></article><article className="total"><span>예상 개발원가</span><b>₩ {money(total)}</b><small>재료비 + 노무비 + 경비</small></article></div><label className="cost-note">원가 메모<textarea rows={4} value={note} onChange={e=>setNote(e.target.value)} placeholder="원가 변경 사유 또는 검토 의견"/></label><button className="primary save-cost" disabled={!activeId} onClick={save}><Coins size={18}/>원가계산서 Version 저장</button></section><section><header><b>BOM 원가 구성</b><span>{data.bom.filter(row=>row.parentPartId===activeId).length}개 구성품</span></header><div className="cost-breakdown">{data.bom.filter(row=>row.parentPartId===activeId).map(row=>{const child=data.parts.find(item=>item.id===row.childPartId),amount=Number(child?.rollupCost||0)*row.quantity,pct=material?Math.round(amount/material*100):0;return <article key={row.id}><div><b>{row.childName}</b><small>{row.childNumber} · {row.quantity} {row.unit}</small></div><span><i style={{width:`${pct}%`}}/></span><strong>₩ {money(amount)}</strong></article>})}</div></section></div><section className="pdw-history"><header><b>원가계산서 이력</b><span>{sheets.length}개 Version</span></header><table><thead><tr><th>Version</th><th>품번</th><th>재료비</th><th>노무비</th><th>경비</th><th>총원가</th><th>등록자</th><th>메모</th></tr></thead><tbody>{sheets.map(item=><tr key={item.id}><td><b>V{item.version}</b></td><td>{item.partNumber}</td><td>₩ {money(item.materialCost)}</td><td>₩ {money(item.laborCost)}</td><td>₩ {money(item.overheadCost)}</td><td><strong>₩ {money(item.totalCost)}</strong></td><td>{item.createdBy||"사용자"}</td><td>{item.note||"—"}</td></tr>)}</tbody></table>{loading&&<p className="pdw-empty">원가 데이터를 불러오는 중…</p>}{!loading&&!sheets.length&&<p className="pdw-empty">저장된 원가계산서가 없습니다. 위 계산 결과를 Version으로 저장해 보세요.</p>}</section></section>
}
