"use client";

import {useEffect,useMemo,useState,type FormEvent} from "react";
import {ArrowDown,ArrowUp,BarChart3,ChevronDown,ChevronRight,Layers3,Plus,RefreshCw,Search,Settings2,Trash2,WalletCards,X} from "lucide-react";
import {V2PanelExpandButton} from "./v2-ui-foundation";
import "./project-cost-workspace.css";
import "./project-cost-entry-panel.css";

type Project={id:string;code:string;name:string;status:string};
type GroupCode="MATERIAL"|"EXPENSE"|"OUTSOURCE"|"OTHER";
type Group={code:GroupCode;name:string;sortOrder:number};
type Category={id:string;code:string;groupCode:GroupCode;name:string;sourceType:"BOM"|"MANUAL";enabled:number;sortOrder:number};
type Budget={categoryCode:string;amount:number};
type CostEntry={id:string;taskId?:string;categoryCode:string;amount:number;occurredOn:string;vendor?:string;note?:string;createdBy?:string};
type Task={id:string;wbsCode:string;name:string;kind:string};
type CostReference={targetCost:number;actualCost:number;projectCode?:string;projectName?:string};
type BomCostRow={id:string;partId:string;partNumber:string;name:string;partType:string;spec?:string;unit:string;quantity:number;totalQuantity:number;depth:number;targetCost:number;actualCost:number;targetAmount:number;actualAmount:number;hasChildren:boolean;costMode:"AUTO"|"DIRECT";reference?:CostReference|null};
type CostData={projects:Project[];project?:Project;groups:Group[];categories:Category[];budgets:Budget[];entries:CostEntry[];tasks:Task[]};
type RootBom={rootPartId:string;partNumber:string;name:string;partType:string;spec?:string;unit?:string;ownerUserId?:string;ownerName?:string;sortOrder:number};
type RootCandidate={id:string;partNumber:string;name:string;partType:string;spec?:string;unit?:string;childCount:number;selected:boolean};
type Member={id:string;name?:string;email?:string};
type RootCost=RootBom&{rows:BomCostRow[];targetMaterial:number;actualMaterial:number;coverage:number};
type Tab="summary"|"bom"|"entries";

const EMPTY:CostData={projects:[],groups:[],categories:[],budgets:[],entries:[],tasks:[]};
const money=(value:number)=>new Intl.NumberFormat("ko-KR",{maximumFractionDigits:0}).format(Math.round(Number(value||0)));
const pct=(value:number,total:number)=>total?Math.round(value/total*1000)/10:0;
const newEntry=()=>({taskId:"",categoryCode:"",amount:0,occurredOn:new Date().toISOString().slice(0,10),vendor:"",note:""});
const SUMMARY_ROWS=[
  {key:"MATERIAL_BOM",label:"원재료비",description:"BOM 기준 재료비",group:"MATERIAL" as GroupCode,auto:true},
  {key:"SUMMARY_MATERIAL_OTHER",label:"기타 재료비",description:"시제품, 기타 재료비성 지출",group:"MATERIAL" as GroupCode},
  {key:"SUMMARY_EXPENSE",label:"경비",description:"출장, 운송, 시험, 인증, 소모품 등 경비성 지출",group:"EXPENSE" as GroupCode},
  {key:"SUMMARY_OUTSOURCE",label:"외주비",description:"외주설계, 외주가공, 외주 설치·시공, 기술용역비 등 지출",group:"OUTSOURCE" as GroupCode},
  {key:"SUMMARY_OTHER",label:"기타",description:"기타 예비비, 기타 비용",group:"OTHER" as GroupCode},
] as const;

export function ProjectCostWorkspace(){
  const [data,setData]=useState<CostData>(EMPTY),[projectId,setProjectId]=useState(""),[tab,setTab]=useState<Tab>("summary"),[loading,setLoading]=useState(true),[notice,setNotice]=useState("");
  const [rootCosts,setRootCosts]=useState<RootCost[]>([]),[rootCandidates,setRootCandidates]=useState<RootCandidate[]>([]),[members,setMembers]=useState<Member[]>([]);
  const [entryOpen,setEntryOpen]=useState(false),[entryWide,setEntryWide]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[rootOpen,setRootOpen]=useState(false),[saving,setSaving]=useState(false),[rootSearch,setRootSearch]=useState(""),[rootOwner,setRootOwner]=useState("");
  const [entry,setEntry]=useState(newEntry);
  const [categoryForm,setCategoryForm]=useState({code:"",groupCode:"EXPENSE" as GroupCode,name:"",sortOrder:90});

  const load=async(id=projectId)=>{setLoading(true);try{
    const response=await fetch(`/api/project-costs${id?`?projectId=${encodeURIComponent(id)}`:""}`,{cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.error||"원가 정보를 불러오지 못했습니다.");
    if(!id&&result.projects?.length){setProjectId(result.projects[0].id);setLoading(false);return void load(result.projects[0].id)}
    setData({...EMPTY,...result});
    if(id){const rootsResponse=await fetch(`/api/project-costs/bom-roots?projectId=${encodeURIComponent(id)}`,{cache:"no-store"});const rootsData=await rootsResponse.json();if(!rootsResponse.ok)throw new Error(rootsData.error||"프로젝트 BOM을 불러오지 못했습니다.");setRootCandidates(rootsData.candidates||[]);setMembers(rootsData.members||[]);
      const roots=(rootsData.roots||[]) as RootBom[];const costs=await Promise.all(roots.map(async root=>{const costResponse=await fetch(`/api/project-costs/bom-cost-data?projectId=${encodeURIComponent(id)}&rootId=${encodeURIComponent(root.rootPartId)}`,{cache:"no-store"});const cost=costResponse.ok?await costResponse.json():{rows:[],targetMaterial:0,actualMaterial:0,coverage:0};return {...root,...cost} as RootCost}));setRootCosts(costs);
    }else{setRootCosts([]);setRootCandidates([]);setMembers([])}setNotice("");
  }catch(reason){setNotice(reason instanceof Error?reason.message:"원가 정보를 불러오지 못했습니다.")}finally{setLoading(false)}};
  useEffect(()=>{void load("")},[]);
  const selectProject=(id:string)=>{setProjectId(id);setTab("summary");void load(id)};
  const categories=data.categories.filter(c=>c.enabled!==0),manualCategories=categories.filter(c=>c.sourceType!=="BOM");
  const budgets=useMemo(()=>new Map(data.budgets.map(row=>[row.categoryCode,Number(row.amount||0)])),[data.budgets]);
  const actualByCategory=useMemo(()=>{const map=new Map<string,number>();for(const row of data.entries)map.set(row.categoryCode,(map.get(row.categoryCode)||0)+Number(row.amount||0));return map},[data.entries]);
  const actualByGroup=useMemo(()=>{const map=new Map<GroupCode,number>();for(const group of data.groups)map.set(group.code,manualCategories.filter(c=>c.groupCode===group.code).reduce((sum,c)=>sum+(actualByCategory.get(c.code)||0),0));return map},[data.groups,manualCategories,actualByCategory]);
  const bomTarget=rootCosts.reduce((sum,root)=>sum+root.targetMaterial,0),bomActual=rootCosts.reduce((sum,root)=>sum+root.actualMaterial,0);
  const costUnits=rootCosts.flatMap(root=>root.rows.filter(row=>!row.hasChildren||row.costMode==="DIRECT")),coveredUnits=costUnits.filter(row=>row.actualCost>0).length,bomCoverage=costUnits.length?Math.round(coveredUnits/costUnits.length*100):0;
  const summaryRows=SUMMARY_ROWS.map(row=>{const budget=row.auto?bomTarget:(budgets.get(row.key)||0);const actual=row.auto?(bomCoverage>0?bomActual:0):(actualByGroup.get(row.group)||0);return {...row,budget,actual}});

  const post=async(body:any)=>{const response=await fetch("/api/project-costs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||"저장하지 못했습니다.");return result};
  const rootPost=async(body:any)=>{const response=await fetch("/api/project-costs/bom-roots",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId,...body})});const result=await response.json();if(!response.ok)throw new Error(result.error||"프로젝트 BOM을 저장하지 못했습니다.");return result};
  const saveSummaryBudget=async(key:string,amount:number)=>{try{const budgetKey=key.replace(/^SUMMARY_/,"");const response=await fetch("/api/project-costs/summary-budget",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId,budgetKey,amount})});const result=await response.json();if(!response.ok)throw new Error(result.error||"예산을 저장하지 못했습니다.");setNotice("프로젝트 예산을 저장했습니다.");await load()}catch(reason){setNotice(reason instanceof Error?reason.message:"예산을 저장하지 못했습니다.")}};
  const updatePartCost=async(row:BomCostRow,targetCost:number,actualCost:number,costMode:"AUTO"|"DIRECT")=>{try{const response=await fetch("/api/project-costs/bom-cost-data",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId,partId:row.partId,targetCost,actualCost,costMode})});const result=await response.json();if(!response.ok)throw new Error(result.error||"PART 원가를 저장하지 못했습니다.");setNotice(`${row.partNumber} 원가를 저장했습니다.`);await load()}catch(reason){setNotice(reason instanceof Error?reason.message:"PART 원가를 저장하지 못했습니다.")}};
  const addRoot=async(candidate:RootCandidate)=>{try{await rootPost({action:"add",rootPartId:candidate.id,ownerUserId:rootOwner});setRootOpen(false);setRootSearch("");setRootOwner("");setNotice(`${candidate.partNumber}을 프로젝트 원가 Root로 추가했습니다.`);await load()}catch(reason){setNotice(reason instanceof Error?reason.message:"Root BOM을 추가하지 못했습니다.")}};
  const removeRoot=async(root:RootBom)=>{if(!confirm(`${root.partNumber}을 프로젝트 원가 Root에서 제외할까요?\n원본 BOM은 삭제되지 않습니다.`))return;try{await rootPost({action:"remove",rootPartId:root.rootPartId});setNotice("Root BOM을 제외했습니다.");await load()}catch(reason){setNotice(reason instanceof Error?reason.message:"Root BOM을 제외하지 못했습니다.")}};
  const changeOwner=async(rootPartId:string,ownerUserId:string)=>{try{await rootPost({action:"owner",rootPartId,ownerUserId});await load()}catch(reason){setNotice(reason instanceof Error?reason.message:"담당자를 변경하지 못했습니다.")}};
  const moveRoot=async(index:number,direction:-1|1)=>{const next=[...rootCosts],target=index+direction;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setRootCosts(next);try{await rootPost({action:"reorder",rootPartIds:next.map(root=>root.rootPartId)});setNotice("Root BOM 순서를 변경했습니다.")}catch(reason){setNotice(reason instanceof Error?reason.message:"순서를 변경하지 못했습니다.");await load()}};
  const closeEntry=()=>{setEntryOpen(false);setEntryWide(false)};
  const openEntry=()=>{setEntry(newEntry());setEntryWide(false);setEntryOpen(true)};
  const addEntry=async(event:FormEvent)=>{event.preventDefault();setSaving(true);try{await post({action:"add-entry",projectId,...entry});closeEntry();setEntry(newEntry());setNotice("비용 실적을 등록했습니다.");await load()}catch(reason){setNotice(reason instanceof Error?reason.message:"비용 실적을 등록하지 못했습니다.")}finally{setSaving(false)}};
  const removeEntry=async(id:string)=>{if(!confirm("이 비용 실적을 삭제할까요?"))return;try{await post({action:"delete-entry",projectId,id});await load()}catch(reason){setNotice(reason instanceof Error?reason.message:"비용 실적을 삭제하지 못했습니다.")}};
  const saveCategory=async(event:FormEvent)=>{event.preventDefault();setSaving(true);try{await post({action:"save-category",...categoryForm});setCategoryForm({code:"",groupCode:"EXPENSE",name:"",sortOrder:90});setNotice("비용 카테고리를 추가했습니다.");await load()}catch(reason){setNotice(reason instanceof Error?reason.message:"비용 카테고리를 저장하지 못했습니다.")}finally{setSaving(false)}};

  const filteredCandidates=rootCandidates.filter(item=>!item.selected&&(!rootSearch.trim()||`${item.partNumber} ${item.name} ${item.spec||""} ${item.partType}`.toLowerCase().includes(rootSearch.trim().toLowerCase())));
  return <section className="pcw-shell">
    <header className="pcw-head"><div><small>PROJECT COST MANAGEMENT</small><h1>원가 관리</h1><p>분산된 개발 BOM과 프로젝트 비용을 통합하여 개발원가를 관리합니다.</p></div><div><button onClick={()=>setSettingsOpen(true)}><Settings2 size={17}/>비용 카테고리</button><button onClick={()=>void load()}><RefreshCw size={17}/>새로고침</button></div></header>
    <div className="pcw-project-bar"><label><span>프로젝트</span><select value={projectId} onChange={e=>selectProject(e.target.value)}>{data.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><em>{data.project?.status||""}</em></div>
    {notice&&<p className="pcw-notice">{notice}</p>}
    <nav className="pcw-tabs"><button className={tab==="summary"?"active":""} onClick={()=>setTab("summary")}><BarChart3 size={17}/>총원가</button><button className={tab==="bom"?"active":""} onClick={()=>setTab("bom")}><Layers3 size={17}/>BOM 원가</button><button className={tab==="entries"?"active":""} onClick={()=>setTab("entries")}><WalletCards size={17}/>프로젝트 비용</button></nav>
    {loading?<div className="pcw-empty">원가 정보를 불러오는 중입니다.</div>:tab==="summary"?<SummaryView rows={summaryRows} bomCoverage={bomCoverage} onSaveBudget={saveSummaryBudget}/>:tab==="bom"?<BomView roots={rootCosts} members={members} target={bomTarget} actual={bomActual} coverage={bomCoverage} onAdd={()=>setRootOpen(true)} onRemove={removeRoot} onOwner={changeOwner} onMove={moveRoot} onSavePart={updatePartCost}/>:<EntriesView data={data} categories={categories} actuals={actualByCategory} onAdd={openEntry} onDelete={removeEntry}/>} 
    {rootOpen&&<div className="pcw-backdrop"><div className="pcw-dialog wide pcw-root-dialog"><header><div><small>PROJECT COST BOM ROOT</small><h2>Root BOM 추가</h2><p>각 담당자가 관리하는 BOM/PART를 프로젝트 개발원가 Root로 추가합니다. Root별 레벨은 서로 달라도 됩니다.</p></div><button onClick={()=>setRootOpen(false)}><X size={18}/></button></header><div className="pcw-root-search"><label><Search size={17}/><input autoFocus placeholder="PART No, 품명, 사양 검색" value={rootSearch} onChange={e=>setRootSearch(e.target.value)}/></label><select value={rootOwner} onChange={e=>setRootOwner(e.target.value)}><option value="">담당자 미지정</option>{members.map(member=><option key={member.id} value={member.id}>{member.name||member.email||member.id}</option>)}</select></div><div className="pcw-root-candidates">{filteredCandidates.slice(0,80).map(item=><button key={item.id} onClick={()=>void addRoot(item)}><span><b>{item.partNumber}</b><small>{item.name}</small></span><span>{item.partType}</span><span>{item.spec||"—"}</span><em>{item.childCount>0?`하위 ${item.childCount}개`:"단일 PART"}</em><strong>추가</strong></button>)}{!filteredCandidates.length&&<div className="pcw-empty">추가 가능한 BOM/PART가 없습니다.</div>}</div><footer><button onClick={()=>setRootOpen(false)}>닫기</button></footer></div></div>}
    {entryOpen&&<aside className={`pcw-right-panel ${entryWide?"wide":""}`}><header><div><small>PROJECT COST ACTUAL</small><h2>비용 실적 등록</h2><p>현재 프로젝트에 비용을 등록합니다. Task 연결은 선택사항입니다.</p></div><div className="pcw-panel-head-actions"><V2PanelExpandButton expanded={entryWide} onToggle={()=>setEntryWide(value=>!value)}/><button type="button" className="pcw-panel-close" onClick={closeEntry} aria-label="비용 실적 등록 닫기"><X size={18}/></button></div></header><form onSubmit={addEntry}><label><span>프로젝트 *</span><input value={data.project?.name||""} readOnly/></label><label><span>Task 선택</span><select value={entry.taskId} onChange={e=>setEntry({...entry,taskId:e.target.value})}><option value="">프로젝트 공통 비용</option>{data.tasks.filter(t=>t.kind==="task").map(t=><option key={t.id} value={t.id}>{t.wbsCode} · {t.name}</option>)}</select></label><label><span>비용 카테고리 *</span><select required value={entry.categoryCode} onChange={e=>setEntry({...entry,categoryCode:e.target.value})}><option value="">비용 카테고리 선택</option>{data.groups.map(g=><optgroup key={g.code} label={g.name}>{manualCategories.filter(c=>c.groupCode===g.code).map(c=><option key={c.code} value={c.code}>{c.name}</option>)}</optgroup>)}</select></label><div className="two"><label><span>금액 *</span><input required type="number" min="1" value={entry.amount||""} onChange={e=>setEntry({...entry,amount:Number(e.target.value)})}/></label><label><span>발생일 *</span><input required type="date" value={entry.occurredOn} onChange={e=>setEntry({...entry,occurredOn:e.target.value})}/></label></div><label><span>업체</span><input value={entry.vendor} onChange={e=>setEntry({...entry,vendor:e.target.value})}/></label><label><span>비고</span><textarea rows={5} value={entry.note} onChange={e=>setEntry({...entry,note:e.target.value})}/></label><footer><button type="button" onClick={closeEntry}>취소</button><button className="primary" disabled={saving||!entry.categoryCode}>{saving?"등록 중…":"비용 등록"}</button></footer></form></aside>}
    {settingsOpen&&<div className="pcw-backdrop"><div className="pcw-dialog wide"><header><div><small>COST CATEGORY SETTINGS</small><h2>비용 카테고리</h2><p>프로젝트 비용 실적 등록에 사용하는 세부 카테고리입니다.</p></div><button onClick={()=>setSettingsOpen(false)}><X size={18}/></button></header><div className="pcw-category-list">{data.groups.map(g=><section key={g.code}><b>{g.name}</b>{data.categories.filter(c=>c.groupCode===g.code).map(c=><span key={c.code}>{c.name}<small>{c.sourceType==="BOM"?"BOM 자동연계":c.code}</small></span>)}</section>)}</div><form className="pcw-category-form" onSubmit={saveCategory}><select value={categoryForm.groupCode} onChange={e=>setCategoryForm({...categoryForm,groupCode:e.target.value as GroupCode})}>{data.groups.map(g=><option key={g.code} value={g.code}>{g.name}</option>)}</select><input required placeholder="코드" value={categoryForm.code} onChange={e=>setCategoryForm({...categoryForm,code:e.target.value.toUpperCase().replace(/\s+/g,"_")})}/><input required placeholder="세부 카테고리명" value={categoryForm.name} onChange={e=>setCategoryForm({...categoryForm,name:e.target.value})}/><button className="primary" disabled={saving}><Plus size={16}/>추가</button></form><footer><button onClick={()=>setSettingsOpen(false)}>닫기</button></footer></div></div>}
  </section>;
}

function SummaryView({rows,bomCoverage,onSaveBudget}:{rows:Array<(typeof SUMMARY_ROWS)[number]&{budget:number;actual:number}>;bomCoverage:number;onSaveBudget:(key:string,amount:number)=>void}){const totalBudget=rows.reduce((sum,row)=>sum+row.budget,0),totalActual=rows.reduce((sum,row)=>sum+row.actual,0);return <div className="pcw-summary"><section className="pcw-budget-table"><header><b>프로젝트 예산 · 집행 요약</b><span>예산은 큰 분류로, 실제 지출은 프로젝트 비용 탭에서 세부 항목으로 관리합니다.</span></header><div className="rows"><div className="th"><span>구분</span><span>비용항목</span><span>예산</span><span>집행실적</span><span>잔여</span><span>집행률</span></div>{rows.map(row=><div className="tr" key={row.key}><b>{row.label}</b><span>{row.description}</span><span>{row.auto?<strong>₩ {money(row.budget)}</strong>:<BudgetEditor initial={row.budget} onSave={value=>onSaveBudget(row.key,value)}/>}</span><span>{row.auto&&bomCoverage===0?<em>미관리</em>:`₩ ${money(row.actual)}`}</span><span>₩ {money(row.budget-row.actual)}</span><span>{row.auto&&bomCoverage===0?"—":`${pct(row.actual,row.budget)}%`}</span></div>)}<div className="tr total"><b>합계</b><span>총 프로젝트 원가</span><strong>₩ {money(totalBudget)}</strong><strong>₩ {money(totalActual)}</strong><strong>₩ {money(totalBudget-totalActual)}</strong><strong>{pct(totalActual,totalBudget)}%</strong></div></div></section></div>}
function BudgetEditor({initial,onSave}:{initial:number;onSave:(value:number)=>void}){const [value,setValue]=useState(initial);useEffect(()=>setValue(initial),[initial]);return <span className="pcw-budget-input"><input type="number" min="0" value={value||""} placeholder="0" onChange={e=>setValue(Number(e.target.value))}/><button onClick={()=>onSave(value)}>저장</button></span>}

function BomView({roots,members,target,actual,coverage,onAdd,onRemove,onOwner,onMove,onSavePart}:{roots:RootCost[];members:Member[];target:number;actual:number;coverage:number;onAdd:()=>void;onRemove:(root:RootBom)=>void;onOwner:(rootId:string,owner:string)=>void;onMove:(index:number,direction:-1|1)=>void;onSavePart:(row:BomCostRow,target:number,actual:number,mode:"AUTO"|"DIRECT")=>void}){
  const [collapsed,setCollapsed]=useState<Set<string>>(new Set());
  useEffect(()=>{setCollapsed(current=>new Set([...current].filter(id=>roots.some(root=>root.rootPartId===id))))},[roots.map(root=>root.rootPartId).join("|")]);
  const toggle=(id:string)=>setCollapsed(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next});
  const allCollapsed=roots.length>0&&roots.every(root=>collapsed.has(root.rootPartId));
  const toggleAll=()=>setCollapsed(allCollapsed?new Set():new Set(roots.map(root=>root.rootPartId)));
  return <div className="pcw-bom"><section className="pcw-bom-toolbar"><div><b>프로젝트 개발원가 BOM</b><span>Root {roots.length}개 · 목표 ₩ {money(target)} · 실제 {coverage>0?`₩ ${money(actual)}`:"미관리"} · 반영률 {coverage}%</span></div><div className="pcw-bom-toolbar-actions"><button className="secondary" onClick={toggleAll}>{allCollapsed?"전체 펼치기":"전체 접기"}</button><button className="primary" onClick={onAdd}><Plus size={17}/>Root BOM 추가</button></div></section>{roots.map((root,index)=>{const isCollapsed=collapsed.has(root.rootPartId),rootRow=root.rows.find(row=>row.partId===root.rootPartId)||root.rows[0];return <section className={`pcw-bom-group ${isCollapsed?"collapsed":""}`} key={root.rootPartId}><header><div className="pcw-bom-group-main"><button className="pcw-collapse-button" onClick={()=>toggle(root.rootPartId)} title={isCollapsed?"펼치기":"접기"}>{isCollapsed?<ChevronRight size={18}/>:<ChevronDown size={18}/>}</button><span className="pcw-root-order"><button disabled={index===0} onClick={()=>onMove(index,-1)} title="위로"><ArrowUp size={16}/></button><button disabled={index===roots.length-1} onClick={()=>onMove(index,1)} title="아래로"><ArrowDown size={16}/></button></span><b>{index+1}. {root.partNumber}</b><span>{root.name}</span></div><div className="pcw-bom-group-meta"><label><small>담당자</small><select value={root.ownerUserId||""} onChange={e=>onOwner(root.rootPartId,e.target.value)}><option value="">미지정</option>{members.map(member=><option key={member.id} value={member.id}>{member.name||member.email||member.id}</option>)}</select></label><strong>목표 ₩ {money(root.targetMaterial)} · 실제 {root.coverage>0?`₩ ${money(root.actualMaterial)}`:"미관리"}</strong><button className="danger" onClick={()=>onRemove(root)} title="Root 제외"><Trash2 size={16}/></button></div></header>{isCollapsed&&rootRow&&<RootQuickCost row={rootRow} onSave={onSavePart}/>} {!isCollapsed&&<div className="pcw-bom-table-wrap"><div className="pcw-bom-table"><div className="th"><span>PART</span><span>품명</span><span>사양</span><span>수량</span><span>단위</span><span>원가방식</span><span>목표단가</span><span>실구매가</span><span>목표금액</span><span>실제금액</span><span>상태</span></div>{root.rows.map(row=><CostRow key={`${root.rootPartId}-${row.id}`} row={row} onSave={onSavePart}/>)}</div></div>}</section>})}{!roots.length&&<div className="pcw-empty">아직 등록된 Root BOM이 없습니다. 기구·전장·보드 등 각 담당 BOM을 추가해 주세요.</div>}</div>}

function RootQuickCost({row,onSave}:{row:BomCostRow;onSave:(row:BomCostRow,target:number,actual:number,mode:"AUTO"|"DIRECT")=>void}){const [target,setTarget]=useState(row.targetCost),[actual,setActual]=useState(row.actualCost),[mode,setMode]=useState<"AUTO"|"DIRECT">(row.costMode||"AUTO");useEffect(()=>{setTarget(row.targetCost);setActual(row.actualCost);setMode(row.costMode||"AUTO")},[row.targetCost,row.actualCost,row.costMode]);const direct=!row.hasChildren||mode==="DIRECT";return <div className="pcw-root-quick-cost"><span><small>원가방식</small>{row.hasChildren?<select value={mode} onChange={e=>setMode(e.target.value as "AUTO"|"DIRECT")}><option value="AUTO">하위 Roll-up</option><option value="DIRECT">모듈 직접 원가</option></select>:<b>직접 원가</b>}</span><span><small>목표단가</small>{direct?<input type="number" min="0" value={target||""} placeholder="미등록" onChange={e=>setTarget(Number(e.target.value))}/>:<b>₩ {money(row.targetAmount)}</b>}</span><span><small>실구매가</small>{direct?<input type="number" min="0" value={actual||""} placeholder="미등록" onChange={e=>setActual(Number(e.target.value))}/>:<b>{row.actualAmount>0?`₩ ${money(row.actualAmount)}`:"미관리"}</b>}</span><span><small>모듈 금액</small><b>목표 ₩ {money(direct?target*row.totalQuantity:row.targetAmount)} · 실제 {direct&&actual===0?"미관리":`₩ ${money(direct?actual*row.totalQuantity:row.actualAmount)}`}</b></span><button onClick={()=>onSave(row,target,actual,mode)}>{mode!==row.costMode?"적용":"저장"}</button></div>}

function CostRow({row,onSave}:{row:BomCostRow;onSave:(row:BomCostRow,target:number,actual:number,mode:"AUTO"|"DIRECT")=>void}){const [target,setTarget]=useState(row.targetCost),[actual,setActual]=useState(row.actualCost),[mode,setMode]=useState<"AUTO"|"DIRECT">(row.costMode||"AUTO");useEffect(()=>{setTarget(row.targetCost);setActual(row.actualCost);setMode(row.costMode||"AUTO")},[row.targetCost,row.actualCost,row.costMode]);const direct=!row.hasChildren||mode==="DIRECT",status=row.hasChildren&&mode==="AUTO"?"Roll-up":target>0&&actual>0?"입력완료":target>0||actual>0?"일부등록":"미관리";return <div className={`tr ${row.hasChildren?"assembly":""}`}><span style={{paddingLeft:`${row.depth*16}px`}}><b>{row.partNumber}</b></span><span><b>{row.name}</b><small>{row.partType}</small></span><span>{row.spec||"—"}</span><span>{row.totalQuantity}</span><span>{row.unit||"EA"}</span><span>{row.hasChildren?<select className="pcw-mode-select" value={mode} onChange={e=>setMode(e.target.value as "AUTO"|"DIRECT")}><option value="AUTO">하위 Roll-up</option><option value="DIRECT">직접 원가</option></select>:<em className="cost-status">직접</em>}</span><span className="pcw-cost-input">{direct?<input type="number" min="0" value={target||""} placeholder="미등록" onChange={e=>setTarget(Number(e.target.value))}/>:<strong>₩ {money(row.targetAmount)}</strong>}{direct&&row.reference&&<small title={`${row.reference.projectCode||""} ${row.reference.projectName||""}`}>참조 ₩ {money(row.reference.targetCost)}</small>}</span><span className="pcw-cost-input">{direct?<input type="number" min="0" value={actual||""} placeholder="미등록" onChange={e=>setActual(Number(e.target.value))}/>:<strong>{row.actualAmount>0?`₩ ${money(row.actualAmount)}`:"미관리"}</strong>}{direct&&row.reference&&<small>참조 ₩ {money(row.reference.actualCost)}</small>}</span><strong>₩ {money(direct?target*row.totalQuantity:row.targetAmount)}</strong><strong>{direct&&actual===0?"—":`₩ ${money(direct?actual*row.totalQuantity:row.actualAmount)}`}</strong><span className="pcw-cost-actions"><em className={`cost-status ${status}`}>{status}</em>{direct&&<button onClick={()=>onSave(row,target,actual,mode)}>저장</button>}{row.hasChildren&&mode==="AUTO"&&row.costMode!==mode&&<button onClick={()=>onSave(row,target,actual,mode)}>적용</button>}</span></div>}

function EntriesView({data,categories,actuals,onAdd,onDelete}:{data:CostData;categories:Category[];actuals:Map<string,number>;onAdd:()=>void;onDelete:(id:string)=>void}){const tasks=new Map(data.tasks.map(t=>[t.id,t])),categoryMap=new Map(categories.map(c=>[c.code,c]));const inlineTotals=data.groups.map(g=>`${g.name} ₩${money(categories.filter(c=>c.groupCode===g.code&&c.sourceType!=="BOM").reduce((sum,c)=>sum+(actuals.get(c.code)||0),0))}`).join(" · ");return <div className="pcw-entries"><header><div><b>프로젝트 비용 실적</b><span>{inlineTotals} · 프로젝트 필수 / Task 선택</span></div><button className="primary" onClick={onAdd}><Plus size={17}/>비용 실적 등록</button></header><div className="pcw-entry-table"><div className="th"><span>발생일</span><span>비용 카테고리</span><span>프로젝트 / Task</span><span>업체</span><span>금액</span><span>등록자</span><span/></div>{data.entries.map(row=>{const task=row.taskId?tasks.get(row.taskId):null,cat=categoryMap.get(row.categoryCode);return <div className="tr" key={row.id}><span>{row.occurredOn}</span><span>{cat?.name||row.categoryCode}</span><span>{task?`${task.wbsCode} · ${task.name}`:"프로젝트 공통"}</span><span>{row.vendor||"—"}</span><strong>₩ {money(row.amount)}</strong><span>{row.createdBy||"—"}</span><button className="danger" onClick={()=>onDelete(row.id)}><Trash2 size={15}/></button></div>})}{!data.entries.length&&<div className="pcw-empty">등록된 프로젝트 비용 실적이 없습니다.</div>}</div></div>}

export default ProjectCostWorkspace;
