"use client";

/* eslint-disable react-hooks/exhaustive-deps */
import {useEffect,useMemo,useState} from "react";
import {Check,Plus,Trash2,Users,X} from "lucide-react";
import type {V2Project} from "./project-workspaces";
import {UserAvatar} from "./user-avatar";

type Member={userId:string;name:string;email?:string;avatarKey?:string;projectRole:string;assignedTaskCount?:number};
type User={userId:string;name:string;email?:string;avatarKey?:string};
type Role={code:string;name:string;groupName:string;required?:boolean|number;sortOrder?:number};

export function ProjectMembersMasterDialog({project,onClose,onSaved}:{project:V2Project;onClose:()=>void;onSaved:(members:Member[])=>void}){
  const [users,setUsers]=useState<User[]>([]);const [roles,setRoles]=useState<Role[]>([]);const [draft,setDraft]=useState<Member[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [notice,setNotice]=useState("");
  useEffect(()=>{const controller=new AbortController();fetch(`/api/projects/${project.id}/members`,{cache:"no-store",signal:controller.signal}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||"참여자를 불러오지 못했습니다.");setUsers(data.users??[]);setRoles(data.roles??[]);setDraft(data.members??[])}).catch(reason=>{if(!(reason instanceof DOMException&&reason.name==="AbortError"))setNotice(reason instanceof Error?reason.message:"참여자를 불러오지 못했습니다.")}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[project.id]);
  const roleGroups=useMemo(()=>Array.from(new Set(roles.map(role=>role.groupName||"업무 수행"))).map(groupName=>({groupName,items:roles.filter(role=>(role.groupName||"업무 수행")===groupName)})),[roles]);
  const pmCount=draft.filter(item=>item.projectRole==="PM").length;
  const fallbackRole=roles.find(role=>role.code==="MEMBER")?.code||roles.find(role=>role.code!=="PM"&&!Boolean(role.required))?.code||roles.find(role=>role.code!=="PM")?.code||"PL";
  const removeMember=(userId:string)=>setDraft(current=>{const existing=current.find(item=>item.userId===userId);if(!existing)return current;if(Number(existing.assignedTaskCount||0)>0){setNotice(`${existing.name}님은 담당 업무 ${existing.assignedTaskCount}건이 있어 참여자에서 삭제할 수 없습니다.`);return current}setNotice("");return current.filter(item=>item.userId!==userId)});
  const toggle=(user:User)=>setDraft(current=>{const existing=current.find(item=>item.userId===user.userId);if(existing){if(Number(existing.assignedTaskCount||0)>0){setNotice(`${existing.name}님은 담당 업무 ${existing.assignedTaskCount}건이 있어 참여자에서 삭제할 수 없습니다.`);return current}setNotice("");return current.filter(item=>item.userId!==user.userId)}setNotice("");return [...current,{...user,projectRole:current.some(item=>item.projectRole==="PM")?fallbackRole:"PM",assignedTaskCount:0}]});
  const assignRole=(userId:string,projectRole:string)=>setDraft(current=>current.map(item=>item.userId===userId?{...item,projectRole}:projectRole==="PM"&&item.projectRole==="PM"?{...item,projectRole:fallbackRole}:item));
  const save=async()=>{if(pmCount!==1){setNotice("프로젝트 PM을 정확히 1명 지정해 주세요.");return}setSaving(true);setNotice("");try{const response=await fetch(`/api/projects/${project.id}/members`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({members:draft.map(item=>({userId:item.userId,projectRole:item.projectRole}))})});const data=await response.json();if(!response.ok)throw new Error(data.error||"참여자를 저장하지 못했습니다.");onSaved(draft)}catch(reason){setNotice(reason instanceof Error?reason.message:"참여자를 저장하지 못했습니다.")}finally{setSaving(false)}};
  return <div className="wv2-module-dialog-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className="wv2-members-dialog" role="dialog" aria-modal="true" aria-label="프로젝트 참여자 관리"><header><div><small>PROJECT MEMBERS · MASTER ROLE</small><h2>조직 · 참여자 관리</h2><p>{project.name} · 시스템 설정의 프로젝트 Role을 사용합니다.</p></div><button onClick={onClose}><X size={18}/></button></header>{loading?<div className="wv2-members-loading"><Users size={26}/><b>참여자를 불러오는 중…</b></div>:<div className="wv2-members-body"><aside><b>활성 사용자</b>{users.map(user=>{const selected=draft.find(item=>item.userId===user.userId),locked=Boolean(selected&&Number(selected.assignedTaskCount||0)>0);return <button key={user.userId} className={selected?"selected":""} onClick={()=>toggle(user)} title={locked?`담당 업무 ${selected?.assignedTaskCount}건이 있어 삭제할 수 없습니다.`:undefined}><UserAvatar avatarKey={user.avatarKey} name={user.name} size={30}/><div><b>{user.name}</b><small>{user.email||"이메일 없음"}</small></div>{selected?<Check size={18}/>:<Plus size={18}/>}</button>})}</aside><main><header><b>프로젝트 참여자</b><span>{draft.length}명 · PM {pmCount}명</span></header>{draft.map(member=>{const assigned=Number(member.assignedTaskCount||0)>0;return <article key={member.userId}><UserAvatar avatarKey={member.avatarKey} name={member.name} size={30}/><span><b>{member.name}</b><small>{member.email||""}{assigned?` · 담당 업무 ${member.assignedTaskCount}건`:""}</small></span><select value={member.projectRole} onChange={event=>assignRole(member.userId,event.target.value)}>{roleGroups.map(group=><optgroup key={group.groupName} label={group.groupName}>{group.items.map(role=><option key={role.code} value={role.code}>{role.name}{Boolean(role.required)?" · 필수":""}</option>)}</optgroup>)}</select><button disabled={assigned} title={assigned?"담당 업무를 다른 참여자에게 이관한 뒤 삭제할 수 있습니다.":"참여자 삭제"} onClick={()=>removeMember(member.userId)}><Trash2 size={18}/></button></article>})}{!draft.length&&<div className="wv2-members-loading"><Users size={26}/><b>참여자를 선택해 주세요.</b></div>}</main></div>}{notice&&<p className="wv2-form-error">{notice}</p>}<footer><button onClick={onClose}>닫기</button><button className="primary" disabled={saving||loading||pmCount!==1} onClick={save}>{saving?"저장 중…":"참여자 저장"}</button></footer></section></div>;
}
