"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import {useEffect,useMemo,useRef,useState} from "react";
import {Check,FileText,Trash2,Upload,X} from "lucide-react";
import "./workflow-document.css";
import "./source-create-workspace.css";

type Project={id:string;code:string;name:string};
type Step={name:string;actionType:string;roleCode?:string;assignmentRule?:string;dueDays?:number;commentRequired?:boolean;attachmentRequired?:boolean};
type Member={userId:string;name:string;email?:string;projectRole:string};
type DirectoryUser={userId:string;name:string;email?:string;organizationPath?:string;roleNames?:string};
type DrawingOption={id:string;projectId:string;projectCode:string;projectName:string;name:string;drawingCode?:string|null;drawingType?:string|null;taskId?:string|null;taskCode?:string|null;taskName?:string|null};
type CommonCodeOption={code:string;label:string;groupCode:string;enabled?:boolean|number};
type PartOption={id:string;partNumber:string;name:string;partType:string;spec?:string|null;unit:string;revision:string;status:string};

const actionLabels:Record<string,string>={WRITE:"작성",PROCESS:"처리",REVIEW:"검토",AGREEMENT:"합의",APPROVAL:"승인",REFERENCE:"참조"};
const json=async(response:Response)=>{const text=await response.text();let data:any={};if(text){try{data=JSON.parse(text)}catch{data={error:text}}}if(!response.ok)throw new Error(data.error||`요청을 처리하지 못했습니다. (${response.status})`);return data};
const automaticAssignees=(steps:Step[],members:Member[])=>{const result:Record<string,string>={};steps.forEach((step,index)=>{if(step.assignmentRule==="requester")return;const wanted=step.assignmentRule==="project_pm"?"PM":step.assignmentRule==="project_pl"?"PL":step.roleCode;const match=members.find(member=>wanted&&member.projectRole.toUpperCase()===wanted.toUpperCase());if(match)result[String(index)]=match.userId});return result};

function OrganizationAssigneeSelect({users,value,onChange,required=true}:{users:DirectoryUser[];value:string;onChange:(value:string)=>void;required?:boolean}){
  const groups=users.reduce<Record<string,DirectoryUser[]>>((result,user)=>{const key=user.organizationPath||"소속 미지정";(result[key]??=[]).push(user);return result},{});
  return <select aria-label="전체 조직 담당자" className={!value&&required?"required":""} value={value} onChange={event=>onChange(event.target.value)}><option value="">{required?"담당자 지정 필요":"담당자 선택(선택)"}</option>{Object.entries(groups).map(([organization,items])=><optgroup key={organization} label={organization}>{items.map(user=><option key={user.userId} value={user.userId}>{user.name}{user.email?` · ${user.email}`:""}{user.roleNames?` · ${user.roleNames}`:""}</option>)}</optgroup>)}</select>;
}

export function SourceCreateWorkspace({kind,projects,initialProjectId,editId,onCancel,onCreated}:{kind:"ECR"|"QUALITY";projects:Project[];initialProjectId:string;editId?:string;onCancel:()=>void;onCreated:(workflowId?:string)=>void}){
  const ecr=kind==="ECR",endpoint=ecr?"/api/ecr":"/api/quality",fileInput=useRef<HTMLInputElement>(null);
  const [form,setForm]=useState<any>({projectId:initialProjectId,partId:"",drawingId:"",workflowId:"",title:"",changeType:"",priority:"normal",severity:"medium",occurredOn:new Date().toISOString().slice(0,10),dueDate:"",beforeContent:"",afterContent:"",reason:"",impactContent:"",issueType:"",description:"",rootCause:"",correctiveAction:"",effectivenessCheck:""});
  const [parts,setParts]=useState<PartOption[]>([]),[partSearch,setPartSearch]=useState(""),[partLoading,setPartLoading]=useState(false);
  const [drawings,setDrawings]=useState<DrawingOption[]>([]),[drawingSearch,setDrawingSearch]=useState(""),[drawingLoading,setDrawingLoading]=useState(false);
  const [steps,setSteps]=useState<Step[]>([]),[users,setUsers]=useState<DirectoryUser[]>([]),[assignees,setAssignees]=useState<Record<string,string>>({});
  const [attachments,setAttachments]=useState<any[]>([]),[removeAttachmentIds,setRemoveAttachmentIds]=useState<string[]>([]),[files,setFiles]=useState<File[]>([]),[dragging,setDragging]=useState(false);
  const [optionsLoading,setOptionsLoading]=useState(false),[loadingEdit,setLoadingEdit]=useState(Boolean(editId)),[saving,setSaving]=useState(false),[error,setError]=useState("");
  const [qualityIssueTypes,setQualityIssueTypes]=useState<CommonCodeOption[]>([]),[designChangeTypes,setDesignChangeTypes]=useState<CommonCodeOption[]>([]);

  useEffect(()=>{const controller=new AbortController();fetch("/api/system/master-data",{cache:"no-store",signal:controller.signal}).then(json).then(data=>{const codes=(data.codes??[]) as CommonCodeOption[];setQualityIssueTypes(codes.filter(item=>item.groupCode==="QUALITY_ISSUE_TYPE"&&item.enabled!==false&&item.enabled!==0));setDesignChangeTypes(codes.filter(item=>item.groupCode==="DESIGN_CHANGE_TYPE"&&item.enabled!==false&&item.enabled!==0))}).catch(()=>{});return()=>controller.abort()},[]);

  useEffect(()=>{const controller=new AbortController(),timer=setTimeout(()=>{setPartLoading(true);const params=new URLSearchParams();const q=partSearch.trim();if(q)params.set("q",q);fetch(`/api/workflows/part-options?${params}`,{cache:"no-store",signal:controller.signal}).then(json).then(data=>setParts(data.parts??[])).catch(reason=>{if(!(reason instanceof DOMException&&reason.name==="AbortError"))setError(reason instanceof Error?reason.message:"PART를 불러오지 못했습니다.")}).finally(()=>setPartLoading(false))},180);return()=>{clearTimeout(timer);controller.abort()}},[partSearch]);

  useEffect(()=>{const controller=new AbortController(),timer=setTimeout(()=>{setDrawingLoading(true);const params=new URLSearchParams();const q=drawingSearch.trim();if(q)params.set("q",q);fetch(`/api/workflows/drawing-options?${params}`,{cache:"no-store",signal:controller.signal}).then(json).then(data=>setDrawings(data.drawings??[])).catch(reason=>{if(!(reason instanceof DOMException&&reason.name==="AbortError"))setError(reason instanceof Error?reason.message:"도면을 불러오지 못했습니다.")}).finally(()=>setDrawingLoading(false))},180);return()=>{clearTimeout(timer);controller.abort()}},[drawingSearch]);

  useEffect(()=>{if(!editId)return;setLoadingEdit(true);fetch(`${endpoint}?id=${editId}`,{cache:"no-store"}).then(json).then(async data=>{const item=data.item;setForm((current:any)=>({...current,...item,projectId:item.projectId||"",partId:item.partId||data.part?.id||"",drawingId:item.drawingId||data.drawing?.id||"",workflowId:item.workflowId||""}));setAttachments(data.attachments??[]);if(item.partId||data.part?.id)setPartSearch(item.partNumber||data.part?.partNumber||"");if(item.drawingId||data.drawing?.id)setDrawingSearch(item.drawingCode||data.drawing?.drawingCode||data.drawing?.name||"");if(item.workflowId){const detail=await fetch(`/api/workflows/${item.workflowId}`,{cache:"no-store"}).then(json);if(detail.workflow.status!=="draft")throw new Error("임시저장 상태에서만 수정할 수 있습니다.");setSteps((detail.steps??[]).map((step:any)=>({name:step.name||step.step_name,actionType:step.action_type,roleCode:step.role_code,assignmentRule:step.assignment_rule,dueDays:step.due_days,commentRequired:Boolean(step.comment_required),attachmentRequired:Boolean(step.attachment_required)})));setAssignees(Object.fromEntries((detail.steps??[]).filter((step:any)=>step.assignee_user_id).map((step:any)=>[String(step.step_order),step.assignee_user_id])))}}).catch(reason=>setError(reason instanceof Error?reason.message:"임시저장 정보를 불러오지 못했습니다.")).finally(()=>setLoadingEdit(false))},[editId,endpoint]);

  useEffect(()=>{setOptionsLoading(true);const templateCode=ecr?"EC_ACTION":"QUALITY_ACTION",params=new URLSearchParams({templateCode,allowProjectless:"1"});if(form.projectId)params.set("projectId",form.projectId);fetch(`/api/workflows/options?${params}`,{cache:"no-store"}).then(json).then(data=>{setSteps(current=>editId&&form.workflowId&&current.length?current:data.steps??[]);setUsers(data.users??[]);if(form.projectId)setAssignees(current=>editId&&form.workflowId&&Object.keys(current).length?current:{...automaticAssignees(data.steps??[],data.members??[]),...current})}).catch(reason=>setError(reason instanceof Error?reason.message:"Workflow 정보를 불러오지 못했습니다.")).finally(()=>setOptionsLoading(false))},[ecr,form.projectId,editId,form.workflowId]);

  const selectedPart=parts.find(item=>item.id===form.partId);
  const visibleParts=useMemo(()=>parts.slice(0,80),[parts]);
  const choosePart=(value:string)=>{const selected=parts.find(item=>`${item.partNumber} · ${item.name} · Rev.${item.revision}`===value||item.id===value||item.partNumber===value||`${item.partNumber} · ${item.name}`===value);setPartSearch(selected?.partNumber||value);setForm((current:any)=>({...current,partId:selected?.id||""}))};
  const selectedDrawing=drawings.find(item=>item.id===form.drawingId);
  const chooseDrawing=(value:string)=>{const selected=drawings.find(item=>drawingLabel(item)===value||item.id===value||item.drawingCode===value||item.name===value);setDrawingSearch(selected?.drawingCode||selected?.name||value);setForm((current:any)=>({...current,drawingId:selected?.id||""}))};
  const drawingProjectMismatch=Boolean(selectedDrawing&&form.projectId&&selectedDrawing.projectId!==form.projectId);
  const missingAssignee=steps.some((step,index)=>index>0&&step.actionType!=="REFERENCE"&&!assignees[String(index)]);
  const workflowReady=!form.projectId||(!optionsLoading&&steps.length>0&&!missingAssignee);
  const projectLocked=Boolean(editId&&form.workflowId);
  const addFiles=(incoming:FileList|File[])=>setFiles(current=>[...current,...Array.from(incoming).filter(file=>!current.some(item=>item.name===file.name&&item.size===file.size))]);
  const save=async()=>{setSaving(true);setError("");try{const body=new FormData();body.set("payload",JSON.stringify({...form,id:editId,assignees,removeAttachmentIds}));files.forEach(file=>body.append("files",file));const data=await fetch(endpoint,{method:editId?"PATCH":"POST",body}).then(json);onCreated(data.workflowId||data.workflow?.id||undefined)}catch(reason){setError(reason instanceof Error?reason.message:"저장하지 못했습니다.")}finally{setSaving(false)}};
  const activeAttachments=attachments.filter(item=>!removeAttachmentIds.includes(item.id));

  return <section className="wv2-workflow-create source wv2-central-create-workspace"><header><div><small>{editId?(ecr?"EDIT DRAFT ENGINEERING CHANGE":"EDIT DRAFT QUALITY CASE"):(ecr?"NEW ENGINEERING CHANGE":"NEW QUALITY CASE")}</small><h1>{editId?(ecr?"설계변경 수정":"품질문제 수정"):(ecr?"새 설계변경":"새 품질문제")}</h1><p>필수정보부터 입력하고 필요한 경우에만 프로젝트·PART·도면을 연결합니다.</p></div><div className="wv2-central-create-actions"><button onClick={onCancel}>취소</button><button className="primary" disabled={saving||loadingEdit||!form.title.trim()||!workflowReady} onClick={save}><Check size={18}/>{saving?"저장 중…":editId?"변경사항 저장":"등록"}</button><button aria-label="작성 탭 닫기" onClick={onCancel}><X size={18}/></button></div></header>
  <main><div className="wv2-source-clean-main">

    <section className="wv2-source-basic-card"><div className="wv2-source-card-head"><div><h2>기본정보</h2><p>업무를 생성하기 위한 핵심정보입니다.</p></div><em>제목 필수</em></div>
      {ecr?<div className="wv2-source-basic-grid ecr"><label className="title"><span>변경 제목 *</span><input autoFocus value={form.title} onChange={event=>setForm({...form,title:event.target.value})}/></label><label><span>설계변경 유형</span><select value={form.changeType||""} onChange={event=>setForm({...form,changeType:event.target.value})}><option value="">선택</option>{designChangeTypes.map(item=><option key={item.code} value={item.code}>{item.label}</option>)}</select></label><label><span>우선순위</span><select value={form.priority||"normal"} onChange={event=>setForm({...form,priority:event.target.value})}><option value="normal">보통</option><option value="high">높음</option><option value="urgent">긴급</option></select></label><label><span>처리기한</span><input type="date" value={form.dueDate||""} onChange={event=>setForm({...form,dueDate:event.target.value})}/></label></div>:<div className="wv2-source-basic-grid quality"><label className="title"><span>문제 제목 *</span><input autoFocus value={form.title} onChange={event=>setForm({...form,title:event.target.value})}/></label><label><span>발생일</span><input type="date" value={form.occurredOn||""} onChange={event=>setForm({...form,occurredOn:event.target.value})}/></label><label><span>문제 유형</span><select value={form.issueType||""} onChange={event=>setForm({...form,issueType:event.target.value})}><option value="">선택</option>{qualityIssueTypes.map(item=><option key={item.code} value={item.code}>{item.label}</option>)}</select></label><label><span>심각도</span><select value={form.severity||"medium"} onChange={event=>setForm({...form,severity:event.target.value})}><option value="low">낮음</option><option value="medium">보통</option><option value="high">높음</option><option value="critical">심각</option></select></label><label><span>처리기한</span><input type="date" value={form.dueDate||""} onChange={event=>setForm({...form,dueDate:event.target.value})}/></label></div>}
    </section>

    <section className="wv2-source-reference-card"><div className="wv2-source-card-head"><div><h2>관련 대상</h2><p>프로젝트, PART, 도면은 모두 선택사항입니다.</p></div><em>선택</em></div><div className="wv2-source-reference-grid">
      <label><span>프로젝트</span><select disabled={projectLocked} value={form.projectId||""} onChange={event=>setForm({...form,projectId:event.target.value})}><option value="">연결 안 함</option>{projects.map(item=><option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label>
      <label><span>관련 PART</span><input list={`${kind.toLowerCase()}-part-options`} value={partSearch} placeholder={partLoading?"PART 검색 중…":"PART Code·품명·사양 검색"} onChange={event=>choosePart(event.target.value)}/><datalist id={`${kind.toLowerCase()}-part-options`}>{visibleParts.map(item=><option key={item.id} value={`${item.partNumber} · ${item.name} · Rev.${item.revision}`}/>)}</datalist></label>
      <label><span>관련 도면</span><input list={`${kind.toLowerCase()}-drawing-options`} value={drawingSearch} placeholder={drawingLoading?"도면 검색 중…":"전사 도면코드·도면명·프로젝트 검색"} onChange={event=>chooseDrawing(event.target.value)}/><datalist id={`${kind.toLowerCase()}-drawing-options`}>{drawings.map(item=><option key={item.id} value={drawingLabel(item)}/>)}</datalist></label>
    </div>
    {(selectedPart||selectedDrawing)&&<div className="wv2-source-reference-summary">{selectedPart&&<div className="wv2-source-ref-chip"><span><b>{selectedPart.partNumber} · {selectedPart.name}</b><small>{selectedPart.partType} · Rev.{selectedPart.revision}{selectedPart.spec?` · ${selectedPart.spec}`:""}</small></span><button aria-label="PART 연결 해제" onClick={()=>{setForm((current:any)=>({...current,partId:""}));setPartSearch("")}}><X size={18}/></button></div>}{selectedDrawing&&<div className="wv2-source-ref-chip"><span><b>{selectedDrawing.drawingCode||"도면코드 없음"} · {selectedDrawing.name}</b><small>{selectedDrawing.projectCode} · {selectedDrawing.projectName}</small></span><button aria-label="도면 연결 해제" onClick={()=>{setForm((current:any)=>({...current,drawingId:""}));setDrawingSearch("")}}><X size={18}/></button></div>}</div>}
    {!form.projectId&&<p className="wv2-source-reference-note">프로젝트 없이 등록하면 회사 공통 Draft로 저장됩니다. 이후 프로젝트를 연결하면 해당 프로젝트 Workflow가 생성됩니다.</p>}
    {projectLocked&&<p className="wv2-source-reference-note">Workflow가 생성된 건은 프로젝트를 변경할 수 없습니다.</p>}
    {drawingProjectMismatch&&<p className="wv2-source-reference-note warning">선택한 도면은 다른 프로젝트 소속입니다. 도면은 참조만 연결되고 해당 도면의 Task는 현재 Workflow에 연결되지 않습니다.</p>}
    {!partLoading&&partSearch.trim()&&!parts.length&&<p className="wv2-source-reference-note">조건에 맞는 PART가 없습니다. PART 없이 등록할 수 있습니다.</p>}
    {!drawingLoading&&drawingSearch.trim()&&!drawings.length&&<p className="wv2-source-reference-note">조건에 맞는 도면이 없습니다. 도면 없이 등록할 수 있습니다.</p>}
    </section>

    <section className="wv2-source-detail-card"><div className="wv2-source-card-head"><div><h2>{ecr?"설계변경 상세":"품질문제 상세"}</h2><p>{ecr?"변경 전·후 내용과 사유·영향을 기록합니다.":"문제 내용과 원인·조치·효과검증을 기록합니다."}</p></div></div><div className="wv2-source-detail-grid">
      {ecr?<><div className="two"><label><span>변경 전 내용</span><textarea rows={4} value={form.beforeContent||""} onChange={event=>setForm({...form,beforeContent:event.target.value})}/></label><label><span>변경 후 내용</span><textarea rows={4} value={form.afterContent||""} onChange={event=>setForm({...form,afterContent:event.target.value})}/></label></div><div className="two"><label><span>변경 사유</span><textarea rows={4} value={form.reason||""} onChange={event=>setForm({...form,reason:event.target.value})}/></label><label><span>영향</span><textarea rows={4} value={form.impactContent||""} onChange={event=>setForm({...form,impactContent:event.target.value})}/></label></div></>:<><label><span>문제 내용</span><textarea rows={4} value={form.description||""} onChange={event=>setForm({...form,description:event.target.value})}/></label><div className="two"><label><span>원인분석</span><textarea rows={4} value={form.rootCause||""} onChange={event=>setForm({...form,rootCause:event.target.value})}/></label><label><span>개선조치</span><textarea rows={4} value={form.correctiveAction||""} onChange={event=>setForm({...form,correctiveAction:event.target.value})}/></label></div><label><span>효과검증</span><textarea rows={3} value={form.effectivenessCheck||""} onChange={event=>setForm({...form,effectivenessCheck:event.target.value})}/></label></>}
    </div></section>

    <section className="wv2-source-workflow-card"><div className="wv2-source-card-head"><div><h2>Workflow</h2><p>{form.projectId?"선택한 프로젝트의 Workflow 단계와 담당자를 확인합니다.":"프로젝트와 무관하게 템플릿 Workflow 단계는 미리 확인할 수 있습니다."}</p></div></div><section className="wv2-workflow-line wv2-source-assignee-line">{steps.map((step,index)=><article key={`${index}-${step.name}`}><b>{index+1}</b><span><strong>{step.name}</strong><small>{actionLabels[step.actionType]} · {step.roleCode||step.assignmentRule}</small></span>{index===0?<em>요청자 자동</em>:form.projectId?<OrganizationAssigneeSelect users={users} value={assignees[String(index)]||""} onChange={value=>setAssignees({...assignees,[String(index)]:value})} required={step.actionType!=="REFERENCE"}/>:<em>프로젝트 연결 후 지정</em>}</article>)}{optionsLoading&&<p className="wv2-workflow-hint">Workflow 단계를 불러오는 중…</p>}{!optionsLoading&&!steps.length&&<p className="wv2-workflow-hint">사용 가능한 Workflow 단계를 찾지 못했습니다.</p>}</section>{!form.projectId&&<p className="wv2-source-reference-note">프로젝트를 선택하면 PM·PL 등 프로젝트 기준 담당자 자동배정과 수동 담당자 지정이 활성화됩니다.</p>}</section>

    <section className={`wv2-source-attachment-compact${dragging?" dragging":""}`} onDragOver={event=>{event.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={event=>{event.preventDefault();setDragging(false);addFiles(event.dataTransfer.files)}}><div className="wv2-source-attachment-head"><div><h2>관련 문서</h2><p>필요한 문서만 간단히 첨부하세요. 파일을 이 영역에 끌어 놓아도 됩니다.</p></div><div><em>{activeAttachments.length+files.length}개</em><button type="button" onClick={()=>fileInput.current?.click()}><Upload size={18}/>파일 첨부</button></div></div>{(activeAttachments.length>0||files.length>0)&&<div className="wv2-source-attachment-chips">{activeAttachments.map(item=><div className="wv2-source-file-chip" key={item.id}><FileText size={18}/><span><b>{item.fileName}</b><small>{Math.max(1,Math.round(Number(item.fileSize||0)/1024))} KB</small></span><button aria-label="첨부 삭제 예약" onClick={()=>setRemoveAttachmentIds(current=>[...current,item.id])}><Trash2 size={18}/></button></div>)}{files.map((file,index)=><div className="wv2-source-file-chip" key={`${file.name}-${file.size}-${index}`}><FileText size={18}/><span><b>{file.name}</b><small>{Math.max(1,Math.round(file.size/1024))} KB</small></span><button aria-label="첨부 취소" onClick={()=>setFiles(current=>current.filter((_,cursor)=>cursor!==index))}><X size={18}/></button></div>)}</div>}<input ref={fileInput} hidden type="file" multiple onChange={event=>event.target.files&&addFiles(event.target.files)}/></section>

    {error&&<p className="wv2-workflow-error">{error}</p>}
  </div></main></section>;
}

function drawingLabel(item:DrawingOption){return `${item.drawingCode||"도면코드 없음"} · ${item.name} · ${item.projectCode} ${item.projectName}`}
