"use client";

import {useEffect,useMemo,useState,type FormEvent} from "react";
import {Plus,RefreshCw,Settings2,Trash2} from "lucide-react";
import {SystemSettingsPanel} from "./system-settings-panel";
import "./system-project-cost-settings.css";

type GroupCode="MATERIAL"|"EXPENSE"|"OUTSOURCE"|"OTHER";
type Category={id:string;code:string;groupCode:GroupCode;name:string;sourceType:"BOM"|"MANUAL";enabled:number;sortOrder:number};
const GROUP_NAMES:Record<GroupCode,string>={MATERIAL:"재료비",EXPENSE:"경비",OUTSOURCE:"외주비",OTHER:"기타"};
const empty=()=>({code:"",groupCode:"EXPENSE" as GroupCode,name:"",enabled:true,sortOrder:90});

export function SystemProjectCostSettings(){
  const [categories,setCategories]=useState<Category[]>([]),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[notice,setNotice]=useState("");
  const [editing,setEditing]=useState<Category|null>(null),[form,setForm]=useState(empty()),[panelOpen,setPanelOpen]=useState(false);
  const load=async()=>{setLoading(true);try{const response=await fetch("/api/project-cost-categories",{cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.error||"비용 카테고리를 불러오지 못했습니다.");setCategories(result.categories??[]);setNotice("")}catch(reason){setNotice(reason instanceof Error?reason.message:"비용 카테고리를 불러오지 못했습니다.")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const grouped=useMemo(()=>Object.fromEntries((Object.keys(GROUP_NAMES) as GroupCode[]).map(group=>[group,categories.filter(row=>row.groupCode===group)])) as Record<GroupCode,Category[]>,[categories]);
  const open=(row?:Category)=>{setEditing(row||null);setForm(row?{code:row.code,groupCode:row.groupCode,name:row.name,enabled:row.enabled!==0,sortOrder:row.sortOrder}:empty());setNotice("");setPanelOpen(true)};
  const close=()=>{setPanelOpen(false);setEditing(null);setForm(empty());setNotice("")};
  const save=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setSaving(true);setNotice("");try{const response=await fetch("/api/project-cost-categories",{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(editing?{id:editing.id,...form}:form)});const result=await response.json();if(!response.ok)throw new Error(result.error||"비용 카테고리를 저장하지 못했습니다.");close();await load()}catch(reason){setNotice(reason instanceof Error?reason.message:"비용 카테고리를 저장하지 못했습니다.")}finally{setSaving(false)}};
  const remove=async(row:Category)=>{if(!window.confirm(`'${row.name}' 비용 카테고리를 삭제할까요?`))return;const response=await fetch("/api/project-cost-categories",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id:row.id})});const result=await response.json();if(!response.ok){setNotice(result.error||"삭제하지 못했습니다.");return}await load()};
  return <section className="spcs"><header><div><small>PROJECT COST CATEGORY</small><h2>프로젝트 비용 카테고리</h2><p>1레벨은 재료비·경비·외주비·기타로 고정하고, 2레벨 항목은 회사별로 관리합니다.</p></div><div><button onClick={()=>void load()} disabled={loading}><RefreshCw size={18}/>{loading?"불러오는 중":"새로고침"}</button><button className="primary" onClick={()=>open()}><Plus size={18}/>카테고리 추가</button></div></header>{notice&&!panelOpen&&<p className="wv2-module-notice">{notice}</p>}<div className="spcs-grid">{(Object.keys(GROUP_NAMES) as GroupCode[]).map(group=><section key={group}><header><div><Settings2 size={18}/><b>{GROUP_NAMES[group]}</b></div><span>{grouped[group].length}개</span></header>{grouped[group].map(row=><article key={row.id}><button onClick={()=>row.sourceType!=="BOM"&&open(row)}><b>{row.name}</b><span>{row.code}</span></button><i>{row.sourceType==="BOM"?"BOM 자동":"일반 LOV"}</i><em>{row.enabled!==0?"사용":"사용 안 함"}</em>{row.sourceType!=="BOM"&&<button className="danger" onClick={()=>void remove(row)} aria-label={`${row.name} 삭제`}><Trash2 size={17}/></button>}</article>)}</section>)}</div>{panelOpen&&<SystemSettingsPanel kicker="PROJECT COST CATEGORY" title={editing?"비용 카테고리 수정":"비용 카테고리 추가"} description="프로젝트 비용 등록 화면에서 선택하는 회사 공통 LOV입니다." onClose={close} onSubmit={save} submitLabel={editing?"변경 저장":"등록"} saving={saving}><div className="two"><label><span>1레벨 *</span><select value={form.groupCode} onChange={e=>setForm({...form,groupCode:e.target.value as GroupCode})}>{Object.entries(GROUP_NAMES).map(([code,name])=><option key={code} value={code}>{name}</option>)}</select></label><label><span>사용 여부</span><select value={form.enabled?"active":"inactive"} onChange={e=>setForm({...form,enabled:e.target.value==="active"})}><option value="active">사용</option><option value="inactive">사용 안 함</option></select></label></div><label><span>코드 *</span><input required disabled={Boolean(editing)} value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase().replace(/\s+/g,"_")})} placeholder="예: EXPENSE_TRAVEL"/></label><label><span>2레벨 비용 항목 *</span><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="예: 출장비"/></label><label><span>정렬 순서</span><input type="number" value={form.sortOrder} onChange={e=>setForm({...form,sortOrder:Number(e.target.value)})}/></label>{notice&&<p className="notice">{notice}</p>}</SystemSettingsPanel>}</section>;
}
