"use client";
import {useCallback,useEffect,useState} from 'react';
import {Download,Eye,RefreshCw,MessagesSquare} from 'lucide-react';
import type {V2Project} from './project-workspaces';
import {trrVersionLabel,type TrrList} from '../../lib/trr-contract';
import {uploadTime} from './customer-data-workspace';
import CommonAiChatPanel from '../common-ai-chat-panel';
import {WorkPanelFrame} from './work-panel';
import './trr-workspace.css';
export default function TrrWorkspace({project,onCloseAi}:{project:V2Project;onCloseAi:()=>void}){
 const [data,setData]=useState<TrrList|null>(null),[error,setError]=useState(''),[selected,setSelected]=useState<string[]>([]),[chatIds,setChatIds]=useState<string[]>([]),[wide,setWide]=useState(true),[busy,setBusy]=useState(false);
 const url=`/api/projects/${project.id}/trr`;
 const refresh=useCallback(async(signal?:AbortSignal)=>{try{const r=await fetch(url,{cache:'no-store',signal}),d=await r.json();if(!r.ok)throw Error(d.error);setData(d);setError('');}catch(e){if(!signal?.aborted)setError((e as Error).message)}},[url]);
 useEffect(()=>{const c=new AbortController();void refresh(c.signal);const focus=()=>void refresh(c.signal),timer=window.setInterval(focus,5000);window.addEventListener('focus',focus);return()=>{c.abort();clearInterval(timer);window.removeEventListener('focus',focus)}},[refresh]);
 const generate=async()=>{if(busy)return;setBusy(true);setError('');try{const r=await fetch(url,{method:'POST'}),d=await r.json();if(!r.ok)throw Error(d.error);await refresh();}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const versions=data?.versions??[],chosen=versions.filter(v=>chatIds.includes(v.id));
 return <><div className="wv2-toolbar"><button onClick={()=>void refresh()}><RefreshCw size={18}/>새로고침</button><button disabled={selected.length<2} onClick={()=>{onCloseAi();setChatIds([...selected]);setWide(true)}}><MessagesSquare size={18}/>선택 버전 AI 비교</button><button className="production-edit-all" disabled={busy||!data?.canGenerate||data.job?.status==='running'} onClick={()=>void generate()}><RefreshCw size={18}/>{data?.job?.status==='failed'?'생성 재시도':'TRR 갱신'}</button><span className="cswind-data-count">{versions.length}개 버전</span></div>
 <section className="wv2-canvas trr-canvas">{error&&<p className="wv2-form-error" role="alert">{error}</p>}{!busy&&data?.job?.status==='failed'&&<p className="wv2-form-error" role="alert">{data.job.error} {versions.length?'기존 보고서는 유지됩니다.':'이번 보고서는 생성되지 않았습니다.'}</p>}{busy?<p role="status">TRR 생성 요청 중입니다.</p>:data?.job?.status==='running'&&<p role="status">TRR 생성 중입니다. 다른 탭으로 이동해도 작업은 계속됩니다.</p>}
 <div className="cswind-data-table"><table className="production-table trr-history-table"><thead><tr><th>선택</th><th>버전</th><th>보고서</th><th>업데이트 내용</th><th>반영 자료</th><th>생성 일시</th><th>미리보기</th><th>Word</th></tr></thead><tbody>{versions.map((v,index)=><tr key={v.id}><td><input type="checkbox" aria-label={`${trrVersionLabel(v.version)} 비교 선택`} checked={selected.includes(v.id)} disabled={!selected.includes(v.id)&&selected.length>=5} onChange={e=>setSelected(ids=>e.target.checked?[...ids,v.id]:ids.filter(id=>id!==v.id))}/></td><td>{trrVersionLabel(v.version)}{index===0?' · 최신':''}</td><td>{project.name} TRR</td><td className="trr-summary">{v.summary}</td><td>{v.sourceCount}건</td><td>{uploadTime(v.createdAt)}</td><td><button aria-label={`${trrVersionLabel(v.version)} 미리보기`} onClick={()=>{const w=window.open(`${url}/${v.id}?preview=1`,'_blank',`popup=yes,width=${window.screen.availWidth},height=${window.screen.availHeight},left=0,top=0,resizable=yes,scrollbars=yes`);if(!w)setError('미리보기 팝업 차단을 해제해 주세요.');else w.opener=null;}}><Eye size={18}/></button></td><td><a href={`${url}/${v.id}`} aria-label={`${trrVersionLabel(v.version)} Word 다운로드`}><Download size={18}/></a></td></tr>)}{!versions.length&&<tr><td colSpan={8}>{!data?'TRR 이력을 불러오는 중…':'생성된 TRR이 없습니다. 고객 Data에 TRR 자료를 등록하면 보고서를 생성합니다.'}</td></tr>}</tbody></table></div></section>
 {chatIds.length>0&&<WorkPanelFrame eyebrow="TRR AI REVIEW" title="TRR 버전 비교" description={chosen.map(v=>trrVersionLabel(v.version)).join(' · ')} wide={wide} onWide={()=>setWide(value=>!value)} onClose={()=>setChatIds([])}><CommonAiChatPanel key={chatIds.join(':')} projectName={project.name} source="TRR 업데이트 이력" contextType="trr-review" contextTitle={`${project.name} TRR 버전 비교`} trrContext={{projectId:project.id,versionIds:chatIds}} items={chosen.map(v=>({id:v.id,kind:'TRR 버전',title:`${project.name} ${trrVersionLabel(v.version)}`}))}/></WorkPanelFrame>}
 </>;
}
