"use client";
import {useEffect,useRef,useState} from "react";
import {Check,ChevronRight,Clock3,FileText,PanelRightClose,PanelRightOpen,Paperclip,Pencil,RefreshCw,ShieldCheck,Sparkles,Trash2,X} from "lucide-react";
import {useAiContextSelection} from "./ai-context-selection";
import {ConnectedAiPanel} from "./connected-ai-panel";
import type {AiDraftRequest,ContextItem} from "./connected-ai-workspaces";
import "./document-management-panel.css";
import "./workflow-detail-panel-v2.css";

type WorkflowRow={id:string;workflowNumber:string;title:string;sourceType:string;dueDate?:string;status:string;currentStepOrder:number;projectCode:string;projectName:string;templateName:string;currentStepName?:string;currentAssigneeName?:string;stepCount:number;stepFlow?:string};
const statusLabels:Record<string,string>={draft:"임시저장",in_progress:"결재 진행 중",supplement:"보완",approved:"승인 완료",rejected:"반려",recalled:"회수"};
const actionLabels:Record<string,string>={WRITE:"작성",PROCESS:"처리",REVIEW:"검토",AGREEMENT:"합의",APPROVAL:"승인",REFERENCE:"참조"};
const workflowTypeLabels:Record<string,string>={GENERAL:"일반",ECR:"설계변경",QUALITY:"품질관리",GATE:"Gate"};
const workflowTypeLabel=(value?:string)=>workflowTypeLabels[String(value||"GENERAL").toUpperCase()]||value||"일반";
const severityLabels:Record<string,string>={low:"낮음",medium:"보통",high:"높음",critical:"심각"};
const priorityLabels:Record<string,string>={normal:"보통",high:"높음",urgent:"긴급"};
const json=async(response:Response)=>{const text=await response.text();let data:any={};if(text){try{data=JSON.parse(text)}catch{data={error:text}}}if(!response.ok){if(response.status===413)throw new Error("파일 업로드 요청이 서버에서 거부되었습니다.");throw new Error(data.error||`요청을 처리하지 못했습니다. (${response.status})`)}return data};
const aiCheckboxStyle={width:15,height:15,margin:0,accentColor:"var(--teal)",cursor:"pointer",flex:"0 0 auto"} as const;
const fmtDateTime=(value:any)=>{const numeric=Number(value);if(!numeric)return "";return new Date(numeric*1000).toLocaleString("ko-KR")};

export function WorkflowStageList({rows,onOpen}:{rows:WorkflowRow[];onOpen:(id:string)=>void}){
  const selection=useAiContextSelection("워크플로우");
  const contextFor=(row:WorkflowRow)=>({id:row.id,kind:"워크플로우",title:`[${row.workflowNumber}] ${row.title}`,meta:`${row.projectName} · ${workflowTypeLabel(row.sourceType)} · 현재 단계 ${row.currentStepName||"작성"} · 처리자 ${row.currentAssigneeName||"미배정"} · 기한 ${row.dueDate||"미정"} · ${statusLabels[row.status]||row.status}`});
  const allSelected=Boolean(rows.length)&&rows.every(row=>selection.has(contextFor(row)));
  const toggleAll=()=>rows.forEach(row=>{const item=contextFor(row);if(allSelected?selection.has(item):!selection.has(item))selection.toggle(item)});
  return <div className="wv2-workflow-table stage-table"><header><span style={{display:"flex",alignItems:"center",gap:8}}><input type="checkbox" aria-label="워크플로우 전체 선택" checked={allSelected} onChange={toggleAll} style={aiCheckboxStyle}/>워크플로우</span><span>대상 프로젝트</span><span>전체 단계</span><span>현재 단계·처리자</span><span>기한</span><span>상태</span><span/></header>{rows.map(row=>{const flow=String(row.stepFlow||"").split("~").filter(Boolean).map(value=>{const [name,status]=value.split("|");return {name,status}}),item=contextFor(row),checked=selection.has(item);return <button key={row.id} onClick={()=>onOpen(row.id)}><span className="workflow-primary" style={{display:"flex",alignItems:"flex-start",gap:8}}><input type="checkbox" aria-label="워크플로우 AI 선택" checked={checked} onClick={event=>event.stopPropagation()} onChange={event=>{event.stopPropagation();selection.toggle(item)}} style={{...aiCheckboxStyle,marginTop:2}}/><span style={{display:"grid",minWidth:0}}><b><em className="workflow-type-badge">{workflowTypeLabel(row.sourceType)}</em>{row.title}</b><small>{row.workflowNumber} · {row.templateName}</small></span></span><span><b>{row.projectName}</b><small>{row.projectCode}</small></span><span className="wv2-stage-flow">{flow.length?flow.map((step,index)=><i key={`${index}-${step.name}`} className={step.status} title={`${index+1}. ${step.name}`}><b>{index+1}</b><small>{step.name}</small></i>):<small>{row.currentStepOrder+1}/{row.stepCount}단계</small>}</span><span><b>{row.currentStepName||"작성"}</b><small>{row.currentAssigneeName||"미배정"}</small></span><span><b>{row.dueDate||"미정"}</b><small>{row.dueDate&&row.dueDate<new Date().toISOString().slice(0,10)&&row.status==="in_progress"?"지연":""}</small></span><em className={`status ${row.status}`}>{statusLabels[row.status]||row.status}</em><ChevronRight size={18}/></button>})}</div>;
}

export function WorkflowDetailPanel({id,onClose,onChanged,onOpenDocuments,onEdit,onDeleted}:{id:string;onClose:()=>void;onChanged:()=>void;onOpenDocuments:(deliverableId:string)=>void;onEdit?:(sourceId:string)=>void;onDeleted?:()=>void}){
  const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[comment,setComment]=useState(""),[wide,setWide]=useState(true),[sectionTab,setSectionTab]=useState<"workflow"|"request"|"documents"|"ai">("workflow"),[deleteConfirm,setDeleteConfirm]=useState(false),[saving,setSaving]=useState(false),[outputUploading,setOutputUploading]=useState(false),[outputDeleting,setOutputDeleting]=useState(""),[error,setError]=useState("");
  const [selectedDocuments,setSelectedDocuments]=useState<string[]>([]),[aiDraft,setAiDraft]=useState<AiDraftRequest|null>(null);
  const outputInputRef=useRef<HTMLInputElement>(null);
  const load=()=>{setLoading(true);setError("");return fetch(`/api/workflows/${id}`,{cache:"no-store"}).then(json).then(async detail=>{const sourceType=String(detail.workflow?.source_type||"").toUpperCase(),sourceId=String(detail.workflow?.source_id||"");if(sourceId&&["ECR","QUALITY"].includes(sourceType)){const endpoint=sourceType==="ECR"?"/api/ecr":"/api/quality";const source=await fetch(`${endpoint}?id=${encodeURIComponent(sourceId)}`,{cache:"no-store"}).then(json);detail.sourceInfo=source.item??null;detail.sourceAttachments=source.attachments??[]}setData(detail)}).catch(reason=>setError(reason.message)).finally(()=>setLoading(false))};
  useEffect(()=>{setSectionTab("workflow");setSelectedDocuments([]);setAiDraft(null);void load()},[id]);
  const act=async(action:string)=>{setSaving(true);setError("");try{await fetch(`/api/workflows/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action,comment})}).then(json);setComment("");await load();onChanged()}catch(reason){setError(reason instanceof Error?reason.message:"처리하지 못했습니다.")}finally{setSaving(false)}};
  const removeDraft=async()=>{setSaving(true);setError("");try{await fetch(`/api/workflows/${id}`,{method:"DELETE"}).then(json);onDeleted?.();onClose()}catch(reason){setError(reason instanceof Error?reason.message:"임시저장 Workflow를 삭제하지 못했습니다.")}finally{setSaving(false)}};
  if(loading)return <aside className="wv2-panel wide"><div className="wv2-panel-loading"><RefreshCw size={30}/><b>Workflow 상세를 불러오는 중…</b></div></aside>;
  if(!data)return <aside className="wv2-panel wide"><header><div><small>WORKFLOW DETAIL</small><h2>상세정보를 불러오지 못했습니다.</h2><span>{error||"잠시 후 다시 시도해 주세요."}</span></div><div><button aria-label="다시 시도" onClick={()=>void load()}><RefreshCw size={18}/></button><button aria-label="닫기" onClick={onClose}><X size={18}/></button></div></header></aside>;
  const w=data.workflow,steps=data.steps??[],history=data.history??[],documents=data.documents??[],linkedDocuments=data.linkedDocuments??[],sourceAttachments=data.sourceAttachments??[],sourceInfo=data.sourceInfo??null,current=steps.find((step:any)=>Number(step.step_order)===Number(w.current_step_order)),canAct=Boolean(data.permissions?.canAct),canManageDraft=w.status==="draft"&&Boolean(data.permissions?.isRequester||data.permissions?.isAdmin),sourceType=String(w.source_type||"GENERAL").toUpperCase();
  const stageOutputs=documents.filter((item:any)=>String(item.documentAction||"").toUpperCase()==="OUTPUT"),outputDeliverableIds=new Set(stageOutputs.map((item:any)=>String(item.deliverableId))),initialDocuments=linkedDocuments.filter((item:any)=>!outputDeliverableIds.has(String(item.deliverableId))),currentOutputs=current?stageOutputs.filter((item:any)=>String(item.stepId)===String(current.id)):[];
  const uploadStageOutputs=async(files:FileList|null)=>{if(!files?.length)return;setOutputUploading(true);setError("");try{for(const selected of Array.from(files)){const body=new FormData();body.set("file",selected);body.set("name",selected.name.replace(/\.[^.]+$/,""));body.set("category","COMMON_ETC");body.set("ownerUserId",String(data.permissions?.viewerUserId||""));const created=await fetch(`/api/projects/${w.project_id}/deliverables`,{method:"POST",body}).then(json);await fetch(`/api/workflows/${id}/outputs`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({deliverableId:created.deliverableId,versionId:created.id})}).then(json)}await load();onChanged()}catch(reason){setError(reason instanceof Error?reason.message:"단계 산출물을 등록하지 못했습니다.")}finally{setOutputUploading(false);if(outputInputRef.current)outputInputRef.current.value=""}};
  const removeStageOutput=async(item:any)=>{if(!window.confirm(`잘못 첨부한 산출물 '${item.fileName||item.name}'을 삭제할까요?`))return;const key=String(item.versionId||item.id);setOutputDeleting(key);setError("");try{await fetch(`/api/workflows/${id}/outputs`,{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({deliverableId:item.deliverableId,versionId:item.versionId})}).then(json);setSelectedDocuments(current=>current.filter(value=>value!==String(item.deliverableId)));await load();onChanged()}catch(reason){setError(reason instanceof Error?reason.message:"단계 산출물을 삭제하지 못했습니다.")}finally{setOutputDeleting("")}};
  const currentNumber=Number(w.current_step_order||0)+1,totalSteps=steps.length;
  const documentContext=(item:any,kind:string,stepName?:string):ContextItem=>({id:String(item.deliverableId||""),kind:"문서",title:item.name||item.fileName||item.latestFileName||"문서",meta:`${kind}${stepName?` · ${stepName}`:""} · ${item.fileName||item.latestFileName||item.name||""} · ${w.projectName}`,fileName:item.fileName||item.latestFileName||undefined,revision:Number(item.revision||item.latestRevision||0)||undefined,fileAttached:Boolean(item.versionId||item.latestVersionId)});
  const sourceAttachmentContext=(item:any):ContextItem=>({id:String(item.id||""),kind:"요청 첨부문서",title:item.fileName||"요청 첨부문서",meta:`요청 첨부문서 · ${Math.max(1,Math.ceil(Number(item.fileSize||0)/1024)).toLocaleString()} KB · ${w.projectName}`,fileName:item.fileName||undefined,fileAttached:true});
  const allDocumentContexts=[...initialDocuments.filter((item:any)=>item.latestVersionId).map((item:any)=>documentContext(item,"상신 문서")),...steps.flatMap((step:any)=>stageOutputs.filter((item:any)=>String(item.stepId)===String(step.id)).map((item:any)=>documentContext(item,"단계 산출물",step.name))),...sourceAttachments.map((item:any)=>sourceAttachmentContext(item))];
  const selectedContexts=allDocumentContexts.filter(item=>selectedDocuments.includes(String(item.id)));
  const toggleDocument=(documentId:string)=>setSelectedDocuments(current=>current.includes(documentId)?current.filter(value=>value!==documentId):[...current,documentId]);
  const openAiConversation=()=>{if(!selectedContexts.length)return;const prompt=selectedContexts.length>1?"선택한 요청 첨부문서, 상신 문서와 단계별 산출물을 비교해서 핵심 변경점, 부서별 검토 결과, 영향 및 최종 승인 전에 확인할 사항을 정리해줘":"선택한 Workflow 문서의 핵심 내용과 검토 필요사항을 정리해줘";setAiDraft({key:Date.now(),prompt,contextItems:selectedContexts,source:`${workflowTypeLabel(sourceType)} Workflow 문서 비교`});setSectionTab("ai")};
  const projectContext={id:String(w.project_id),code:String(w.projectCode||""),name:String(w.projectName||"")};
  return <aside className={`wv2-panel${wide?" wide":""}`}>
    <div className="wv2-resize"/>
    <header><div><small>{w.workflow_number}</small><h2>{w.title}</h2><span>{w.projectCode} · {w.projectName}</span></div><div><button aria-label={wide?"기본 너비":"넓게 보기"} onClick={()=>setWide(value=>!value)}>{wide?<PanelRightOpen size={18}/>:<PanelRightClose size={18}/>}</button><button aria-label="닫기" onClick={onClose}><X size={18}/></button></div></header>
    <nav><button className={sectionTab==="workflow"?"active":""} onClick={()=>setSectionTab("workflow")}>워크플로우</button><button className={sectionTab==="request"?"active":""} onClick={()=>setSectionTab("request")}>요청정보</button><button className={sectionTab==="documents"?"active":""} onClick={()=>setSectionTab("documents")}>문서·산출물</button><button className={sectionTab==="ai"?"active":""} onClick={()=>setSectionTab("ai")}>AI 대화</button></nav>
    <section className="wv2-panel-body wv2-workflow-panel-content">
      {sectionTab==="workflow"&&<>
        <section className="wv2-workflow-quick-status"><span className={`status ${w.status}`}>{statusLabels[w.status]||w.status}</span><b>현재 {currentNumber}/{totalSteps} · {current?.name||"단계 미정"}</b><span>담당 {current?.assigneeName||"미배정"}</span><span>기한 {w.due_date||"미정"}</span></section>
        {canManageDraft&&<section className="wv2-draft-management compact"><div><b>임시저장 관리</b><small>결재 요청 전까지 수정·삭제할 수 있습니다.</small></div><div>{onEdit&&<button onClick={()=>onEdit(w.source_id||w.id)}><Pencil size={17}/>정보 수정</button>}{deleteConfirm?<><button onClick={()=>setDeleteConfirm(false)}>취소</button><button className="danger" disabled={saving} onClick={removeDraft}><Trash2 size={17}/>{saving?"삭제 중…":"삭제 확인"}</button></>:<button className="danger" onClick={()=>setDeleteConfirm(true)}><Trash2 size={17}/>삭제</button>}</div></section>}
        <section className="wv2-workflow-step-history"><header><h3>단계별 처리 현황</h3><small>단계·담당자·처리 결과·의견을 한 번에 확인합니다.</small></header>{steps.map((step:any)=>{const related=history.filter((item:any)=>String(item.stepName||"")===String(step.name||"")||Number(item.step_order)===Number(step.step_order)),comments=related.filter((item:any)=>item.comment&&item.action!=="STEP_OUTPUT_ADDED"),outputCount=stageOutputs.filter((item:any)=>String(item.stepId)===String(step.id)).length;return <article key={step.id} className={`step-card ${step.status}`}><i>{step.status==="completed"?<Check size={17}/>:<Clock3 size={17}/>}</i><div><b>{Number(step.step_order)+1}. {step.name}</b><small>{actionLabels[step.action_type]} · {step.assigneeName||step.role_code||"미배정"}{related.length?` · 처리 ${related.length}건`:""}{outputCount?` · 산출물 ${outputCount}건`:""}</small>{comments.slice(-2).map((item:any)=><p key={item.id}><strong>{item.actorName}</strong> {item.comment}<em>{fmtDateTime(item.created_at)}</em></p>)}</div><span>{step.status==="completed"?"완료":step.status==="active"?"처리 중":step.status==="rejected"?"반려":"대기"}</span></article>})}</section>
        {!["approved","rejected"].includes(w.status)&&canAct&&<section className="action wv2-current-step-action"><div className="wv2-current-step-action-head"><h3>{currentNumber}. {current?.name||"현재 단계"} · {actionLabels[current?.action_type]||"처리"}</h3><button type="button" className="wv2-step-attachment-add" disabled={outputUploading} onClick={()=>outputInputRef.current?.click()}><Paperclip size={15}/>{outputUploading?"등록 중…":"+ 산출물 추가"}</button><input ref={outputInputRef} hidden multiple type="file" onChange={event=>void uploadStageOutputs(event.target.files)}/></div><textarea rows={3} value={comment} onChange={event=>setComment(event.target.value)} placeholder={current?.comment_required?"처리 의견을 반드시 입력하세요.":"처리 의견을 입력하세요."}/><div>{["draft","supplement","recalled"].includes(w.status)?<button className="primary" disabled={saving} onClick={()=>act(w.status==="supplement"?"RESUBMIT":"SUBMIT")}>결재 요청</button>:<><button className="primary" disabled={saving} onClick={()=>act(current?.action_type||"COMPLETE")}>{actionLabels[current?.action_type]||"처리"}</button><button disabled={saving} onClick={()=>act("SUPPLEMENT")}>보완 요청</button><button className="danger" disabled={saving} onClick={()=>act("REJECT")}>반려</button>{data.permissions?.isRequester&&<button disabled={saving} onClick={()=>act("RECALL")}>회수</button>}</>}</div>{currentOutputs.length>0&&<div className="wv2-current-step-attachments"><small>단계 산출물 {currentOutputs.length}건</small>{currentOutputs.map((item:any)=>{const deleting=outputDeleting===String(item.versionId||item.id);return <div className="wv2-current-step-output-row" key={item.id}><a href={`/api/projects/${w.project_id}/deliverables?versionId=${encodeURIComponent(item.versionId)}`} target="_blank" rel="noreferrer"><FileText size={15}/><span><b>{item.fileName||item.name}</b><small>{Math.max(1,Math.ceil(Number(item.fileSize||0)/1024)).toLocaleString()} KB · {item.createdBy||"등록자"}</small></span></a><button type="button" className="wv2-step-output-delete" disabled={Boolean(outputDeleting)} onClick={()=>void removeStageOutput(item)} title="잘못 첨부한 산출물 삭제" aria-label={`${item.fileName||item.name} 삭제`}><Trash2 size={15}/>{deleting?"삭제 중":""}</button></div>})}</div>}</section>}
        {!canAct&&!["approved","rejected"].includes(w.status)&&<p className="wv2-workflow-readonly">현재 단계 담당자만 처리 의견과 산출물을 등록할 수 있습니다.</p>}
        {w.official_document_id&&w.main_deliverable_id&&<button className="wv2-approved-document" onClick={()=>onOpenDocuments(w.main_deliverable_id)}><ShieldCheck size={20}/><span><b>승인문서 보기</b><small>{w.officialDocumentTitle||w.mainDocumentName} · 최종 문서</small></span><ChevronRight size={18}/></button>}
      </>}
      {sectionTab==="request"&&<RequestInformation sourceType={sourceType} sourceInfo={sourceInfo} workflow={w} attachments={sourceAttachments}/>} 
      {sectionTab==="documents"&&<>
        <section className="wv2-workflow-documents"><header><div><h3>상신 문서</h3><small>Workflow 시작 시 등록·연결된 기준 문서입니다.</small></div></header>{initialDocuments.length?initialDocuments.map((item:any)=>{const context=documentContext(item,"상신 문서"),key=String(context.id),checked=selectedDocuments.includes(key),selectable=Boolean(item.latestVersionId);return <article className={`workflow-document-card${checked?" selected":""}`} key={item.deliverableId}><div className="document-main">{selectable&&<input type="checkbox" aria-label="AI 문서 선택" checked={checked} onChange={()=>toggleDocument(key)} style={aiCheckboxStyle}/>}<button className="document-open" onClick={()=>onOpenDocuments(item.deliverableId)}><FileText size={20}/><span><b>{item.name}</b><small>{item.documentKind==="drawing"?`${item.drawingCode||"도면"} · 도면`:item.category||"일반 산출물"} · {item.latestRevision?`Rev.${String(item.latestRevision).padStart(2,"0")}`:item.version||"파일 미등록"}</small></span><ChevronRight size={18}/></button>{item.latestVersionId&&<a href={`/api/projects/${w.project_id}/deliverables?versionId=${item.latestVersionId}`} target="_blank" rel="noreferrer">다운로드</a>}</div></article>}):<p className="document-empty">상신 문서가 없습니다.</p>}</section>
        <section className="wv2-workflow-documents"><header><div><h3>단계별 산출물</h3><small>각 부서가 자신의 Workflow 단계에서 추가한 검토·수정 결과 문서입니다.</small></div></header>{steps.map((step:any)=>{const outputs=stageOutputs.filter((item:any)=>String(item.stepId)===String(step.id));if(!outputs.length)return null;return <section className="wv2-stage-output-group" key={step.id}><h4>{Number(step.step_order)+1}. {step.name} · {step.assigneeName||step.role_code||"미배정"}</h4>{outputs.map((item:any)=>{const context=documentContext(item,"단계 산출물",step.name),key=String(context.id),checked=selectedDocuments.includes(key);return <article className={`workflow-document-card${checked?" selected":""}`} key={item.id}><div className="document-main"><input type="checkbox" aria-label="AI 산출물 선택" checked={checked} onChange={()=>toggleDocument(key)} style={aiCheckboxStyle}/><a className="document-open" href={`/api/projects/${w.project_id}/deliverables?versionId=${encodeURIComponent(item.versionId)}`} target="_blank" rel="noreferrer"><FileText size={20}/><span><b>{item.fileName||item.name}</b><small>{item.createdBy||"등록자"} · {Math.max(1,Math.ceil(Number(item.fileSize||0)/1024)).toLocaleString()} KB</small></span><ChevronRight size={18}/></a></div></article>})}</section>})}{!stageOutputs.length&&<p className="document-empty">단계별 등록 산출물이 없습니다.</p>}</section>
        {sourceAttachments.length>0&&<section className="wv2-workflow-documents"><header><div><h3>요청 첨부문서</h3><small>설계변경·품질 요청 등록 시 첨부된 원본 요청 문서입니다.</small></div></header>{sourceAttachments.map((item:any)=>{const context=sourceAttachmentContext(item),key=String(context.id),checked=selectedDocuments.includes(key);return <article className={`workflow-document-card${checked?" selected":""}`} key={item.id}><div className="document-main"><input type="checkbox" aria-label="AI 요청 첨부문서 선택" checked={checked} onChange={()=>toggleDocument(key)} style={aiCheckboxStyle}/><a className="document-open" href={`/api/workflows/source-attachments?attachmentId=${encodeURIComponent(item.id)}`} target="_blank" rel="noreferrer"><FileText size={20}/><span><b>{item.fileName}</b><small>{Math.max(1,Math.ceil(Number(item.fileSize||0)/1024)).toLocaleString()} KB · 요청 등록</small></span><ChevronRight size={18}/></a></div></article>})}</section>}
        {selectedContexts.length>0&&<div className="wv2-doc-history-selection"><span>{selectedContexts.length}개 문서 선택</span><button onClick={openAiConversation}><Sparkles size={18}/>AI 대화</button></div>}
      </>}
      {sectionTab==="ai"&&<ConnectedAiPanel project={projectContext} draftRequest={aiDraft}/>} 
      {error&&<p className="wv2-workflow-error">{error}</p>}
    </section>
  </aside>;
}

function RequestInformation({sourceType,sourceInfo,workflow,attachments}:{sourceType:string;sourceInfo:any;workflow:any;attachments:any[]}){
  if(sourceType==="ECR"&&sourceInfo)return <section className="wv2-request-info"><header><small>ENGINEERING CHANGE REQUEST</small><h3>{sourceInfo.ecrNumber} · {sourceInfo.title}</h3></header><dl><div><dt>설계변경 유형</dt><dd>{sourceInfo.changeType||"미지정"}</dd></div><div><dt>우선순위</dt><dd>{priorityLabels[sourceInfo.priority]||sourceInfo.priority||"보통"}</dd></div><div><dt>처리기한</dt><dd>{sourceInfo.dueDate||"미정"}</dd></div><div><dt>관련 Task</dt><dd>{workflow.taskCode?`${workflow.taskCode} ${workflow.taskName}`:"연결 없음"}</dd></div></dl>{sourceInfo.beforeContent&&<InfoBlock title="변경 전 내용" value={sourceInfo.beforeContent}/>} {sourceInfo.afterContent&&<InfoBlock title="변경 후 내용" value={sourceInfo.afterContent}/>} {sourceInfo.reason&&<InfoBlock title="변경 사유" value={sourceInfo.reason}/>} {sourceInfo.impactContent&&<InfoBlock title="영향" value={sourceInfo.impactContent}/>}<AttachmentSummary attachments={attachments}/></section>;
  if(sourceType==="QUALITY"&&sourceInfo)return <section className="wv2-request-info"><header><small>QUALITY CASE</small><h3>{sourceInfo.qualityNumber} · {sourceInfo.title}</h3></header><dl><div><dt>발생일</dt><dd>{sourceInfo.occurredOn||"미정"}</dd></div><div><dt>문제 유형</dt><dd>{sourceInfo.issueType||"미지정"}</dd></div><div><dt>심각도</dt><dd>{severityLabels[sourceInfo.severity]||sourceInfo.severity||"보통"}</dd></div><div><dt>처리기한</dt><dd>{sourceInfo.dueDate||"미정"}</dd></div></dl>{sourceInfo.description&&<InfoBlock title="문제 내용" value={sourceInfo.description}/>} {sourceInfo.rootCause&&<InfoBlock title="원인분석" value={sourceInfo.rootCause}/>} {sourceInfo.correctiveAction&&<InfoBlock title="개선조치" value={sourceInfo.correctiveAction}/>} {sourceInfo.effectivenessCheck&&<InfoBlock title="효과검증" value={sourceInfo.effectivenessCheck}/>}<AttachmentSummary attachments={attachments}/></section>;
  return <section className="wv2-request-info"><header><small>{workflowTypeLabel(sourceType)} WORKFLOW REQUEST</small><h3>{workflow.title}</h3></header><dl><div><dt>요청자</dt><dd>{workflow.requesterName||"미지정"}</dd></div><div><dt>우선순위</dt><dd>{priorityLabels[workflow.priority]||workflow.priority||"보통"}</dd></div><div><dt>처리기한</dt><dd>{workflow.due_date||"미정"}</dd></div><div><dt>관련 Task</dt><dd>{workflow.taskCode?`${workflow.taskCode} ${workflow.taskName}`:"연결 없음"}</dd></div></dl><InfoBlock title="요청내용" value={workflow.request_content||"등록된 요청내용이 없습니다."}/><AttachmentSummary attachments={attachments}/></section>;
}
function InfoBlock({title,value}:{title:string;value:string}){return <section className="wv2-request-block"><h4>{title}</h4><p>{value}</p></section>}
function AttachmentSummary({attachments}:{attachments:any[]}){return <section className="wv2-request-attachments"><h4>요청 첨부문서 <em>{attachments.length}</em></h4>{attachments.length?attachments.map(item=><a key={item.id} href={`/api/workflows/source-attachments?attachmentId=${item.id}`}><FileText size={17}/><span><b>{item.fileName}</b><small>{Math.max(1,Math.ceil(Number(item.fileSize||0)/1024)).toLocaleString()} KB</small></span></a>):<p>등록된 첨부문서가 없습니다.</p>}</section>}
