import { getLegacyDbCompat } from "../../../../db/postgres-d1-compat";
import {ensureProjectDataFoundation,type RuntimeD1} from "../../../../db/project-data-foundation";
import {contextErrorResponse,resolveRequestContext,type RequestContext} from "../../../../db/request-context";

/* eslint-disable @typescript-eslint/no-explicit-any */
type D1=RuntimeD1;
type Entity="organization"|"user"|"role"|"code"|"partner"|"projectType"|"projectRole";
const ENTITIES=new Set<Entity>(["organization","user","role","code","partner","projectType","projectRole"]);
const DEFAULT_DELIVERABLE_CATEGORIES=[
  ["PLAN_DEV","기획 > 개발계획"],["PLAN_SCHEDULE","기획 > 일정"],["PLAN_ORG","기획 > 조직"],["PLAN_MEETING","기획 > 회의"],
  ["DEV_REQUIREMENT","개발 > 요구사항"],["DEV_SPEC","개발 > 사양"],["DEV_RESULT","개발 > 개발결과"],
  ["DESIGN_DRAWING","설계 > 도면"],["DESIGN_BOM","설계 > BOM"],["DESIGN_CHANGE","설계 > 설계변경"],
  ["PURCHASE_QUOTE","구매 > 견적"],["PURCHASE_VENDOR","구매 > 업체평가"],["PURCHASE_ORDER","구매 > 발주"],
  ["QUALITY_FMEA","품질 > FMEA"],["QUALITY_INSPECTION","품질 > 검사기준"],["QUALITY_TEST","품질 > 시험결과"],["QUALITY_ISIR","품질 > ISIR"],
  ["PRODUCTION_PROCESS","생산 > 공정계획"],["PRODUCTION_STANDARD","생산 > 작업표준"],["PRODUCTION_TRANSFER","생산 > 양산이관"],
  ["APPROVAL_GATE","승인 > Gate"],["APPROVAL_SIGN","승인 > 승인서"],["APPROVAL_FINAL","승인 > 완료보고"],
  ["COMMON_CONTRACT","공통 > 계약"],["COMMON_REFERENCE","공통 > 참고자료"],["COMMON_ETC","공통 > 기타"],
] as const;
const DEFAULT_COMPLETION_CONDITIONS=[["PROGRESS","진척 완료"],["REQUIRED_UPLOAD","필수 등록"],["REQUIRED_APPROVAL","필수 승인"],["CHILD_COMPLETE","하위 완료"],["GATE_APPROVAL","Gate 승인"],["OWNER_CONFIRM","담당 확인"]] as const;
const DEFAULT_QUALITY_ISSUE_TYPES=[["DESIGN","설계 문제"],["MATERIAL_PART","자재·부품 문제"],["EQUIPMENT","설비 문제"],["WORK_METHOD","작업방법 문제"],["MANUFACTURING_PROCESS","제조·공정 문제"],["INSPECTION_TEST","검사·시험 문제"],["DOCUMENT_SPEC","문서·사양 문제"],["SUPPLIER","협력사 문제"],["CUSTOMER_FIELD","고객·현장 문제"],["OTHER","기타"]] as const;
const DEFAULT_DESIGN_CHANGE_TYPES=[["DESIGN_SPEC","설계·사양 변경"],["DRAWING","도면 변경"],["BOM","BOM 변경"],["SW","SW 변경"],["MATERIAL_PART","자재·부품 변경"],["MANUFACTURING_PROCESS","제조·공정 변경"],["QUALITY_IMPROVEMENT","품질 개선"],["CUSTOMER_REQUEST","고객 요구"],["COST_REDUCTION","원가 절감"],["REGULATION_CERTIFICATION","법규·인증 대응"],["OTHER","기타"]] as const;
const DEFAULT_PARTNERS=[
  ["KOLON","코오롱인더스트리","CUSTOMER","김민준","project@kolon-demo.co.kr","02-3677-3114","Kolon Industries","대한민국","화학·첨단소재","서울특별시 강서구"],
  ["MFM","미래모빌리티","CUSTOMER","이서윤","pm@mirae-mobility.example","031-710-1201","Mirae Mobility","대한민국","자동차 부품","경기도 성남시"],
  ["HANBIT","한빛전자","CUSTOMER","박도윤","dev@hanbit-elec.example","031-420-2202","Hanbit Electronics","대한민국","전자·전장","경기도 안양시"],
  ["SERIM","세림테크","SUPPLIER","최지우","sales@serim-tech.example","041-550-3303","Serim Tech","대한민국","정밀가공","충청남도 천안시"],
  ["DAEKYUNG","대경정밀","SUPPLIER","정현우","contact@daekyung.example","053-610-4404","Daekyung Precision","대한민국","금형·정밀부품","대구광역시 달서구"],
  ["YUJIN","유진오토텍","SUPPLIER","강하윤","quality@yujin-auto.example","052-720-5505","Yujin Autotech","대한민국","자동차 부품","울산광역시 북구"],
  ["ACE","에이스솔루션","OUTSOURCE","윤서준","project@ace-solution.example","02-830-6606","ACE Solution","대한민국","SW·시스템 통합","서울특별시 금천구"],
  ["DONGWOO","동우산업","OUTSOURCE","장서아","partner@dongwoo.example","055-330-7707","Dongwoo Industry","대한민국","생산·조립","경상남도 김해시"],
  ["NEXTR","넥스트로보틱스","CUSTOMER","한지호","rnd@nextrobotics.example","042-860-8808","Next Robotics","대한민국","로봇·자동화","대전광역시 유성구"],
  ["SHINSUNG","신성에너지","OTHER","오수빈","business@shinsung-energy.example","061-350-9909","Shinsung Energy","대한민국","에너지","전라남도 나주시"],
] as const;
async function runtimeDb():Promise<D1>{return getLegacyDbCompat() as D1;}
async function ensureUserAvatarColumn(db:D1){const columns=await db.prepare("PRAGMA table_info(users)").all();if(!(columns.results??[]).some((column:any)=>column.name==="avatar_key"))await db.prepare("ALTER TABLE users ADD COLUMN avatar_key text DEFAULT 'avatar-01'").run();}

async function ensureSystemFoundation(db:D1,companyId:string){
  await ensureProjectDataFoundation(db);await ensureUserAvatarColumn(db);const now=Math.floor(Date.now()/1000);
  await db.batch([
    db.prepare(`CREATE TABLE IF NOT EXISTS roles (id text PRIMARY KEY NOT NULL,company_id text NOT NULL,code text NOT NULL,name text NOT NULL,scope text NOT NULL,permissions text NOT NULL,created_at integer NOT NULL,updated_at integer NOT NULL,FOREIGN KEY(company_id) REFERENCES companies(id))`),
    db.prepare("CREATE UNIQUE INDEX IF NOT EXISTS roles_company_code_uq ON roles(company_id,code)"),
    db.prepare(`CREATE TABLE IF NOT EXISTS user_roles (user_id text NOT NULL,role_id text NOT NULL,project_id text,PRIMARY KEY(user_id,role_id),FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(role_id) REFERENCES roles(id))`),
    ...[["system-role-admin","SYSTEM_ADMIN","시스템 관리자","company",["*"]],["system-role-user","USER","일반 사용자","company",["PROJECT_READ"]]].map(([id,code,name,scope,permissions])=>db.prepare("INSERT OR IGNORE INTO roles (id,company_id,code,name,scope,permissions,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)").bind(id,companyId,code,name,scope,JSON.stringify(permissions),now,now)),
    db.prepare(`CREATE TABLE IF NOT EXISTS common_codes (id text PRIMARY KEY NOT NULL,company_id text NOT NULL,group_code text NOT NULL,code text NOT NULL,label text NOT NULL,version integer DEFAULT 1 NOT NULL,sort_order integer DEFAULT 0 NOT NULL,enabled integer DEFAULT 1 NOT NULL,created_at integer NOT NULL,updated_at integer NOT NULL,FOREIGN KEY(company_id) REFERENCES companies(id))`),
    db.prepare("CREATE UNIQUE INDEX IF NOT EXISTS common_codes_version_uq ON common_codes(company_id,group_code,code,version)"),
    db.prepare(`CREATE TABLE IF NOT EXISTS partners (id text PRIMARY KEY NOT NULL,company_id text NOT NULL,code text NOT NULL,name text NOT NULL,category text,contact_name text,email text,phone text,status text DEFAULT 'active' NOT NULL,created_at integer NOT NULL,updated_at integer NOT NULL,FOREIGN KEY(company_id) REFERENCES companies(id))`),
    db.prepare("CREATE UNIQUE INDEX IF NOT EXISTS partners_company_code_uq ON partners(company_id,code)"),
    db.prepare(`CREATE TABLE IF NOT EXISTS project_types (id text PRIMARY KEY NOT NULL,company_id text NOT NULL,code text NOT NULL,name text NOT NULL,description text,status text DEFAULT 'active' NOT NULL,created_at integer NOT NULL,updated_at integer NOT NULL,FOREIGN KEY(company_id) REFERENCES companies(id))`),
    db.prepare("CREATE UNIQUE INDEX IF NOT EXISTS project_types_company_code_uq ON project_types(company_id,code)"),
    db.prepare(`CREATE TABLE IF NOT EXISTS partner_profiles (partner_id text PRIMARY KEY NOT NULL,english_name text,country text,industry text,representative_name text,business_registration_number text,address text,main_phone text,extra text,note text,updated_at integer NOT NULL,FOREIGN KEY(partner_id) REFERENCES partners(id) ON DELETE CASCADE)`),
    db.prepare(`CREATE TABLE IF NOT EXISTS project_role_catalog (id text PRIMARY KEY NOT NULL,company_id text NOT NULL,code text NOT NULL,name text NOT NULL,group_name text NOT NULL,required integer DEFAULT 0 NOT NULL,enabled integer DEFAULT 1 NOT NULL,sort_order integer DEFAULT 0 NOT NULL,created_at integer NOT NULL,updated_at integer NOT NULL,FOREIGN KEY(company_id) REFERENCES companies(id))`),
    db.prepare("CREATE UNIQUE INDEX IF NOT EXISTS project_role_catalog_company_code_uq ON project_role_catalog(company_id,code)"),
    ...[["partner-category-customer","PARTNER_CATEGORY","CUSTOMER","고객사",0],["partner-category-supplier","PARTNER_CATEGORY","SUPPLIER","공급사",1],["partner-category-outsource","PARTNER_CATEGORY","OUTSOURCE","외주처",2],["partner-category-other","PARTNER_CATEGORY","OTHER","기타",3]].map(([id,group,code,label,sort])=>db.prepare("INSERT OR IGNORE INTO common_codes (id,company_id,group_code,code,label,version,sort_order,enabled,created_at,updated_at) VALUES (?,?,?,?,?,1,?,1,?,?)").bind(id,companyId,group,code,label,sort,now,now)),
    ...(false?DEFAULT_DELIVERABLE_CATEGORIES:[]).map(([code,label],sort)=>db.prepare("INSERT OR IGNORE INTO common_codes (id,company_id,group_code,code,label,version,sort_order,enabled,created_at,updated_at) VALUES (?,?,?,?,?,1,?,1,?,?)").bind(`deliverable-category-${code.toLowerCase().replaceAll('_','-')}`,companyId,"DELIVERABLE_CATEGORY",code,label,sort*10,now,now)),
    ...DEFAULT_COMPLETION_CONDITIONS.map(([code,label],sort)=>db.prepare("INSERT OR IGNORE INTO common_codes (id,company_id,group_code,code,label,version,sort_order,enabled,created_at,updated_at) VALUES (?,?,?,?,?,1,?,1,?,?)").bind(`completion-condition-${code.toLowerCase().replaceAll('_','-')}`,companyId,"COMPLETION_CONDITION",code,label,sort*10,now,now)),
    ...DEFAULT_QUALITY_ISSUE_TYPES.map(([code,label],sort)=>db.prepare("INSERT OR IGNORE INTO common_codes (id,company_id,group_code,code,label,version,sort_order,enabled,created_at,updated_at) VALUES (?,?,?,?,?,1,?,1,?,?)").bind(`quality-issue-type-${code.toLowerCase().replaceAll('_','-')}`,companyId,"QUALITY_ISSUE_TYPE",code,label,sort*10,now,now)),
    ...DEFAULT_DESIGN_CHANGE_TYPES.map(([code,label],sort)=>db.prepare("INSERT OR IGNORE INTO common_codes (id,company_id,group_code,code,label,version,sort_order,enabled,created_at,updated_at) VALUES (?,?,?,?,?,1,?,1,?,?)").bind(`design-change-type-${code.toLowerCase().replaceAll('_','-')}`,companyId,"DESIGN_CHANGE_TYPE",code,label,sort*10,now,now)),
    ...[["issue-severity-low","ISSUE_SEVERITY","LOW","낮음",0],["issue-severity-medium","ISSUE_SEVERITY","MEDIUM","보통",10],["issue-severity-high","ISSUE_SEVERITY","HIGH","높음",20],["issue-severity-critical","ISSUE_SEVERITY","CRITICAL","심각",30],["deliverable-status-planned","DELIVERABLE_STATUS","PLANNED","등록 예정",0],["deliverable-status-submitted","DELIVERABLE_STATUS","SUBMITTED","제출",10],["deliverable-status-reviewed","DELIVERABLE_STATUS","REVIEWED","검토",20],["deliverable-status-approved","DELIVERABLE_STATUS","APPROVED","승인",30],["deliverable-status-rejected","DELIVERABLE_STATUS","REJECTED","반려",40]].map(([id,group,code,label,sort])=>db.prepare("INSERT OR IGNORE INTO common_codes (id,company_id,group_code,code,label,version,sort_order,enabled,created_at,updated_at) VALUES (?,?,?,?,?,1,?,1,?,?)").bind(id,companyId,group,code,label,sort,now,now)),
    ...[["project-type-part","PART_DEVELOPMENT","부품 개발",0],["project-type-sw","SW_DEVELOPMENT","SW 개발",1],["project-type-mass","MASS_DEVELOPMENT","양산 개발",2],["project-type-production","PRODUCTION","생산",3],["project-type-setup","SETUP","SETUP(설치)",4]].map(([id,code,name,sort])=>db.prepare("INSERT OR IGNORE INTO project_types (id,company_id,code,name,description,status,created_at,updated_at) VALUES (?,?,?,?,?,'active',?,?)").bind(id,companyId,code,name,`기본 프로젝트 유형 ${Number(sort)+1}`,now,now)),
    ...[["project-role-pm","PM","PM","프로젝트 관리",1,0],["project-role-pl","PL","PL","프로젝트 관리",1,1],["project-role-plan","PLAN","기획","업무 수행",0,10],["project-role-sales","SALES","영업","업무 수행",0,20],["project-role-dev","DEV","개발","업무 수행",0,30],["project-role-design","DESIGN","설계","업무 수행",0,40],["project-role-purchase","PURCHASE","구매","업무 수행",0,50],["project-role-material","MATERIAL","자재","업무 수행",0,60],["project-role-production","PRODUCTION","생산","업무 수행",0,70],["project-role-quality","QUALITY","품질","업무 수행",0,80],["project-role-service","SERVICE","서비스","업무 수행",0,90],["project-role-sw","SW","SW","전문 분야",0,100],["project-role-mech","MECHANICAL","기구","전문 분야",0,110],["project-role-electric","ELECTRICAL","전장","전문 분야",0,120],["project-role-circuit","CIRCUIT","회로","전문 분야",0,130]].map(([id,code,name,group,required,sort])=>db.prepare("INSERT OR IGNORE INTO project_role_catalog (id,company_id,code,name,group_name,required,enabled,sort_order,created_at,updated_at) VALUES (?,?,?,?,?,?,1,?,?,?)").bind(id,companyId,code,name,group,required,sort,now,now)),
    ...DEFAULT_PARTNERS.map(([code,name,category,contactName,email,phone])=>db.prepare("INSERT OR IGNORE INTO partners (id,company_id,code,name,category,contact_name,email,phone,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,'active',?,?)").bind(`${companyId}-demo-partner-${code.toLowerCase()}`,companyId,code,name,category,contactName,email,phone,now,now)),
    ...DEFAULT_PARTNERS.map(partner=>db.prepare("INSERT OR IGNORE INTO partner_profiles (partner_id,english_name,country,industry,address,main_phone,note,updated_at) VALUES (?,?,?,?,?,?,?,?)").bind(`${companyId}-demo-partner-${partner[0].toLowerCase()}`,partner[6],partner[7],partner[8],partner[9],null,"V2 데모 거래처",now)),
  ]);
}

async function systemContext(request:Request,db:D1){await ensureProjectDataFoundation(db);let context=await resolveRequestContext(request,db);await ensureSystemFoundation(db,context.companyId);const development=["localhost","127.0.0.1"].includes(new URL(request.url).hostname);if(development){const assigned=await db.prepare("SELECT ur.user_id FROM user_roles ur JOIN roles r ON r.id=ur.role_id WHERE r.company_id=? AND r.code IN ('SUPER_ADMIN','ADMIN','SYSTEM_ADMIN') LIMIT 1").bind(context.companyId).first();if(!assigned){await db.prepare("INSERT OR IGNORE INTO user_roles (user_id,role_id,project_id) SELECT ?,id,NULL FROM roles WHERE company_id=? AND code='SYSTEM_ADMIN'").bind(context.userId,context.companyId).run();context=await resolveRequestContext(request,db)}}return context;}
const isSystemAdmin=(context:RequestContext)=>context.systemRoles.some(role=>["SUPER_ADMIN","ADMIN","SYSTEM_ADMIN"].includes(role));

export async function GET(request:Request){const db=await runtimeDb();let context;try{context=await systemContext(request,db)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"사용자 정보를 확인하지 못했습니다."},{status:500})}const companyId=context.companyId;const [organizations,users,roles,codes,partners,projectTypes,projectRoles]=await Promise.all([
  db.prepare("SELECT id,parent_id AS parentId,name,code,sort_order AS sortOrder,'active' AS status FROM organizations WHERE company_id=? ORDER BY sort_order,name").bind(companyId).all(),
  db.prepare(`SELECT u.id,u.organization_id AS organizationId,u.email,u.name,u.status,COALESCE(u.avatar_key,'avatar-01') AS avatarKey,GROUP_CONCAT(r.id) AS roleIds,GROUP_CONCAT(r.name) AS roleNames FROM users u LEFT JOIN user_roles ur ON ur.user_id=u.id AND ur.project_id IS NULL LEFT JOIN roles r ON r.id=ur.role_id WHERE u.company_id=? GROUP BY u.id ORDER BY u.name`).bind(companyId).all(),
  db.prepare("SELECT id,code,name,scope,permissions FROM roles WHERE company_id=? ORDER BY code").bind(companyId).all(),
  db.prepare("SELECT id,group_code AS groupCode,code,label,version,sort_order AS sortOrder,enabled FROM common_codes WHERE company_id=? ORDER BY group_code,sort_order,code").bind(companyId).all(),
  db.prepare("SELECT p.id,p.code,p.name,p.category,p.contact_name AS contactName,p.email,p.phone,p.status,pp.english_name AS englishName,pp.country,pp.industry,pp.representative_name AS representativeName,pp.business_registration_number AS businessRegistrationNumber,pp.address,pp.main_phone AS mainPhone,pp.extra,pp.note FROM partners p LEFT JOIN partner_profiles pp ON pp.partner_id=p.id WHERE p.company_id=? ORDER BY p.name").bind(companyId).all(),
  db.prepare("SELECT id,code,name,description,status FROM project_types WHERE company_id=? ORDER BY name").bind(companyId).all(),
  db.prepare("SELECT id,code,name,group_name AS groupName,required,enabled,sort_order AS sortOrder FROM project_role_catalog WHERE company_id=? ORDER BY sort_order,name").bind(companyId).all(),
]);return Response.json({organizations:organizations.results??[],users:(users.results??[]).map((row:any)=>({...row,roleIds:row.roleIds?String(row.roleIds).split(','):[],roleNames:row.roleNames?String(row.roleNames).split(','):[]})),roles:(roles.results??[]).map((row:any)=>{try{return {...row,permissions:JSON.parse(row.permissions||"[]")}}catch{return {...row,permissions:[]}}}),codes:codes.results??[],partners:partners.results??[],projectTypes:projectTypes.results??[],projectRoles:projectRoles.results??[]});}

export async function POST(request:Request){const db=await runtimeDb();let context;try{context=await systemContext(request,db)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"사용자 정보를 확인하지 못했습니다."},{status:500})}if(!isSystemAdmin(context))return Response.json({error:"시스템 관리자만 기준정보를 등록할 수 있습니다."},{status:403});const companyId=context.companyId;const input=await request.json() as any;const entity=input.entity as Entity;const now=Math.floor(Date.now()/1000),id=crypto.randomUUID();if(!ENTITIES.has(entity))return Response.json({error:"관리 대상을 지정해 주세요."},{status:400});try{
  if(entity==="organization"){if(!input.name?.trim()||!input.code?.trim())throw new Error("조직명과 코드는 필수입니다.");await db.prepare("INSERT INTO organizations (id,company_id,parent_id,name,code,sort_order,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)").bind(id,companyId,input.parentId||null,input.name.trim(),input.code.trim(),Number(input.sortOrder)||0,now,now).run();}
  if(entity==="user"){if(!input.name?.trim()||!input.email?.trim())throw new Error("사용자명과 이메일은 필수입니다.");await db.prepare("INSERT INTO users (id,company_id,organization_id,email,name,status,avatar_key,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)").bind(id,companyId,input.organizationId||null,input.email.trim(),input.name.trim(),input.status||"active",input.avatarKey||"avatar-01",now,now).run();await replaceUserRoles(db,id,input.roleIds??[],companyId);}
  if(entity==="role"){if(!input.name?.trim()||!input.code?.trim())throw new Error("권한명과 코드는 필수입니다.");await db.prepare("INSERT INTO roles (id,company_id,code,name,scope,permissions,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)").bind(id,companyId,input.code.trim(),input.name.trim(),input.scope||"company",JSON.stringify(input.permissions??[]),now,now).run();}
  if(entity==="code"){if(!input.groupCode?.trim()||!input.code?.trim()||!input.label?.trim())throw new Error("그룹·코드·표시명은 필수입니다.");await db.prepare("INSERT INTO common_codes (id,company_id,group_code,code,label,version,sort_order,enabled,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(id,companyId,input.groupCode.trim(),input.code.trim(),input.label.trim(),Number(input.version)||1,Number(input.sortOrder)||0,input.enabled===false||input.enabled===0||input.status==="inactive"?0:1,now,now).run();}
  if(entity==="partner"){if(!input.name?.trim()||!input.code?.trim()||!input.category?.trim())throw new Error("거래처명, 코드와 유형은 필수입니다.");await db.batch([db.prepare("INSERT INTO partners (id,company_id,code,name,category,contact_name,email,phone,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind(id,companyId,input.code.trim(),input.name.trim(),input.category,input.contactName||null,input.email||null,input.phone||null,input.status||"active",now,now),db.prepare("INSERT INTO partner_profiles (partner_id,english_name,country,industry,representative_name,business_registration_number,address,main_phone,extra,note,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind(id,input.englishName||null,input.country||null,input.industry||null,input.representativeName||null,input.businessRegistrationNumber||null,input.address||null,input.mainPhone||null,input.extra||null,input.note||null,now)]);}
  if(entity==="projectType"){if(!input.name?.trim()||!input.code?.trim())throw new Error("프로젝트 유형명과 코드는 필수입니다.");await db.prepare("INSERT INTO project_types (id,company_id,code,name,description,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)").bind(id,companyId,input.code.trim(),input.name.trim(),input.description||null,input.status||"active",now,now).run();}
  if(entity==="projectRole"){if(!input.name?.trim()||!input.code?.trim())throw new Error("프로젝트 Role명과 코드는 필수입니다.");await db.prepare("INSERT INTO project_role_catalog (id,company_id,code,name,group_name,required,enabled,sort_order,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(id,companyId,input.code.trim(),input.name.trim(),input.groupName||"업무 수행",input.required?1:0,input.enabled===false?0:1,Number(input.sortOrder)||0,now,now).run();}
  return Response.json({ok:true,id},{status:201});
}catch(error){return Response.json({error:error instanceof Error?error.message:"저장하지 못했습니다."},{status:409});}}

async function replaceUserRoles(db:D1,userId:string,roleIds:string[],companyId:string){const statements=[db.prepare("DELETE FROM user_roles WHERE user_id=? AND project_id IS NULL").bind(userId)];for(const roleId of [...new Set(roleIds)])statements.push(db.prepare("INSERT INTO user_roles (user_id,role_id,project_id) SELECT ?,id,NULL FROM roles WHERE id=? AND company_id=?").bind(userId,roleId,companyId));await db.batch(statements);}

export async function PATCH(request:Request){const db=await runtimeDb();let context;try{context=await systemContext(request,db)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"사용자 정보를 확인하지 못했습니다."},{status:500})}if(!isSystemAdmin(context))return Response.json({error:"시스템 관리자만 기준정보를 수정할 수 있습니다."},{status:403});const companyId=context.companyId;const input=await request.json() as any;const entity=input.entity as Entity,id=String(input.id||"");if(!ENTITIES.has(entity)||!id)return Response.json({error:"수정 대상을 지정해 주세요."},{status:400});const now=Math.floor(Date.now()/1000);try{
  if(entity==="organization")await db.prepare("UPDATE organizations SET parent_id=?,name=?,code=?,sort_order=?,updated_at=? WHERE id=? AND company_id=?").bind(input.parentId||null,input.name.trim(),input.code.trim(),Number(input.sortOrder)||0,now,id,companyId).run();
  if(entity==="user"){await db.prepare("UPDATE users SET organization_id=?,email=?,name=?,status=?,avatar_key=?,updated_at=? WHERE id=? AND company_id=?").bind(input.organizationId||null,input.email.trim(),input.name.trim(),input.status||"active",input.avatarKey||"avatar-01",now,id,companyId).run();await replaceUserRoles(db,id,input.roleIds??[],companyId);}
  if(entity==="role")await db.prepare("UPDATE roles SET code=?,name=?,scope=?,permissions=?,updated_at=? WHERE id=? AND company_id=?").bind(input.code.trim(),input.name.trim(),input.scope||"company",JSON.stringify(input.permissions??[]),now,id,companyId).run();
  if(entity==="code")await db.prepare("UPDATE common_codes SET group_code=?,code=?,label=?,version=?,sort_order=?,enabled=?,updated_at=? WHERE id=? AND company_id=?").bind(input.groupCode.trim(),input.code.trim(),input.label.trim(),Number(input.version)||1,Number(input.sortOrder)||0,input.enabled===false||input.enabled===0||input.status==="inactive"?0:1,now,id,companyId).run();
  if(entity==="partner")await db.batch([db.prepare("UPDATE partners SET code=?,name=?,category=?,contact_name=?,email=?,phone=?,status=?,updated_at=? WHERE id=? AND company_id=?").bind(input.code.trim(),input.name.trim(),input.category||null,input.contactName||null,input.email||null,input.phone||null,input.status||"active",now,id,companyId),db.prepare("INSERT INTO partner_profiles (partner_id,english_name,country,industry,representative_name,business_registration_number,address,main_phone,extra,note,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(partner_id) DO UPDATE SET english_name=excluded.english_name,country=excluded.country,industry=excluded.industry,representative_name=excluded.representative_name,business_registration_number=excluded.business_registration_number,address=excluded.address,main_phone=excluded.main_phone,extra=excluded.extra,note=excluded.note,updated_at=excluded.updated_at").bind(id,input.englishName||null,input.country||null,input.industry||null,input.representativeName||null,input.businessRegistrationNumber||null,input.address||null,input.mainPhone||null,input.extra||null,input.note||null,now)]);
  if(entity==="projectType")await db.prepare("UPDATE project_types SET code=?,name=?,description=?,status=?,updated_at=? WHERE id=? AND company_id=?").bind(input.code.trim(),input.name.trim(),input.description||null,input.status||"active",now,id,companyId).run();
  if(entity==="projectRole")await db.prepare("UPDATE project_role_catalog SET code=?,name=?,group_name=?,required=?,enabled=?,sort_order=?,updated_at=? WHERE id=? AND company_id=?").bind(input.code.trim(),input.name.trim(),input.groupName||"업무 수행",input.required?1:0,input.enabled===false?0:1,Number(input.sortOrder)||0,now,id,companyId).run();
  return Response.json({ok:true});
}catch(error){return Response.json({error:error instanceof Error?error.message:"수정하지 못했습니다."},{status:409});}}

export async function DELETE(request:Request){const db=await runtimeDb();let context;try{context=await systemContext(request,db)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"사용자 정보를 확인하지 못했습니다."},{status:500})}if(!isSystemAdmin(context))return Response.json({error:"시스템 관리자만 기준정보를 삭제할 수 있습니다."},{status:403});const companyId=context.companyId;const input=await request.json() as {entity?:Entity;id?:string};if(!input.entity||!ENTITIES.has(input.entity)||!input.id)return Response.json({error:"삭제 대상을 지정해 주세요."},{status:400});const refs=input.entity==="organization"?await db.prepare("SELECT id FROM users WHERE organization_id=? LIMIT 1").bind(input.id).first():input.entity==="role"?await db.prepare("SELECT user_id FROM user_roles WHERE role_id=? LIMIT 1").bind(input.id).first():input.entity==="user"?await db.prepare("SELECT user_id FROM project_members WHERE user_id=? LIMIT 1").bind(input.id).first():input.entity==="partner"?await db.prepare("SELECT id FROM projects WHERE partner_id=? LIMIT 1").bind(input.id).first():input.entity==="projectType"?await db.prepare("SELECT id FROM projects WHERE project_type_id=? LIMIT 1").bind(input.id).first():input.entity==="projectRole"?await db.prepare("SELECT id FROM project_roles WHERE code=(SELECT code FROM project_role_catalog WHERE id=?) LIMIT 1").bind(input.id).first():null;if(refs)return Response.json({error:"사용 중인 항목은 삭제할 수 없습니다. 사용 안 함으로 전환해 주세요."},{status:409});const table={organization:"organizations",user:"users",role:"roles",code:"common_codes",partner:"partners",projectType:"project_types",projectRole:"project_role_catalog"}[input.entity];if(input.entity==="user")await db.prepare("DELETE FROM user_roles WHERE user_id=?").bind(input.id).run();await db.prepare(`DELETE FROM ${table} WHERE id=? AND company_id=?`).bind(input.id,companyId).run();return Response.json({ok:true});}
