/* eslint-disable @typescript-eslint/no-explicit-any */
import {contextErrorResponse,resolveRequestContext} from "../../../../db/request-context";
import {workflowDb} from "../shared";

export async function GET(request:Request){
  const db=await workflowDb();let context;try{context=await resolveRequestContext(request,db)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"사용자 정보를 확인하지 못했습니다."},{status:500})}
  const url=new URL(request.url),scope=url.searchParams.get("scope")||"pending",q=url.searchParams.get("q")?.trim().toLowerCase()||"";const filters=["w.company_id=?"],binds:any[]=[context.companyId];
  if(scope==="pending"){filters.push("s.assignee_user_id=? AND s.status='active' AND w.status='in_progress'");binds.push(context.userId)}else if(scope==="requested"){filters.push("w.requester_user_id=?");binds.push(context.userId)}else if(scope==="participated"){filters.push("EXISTS(SELECT 1 FROM workflow_instance_steps ps WHERE ps.workflow_id=w.id AND ps.assignee_user_id=?)");binds.push(context.userId)}else if(scope==="completed"){filters.push("w.status IN ('approved','rejected') AND (w.requester_user_id=? OR EXISTS(SELECT 1 FROM workflow_instance_steps ps WHERE ps.workflow_id=w.id AND ps.assignee_user_id=?))");binds.push(context.userId,context.userId)}if(q){filters.push("(lower(w.title) LIKE ? OR lower(w.workflow_number) LIKE ? OR lower(p.name) LIKE ?)");binds.push(`%${q}%`,`%${q}%`,`%${q}%`)}
  const rows=await db.prepare(`SELECT w.id,w.workflow_number AS workflowNumber,w.title,w.source_type AS sourceType,w.status,w.priority,w.due_date AS dueDate,w.current_step_order AS currentStepOrder,p.id AS projectId,p.code AS projectCode,p.name AS projectName,t.name AS templateName,tv.version AS templateVersion,s.name AS currentStepName,s.action_type AS currentActionType,s.assignee_user_id AS currentAssigneeUserId,COALESCE(dr.document_action,'NONE') AS currentDocumentAction,COALESCE(dr.document_required,0) AS currentDocumentRequired,CASE WHEN w.main_deliverable_id IS NULL THEN 0 ELSE 1 END AS hasMainDocument,(SELECT COUNT(*) FROM workflow_step_documents wd WHERE wd.workflow_id=w.id) AS documentCount,au.name AS currentAssigneeName,(SELECT COUNT(*) FROM workflow_instance_steps x WHERE x.workflow_id=w.id) AS stepCount,(SELECT group_concat(flow.name||'|'||flow.status,'~') FROM (SELECT name,status FROM workflow_instance_steps WHERE workflow_id=w.id ORDER BY step_order) flow) AS stepFlow,(SELECT COUNT(*) FROM workflow_history h WHERE h.workflow_id=w.id AND h.comment IS NOT NULL) AS commentCount FROM workflow_instances w JOIN projects p ON p.id=w.project_id JOIN workflow_templates t ON t.id=w.template_id JOIN workflow_template_versions tv ON tv.id=w.template_version_id LEFT JOIN workflow_instance_steps s ON s.workflow_id=w.id AND s.step_order=w.current_step_order LEFT JOIN workflow_step_document_rules dr ON dr.step_id=s.id LEFT JOIN users au ON au.id=s.assignee_user_id WHERE ${filters.join(" AND ")} ORDER BY CASE WHEN s.status='active' AND s.assignee_user_id=? THEN 0 ELSE 1 END,COALESCE(w.due_date,'9999-12-31'),w.updated_at DESC`).bind(...binds,context.userId).all();
  const counts=await db.prepare(`SELECT SUM(CASE WHEN w.status='in_progress' AND s.status='active' AND s.assignee_user_id=? THEN 1 ELSE 0 END) AS pending,SUM(CASE WHEN w.requester_user_id=? AND w.status NOT IN ('approved','rejected') THEN 1 ELSE 0 END) AS requested,SUM(CASE WHEN w.status IN ('approved','rejected') AND (w.requester_user_id=? OR EXISTS(SELECT 1 FROM workflow_instance_steps ps WHERE ps.workflow_id=w.id AND ps.assignee_user_id=?)) THEN 1 ELSE 0 END) AS completed FROM workflow_instances w LEFT JOIN workflow_instance_steps s ON s.workflow_id=w.id AND s.step_order=w.current_step_order WHERE w.company_id=?`).bind(context.userId,context.userId,context.userId,context.userId,context.companyId).first();
  return Response.json({workflows:rows.results??[],counts:counts??{pending:0,requested:0,completed:0}});
}
