/* eslint-disable @typescript-eslint/no-explicit-any */
import {contextErrorResponse,requireProjectAccess,resolveRequestContext} from "../../../db/request-context";
import {clearSourceDrawings,getSourceDrawingsMap,getSourcePrimaryDrawing,requireWorkflowDrawing,setSourcePrimaryDrawing} from "../../../services/workflow-drawing-service";
import {clearSourceParts,getSourcePrimaryPart,getSourcePartsMap,requireWorkflowPart,setSourcePrimaryPart} from "../../../services/workflow-part-service";
import {deleteDraftWorkflow,updateDraftWorkflow} from "../workflows/draft-management";
import {readSourceUpload,reassignSourceAttachments,removeSourceFiles,syncSourceAttachments} from "../workflows/source-files";
import {createWorkflowInstance,nowSeconds,seedDefaultWorkflowTemplates,workflowDb} from "../workflows/shared";

async function ensureEcrDrawingCompatibility(db:any){try{await db.prepare("ALTER TABLE design_change_requests ADD COLUMN drawing_id TEXT").run()}catch{}try{await db.prepare("ALTER TABLE design_change_requests ADD COLUMN change_type TEXT").run()}catch{}try{await db.prepare("ALTER TABLE deliverables ADD COLUMN document_kind TEXT NOT NULL DEFAULT 'document'").run()}catch{}try{await db.prepare("ALTER TABLE deliverables ADD COLUMN drawing_code TEXT").run()}catch{}}
const partFields=(part:any)=>part?{partId:part.id,partNumber:part.partNumber,partName:part.name,partRevision:part.revision,partType:part.partType,partSpec:part.spec}:{};
const drawingFields=(drawing:any)=>drawing?{drawingId:drawing.id,drawingCode:drawing.drawingCode,drawingName:drawing.name,drawingType:drawing.drawingType,drawingProjectId:drawing.projectId,drawingProjectCode:drawing.projectCode,drawingProjectName:drawing.projectName,drawingTaskId:drawing.taskId,drawingTaskCode:drawing.taskCode,drawingTaskName:drawing.taskName}:{};
const isAdmin=(context:any)=>context.systemRoles.some((role:string)=>["SUPER_ADMIN","ADMIN","SYSTEM_ADMIN"].includes(role));

export async function GET(request:Request){
 const db=await workflowDb();await ensureEcrDrawingCompatibility(db);let context;try{context=await resolveRequestContext(request,db);await seedDefaultWorkflowTemplates(db,context)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"설계변경을 불러오지 못했습니다."},{status:500})}
 const url=new URL(request.url),id=url.searchParams.get("id")||"",projectId=url.searchParams.get("projectId")||"";
 if(id){const item=await db.prepare("SELECT e.id,e.project_id AS projectId,e.task_id AS taskId,e.drawing_id AS drawingId,e.ecr_number AS ecrNumber,e.title,e.change_type AS changeType,e.before_content AS beforeContent,e.after_content AS afterContent,e.reason,e.impact_content AS impactContent,e.priority,e.status,e.workflow_id AS workflowId,e.requester_user_id AS requesterUserId,COALESCE(w.due_date,e.due_date) AS dueDate FROM design_change_requests e LEFT JOIN workflow_instances w ON w.id=e.workflow_id WHERE e.id=? AND e.company_id=?").bind(id,context.companyId).first<any>();if(!item)return Response.json({error:"설계변경을 찾을 수 없습니다."},{status:404});if(item.projectId){try{await requireProjectAccess(db,context,item.projectId)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"설계변경 접근 권한이 없습니다."},{status:403})}}const [attachments,part,linkedDrawing]=await Promise.all([db.prepare("SELECT id,file_name AS fileName,file_size AS fileSize,content_type AS contentType FROM workflow_source_attachments WHERE company_id=? AND source_type='ECR' AND source_id=? ORDER BY created_at,id").bind(context.companyId,id).all(),getSourcePrimaryPart(context.companyId,"ECR",id),getSourcePrimaryDrawing(context.companyId,"ECR",id)]);const drawing=linkedDrawing||(item.drawingId?await requireWorkflowDrawing(context.companyId,String(item.drawingId)).catch(()=>null):null);return Response.json({item:{...item,...partFields(part),...drawingFields(drawing)},part,drawing,attachments:attachments.results??[]})}
 const rows=await db.prepare(`SELECT e.id,e.ecr_number AS ecrNumber,e.title,e.change_type AS changeType,e.change_target AS changeTarget,e.priority,e.status,e.requested_at AS requestedAt,e.workflow_id AS workflowId,p.id AS projectId,p.code AS projectCode,p.name AS projectName,w.status AS workflowStatus,w.current_step_order AS currentStepOrder,COALESCE(w.due_date,e.due_date) AS dueDate,cs.name AS currentStepName,cu.name AS currentAssigneeName,(SELECT COUNT(*) FROM workflow_instance_steps x WHERE x.workflow_id=w.id) AS stepCount,(SELECT string_agg(flow.name||'|'||flow.status,'~') FROM (SELECT name,status FROM workflow_instance_steps WHERE workflow_id=w.id ORDER BY step_order) flow) AS stepFlow,e.drawing_id AS drawingId,d.drawing_code AS drawingCode,d.name AS drawingName,dp.code AS drawingProjectCode,dp.name AS drawingProjectName,t.wbs_code AS taskCode,t.name AS taskName FROM design_change_requests e LEFT JOIN projects p ON p.id=e.project_id LEFT JOIN workflow_instances w ON w.id=e.workflow_id LEFT JOIN workflow_instance_steps cs ON cs.workflow_id=w.id AND cs.step_order=w.current_step_order LEFT JOIN users cu ON cu.id=cs.assignee_user_id LEFT JOIN deliverables d ON d.id=e.drawing_id LEFT JOIN projects dp ON dp.id=d.project_id LEFT JOIN wbs_tasks t ON t.id=e.task_id WHERE e.company_id=? ${projectId?"AND e.project_id=?":""} ORDER BY e.updated_at DESC`).bind(context.companyId,...(projectId?[projectId]:[])).all();const items=(rows.results??[]) as any[],ids=items.map(item=>String(item.id)),[partsMap,drawingsMap]=await Promise.all([getSourcePartsMap(context.companyId,"ECR",ids),getSourceDrawingsMap(context.companyId,"ECR",ids)]);return Response.json({items:items.map(item=>({...item,...partFields(partsMap.get(String(item.id))?.[0]),...drawingFields(drawingsMap.get(String(item.id))?.[0])}))});
}

export async function POST(request:Request){
 const db=await workflowDb();await ensureEcrDrawingCompatibility(db);let context;try{context=await resolveRequestContext(request,db);await seedDefaultWorkflowTemplates(db,context)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"사용자 정보를 확인하지 못했습니다."},{status:500})}
 let upload;try{upload=await readSourceUpload(request)}catch(reason){return Response.json({error:reason instanceof Error?reason.message:"등록 정보를 확인하지 못했습니다."},{status:400})}const {input,files}=upload;
 if(!input.title?.trim())return Response.json({error:"변경 제목을 입력해 주세요."},{status:400});const projectId=String(input.projectId||"").trim()||null;if(projectId){try{await requireProjectAccess(db,context,projectId,true)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"프로젝트 접근 권한이 없습니다."},{status:403})}}
 let part:any=null;if(input.partId){try{part=await requireWorkflowPart(context.companyId,String(input.partId))}catch(reason){return Response.json({error:reason instanceof Error?reason.message:"관련 PART를 확인하지 못했습니다."},{status:400})}}
 let drawing:any=null;if(input.drawingId){try{drawing=await requireWorkflowDrawing(context.companyId,String(input.drawingId))}catch(reason){return Response.json({error:reason instanceof Error?reason.message:"관련 도면을 확인하지 못했습니다."},{status:400})}}
 const taskId=projectId&&drawing?.projectId===projectId?drawing.taskId||null:null,changeTarget=[[part?.partNumber,part?.name].filter(Boolean).join(" · "),[drawing?.drawingCode,drawing?.name].filter(Boolean).join(" · ")].filter(Boolean).join(" / ")||null,now=nowSeconds(),id=crypto.randomUUID(),seq=await db.prepare("SELECT COUNT(*) AS count FROM design_change_requests WHERE company_id=?").bind(context.companyId).first<{count:number}>(),number=`ECR-${new Date().toISOString().slice(0,4)}-${String(Number(seq?.count||0)+1).padStart(4,"0")}`;
 await db.prepare("INSERT INTO design_change_requests (id,company_id,project_id,task_id,drawing_id,ecr_number,title,change_type,change_target,before_content,after_content,reason,impact_content,priority,due_date,requester_user_id,requested_at,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?, 'draft',?,?)").bind(id,context.companyId,projectId,taskId,drawing?.id||null,number,input.title.trim(),input.changeType||null,changeTarget,input.beforeContent||null,input.afterContent||null,input.reason||null,input.impactContent||null,input.priority||"normal",input.dueDate||null,context.userId,now,now,now).run();
 try{if(part)await setSourcePrimaryPart(context.companyId,"ECR",id,part.id);if(drawing)await setSourcePrimaryDrawing(context.companyId,"ECR",id,drawing)}catch(reason){await clearSourceParts(context.companyId,"ECR",id);await clearSourceDrawings(context.companyId,"ECR",id);await db.prepare("DELETE FROM design_change_requests WHERE id=? AND company_id=?").bind(id,context.companyId).run();return Response.json({error:reason instanceof Error?reason.message:"관련 대상 연결을 저장하지 못했습니다."},{status:500})}
 let workflow:any=null;if(projectId){try{workflow=await createWorkflowInstance(db,context,{projectId,taskId:taskId||undefined,templateCode:"EC_ACTION",title:`[${number}] ${input.title.trim()}`,requestContent:input.reason||input.afterContent,priority:input.priority,dueDate:input.dueDate||undefined,sourceType:"ECR",sourceId:id,assignees:input.assignees,submit:Boolean(input.submit)});await db.prepare("UPDATE design_change_requests SET workflow_id=?,status=?,updated_at=? WHERE id=?").bind(workflow.id,workflow.status,now,id).run()}catch(reason){await clearSourceParts(context.companyId,"ECR",id);await clearSourceDrawings(context.companyId,"ECR",id);await db.prepare("DELETE FROM design_change_requests WHERE id=? AND company_id=?").bind(id,context.companyId).run();return Response.json({error:reason instanceof Error?reason.message:"설계변경 Workflow를 생성하지 못했습니다."},{status:400})}}
 await syncSourceAttachments(db,context,{projectId,sourceType:"ECR",sourceId:id,files});return Response.json({id,ecrNumber:number,workflowId:workflow?.id||null,standalone:!projectId,part,drawing,workflow},{status:201});
}

export async function PATCH(request:Request){
 const db=await workflowDb();await ensureEcrDrawingCompatibility(db);let context;try{context=await resolveRequestContext(request,db)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"사용자 정보를 확인하지 못했습니다."},{status:500})}
 let upload;try{upload=await readSourceUpload(request)}catch(reason){return Response.json({error:reason instanceof Error?reason.message:"수정 정보를 확인하지 못했습니다."},{status:400})}const {input,files}=upload;if(!input.id)return Response.json({error:"수정할 설계변경이 필요합니다."},{status:400});if(!String(input.title||"").trim())return Response.json({error:"변경 제목을 입력해 주세요."},{status:400});
 const current=await db.prepare("SELECT id,project_id AS projectId,ecr_number AS ecrNumber,workflow_id AS workflowId,requester_user_id AS requesterUserId,status FROM design_change_requests WHERE id=? AND company_id=?").bind(input.id,context.companyId).first<any>();if(!current)return Response.json({error:"설계변경을 찾을 수 없습니다."},{status:404});const projectId=String(input.projectId||"").trim()||null;if(current.workflowId&&projectId!==current.projectId)return Response.json({error:"Workflow가 생성된 설계변경은 프로젝트를 변경하거나 해제할 수 없습니다."},{status:409});if(projectId){try{await requireProjectAccess(db,context,projectId,true)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"설계변경 수정 권한이 없습니다."},{status:403})}}else if(current.requesterUserId!==context.userId&&!isAdmin(context))return Response.json({error:"요청자만 프로젝트 미연결 설계변경을 수정할 수 있습니다."},{status:403});
 let part:any=null;if(input.partId){try{part=await requireWorkflowPart(context.companyId,String(input.partId))}catch(reason){return Response.json({error:reason instanceof Error?reason.message:"관련 PART를 확인하지 못했습니다."},{status:400})}}
 let drawing:any=null;if(input.drawingId){try{drawing=await requireWorkflowDrawing(context.companyId,String(input.drawingId))}catch(reason){return Response.json({error:reason instanceof Error?reason.message:"관련 도면을 확인하지 못했습니다."},{status:400})}}
 const taskId=projectId&&drawing?.projectId===projectId?drawing.taskId||null:null,now=nowSeconds(),title=String(input.title||"").trim(),changeTarget=[[part?.partNumber,part?.name].filter(Boolean).join(" · "),[drawing?.drawingCode,drawing?.name].filter(Boolean).join(" · ")].filter(Boolean).join(" / ")||null;
 let workflow:any=null;if(current.workflowId){await updateDraftWorkflow(db,context,current.workflowId,{title:`[${current.ecrNumber}] ${title}`,taskId:taskId||"",requestContent:input.reason||input.afterContent,priority:input.priority,dueDate:input.dueDate,assignees:input.assignees});workflow={id:current.workflowId,status:"draft"}}else if(projectId){workflow=await createWorkflowInstance(db,context,{projectId,taskId:taskId||undefined,templateCode:"EC_ACTION",title:`[${current.ecrNumber}] ${title}`,requestContent:input.reason||input.afterContent,priority:input.priority,dueDate:input.dueDate||undefined,sourceType:"ECR",sourceId:input.id,assignees:input.assignees,submit:Boolean(input.submit)})}
 await db.prepare("UPDATE design_change_requests SET project_id=?,task_id=?,drawing_id=?,workflow_id=COALESCE(?,workflow_id),status=?,title=?,change_type=?,change_target=?,before_content=?,after_content=?,reason=?,impact_content=?,priority=?,due_date=?,updated_at=? WHERE id=?").bind(projectId,taskId,drawing?.id||null,workflow?.id||null,workflow?.status||current.status||"draft",title,input.changeType||null,changeTarget,input.beforeContent||null,input.afterContent||null,input.reason||null,input.impactContent||null,input.priority||"normal",input.dueDate||null,now,input.id).run();if(part)await setSourcePrimaryPart(context.companyId,"ECR",input.id,part.id);else await clearSourceParts(context.companyId,"ECR",input.id);if(drawing)await setSourcePrimaryDrawing(context.companyId,"ECR",input.id,drawing);else await clearSourceDrawings(context.companyId,"ECR",input.id);await reassignSourceAttachments(db,context,"ECR",input.id,projectId);await syncSourceAttachments(db,context,{projectId,sourceType:"ECR",sourceId:input.id,files,removeAttachmentIds:input.removeAttachmentIds});return Response.json({ok:true,id:input.id,workflowId:workflow?.id||current.workflowId||null,standalone:!projectId,part,drawing});
}

export async function DELETE(request:Request){const db=await workflowDb();let context;try{context=await resolveRequestContext(request,db);const id=new URL(request.url).searchParams.get("id")||"",item=await db.prepare("SELECT project_id AS projectId,workflow_id AS workflowId,requester_user_id AS requesterUserId FROM design_change_requests WHERE id=? AND company_id=?").bind(id,context.companyId).first<any>();if(!item)return Response.json({error:"설계변경을 찾을 수 없습니다."},{status:404});if(item.workflowId)return Response.json(await deleteDraftWorkflow(db,context,item.workflowId));if(item.projectId){try{await requireProjectAccess(db,context,item.projectId,true)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"설계변경 삭제 권한이 없습니다."},{status:403})}}else if(item.requesterUserId!==context.userId&&!isAdmin(context))return Response.json({error:"요청자만 프로젝트 미연결 설계변경을 삭제할 수 있습니다."},{status:403});await removeSourceFiles(db,context,"ECR",id);await clearSourceParts(context.companyId,"ECR",id);await clearSourceDrawings(context.companyId,"ECR",id);await db.prepare("DELETE FROM design_change_requests WHERE id=? AND company_id=?").bind(id,context.companyId).run();return Response.json({ok:true})}catch(reason){return contextErrorResponse(reason)??Response.json({error:reason instanceof Error?reason.message:"설계변경을 삭제하지 못했습니다."},{status:400})}}
