import {TRR_SECTIONS,trrVersionLabel,type TrrDocument} from '../lib/trr-contract';
import {zipStore} from '../lib/trr-zip';
export const escapeXml=(s:string)=>s.replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
type Block={text:string;style?:'Title'|'Subtitle'|'Heading1'|'Heading2';page?:boolean};
export function trrBlocks(doc:TrrDocument):Block[]{
 const blocks:Block[]=[{text:'J SOLUTION',style:'Subtitle'},{text:`${doc.projectName} TRR`,style:'Title'},{text:'Technical Review Report',style:'Subtitle'},{text:'검토용 보고서'},{text:'서명 및 검토',style:'Heading1',page:true},{text:'작성자: ____________________    작성일: ____________________'},{text:'검토자: ____________________    검토일: ____________________'},{text:'승인자: ____________________    승인일: ____________________'},{text:'목차',style:'Heading1',page:true},...TRR_SECTIONS.map((s,i)=>({text:`${i+1}. ${s}`})),{text:'9. 참조자료'}];
 if(doc.version)blocks.splice(4,0,{text:trrVersionLabel(doc.version)});
 TRR_SECTIONS.forEach((section,index)=>{blocks.push({text:`${index+1}. ${section}`,style:'Heading1',page:index===0});let count=0;
  for(const source of doc.sources)for(const fact of source.facts.filter(f=>f.section===section)){count++;blocks.push({text:fact.title,style:'Heading2'},{text:source.kind==='historical'?`과거 사례 참고 · ${fact.detail}`:fact.detail},{text:`근거: ${source.fileName} · ${fact.reference}`});}
  if(!count)blocks.push({text:'등록 자료에서 확인된 내용이 없습니다.'});
 });
 blocks.push({text:'9. 참조자료',style:'Heading1'});doc.sources.forEach((s,i)=>blocks.push({text:`${i+1}. ${s.fileName} | 자료 ID ${s.id} | 원본 Revision ${s.revision} | ${s.kind==='historical'?'과거 사례':'현재 기술자료'}`}));return blocks;
}
export function createTrrDocx(doc:TrrDocument){
 const paragraphs=trrBlocks(doc).map((b,index,blocks)=>`<w:p><w:pPr>${b.style?`<w:pStyle w:val="${b.style}"/>`:''}${b.page?'<w:pageBreakBefore/>':''}${blocks[index+1]?.text.startsWith('근거:')?'<w:keepNext/>':''}</w:pPr><w:r><w:t xml:space="preserve">${escapeXml(b.text)}</w:t></w:r></w:p>`).join('');
 const styles=`<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial" w:eastAsia="Malgun Gothic"/><w:sz w:val="22"/></w:rPr></w:rPrDefault><w:pPrDefault><w:pPr><w:spacing w:after="120" w:line="300" w:lineRule="auto"/></w:pPr></w:pPrDefault></w:docDefaults><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style>${[['Title',40],['Subtitle',26],['Heading1',30],['Heading2',24]].map(([name,size])=>`<w:style w:type="paragraph" w:styleId="${name}"><w:name w:val="${name}"/><w:basedOn w:val="Normal"/><w:pPr><w:keepNext/><w:spacing w:before="240" w:after="160"/>${String(name).startsWith('Heading')?`<w:outlineLvl w:val="${name==='Heading1'?0:1}"/>`:''}</w:pPr><w:rPr><w:b/><w:color w:val="000000"/><w:sz w:val="${size}"/></w:rPr></w:style>`).join('')}</w:styles>`;
 const entries={'[Content_Types].xml':'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>','_rels/.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>','word/_rels/document.xml.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>','word/styles.xml':styles,'word/document.xml':`<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${paragraphs}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1134" w:right="1134" w:bottom="1134" w:left="1134"/></w:sectPr></w:body></w:document>`};
 return zipStore(Object.entries(entries).map(([name,data])=>({name,data:new TextEncoder().encode(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>${data}`)})));
}
export function previewTrr(doc:TrrDocument,label:string){return `<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeXml(doc.projectName)} TRR ${label}</title><style>body{font:16px/1.7 Arial,sans-serif;background:#f3f5f5;color:#202b30;margin:0}main{max-width:900px;margin:24px auto;background:white;padding:48px;box-sizing:border-box}p{white-space:pre-wrap;overflow-wrap:anywhere}h1,h2,h3{break-after:avoid}h1{font-size:28px}h2{font-size:22px;margin-top:36px}h3{font-size:18px}@media print{main{margin:0;padding:0;max-width:none}.page{break-before:page}}</style><main><p>${escapeXml(label)} · 검토용 보고서</p>${trrBlocks(doc).map(b=>{const tag=b.style==='Title'?'h1':b.style==='Heading1'?'h2':b.style==='Heading2'?'h3':'p';return `<${tag}${b.page?' class="page"':''}>${escapeXml(b.text)}</${tag}>`}).join('')}</main></html>`;}
