import { createAiPptx } from "./ai-pptx-download";

export type AiArtifactType="pptx"|"docx"|"xlsx"|"pdf"|"image";
type ZipEntry={name:string;data:Uint8Array};
const encoder=new TextEncoder();
const utf8=(value:string)=>encoder.encode(value);
const xmlEscape=(value:string)=>value.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&apos;");
const crcTable=(()=>{const table=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?(0xedb88320^(c>>>1)):(c>>>1);table[n]=c>>>0;}return table;})();
const crc32=(data:Uint8Array)=>{let c=0xffffffff;for(const b of data)c=crcTable[(c^b)&0xff]^(c>>>8);return (c^0xffffffff)>>>0;};
const u16=(n:number)=>[n&255,(n>>>8)&255];
const u32=(n:number)=>[n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255];
const bytes=(values:number[])=>new Uint8Array(values);
function concat(parts:Uint8Array[]){const size=parts.reduce((sum,p)=>sum+p.length,0);const out=new Uint8Array(size);let offset=0;for(const part of parts){out.set(part,offset);offset+=part.length;}return out;}
function zipStore(entries:ZipEntry[]){const locals:Uint8Array[]=[];const centrals:Uint8Array[]=[];let offset=0;for(const entry of entries){const name=utf8(entry.name),data=entry.data,crc=crc32(data);const local=concat([bytes([...u32(0x04034b50),...u16(20),...u16(0x0800),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(data.length),...u32(data.length),...u16(name.length),...u16(0)]),name,data]);locals.push(local);centrals.push(concat([bytes([...u32(0x02014b50),...u16(20),...u16(20),...u16(0x0800),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(data.length),...u32(data.length),...u16(name.length),...u16(0),...u16(0),...u16(0),...u16(0),...u32(0),...u32(offset)]),name]));offset+=local.length;}const central=concat(centrals);return concat([...locals,central,bytes([...u32(0x06054b50),...u16(0),...u16(0),...u16(entries.length),...u16(entries.length),...u32(central.length),...u32(offset),...u16(0)])]);}
function downloadBlob(blob:Blob,fileName:string){const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=fileName;document.body.appendChild(anchor);anchor.click();anchor.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000);}
function safeBase(value:string){return value.replace(/[\\/:*?\"<>|]+/g,"-").replace(/\s+/g," ").trim().slice(0,90)||"J-SOLUTION-AI";}
export function detectAiArtifactType(message:string):AiArtifactType|null{if(/(pptx?|파워포인트|슬라이드)/i.test(message))return"pptx";if(/(docx?|word|워드|문서파일)/i.test(message))return"docx";if(/(xlsx?|excel|엑셀|스프레드시트)/i.test(message))return"xlsx";if(/\bpdf\b|피디에프/i.test(message))return"pdf";if(/(png|jpe?g|webp|이미지|그림)/i.test(message))return"image";return null;}
export const artifactLabel=(type:AiArtifactType)=>({pptx:"PPTX",docx:"WORD",xlsx:"EXCEL",pdf:"PDF",image:"IMAGE"}[type]);

function createDocx(content:string,fileBase:string){const paragraphs=content.split(/\r?\n/).map(line=>line.trim()).filter(Boolean).map(line=>`<w:p><w:r><w:rPr><w:lang w:val="ko-KR"/></w:rPr><w:t xml:space="preserve">${xmlEscape(line)}</w:t></w:r></w:p>`).join("");const entries:ZipEntry[]=[{name:"[Content_Types].xml",data:utf8(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>`)},{name:"_rels/.rels",data:utf8(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`)},{name:"word/document.xml",data:utf8(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${paragraphs}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1134" w:right="1134" w:bottom="1134" w:left="1134"/></w:sectPr></w:body></w:document>`)}];downloadBlob(new Blob([zipStore(entries)],{type:"application/vnd.openxmlformats-officedocument.wordprocessingml.document"}),`${safeBase(fileBase)}.docx`);}
function rowsFromContent(content:string){const lines=content.split(/\r?\n/).map(line=>line.trim()).filter(Boolean);const table=lines.filter(line=>line.includes("|")).map(line=>line.replace(/^\||\|$/g,"").split("|").map(cell=>cell.trim())).filter(row=>!row.every(cell=>/^:?-{2,}:?$/.test(cell)));if(table.length)return table;return lines.map((line,index)=>[String(index+1),line]);}
function colName(index:number){let n=index+1,name="";while(n){const r=(n-1)%26;name=String.fromCharCode(65+r)+name;n=Math.floor((n-1)/26);}return name;}
function createXlsx(content:string,fileBase:string){const rows=rowsFromContent(content);const sheetRows=rows.map((row,r)=>`<row r="${r+1}">${row.map((cell,c)=>`<c r="${colName(c)}${r+1}" t="inlineStr"><is><t xml:space="preserve">${xmlEscape(cell)}</t></is></c>`).join("")}</row>`).join("");const entries:ZipEntry[]=[{name:"[Content_Types].xml",data:utf8(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>`)},{name:"_rels/.rels",data:utf8(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`)},{name:"xl/workbook.xml",data:utf8(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="AI 결과" sheetId="1" r:id="rId1"/></sheets></workbook>`)},{name:"xl/_rels/workbook.xml.rels",data:utf8(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>`)},{name:"xl/worksheets/sheet1.xml",data:utf8(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${sheetRows}</sheetData></worksheet>`)}];downloadBlob(new Blob([zipStore(entries)],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}),`${safeBase(fileBase)}.xlsx`);}
function wrapCanvasText(ctx:CanvasRenderingContext2D,text:string,maxWidth:number){const words=text.split(/\s+/);const lines:string[]=[];let line="";for(const word of words){const next=line?`${line} ${word}`:word;if(ctx.measureText(next).width>maxWidth&&line){lines.push(line);line=word}else line=next;}if(line)lines.push(line);return lines;}
function renderPageCanvas(content:string){const canvas=document.createElement("canvas");canvas.width=1240;canvas.height=1754;const ctx=canvas.getContext("2d")!;ctx.fillStyle="#ffffff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#10252a";ctx.font="700 42px Arial, 'Malgun Gothic', sans-serif";ctx.fillText("J SOLUTION AI",90,100);ctx.font="28px Arial, 'Malgun Gothic', sans-serif";let y=165;for(const paragraph of content.split(/\r?\n/).filter(Boolean)){for(const line of wrapCanvasText(ctx,paragraph,1060)){if(y>1640)break;ctx.fillText(line,90,y);y+=44;}y+=16;if(y>1640)break;}ctx.fillStyle="#6f858a";ctx.font="20px Arial, sans-serif";ctx.fillText("AI generated artifact",90,1690);return canvas;}
function createImage(content:string,fileBase:string){renderPageCanvas(content).toBlob(blob=>{if(blob)downloadBlob(blob,`${safeBase(fileBase)}.png`)},"image/png");}
function createPdf(content:string,fileBase:string){const canvas=renderPageCanvas(content);const dataUrl=canvas.toDataURL("image/jpeg",0.92);const binary=atob(dataUrl.split(",")[1]);const image=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)image[i]=binary.charCodeAt(i);const chunks:Array<string|Uint8Array>=[];const offsets:number[]=[];let length=0;const push=(part:string|Uint8Array)=>{chunks.push(part);length+=typeof part==="string"?encoder.encode(part).length:part.length;};push("%PDF-1.4\n");const obj=(id:number,body:string|Uint8Array,prefix="",suffix="")=>{offsets[id]=length;push(`${id} 0 obj\n${prefix}`);push(body);push(`${suffix}\nendobj\n`);};obj(1,"<< /Type /Catalog /Pages 2 0 R >>");obj(2,"<< /Type /Pages /Kids [3 0 R] /Count 1 >>");obj(3,"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>");obj(4,image,`<< /Type /XObject /Subtype /Image /Width ${canvas.width} /Height ${canvas.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${image.length} >>\nstream\n`,`\nendstream`);const stream="q 595 0 0 842 0 0 cm /Im0 Do Q";obj(5,stream,`<< /Length ${stream.length} >>\nstream\n`,`\nendstream`);const xref=length;push(`xref\n0 6\n0000000000 65535 f \n`);for(let i=1;i<=5;i++)push(`${String(offsets[i]).padStart(10,"0")} 00000 n \n`);push(`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`);const total=chunks.map(part=>typeof part==="string"?encoder.encode(part):part);downloadBlob(new Blob(total,{type:"application/pdf"}),`${safeBase(fileBase)}.pdf`);}

export function downloadAiArtifact(type:AiArtifactType,content:string,fileBase:string){if(type==="pptx"){createAiPptx(content,fileBase);return;}if(type==="docx"){createDocx(content,fileBase);return;}if(type==="xlsx"){createXlsx(content,fileBase);return;}if(type==="pdf"){createPdf(content,fileBase);return;}createImage(content,fileBase);}
export function artifactRows(content:string){return rowsFromContent(content);}
