"use client";

import { useEffect,useMemo,useState } from "react";
import { Check,Download,Eye,FileText,ListFilter,Plus,RefreshCw,Search,Trash2,Upload,X } from "lucide-react";
import ProjectModuleFilterDrawer from "./project-module-filter-drawer";
import type { DocumentPreviewData } from "./document-file-preview-view";

type Project={id:string;code:string;name:string;customerName?:string;status:string};
type Task={id:string;wbsCode:string;name:string;kind:"summary"|"task"};
type Deliverable={id:string;taskId?:string;name:string;type?:string;required:number|boolean;status:string;version?:string;source:"planned"|"ad_hoc";revisionCount:number};
type Version={id:string;deliverableId:string;taskId?:string;revision:number;fileName:string;fileSize:number;contentType?:string;note?:string;createdAt:number;createdBy?:string};
export type DocumentAiContext={id:string;kind:"문서";title:string;meta:string;preview?:DocumentPreviewData};
type Props={project:Project|null;onProjectChange:(project:Project)=>void;onAiContextChange:(items:DocumentAiContext[])=>void;onPreview:(data:DocumentPreviewData)=>void;selectedIds:string[];onSelectedIdsChange:(ids:string[])=>void};
const bytes=(v:number)=>v>=1048576?`${(v/1048576).toFixed(1)} MB`:v>=1024?`${Math.round(v/1024)} KB`:`${v} B`;

export default function ProjectDocumentWorkspace({project,onProjectChange,onAiContextChange,onPreview,selectedIds,onSelectedIdsChange}:Props){
  const [projects,setProjects]=useState<Project[]>([]);const [tasks,setTasks]=useState<Task[]>([]);const [deliverables,setDeliverables]=useState<Deliverable[]>([]);const [versions,setVersions]=useState<Version[]>([]);
  const [loading,setLoading]=useState(false);const [query,setQuery]=useState("");const [sourceFilter,setSourceFilter]=useState<"all"|"planned"|"ad_hoc">("all");const [statusFilter,setStatusFilter]=useState<"all"|"planned"|"submitted">("all");
  const [detailId,setDetailId]=useState("");const [dialogOpen,setDialogOpen]=useState(false);const [saving,setSaving]=useState(false);const [notice,setNotice]=useState("");
  const [filterOpen,setFilterOpen]=useState(false);const [filterProjectSearch,setFilterProjectSearch]=useState("");const [advanced,setAdvanced]=useState({logic:"AND" as "AND"|"OR",sources:[] as string[],statuses:[] as string[],types:[] as string[]});const [draftAdvanced,setDraftAdvanced]=useState(advanced);
  const [form,setForm]=useState({deliverableId:"",taskId:"",name:"",category:"",note:""});const [file,setFile]=useState<File|null>(null);

  useEffect(()=>{fetch("/api/projects",{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then((d:{projects?:Project[]})=>{const list=d.projects??[];setProjects(list);if(!project&&list[0])onProjectChange(list[0]);}).catch(()=>setProjects([]));},[]); // eslint-disable-line react-hooks/exhaustive-deps
  const load=async()=>{if(!project?.id){setTasks([]);setDeliverables([]);setVersions([]);return;}setLoading(true);setNotice("");try{const [wr,dr]=await Promise.all([fetch(`/api/projects/${project.id}/wbs`,{cache:"no-store"}),fetch(`/api/projects/${project.id}/deliverables`,{cache:"no-store"})]);if(!wr.ok||!dr.ok)throw new Error("프로젝트 문서·산출물 데이터를 불러오지 못했습니다.");const w=await wr.json() as {tasks?:Task[]};const d=await dr.json() as {deliverables?:Deliverable[];versions?:Version[]};setTasks((w.tasks??[]).filter(t=>t.kind==="task"));setDeliverables(d.deliverables??[]);setVersions(d.versions??[]);}catch(e){setNotice(e instanceof Error?e.message:"데이터를 불러오지 못했습니다.");}finally{setLoading(false);}};
  useEffect(()=>{void load();},[project?.id]); // eslint-disable-line react-hooks/exhaustive-deps

  const taskMap=useMemo(()=>new Map(tasks.map(t=>[t.id,t])),[tasks]);const versionMap=useMemo(()=>{const m=new Map<string,Version[]>();versions.forEach(v=>m.set(v.deliverableId,[...(m.get(v.deliverableId)||[]),v]));return m;},[versions]);
  const detail=deliverables.find(d=>d.id===detailId)||null;const detailVersions=detail?versionMap.get(detail.id)||[]:[];
  const baseVisible=useMemo(()=>deliverables.filter(d=>{const q=query.trim().toLowerCase(),t=d.taskId?taskMap.get(d.taskId):undefined;return(sourceFilter==="all"||d.source===sourceFilter)&&(statusFilter==="all"||d.status===statusFilter)&&(!q||`${d.name} ${d.type||""} ${t?.wbsCode||""} ${t?.name||""}`.toLowerCase().includes(q));}),[deliverables,query,sourceFilter,statusFilter,taskMap]);
  const matchesAdvanced=(d:Deliverable,filter=advanced)=>{const tests=[filter.sources.length?filter.sources.includes(d.source):null,filter.statuses.length?filter.statuses.includes(d.status):null,filter.types.length?filter.types.includes(d.type||"미분류"):null].filter(v=>v!==null) as boolean[];return !tests.length||filter.logic==="AND"?tests.every(Boolean):tests.some(Boolean)};
  const visible=useMemo(()=>baseVisible.filter(d=>matchesAdvanced(d)),[baseVisible,advanced]);
  const draftCount=useMemo(()=>baseVisible.filter(d=>matchesAdvanced(d,draftAdvanced)).length,[baseVisible,draftAdvanced]);
  const filterTypes=useMemo(()=>Array.from(new Set(deliverables.map(d=>d.type||"미분류"))).sort(),[deliverables]);
  const toggleDraft=(key:"sources"|"statuses"|"types",value:string)=>setDraftAdvanced(c=>({...c,[key]:c[key].includes(value)?c[key].filter(x=>x!==value):[...c[key],value]}));
  useEffect(()=>{onAiContextChange(deliverables.filter(d=>selectedIds.includes(d.id)).map(d=>{const t=d.taskId?taskMap.get(d.taskId):undefined,v=(versionMap.get(d.id)||[])[0];return{id:d.id,kind:"문서" as const,title:d.name,meta:[d.source==="planned"?"계획 산출물":"추가 산출물",d.type||"미분류",d.version||"Revision 없음",t?`WBS ${t.wbsCode} ${t.name}`:"",v?.fileName||"파일 미등록"].filter(Boolean).join(" · "),preview:v&&project?.id?{projectId:project.id,versionId:v.id,title:d.name,fileName:v.fileName,contentType:v.contentType,revision:v.revision}:undefined};}));},[selectedIds,deliverables,taskMap,versionMap]); // eslint-disable-line react-hooks/exhaustive-deps

  const openRegister=(deliverable?:Deliverable)=>{setForm({deliverableId:deliverable?.id||"",taskId:deliverable?.taskId||tasks[0]?.id||"",name:deliverable?.source==="ad_hoc"?deliverable.name:"",category:deliverable?.type||"",note:""});setFile(null);setDialogOpen(true);};
  const register=async()=>{if(!project?.id||saving)return;if(!file){setNotice("등록할 파일을 선택해 주세요.");return;}if(!form.deliverableId&&!form.taskId){setNotice("연결 Task를 선택해 주세요.");return;}setSaving(true);try{const body=new FormData();Object.entries(form).forEach(([k,v])=>body.append(k,v));body.append("file",file);const r=await fetch(`/api/projects/${project.id}/deliverables`,{method:"POST",body});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||"파일을 등록하지 못했습니다.");setDialogOpen(false);setNotice("산출물 Revision을 등록했습니다.");await load();}catch(e){setNotice(e instanceof Error?e.message:"파일을 등록하지 못했습니다.");}finally{setSaving(false);}};
  const removeVersion=async(versionId:string)=>{if(!project?.id||!window.confirm("이 Revision을 삭제할까요?"))return;const r=await fetch(`/api/projects/${project.id}/deliverables`,{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({versionId})});const d=await r.json() as {error?:string};if(!r.ok){setNotice(d.error||"삭제하지 못했습니다.");return;}setNotice("Revision을 삭제했습니다.");await load();};
  const removeDeliverable=async(deliverableId:string)=>{if(!project?.id||!window.confirm("추가 산출물과 등록된 Revision을 모두 삭제할까요?"))return;const r=await fetch(`/api/projects/${project.id}/deliverables`,{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({deliverableId})});const d=await r.json() as {error?:string};if(!r.ok){setNotice(d.error||"삭제하지 못했습니다.");return;}setDetailId("");setNotice("추가 산출물을 삭제했습니다.");await load();};

  return <div className={`content document-content native-module-workspace ${detail?"has-module-detail":""}`}>
    <section className="document-heading module-compact-heading"><div><p className="eyebrow"><FileText size={15}/> 문서 · 산출물</p></div><div className="document-actions"><select className="project-select" value={project?.id||""} onChange={e=>{const p=projects.find(x=>x.id===e.target.value);if(p)onProjectChange(p)}}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="new-work" disabled={!project||project.status!=="active"} onClick={()=>openRegister()}><Plus size={17}/> 문서 등록</button></div></section>
    {notice&&<div className="module-notice">{notice}<button onClick={()=>setNotice("")}><X size={14}/></button></div>}
    <section className="panel document-board"><div className="document-toolbar module-list-toolbar"><div><button className={sourceFilter==="all"?"active":""} onClick={()=>setSourceFilter("all")}>전체 <em>{deliverables.length}</em></button><button className={sourceFilter==="planned"?"active":""} onClick={()=>setSourceFilter("planned")}>계획 산출물</button><button className={sourceFilter==="ad_hoc"?"active":""} onClick={()=>setSourceFilter("ad_hoc")}>추가 산출물</button></div><label className="work-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="문서명, 분류, WBS 검색"/></label><select className="project-select" value={statusFilter} onChange={e=>setStatusFilter(e.target.value as typeof statusFilter)}><option value="all">전체 상태</option><option value="planned">미등록</option><option value="submitted">등록됨</option></select><button className="filter-button" onClick={()=>{setDraftAdvanced(advanced);setFilterProjectSearch("");setFilterOpen(true)}}><ListFilter size={15}/> 필터</button><button className="filter-button" onClick={()=>void load()}><RefreshCw size={15}/> 새로고침</button></div>
      <div className="document-table-head"><span/><span>문서 / 산출물</span><span>연결 Task</span><span>분류</span><span>Revision</span><span>최근 파일</span><span>상태</span><span/></div>
      <div className="document-rows">{loading?<div className="project-loading">데이터를 불러오는 중입니다.</div>:visible.map(d=>{const t=d.taskId?taskMap.get(d.taskId):undefined,vs=versionMap.get(d.id)||[],latest=vs[0];return <article key={d.id} className={detailId===d.id?"selected":""} onClick={()=>setDetailId(d.id)}><button className={`doc-check ${selectedIds.includes(d.id)?"checked":""}`} onClick={e=>{e.stopPropagation();onSelectedIdsChange(selectedIds.includes(d.id)?selectedIds.filter(x=>x!==d.id):[...selectedIds,d.id])}}>{selectedIds.includes(d.id)&&<Check size={13}/>}</button><div className="document-name"><span className="linked-icon file"><FileText size={17}/></span><div><small>{d.source==="planned"?"계획 산출물":"추가 산출물"} · {d.id.slice(0,8)}</small><strong>{d.name} {d.required?<b>필수</b>:null}</strong></div></div><span className="document-link"><b>{t?`WBS ${t.wbsCode}`:"-"}</b><small>{t?.name||"연결 Task 없음"}</small></span><span className="document-project"><b>{d.type||"미분류"}</b><small>{d.source==="planned"?"템플릿/WBS 기준":"직접 등록"}</small></span><span><b>{d.version||"-"}</b><small>{vs.length}개 Revision</small></span><span className="document-project"><b>{latest?.fileName||"파일 미등록"}</b><small>{latest?bytes(latest.fileSize):"-"}</small></span><em className={`wbs-state ${d.status==="submitted"?"done":"planned"}`}>{d.status==="submitted"?"등록됨":"미등록"}</em><div className="document-row-actions">{latest&&<button className="row-preview" onClick={e=>{e.stopPropagation();onPreview({projectId:project!.id,versionId:latest.id,title:d.name,fileName:latest.fileName,contentType:latest.contentType,revision:latest.revision})}} title="문서 미리보기" aria-label={`${d.name} 미리보기`}><Eye size={16}/></button>}<button className="row-arrow" onClick={e=>{e.stopPropagation();openRegister(d)}} title="새 Revision 등록" aria-label={`${d.name} 새 Revision 등록`}><Plus size={15}/></button></div></article>})}</div>
      {!loading&&!visible.length&&<div className="empty-work"><FileText size={28}/><strong>조건에 맞는 문서·산출물이 없습니다.</strong><p>프로젝트 WBS 산출물 계획을 확인하거나 새 문서를 등록하세요.</p></div>}
    </section>
    {detail&&<aside className="context-panel module-context-panel"><div className="context-head"><div><span>{detail.source==="planned"?"계획 산출물":"추가 산출물"}</span><strong>{detail.name}</strong><p>{detail.type||"미분류"} · {detail.version||"Revision 없음"}</p></div><button onClick={()=>{const closingId=detailId;setDetailId("");onSelectedIdsChange(closingId&&selectedIds.includes(closingId)?selectedIds.filter(id=>id!==closingId):selectedIds)}}><X size={20}/></button></div><div className="context-body detail-body"><div className="context-summary"><span>현재 상태</span><strong>{detail.status==="submitted"?"파일 등록됨":"파일 미등록"}</strong><p>{detail.taskId&&taskMap.get(detail.taskId)?`${taskMap.get(detail.taskId)!.wbsCode} · ${taskMap.get(detail.taskId)!.name}`:"연결 Task 정보가 없습니다."}</p></div><dl><div><dt>문서 분류</dt><dd>{detail.type||"미분류"}</dd></div><div><dt>필수 여부</dt><dd>{detail.required?"필수":"선택"}</dd></div><div><dt>등록 방식</dt><dd>{detail.source==="planned"?"WBS 계획":"추가 등록"}</dd></div><div><dt>Revision</dt><dd>{detailVersions.length}개</dd></div></dl><div className="module-status-actions">{detailVersions[0]&&<button onClick={()=>onPreview({projectId:project!.id,versionId:detailVersions[0].id,title:detail.name,fileName:detailVersions[0].fileName,contentType:detailVersions[0].contentType,revision:detailVersions[0].revision})}><Eye size={15}/> 미리보기</button>}<button className="primary-action" onClick={()=>openRegister(detail)}><Upload size={15}/> 새 Revision 등록</button>{detail.source==="ad_hoc"&&<button className="danger" onClick={()=>void removeDeliverable(detail.id)}><Trash2 size={15}/> 추가 산출물 삭제</button>}</div><div className="linked-title"><div><strong>Revision 이력</strong><span>최신 Revision 우선</span></div></div>{detailVersions.length?detailVersions.map(v=><div className="linked-card" key={v.id}><span className="linked-icon file"><FileText size={17}/></span><span><strong>Rev.{String(v.revision).padStart(2,"0")} · {v.fileName}</strong><small>{bytes(v.fileSize)} · {v.createdBy||"-"} · {new Date(v.createdAt*1000).toLocaleString("ko-KR")}</small></span><a href={`/api/projects/${project!.id}/deliverables?versionId=${encodeURIComponent(v.id)}`} title="다운로드"><Download size={16}/></a><button onClick={()=>void removeVersion(v.id)} title="Revision 삭제"><Trash2 size={15}/></button></div>):<div className="linked-empty"><FileText size={18}/><span>등록된 Revision이 없습니다.</span></div>}</div></aside>}
    {filterOpen&&<ProjectModuleFilterDrawer eyebrow="문서 · 산출물" logic={draftAdvanced.logic} onLogic={logic=>setDraftAdvanced(c=>({...c,logic}))} projects={projects.map(p=>({value:p.id,label:p.name,meta:p.code}))} projectId={project?.id||""} projectSearch={filterProjectSearch} onProjectSearch={setFilterProjectSearch} onProject={id=>{const p=projects.find(x=>x.id===id);if(p)onProjectChange(p)}} groups={[{key:"source",label:"문서 유형",options:[{value:"planned",label:"계획 산출물"},{value:"ad_hoc",label:"추가 산출물"}],selected:draftAdvanced.sources,onToggle:v=>toggleDraft("sources",v)},{key:"status",label:"등록 상태",options:[{value:"planned",label:"미등록"},{value:"submitted",label:"등록됨"}],selected:draftAdvanced.statuses,onToggle:v=>toggleDraft("statuses",v)},{key:"type",label:"문서 분류",options:filterTypes.map(v=>({value:v,label:v})),selected:draftAdvanced.types,onToggle:v=>toggleDraft("types",v)}]} resultCount={draftCount} onReset={()=>setDraftAdvanced({logic:"AND",sources:[],statuses:[],types:[]})} onApply={()=>{setAdvanced(draftAdvanced);setFilterOpen(false)}} onClose={()=>setFilterOpen(false)}/>}
    {dialogOpen&&<div className="wbs-dialog-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setDialogOpen(false)}}><section className="wbs-dialog"><header><div><span>PROJECT DELIVERABLE</span><h2>{form.deliverableId?"새 Revision 등록":"문서 · 산출물 등록"}</h2></div><button onClick={()=>setDialogOpen(false)}><X size={19}/></button></header><div className="wbs-edit-form"><label className="wide"><span>등록 대상</span><select value={form.deliverableId} onChange={e=>{const d=deliverables.find(x=>x.id===e.target.value);setForm(c=>({...c,deliverableId:e.target.value,taskId:d?.taskId||c.taskId,category:d?.type||c.category}))}}><option value="">추가 산출물로 등록</option>{deliverables.map(d=><option key={d.id} value={d.id}>{d.name} · {d.version||"미등록"}</option>)}</select></label>{!form.deliverableId&&<><label><span>연결 Task</span><select value={form.taskId} onChange={e=>setForm(c=>({...c,taskId:e.target.value}))}><option value="">Task 선택</option>{tasks.map(t=><option key={t.id} value={t.id}>{t.wbsCode} · {t.name}</option>)}</select></label><label><span>문서 분류</span><input value={form.category} onChange={e=>setForm(c=>({...c,category:e.target.value}))} placeholder="비우면 파일명 기준 자동 제안"/></label><label className="wide"><span>산출물명</span><input value={form.name} onChange={e=>setForm(c=>({...c,name:e.target.value}))} placeholder="비우면 파일명 사용"/></label></>}<label className="wide"><span>파일</span><input type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/><small>{file?`${file.name} · ${bytes(file.size)}`:"등록할 파일을 선택하세요."}</small></label><label className="wide"><span>Revision 메모</span><textarea value={form.note} onChange={e=>setForm(c=>({...c,note:e.target.value}))} placeholder="변경 내용 또는 등록 사유"/></label></div><footer><button onClick={()=>setDialogOpen(false)}>취소</button><button className="primary" disabled={saving} onClick={()=>void register()}><Upload size={15}/>{saving?"등록 중":"등록"}</button></footer></section></div>}
  </div>;
}
