"use client";

import { useEffect,useMemo,useState } from "react";
import { AlertTriangle,Check,ChevronDown,Download,FileText,ListFilter,Pencil,Plus,RefreshCw,Save,Search,Users,X } from "lucide-react";
import ProjectModuleFilterDrawer from "./project-module-filter-drawer";

type Project={id:string;code:string;name:string;customerName?:string;status:string};
type Task={id:string;wbsCode:string;name:string;kind:"summary"|"task"};
type Member={userId:string;name:string;projectRole:string};
type Attachment={id:string;fileName:string;fileSize:number;contentType?:string;createdAt:number;createdBy?:string};
type Issue={id:string;taskId?:string;issueType:"issue"|"risk"|"collaboration";title:string;description?:string;severity:"low"|"medium"|"high"|"critical";status:"open"|"in_progress"|"resolved"|"closed";ownerUserId?:string;ownerName?:string;createdByName?:string;dueDate?:string;createdAt:number;updatedAt:number;attachmentCount:number;attachments:Attachment[]};
export type IssueAiContext={id:string;kind:"이슈";title:string;meta:string};

type Props={project:Project|null;onProjectChange:(project:Project)=>void;onAiContextChange:(items:IssueAiContext[])=>void;selectedIds:string[];onSelectedIdsChange:(ids:string[])=>void};
const typeLabel=(v:Issue["issueType"])=>v==="risk"?"리스크":v==="collaboration"?"협업요청":"이슈";
const statusLabel=(v:Issue["status"])=>({open:"오픈",in_progress:"조치 중",resolved:"해결",closed:"종료"}[v]);
const severityLabel=(v:Issue["severity"])=>({low:"낮음",medium:"중간",high:"높음",critical:"치명"}[v]);
const bytes=(v:number)=>v>=1048576?`${(v/1048576).toFixed(1)} MB`:v>=1024?`${Math.round(v/1024)} KB`:`${v} B`;

export default function ProjectIssueWorkspace({project,onProjectChange,onAiContextChange,selectedIds,onSelectedIdsChange}:Props){
  const [projects,setProjects]=useState<Project[]>([]);const [tasks,setTasks]=useState<Task[]>([]);const [members,setMembers]=useState<Member[]>([]);const [issues,setIssues]=useState<Issue[]>([]);
  const [loading,setLoading]=useState(false);const [query,setQuery]=useState("");const [typeFilter,setTypeFilter]=useState<"all"|Issue["issueType"]>("all");const [statusFilter,setStatusFilter]=useState<"all"|Issue["status"]>("all");
  const [detailId,setDetailId]=useState("");const [dialogOpen,setDialogOpen]=useState(false);const [editingId,setEditingId]=useState("");const [saving,setSaving]=useState(false);const [notice,setNotice]=useState("");
  const [filterOpen,setFilterOpen]=useState(false);const [filterProjectSearch,setFilterProjectSearch]=useState("");const [advanced,setAdvanced]=useState({logic:"AND" as "AND"|"OR",severities:[] as string[],statuses:[] as string[],owners:[] as string[]});const [draftAdvanced,setDraftAdvanced]=useState(advanced);
  const [form,setForm]=useState({issueType:"issue" as Issue["issueType"],taskId:"",title:"",description:"",severity:"medium" as Issue["severity"],ownerUserId:"",dueDate:""});const [files,setFiles]=useState<File[]>([]);

  useEffect(()=>{fetch("/api/projects",{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then((d:{projects?:Project[]})=>{const list=d.projects??[];setProjects(list);if(!project&&list[0])onProjectChange(list[0]);}).catch(()=>setProjects([]));},[]); // eslint-disable-line react-hooks/exhaustive-deps
  const load=async()=>{if(!project?.id){setTasks([]);setMembers([]);setIssues([]);return;}setLoading(true);setNotice("");try{const [wr,ir]=await Promise.all([fetch(`/api/projects/${project.id}/wbs`,{cache:"no-store"}),fetch(`/api/projects/${project.id}/issues`,{cache:"no-store"})]);if(!wr.ok||!ir.ok)throw new Error("프로젝트 이슈·리스크 데이터를 불러오지 못했습니다.");const w=await wr.json() as {tasks?:Task[];members?:Member[]};const i=await ir.json() as {issues?:Issue[]};setTasks((w.tasks??[]).filter(t=>t.kind==="task"));setMembers(w.members??[]);setIssues(i.issues??[]);}catch(e){setNotice(e instanceof Error?e.message:"데이터를 불러오지 못했습니다.");}finally{setLoading(false);}};
  useEffect(()=>{void load();},[project?.id]); // eslint-disable-line react-hooks/exhaustive-deps

  const taskMap=useMemo(()=>new Map(tasks.map(t=>[t.id,t])),[tasks]);const detail=issues.find(i=>i.id===detailId)||null;
  const baseVisible=useMemo(()=>issues.filter(i=>{const q=query.trim().toLowerCase(),t=i.taskId?taskMap.get(i.taskId):undefined;return(typeFilter==="all"||i.issueType===typeFilter)&&(statusFilter==="all"||i.status===statusFilter)&&(!q||`${i.title} ${i.description||""} ${i.ownerName||""} ${t?.wbsCode||""} ${t?.name||""}`.toLowerCase().includes(q));}),[issues,query,typeFilter,statusFilter,taskMap]);
  const matchesAdvanced=(i:Issue,filter=advanced)=>{const tests=[filter.severities.length?filter.severities.includes(i.severity):null,filter.statuses.length?filter.statuses.includes(i.status):null,filter.owners.length?filter.owners.includes(i.ownerUserId||""):null].filter(v=>v!==null) as boolean[];return !tests.length||filter.logic==="AND"?tests.every(Boolean):tests.some(Boolean)};
  const visible=useMemo(()=>baseVisible.filter(i=>matchesAdvanced(i)),[baseVisible,advanced]);
  const draftCount=useMemo(()=>baseVisible.filter(i=>matchesAdvanced(i,draftAdvanced)).length,[baseVisible,draftAdvanced]);
  const toggleDraft=(key:"severities"|"statuses"|"owners",value:string)=>setDraftAdvanced(c=>({...c,[key]:c[key].includes(value)?c[key].filter(x=>x!==value):[...c[key],value]}));
  useEffect(()=>{onAiContextChange(issues.filter(i=>selectedIds.includes(i.id)).map(i=>{const t=i.taskId?taskMap.get(i.taskId):undefined;return{id:i.id,kind:"이슈" as const,title:i.title,meta:[typeLabel(i.issueType),severityLabel(i.severity),statusLabel(i.status),t?`WBS ${t.wbsCode} ${t.name}`:"",i.ownerName?`담당 ${i.ownerName}`:"",i.dueDate?`기한 ${i.dueDate}`:"",i.description||""].filter(Boolean).join(" · ")};}));},[selectedIds,issues,taskMap]); // eslint-disable-line react-hooks/exhaustive-deps

  const openCreate=()=>{setEditingId("");setForm({issueType:"issue",taskId:tasks[0]?.id||"",title:"",description:"",severity:"medium",ownerUserId:"",dueDate:""});setFiles([]);setDialogOpen(true);};
  const openEdit=(issue:Issue)=>{setEditingId(issue.id);setForm({issueType:issue.issueType,taskId:issue.taskId||"",title:issue.title,description:issue.description||"",severity:issue.severity,ownerUserId:issue.ownerUserId||"",dueDate:issue.dueDate||""});setFiles([]);setDialogOpen(true);};
  const saveIssue=async()=>{if(!project?.id||saving)return;if(!form.taskId||!form.title.trim()){setNotice("Task와 제목을 입력해 주세요.");return;}setSaving(true);try{if(editingId){const r=await fetch(`/api/projects/${project.id}/issues`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:editingId,issueType:form.issueType,title:form.title,description:form.description,severity:form.severity,ownerUserId:form.ownerUserId||null,dueDate:form.dueDate||null})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||"수정하지 못했습니다.");if(files.length){const body=new FormData();body.set("issueId",editingId);files.forEach(f=>body.append("files",f));const ar=await fetch(`/api/projects/${project.id}/issues/attachments`,{method:"POST",body});const ad=await ar.json() as {error?:string};if(!ar.ok)throw new Error(ad.error||"이슈는 수정했지만 첨부파일을 추가하지 못했습니다.");}setNotice(files.length?`수정했습니다. 첨부파일 ${files.length}건을 추가했습니다.`:"수정했습니다.");}else{const body=new FormData();Object.entries(form).forEach(([k,v])=>body.append(k,v));files.forEach(f=>body.append("files",f));const r=await fetch(`/api/projects/${project.id}/issues`,{method:"POST",body});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||"등록하지 못했습니다.");setNotice("등록했습니다.");}const keepId=editingId;setDialogOpen(false);setEditingId("");await load();if(keepId)setDetailId(keepId);}catch(e){setNotice(e instanceof Error?e.message:(editingId?"수정하지 못했습니다.":"등록하지 못했습니다."));}finally{setSaving(false);}};
  const changeStatus=async(id:string,status:Issue["status"])=>{if(!project?.id)return;const before=issues;setIssues(c=>c.map(i=>i.id===id?{...i,status}:i));try{const r=await fetch(`/api/projects/${project.id}/issues`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status})});if(!r.ok){const d=await r.json() as {error?:string};throw new Error(d.error||"상태를 변경하지 못했습니다.");}}catch(e){setIssues(before);setNotice(e instanceof Error?e.message:"상태를 변경하지 못했습니다.");}};

  return <div className={`content issue-content native-module-workspace ${detail?"has-module-detail":""}`}>
    <section className="issue-heading module-compact-heading"><div><p className="eyebrow"><AlertTriangle size={15}/> 이슈 · 리스크</p></div><div className="document-actions"><select className="project-select" value={project?.id||""} onChange={e=>{const p=projects.find(x=>x.id===e.target.value);if(p)onProjectChange(p)}}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="new-work" disabled={!project||project.status!=="active"} onClick={openCreate}><Plus size={17}/> 이슈 등록</button></div></section>
    {notice&&<div className="module-notice">{notice}<button onClick={()=>setNotice("")}><X size={14}/></button></div>}
    <section className="panel issue-board"><div className="issue-toolbar module-list-toolbar"><div><button className={typeFilter==="all"?"active":""} onClick={()=>setTypeFilter("all")}>전체 <em>{issues.length}</em></button><button className={typeFilter==="issue"?"active":""} onClick={()=>setTypeFilter("issue")}>이슈</button><button className={typeFilter==="risk"?"active":""} onClick={()=>setTypeFilter("risk")}>리스크</button><button className={typeFilter==="collaboration"?"active":""} onClick={()=>setTypeFilter("collaboration")}>협업요청</button></div><label className="work-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="제목, 담당자, WBS 검색"/></label><select className="project-select" value={statusFilter} onChange={e=>setStatusFilter(e.target.value as typeof statusFilter)}><option value="all">전체 상태</option><option value="open">오픈</option><option value="in_progress">조치 중</option><option value="resolved">해결</option><option value="closed">종료</option></select><button className="filter-button" onClick={()=>{setDraftAdvanced(advanced);setFilterProjectSearch("");setFilterOpen(true)}}><ListFilter size={15}/> 필터</button><button className="filter-button" onClick={()=>void load()}><RefreshCw size={15}/> 새로고침</button></div>
      <div className="issue-table-head"><span/><span>이슈 · 리스크</span><span>연결 Task</span><span>영향도</span><span>담당자</span><span>기한</span><span>상태</span><span/></div>
      <div className="issue-rows">{loading?<div className="project-loading">데이터를 불러오는 중입니다.</div>:visible.map(i=>{const t=i.taskId?taskMap.get(i.taskId):undefined;return <article key={i.id} className={detailId===i.id?"selected":""} onClick={()=>setDetailId(i.id)}><button className={`doc-check ${selectedIds.includes(i.id)?"checked":""}`} onClick={e=>{e.stopPropagation();onSelectedIdsChange(selectedIds.includes(i.id)?selectedIds.filter(x=>x!==i.id):[...selectedIds,i.id])}}>{selectedIds.includes(i.id)&&<Check size={13}/>}</button><div className="issue-name"><span className={`issue-icon ${i.severity==="critical"||i.severity==="high"?"red":i.severity==="medium"?"amber":"blue"}`}><AlertTriangle size={16}/></span><div><small>{i.id.slice(0,8)} · {typeLabel(i.issueType)}</small><strong>{i.title}</strong></div></div><span className="issue-link"><b>{t?`WBS ${t.wbsCode}`:"-"}</b><small>{t?.name||"연결 Task 없음"}</small></span><span className="issue-impact">{severityLabel(i.severity)}</span><span className="wbs-owner"><b>{(i.ownerName||"-").slice(0,1)}</b>{i.ownerName||"미지정"}</span><time>{i.dueDate||"-"}</time><em className={`wbs-state ${i.status==="resolved"||i.status==="closed"?"done":i.severity==="high"||i.severity==="critical"?"risk":"active"}`}>{statusLabel(i.status)}</em><ChevronDown size={16}/></article>})}</div>
      {!loading&&!visible.length&&<div className="empty-work"><AlertTriangle size={28}/><strong>등록된 이슈·리스크가 없습니다.</strong><p>진행 중인 프로젝트의 실행 Task에서 새 항목을 등록할 수 있습니다.</p></div>}
    </section>
    {detail&&<aside className="context-panel module-context-panel"><div className="context-head"><div><span>{typeLabel(detail.issueType)}</span><strong>{detail.title}</strong><p>{detail.id} · {severityLabel(detail.severity)} · {statusLabel(detail.status)}</p></div><button onClick={()=>{const closingId=detailId;setDetailId("");onSelectedIdsChange(closingId&&selectedIds.includes(closingId)?selectedIds.filter(id=>id!==closingId):selectedIds)}}><X size={20}/></button></div><div className="context-body detail-body"><div className="context-summary"><span>현재 상태</span><strong>{statusLabel(detail.status)} · {severityLabel(detail.severity)} 영향도</strong><p>{detail.description||"등록된 상세 내용이 없습니다."}</p></div><dl><div><dt>연결 Task</dt><dd>{detail.taskId&&taskMap.get(detail.taskId)?`${taskMap.get(detail.taskId)!.wbsCode} · ${taskMap.get(detail.taskId)!.name}`:"-"}</dd></div><div><dt>담당자</dt><dd>{detail.ownerName||"미지정"}</dd></div><div><dt>기한</dt><dd>{detail.dueDate||"미지정"}</dd></div><div><dt>등록자</dt><dd>{detail.createdByName||"-"}</dd></div></dl><div className="module-detail-actions"><button className="primary" onClick={()=>openEdit(detail)}><Pencil size={14}/> 수정</button></div><div className="module-status-actions"><button onClick={()=>void changeStatus(detail.id,"open")}>오픈</button><button onClick={()=>void changeStatus(detail.id,"in_progress")}>조치 중</button><button onClick={()=>void changeStatus(detail.id,"resolved")}>해결</button><button onClick={()=>void changeStatus(detail.id,"closed")}>종료</button></div><div className="linked-title"><div><strong>첨부파일</strong><span>{detail.attachments?.length||0}개</span></div></div>{detail.attachments?.map(a=><a className="linked-card" key={a.id} href={`/api/projects/${project!.id}/issues?attachmentId=${encodeURIComponent(a.id)}`}><span className="linked-icon file"><FileText size={17}/></span><span><strong>{a.fileName}</strong><small>{bytes(a.fileSize)} · {a.createdBy||"-"}</small></span><Download size={17}/></a>)}</div></aside>}
    {filterOpen&&<ProjectModuleFilterDrawer eyebrow="이슈 · 리스크" logic={draftAdvanced.logic} onLogic={logic=>setDraftAdvanced(c=>({...c,logic}))} projects={projects.map(p=>({value:p.id,label:p.name,meta:p.code}))} projectId={project?.id||""} projectSearch={filterProjectSearch} onProjectSearch={setFilterProjectSearch} onProject={id=>{const p=projects.find(x=>x.id===id);if(p)onProjectChange(p)}} groups={[{key:"severity",label:"위험도",options:[{value:"critical",label:"치명"},{value:"high",label:"높음"},{value:"medium",label:"중간"},{value:"low",label:"낮음"}],selected:draftAdvanced.severities,onToggle:v=>toggleDraft("severities",v)},{key:"status",label:"조치 상태",options:[{value:"open",label:"오픈"},{value:"in_progress",label:"조치 중"},{value:"resolved",label:"해결"},{value:"closed",label:"종료"}],selected:draftAdvanced.statuses,onToggle:v=>toggleDraft("statuses",v)},{key:"owner",label:"담당자",options:members.map(m=>({value:m.userId,label:m.name,meta:m.projectRole})),selected:draftAdvanced.owners,onToggle:v=>toggleDraft("owners",v)}]} resultCount={draftCount} onReset={()=>setDraftAdvanced({logic:"AND",severities:[],statuses:[],owners:[]})} onApply={()=>{setAdvanced(draftAdvanced);setFilterOpen(false)}} onClose={()=>setFilterOpen(false)}/>}
    {dialogOpen&&<div className="wbs-dialog-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setDialogOpen(false)}}><section className="wbs-dialog"><header><div><span>PROJECT ISSUE</span><h2>{editingId?"이슈 · 리스크 수정":"이슈 · 리스크 등록"}</h2></div><button onClick={()=>setDialogOpen(false)}><X size={19}/></button></header><div className="wbs-edit-form"><label><span>구분</span><select value={form.issueType} onChange={e=>setForm(c=>({...c,issueType:e.target.value as Issue["issueType"]}))}><option value="issue">이슈</option><option value="risk">리스크</option><option value="collaboration">협업요청</option></select></label><label><span>연결 Task</span><select value={form.taskId} disabled={Boolean(editingId)} onChange={e=>setForm(c=>({...c,taskId:e.target.value}))}><option value="">Task 선택</option>{tasks.map(t=><option key={t.id} value={t.id}>{t.wbsCode} · {t.name}</option>)}</select></label><label className="wide"><span>제목</span><input value={form.title} onChange={e=>setForm(c=>({...c,title:e.target.value}))}/></label><label className="wide"><span>내용</span><textarea value={form.description} onChange={e=>setForm(c=>({...c,description:e.target.value}))}/></label><label><span>영향도</span><select value={form.severity} onChange={e=>setForm(c=>({...c,severity:e.target.value as Issue["severity"]}))}><option value="low">낮음</option><option value="medium">중간</option><option value="high">높음</option><option value="critical">치명</option></select></label><label><span>처리 담당자</span><select value={form.ownerUserId} onChange={e=>setForm(c=>({...c,ownerUserId:e.target.value}))}><option value="">미지정</option>{members.map(m=><option key={m.userId} value={m.userId}>{m.name} · {m.projectRole}</option>)}</select></label><label><span>기한</span><input type="date" value={form.dueDate} onChange={e=>setForm(c=>({...c,dueDate:e.target.value}))}/></label><label className="wide"><span>첨부파일</span><input type="file" multiple onChange={e=>setFiles(Array.from(e.target.files||[]))}/><small>{files.length?`${files.length}개 파일 선택됨`:"필요한 근거 자료를 함께 등록할 수 있습니다."}</small></label></div><footer><button onClick={()=>setDialogOpen(false)}>취소</button><button className="primary" disabled={saving} onClick={()=>void saveIssue()}><Users size={15}/>{saving?"등록 중":"등록"}</button></footer></section></div>}
  </div>;
}
