"use client";

import { useCallback,useEffect,useMemo,useState } from "react";
import { createPortal } from "react-dom";
import { AlertTriangle,Check,Download,FileText,History,Pencil,Plus,Save,Sparkles,Trash2,Upload,X } from "lucide-react";
import CommonAiChatPanel,{type CommonAiContextItem} from "./common-ai-chat-panel";

type Project={id:string;code:string;name:string;status:string};
type Member={userId:string;name:string;projectRole:string};
type Deliverable={id:string;name:string;type?:string;required?:boolean|number;status?:string;version?:string;source?:"planned"|"ad_hoc";revisionCount?:number};
type DeliverableVersion={id:string;deliverableId:string;revision:number;fileName:string;fileSize:number;note?:string;createdAt:number;createdBy?:string};
type IssueAttachment={id:string;issueId:string;fileName:string;fileSize:number;createdAt:number;createdBy?:string};
type Issue={id:string;taskId:string;issueType:"issue"|"risk"|"collaboration";title:string;description?:string;severity:string;status:string;ownerUserId?:string;ownerName?:string;createdByUserId?:string;createdByName?:string;dueDate?:string;attachments?:IssueAttachment[]};
type WbsTask={id:string;wbsCode:string;level:number;kind:"summary"|"task";name:string;taskType:"normal"|"gate";durationDays:number;plannedStart?:string;plannedEnd?:string;predecessorCode?:string;roleCode?:string;assigneeName?:string;progress:number;status:string;deliverables:Deliverable[]};
type ActualSummary={taskId:string;latestActualDate?:string;latestProgress?:number;totalHours:number;issueCount:number};
type PanelMode="detail"|"actual"|"deliverables"|"issues"|"history"|"ai";
type AiContextItem={key:string;id:string;kind:"WBS"|"산출물"|"이슈"|"리스크"|"협업";title:string;meta:string;taskId?:string;wbsCode?:string};

const today=()=>new Date().toISOString().slice(0,10);
const screenProjectCode=()=>document.querySelector(".unified-project-info small")?.textContent?.match(/[A-Z]+-\d{4}-\d+/i)?.[0]||"";
const rowCode=(row:HTMLElement)=>row.querySelector(".unified-task-cell > b, :scope > span:nth-child(2) > b")?.textContent?.trim()||"";
const unifiedRows=()=>Array.from(document.querySelectorAll(".unified-grid-row,.unified-gantt-row")) as HTMLElement[];
function topLevelCell(target:HTMLElement,row:HTMLElement){let node:HTMLElement|null=target;while(node&&node.parentElement&&node.parentElement!==row)node=node.parentElement;return node&&node.parentElement===row?node:null;}
const typeLabel=(v:string)=>v==="risk"?"리스크":v==="collaboration"?"협업":"이슈";
const statusLabel=(v:string)=>v==="resolved"||v==="closed"?"완료":v==="in_progress"?"진행":"열림";
const fmtSize=(n:number)=>n>1024*1024?`${(n/1024/1024).toFixed(1)}MB`:n>1024?`${Math.round(n/1024)}KB`:`${n}B`;
const safeJson=async(response:Response)=>{const text=await response.text();if(!text)return {} as {error?:string};try{return JSON.parse(text) as {error?:string}}catch{return {error:text}}};
const emptyIssueDraft=()=>({issueType:"issue",title:"",description:"",severity:"medium",ownerUserId:"",dueDate:""});

export default function WbsDirectContext(){
  const [project,setProject]=useState<Project|null>(null),[tasks,setTasks]=useState<WbsTask[]>([]),[members,setMembers]=useState<Member[]>([]),[actuals,setActuals]=useState<Record<string,ActualSummary>>({});
  const [activeCode,setActiveCode]=useState(""),[mode,setMode]=useState<PanelMode>("detail"),[selected,setSelected]=useState<string[]>([]),[aiBasket,setAiBasket]=useState<AiContextItem[]>([]),[domTick,setDomTick]=useState(0),[saving,setSaving]=useState(false),[notice,setNotice]=useState("");
  const [actualDraft,setActualDraft]=useState({actualDate:today(),actualHours:"",progress:0,workNote:"",completed:false});
  const [deliverables,setDeliverables]=useState<Deliverable[]>([]),[versions,setVersions]=useState<DeliverableVersion[]>([]),[issues,setIssues]=useState<Issue[]>([]);
  const [uploadId,setUploadId]=useState(""),[uploadFile,setUploadFile]=useState<File|null>(null),[uploadNote,setUploadNote]=useState("");
  const [adHocOpen,setAdHocOpen]=useState(false),[adHocFile,setAdHocFile]=useState<File|null>(null),[adHocName,setAdHocName]=useState(""),[adHocCategory,setAdHocCategory]=useState(""),[dragging,setDragging]=useState(false);
  const [issueDraft,setIssueDraft]=useState(emptyIssueDraft()),[issueFiles,setIssueFiles]=useState<File[]>([]),[issueDragging,setIssueDragging]=useState(false),[editingIssueId,setEditingIssueId]=useState(""),[issueFormOpen,setIssueFormOpen]=useState(false);

  const activeTask=tasks.find(t=>t.wbsCode===activeCode)||null;
  const selectedTasks=useMemo(()=>tasks.filter(t=>selected.includes(t.wbsCode)),[tasks,selected]);
  const selectedOutputs=selectedTasks.reduce((s,t)=>s+t.deliverables.length,0),selectedIssues=selectedTasks.reduce((s,t)=>s+(actuals[t.id]?.issueCount||0),0);
  const taskAiItems=useMemo<AiContextItem[]>(()=>selectedTasks.map(t=>({key:`task:${t.id}`,id:t.id,kind:"WBS",title:`${t.wbsCode} · ${t.name}`,wbsCode:t.wbsCode,taskId:t.id,meta:`진행률 ${t.progress}% · 산출물 ${t.deliverables.length} · 이슈 ${actuals[t.id]?.issueCount||0}`})),[selectedTasks,actuals]);
  const aiContextItems=useMemo(()=>[...taskAiItems,...aiBasket.filter(item=>!taskAiItems.some(t=>t.key===item.key))],[taskAiItems,aiBasket]);
  const toast=(m:string)=>{setNotice(m);window.setTimeout(()=>setNotice(""),1800)};
  const toggleAiItem=(item:AiContextItem)=>setAiBasket(current=>current.some(x=>x.key===item.key)?current.filter(x=>x.key!==item.key):[...current,item]);
  const removeAiItem=(item:AiContextItem)=>{if(item.kind==="WBS"&&item.wbsCode)setSelected(current=>current.filter(code=>code!==item.wbsCode));else setAiBasket(current=>current.filter(x=>x.key!==item.key))};
  const clearAiContext=()=>{setSelected([]);setAiBasket([])};

  const load=useCallback(async()=>{
    const code=screenProjectCode();if(!code)return;
    const pr=await fetch("/api/projects",{cache:"no-store"});if(!pr.ok)return;
    const data=await pr.json() as {projects?:Project[]};const found=(data.projects??[]).find(p=>p.code.toLowerCase()===code.toLowerCase())||null;if(!found)return;
    setProject(found);
    const [wr,ar]=await Promise.all([fetch(`/api/projects/${found.id}/wbs`,{cache:"no-store"}),fetch(`/api/projects/${found.id}/actuals`,{cache:"no-store"})]);
    if(wr.ok){const w=await wr.json() as {tasks?:WbsTask[];members?:Member[]};setTasks(w.tasks??[]);setMembers(w.members??[])}
    if(ar.ok){const a=await ar.json() as {summaries?:ActualSummary[]};setActuals(Object.fromEntries((a.summaries??[]).map(x=>[x.taskId,x])))}
  },[]);

  const loadOps=useCallback(async(task:WbsTask)=>{
    if(!project||task.kind==="summary")return;
    const [dr,ir]=await Promise.all([fetch(`/api/projects/${project.id}/deliverables?taskId=${task.id}`,{cache:"no-store"}),fetch(`/api/projects/${project.id}/issues?taskId=${task.id}`,{cache:"no-store"})]);
    if(dr.ok){const d=await dr.json() as {deliverables?:Deliverable[];versions?:DeliverableVersion[]};setDeliverables(d.deliverables??[]);setVersions(d.versions??[])}
    if(ir.ok){const i=await ir.json() as {issues?:Issue[]};setIssues(i.issues??[])}
  },[project]);

  useEffect(()=>{void load();const o=new MutationObserver(()=>{setDomTick(v=>v+1);const c=screenProjectCode();if(c&&c!==project?.code)void load()});o.observe(document.body,{subtree:true,childList:true});return()=>o.disconnect()},[load,project?.code]);
  const openTask=(code:string,next:PanelMode="detail")=>{const t=tasks.find(x=>x.wbsCode===code);if(!t)return;setActiveCode(code);setMode(next);if(next==="actual")setActualDraft({actualDate:today(),actualHours:"",progress:Number(t.progress)||0,workNote:"",completed:Number(t.progress)>=100});if(next==="deliverables"||next==="issues"||next==="history")void loadOps(t)};
  useEffect(()=>{setAdHocOpen(false);setAdHocFile(null);setAdHocName("");setAdHocCategory("");setDragging(false);setUploadId("");setUploadFile(null);setUploadNote("");setIssueDraft(emptyIssueDraft());setIssueFiles([]);setIssueDragging(false);setEditingIssueId("");setIssueFormOpen(false)},[activeCode]);
  useEffect(()=>{if(mode!=="deliverables"){setAdHocOpen(false);setAdHocFile(null);setAdHocName("");setAdHocCategory("");setDragging(false);setUploadId("");setUploadFile(null);setUploadNote("")}if(mode!=="issues"){setIssueDraft(emptyIssueDraft());setIssueFiles([]);setIssueDragging(false);setEditingIssueId("");setIssueFormOpen(false)}},[mode]);
  useEffect(()=>{for(const row of unifiedRows()){const code=rowCode(row),on=selected.includes(code);row.classList.toggle("multi-selected",on);const b=row.querySelector(".unified-check") as HTMLButtonElement|null;b?.classList.toggle("checked",on);b?.setAttribute("aria-pressed",String(on))}},[selected,domTick]);
  useEffect(()=>{const h=(e:MouseEvent)=>{const target=e.target as HTMLElement,row=target.closest(".unified-grid-row,.unified-gantt-row") as HTMLElement|null;if(row){const code=rowCode(row);const task=tasks.find(t=>t.wbsCode===code);if(!code||!task||target.closest(".tree-toggle,.row-action"))return;e.preventDefault();e.stopPropagation();if(target.closest(".unified-check")){setSelected(c=>c.includes(code)?c.filter(x=>x!==code):[...c,code]);return}if(row.classList.contains("unified-grid-row")){const cell=topLevelCell(target,row),index=cell?Array.from(row.children).indexOf(cell):-1;if(index===10)return openTask(code,"deliverables");if(index===11)return openTask(code,"issues");if(index===12||index===14)return openTask(code,"actual")}const retained:PanelMode=task.kind==="summary"?"detail":(mode==="actual"||mode==="deliverables"||mode==="issues"?mode:"detail");openTask(code,retained)}else if(target.closest(".floating-ai")&&aiContextItems.length&&document.querySelector(".unified-wbs-host")){e.preventDefault();e.stopPropagation();const targetCode=activeCode||selected[0]||aiBasket[0]?.wbsCode||"";if(targetCode)setActiveCode(targetCode);setMode("ai")}};document.addEventListener("click",h,true);return()=>document.removeEventListener("click",h,true)},[tasks,selected,mode,aiContextItems,activeCode,aiBasket]);

  const saveActual=async()=>{if(!project||!activeTask||saving)return;setSaving(true);try{const p=actualDraft.completed?100:actualDraft.progress,r=await fetch(`/api/projects/${project.id}/actuals`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({taskId:activeTask.id,actualDate:actualDraft.actualDate,actualHours:Number(actualDraft.actualHours)||0,progress:p,workNote:actualDraft.workNote,completed:actualDraft.completed})}),j=await r.json() as {error?:string};if(!r.ok)throw new Error(j.error||"실적 저장 실패");toast("실적을 저장했습니다.");await load()}catch(e){alert(e instanceof Error?e.message:"실적 저장 실패")}finally{setSaving(false)}};

  const uploadPlanned=async()=>{if(!project||!activeTask||!uploadId||!uploadFile||saving)return;setSaving(true);try{const f=new FormData();f.set("deliverableId",uploadId);f.set("file",uploadFile);f.set("note",uploadNote);const r=await fetch(`/api/projects/${project.id}/deliverables`,{method:"POST",body:f}),j=await r.json() as {error?:string;version?:string};if(!r.ok)throw new Error(j.error||"산출물 등록 실패");toast(`${j.version||"새 Revision"}으로 등록했습니다.`);setUploadFile(null);setUploadNote("");setUploadId("");await Promise.all([load(),loadOps(activeTask)])}catch(e){alert(e instanceof Error?e.message:"산출물 등록 실패")}finally{setSaving(false)}};

  const chooseAdHocFile=(file:File)=>{setAdHocFile(file);if(!adHocName)setAdHocName(file.name.replace(/\.[^.]+$/,""));void suggestCategory(file.name)};
  const suggestCategory=async(name?:string)=>{if(!project)return;const r=await fetch(`/api/projects/${project.id}/deliverables`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"suggest-category",name:name||adHocName||adHocFile?.name||""})});if(r.ok){const j=await r.json() as {category?:string};setAdHocCategory(j.category||"")}};
  const uploadAdHoc=async()=>{if(!project||!activeTask||!adHocFile||saving)return;setSaving(true);try{const f=new FormData();f.set("taskId",activeTask.id);f.set("name",adHocName.trim());f.set("category",adHocCategory.trim());f.set("file",adHocFile);const r=await fetch(`/api/projects/${project.id}/deliverables`,{method:"POST",body:f}),j=await r.json() as {error?:string;version?:string;category?:string};if(!r.ok)throw new Error(j.error||"추가 산출물 등록 실패");toast(`추가 산출물을 ${j.version||"Rev.01"}으로 등록했습니다.`);setAdHocOpen(false);setAdHocFile(null);setAdHocName("");setAdHocCategory("");await Promise.all([load(),loadOps(activeTask)])}catch(e){alert(e instanceof Error?e.message:"추가 산출물 등록 실패")}finally{setSaving(false)}};

  const deleteVersion=async(version:DeliverableVersion)=>{if(!project||!activeTask||saving)return;if(!window.confirm(`Rev.${String(version.revision).padStart(2,"0")} '${version.fileName}'을 삭제할까요?\n삭제한 Revision 번호는 다시 사용하지 않습니다.`))return;setSaving(true);try{const r=await fetch(`/api/projects/${project.id}/deliverables`,{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({versionId:version.id})});const j=await safeJson(r);if(!r.ok)throw new Error(j.error||"Revision 삭제 실패");toast(`Rev.${String(version.revision).padStart(2,"0")}을 삭제했습니다.`);await Promise.all([load(),loadOps(activeTask)])}catch(e){window.alert(e instanceof Error?e.message:"Revision 삭제 실패")}finally{setSaving(false)}};

  const startIssueAdd=()=>{setEditingIssueId("");setIssueDraft(emptyIssueDraft());setIssueFiles([]);setIssueDragging(false);setIssueFormOpen(true)};
  const startIssueEdit=(issue:Issue)=>{setEditingIssueId(issue.id);setIssueFiles([]);setIssueDraft({issueType:issue.issueType,title:issue.title,description:issue.description||"",severity:issue.severity||"medium",ownerUserId:issue.ownerUserId||"",dueDate:issue.dueDate||""});setIssueFormOpen(true)};
  const cancelIssueEdit=()=>{setEditingIssueId("");setIssueFiles([]);setIssueDraft(emptyIssueDraft());setIssueFormOpen(false)};
  const saveIssue=async()=>{if(!project||!activeTask||saving)return;setSaving(true);try{if(editingIssueId){const r=await fetch(`/api/projects/${project.id}/issues`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:editingIssueId,...issueDraft})}),j=await safeJson(r);if(!r.ok)throw new Error(j.error||"수정 실패");if(issueFiles.length){const f=new FormData();f.set("issueId",editingIssueId);issueFiles.forEach(file=>f.append("files",file));const ar=await fetch(`/api/projects/${project.id}/issues/attachments`,{method:"POST",body:f}),aj=await safeJson(ar);if(!ar.ok)throw new Error(aj.error||"첨부파일 추가 실패")}toast(`${typeLabel(issueDraft.issueType)}를 수정했습니다.${issueFiles.length?` 첨부 ${issueFiles.length}건 추가`:""}`)}else{const f=new FormData();Object.entries({...issueDraft,taskId:activeTask.id}).forEach(([k,v])=>f.set(k,String(v||"")));issueFiles.forEach(file=>f.append("files",file));const r=await fetch(`/api/projects/${project.id}/issues`,{method:"POST",body:f}),j=await safeJson(r);if(!r.ok)throw new Error(j.error||"등록 실패");toast(`${typeLabel(issueDraft.issueType)}를 등록했습니다.`)}setEditingIssueId("");setIssueDraft(emptyIssueDraft());setIssueFiles([]);setIssueFormOpen(false);await Promise.all([load(),loadOps(activeTask)])}catch(e){alert(e instanceof Error?e.message:(editingIssueId?"수정 실패":"등록 실패"))}finally{setSaving(false)}};
  const setIssueStatus=async(id:string,status:string)=>{if(!project||!activeTask)return;const r=await fetch(`/api/projects/${project.id}/issues`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status})});if(r.ok){toast("상태를 변경했습니다.");await Promise.all([load(),loadOps(activeTask)])}};


  const floatingAi=typeof document!=="undefined"?document.querySelector(".floating-ai"):null,shell=typeof document!=="undefined"?document.querySelector(".unified-wbs-shell"):null;
  return <>
    {floatingAi&&aiContextItems.length>0&&createPortal(<b className="direct-wbs-ai-badge">{aiContextItems.length}</b>,floatingAi)}
    {activeTask&&typeof document!=="undefined"&&createPortal(<aside className="context-panel direct-wbs-context">
      <div className="context-head"><div><span>WBS</span><strong>{activeTask.name}</strong><p>WBS {activeTask.wbsCode} · {activeTask.status}</p></div><button onClick={()=>setActiveCode("")}><X size={20}/></button></div>
      <div className="context-tabs wbs-context-tabs"><button className={mode==="detail"?"active":""} onClick={()=>setMode("detail")}>상세정보</button>{activeTask.kind!=="summary"&&<button className={mode==="actual"?"active":""} onClick={()=>openTask(activeTask.wbsCode,"actual")}><Pencil size={14}/> 실적</button>}<button className={mode==="deliverables"?"active":""} onClick={()=>openTask(activeTask.wbsCode,"deliverables")}>산출물</button><button className={mode==="issues"?"active":""} onClick={()=>openTask(activeTask.wbsCode,"issues")}>이슈</button><button className={mode==="history"?"active":""} onClick={()=>openTask(activeTask.wbsCode,"history")}>이력</button><button className={mode==="ai"?"active":""} onClick={()=>setMode("ai")}><Sparkles size={14}/> AI 대화</button></div>

      {mode==="detail"&&<div className="context-body detail-body"><div className="context-summary"><span>현재 Task</span><strong>{activeTask.wbsCode} · {activeTask.name}</strong><p>프로젝트 DB WBS를 직접 참조합니다.</p></div><dl><div><dt>구분</dt><dd>{activeTask.kind==="summary"?`${activeTask.level}레벨 그룹`:"실행 Task"}</dd></div><div><dt>Task Type</dt><dd>{activeTask.taskType==="gate"?"Gate Task":"일반 Task"}</dd></div><div><dt>계획 기간</dt><dd>{activeTask.plannedStart||"미정"} — {activeTask.plannedEnd||"미정"}</dd></div><div><dt>Role / 담당자</dt><dd>{activeTask.roleCode||"미지정"} · {activeTask.assigneeName||"미배정"}</dd></div><div><dt>진척률</dt><dd>{activeTask.progress}%</dd></div><div><dt>산출물 / 이슈</dt><dd>{activeTask.deliverables.length} / {actuals[activeTask.id]?.issueCount||0}</dd></div></dl></div>}

      {mode==="actual"&&<div className="context-body direct-actual-body"><div className="context-summary"><span>WBS 실적입력</span><strong>{activeTask.wbsCode} · {activeTask.name}</strong></div><div className="direct-actual-form"><label><span>실적일</span><input type="date" value={actualDraft.actualDate} onChange={e=>setActualDraft({...actualDraft,actualDate:e.target.value})}/></label><label><span>실적공수</span><div><input type="number" min="0" step="0.5" value={actualDraft.actualHours} onChange={e=>setActualDraft({...actualDraft,actualHours:e.target.value})}/><b>시간</b></div></label><label className="wide"><span>진행률</span><div className="direct-progress-number"><input type="number" min="0" max="100" value={actualDraft.progress} onChange={e=>{const v=Math.max(0,Math.min(100,Number(e.target.value)||0));setActualDraft({...actualDraft,progress:v,completed:v>=100})}}/><b>%</b></div><input className="direct-progress-range" type="range" min="0" max="100" value={actualDraft.progress} onChange={e=>{const v=Number(e.target.value);setActualDraft({...actualDraft,progress:v,completed:v>=100})}}/></label><label className="wide"><span>오늘 작업 내용</span><textarea value={actualDraft.workNote} onChange={e=>setActualDraft({...actualDraft,workNote:e.target.value})}/></label><label className="direct-complete"><input type="checkbox" checked={actualDraft.completed} onChange={e=>setActualDraft({...actualDraft,completed:e.target.checked,progress:e.target.checked?100:Math.min(actualDraft.progress,99)})}/><span>Task 완료</span></label></div><div className="direct-panel-actions"><button onClick={()=>openTask(activeTask.wbsCode,"deliverables")}><FileText size={14}/> 산출물</button><button onClick={()=>openTask(activeTask.wbsCode,"issues")}><AlertTriangle size={14}/> 이슈</button><button className="primary" disabled={saving} onClick={()=>void saveActual()}><Save size={14}/>{saving?"저장 중":"실적 저장"}</button></div></div>}

      {mode==="deliverables"&&<div className="context-body ops-body"><div className="ops-section-head"><strong>산출물 등록</strong><button className="ops-upload-open" onClick={()=>setAdHocOpen(v=>!v)}><Plus size={14}/> 추가 산출물</button></div>
        {adHocOpen&&<div className="ops-form"><div className={`drop-zone ${dragging?"dragging":""}`} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);const f=e.dataTransfer.files?.[0];if(f)chooseAdHocFile(f)}} onClick={()=>document.getElementById("adhoc-file-input")?.click()}><Upload size={21}/><strong>{adHocFile?adHocFile.name:"파일을 여기에 드래그하거나 클릭하세요"}</strong><small>{adHocFile?fmtSize(adHocFile.size):"지정되지 않은 추가 산출물도 바로 등록할 수 있습니다."}</small><input id="adhoc-file-input" hidden type="file" onChange={e=>{const f=e.target.files?.[0];if(f)chooseAdHocFile(f)}}/></div><input value={adHocName} onChange={e=>setAdHocName(e.target.value)} placeholder="산출물 이름"/><div className="ai-category-row"><input value={adHocCategory} onChange={e=>setAdHocCategory(e.target.value)} placeholder="카테고리"/><button onClick={()=>void suggestCategory()}><Sparkles size={14}/> AI 추천</button></div><button className="primary" disabled={!adHocFile||saving} onClick={()=>void uploadAdHoc()}><Upload size={14}/> 추가 산출물 등록</button></div>}
        {deliverables.length?deliverables.map(d=>{const revs=versions.filter(v=>v.deliverableId===d.id),aiKey=`deliverable:${d.id}`,picked=aiBasket.some(x=>x.key===aiKey);const aiItem:AiContextItem={key:aiKey,id:d.id,kind:"산출물",title:d.name,taskId:activeTask.id,wbsCode:activeTask.wbsCode,meta:`WBS ${activeTask.wbsCode} · ${d.type||"미분류"} · ${d.version||"미등록"}${revs[0]?.fileName?` · 파일 ${revs[0].fileName}`:""}`};return <div className={`ops-card ${picked?"ai-picked":""}`} key={d.id}><div className="ops-card-head"><span><button type="button" className={`ai-context-check ${picked?"checked":""}`} title="AI 문맥 선택" aria-pressed={picked} onClick={e=>{e.stopPropagation();toggleAiItem(aiItem)}}>{picked&&<Check size={12}/>}</button><FileText size={17}/><strong>{d.name}</strong><small>{d.type||"미분류"} · {d.source==="ad_hoc"?"일반 산출물":(d.required===false||Number(d.required)===0?"선택":"필수")}</small></span><div><span className={`source-badge ${d.source==="ad_hoc"?"ad-hoc":""}`}>{d.source==="ad_hoc"?"추가":"지정"}</span> <em>{d.version||"미등록"}</em></div></div>{revs.slice(0,3).map(v=><div className="revision-row" key={v.id}><span>Rev.{String(v.revision).padStart(2,"0")} · {v.fileName}<small> · {v.createdBy||"사용자"}</small></span><div className="revision-actions"><button onClick={()=>{if(project)window.open(`/api/projects/${project.id}/deliverables?versionId=${v.id}`,"_blank")}}><Download size={13}/> 다운로드</button><button type="button" className="ops-delete-button" disabled={saving} onClick={()=>void deleteVersion(v)}><Trash2 size={13}/> 삭제</button></div></div>)}<button className="ops-upload-open" onClick={()=>setUploadId(uploadId===d.id?"":d.id)}><Upload size={13}/> {d.version?"새 Revision":"파일 등록"}</button>{uploadId===d.id&&<div className="ops-form"><input type="file" onChange={e=>setUploadFile(e.target.files?.[0]||null)}/><input value={uploadNote} onChange={e=>setUploadNote(e.target.value)} placeholder="Revision 메모 (선택)"/><button className="primary" disabled={!uploadFile||saving} onClick={()=>void uploadPlanned()}><Save size={14}/> 등록</button></div>}</div>}):<div className="empty-ops">지정된 산출물이 없습니다. 위의 추가 산출물로 바로 등록할 수 있습니다.</div>}
      </div>}

      {mode==="issues"&&<div className="context-body ops-body"><div className="ops-section-head"><strong>이슈 · 리스크 · 협업</strong><button className="ops-upload-open" onClick={()=>{if(issueFormOpen)cancelIssueEdit();else startIssueAdd()}}>{issueFormOpen?<X size={14}/>:<Plus size={14}/>} {issueFormOpen?"닫기":"추가"}</button></div>{issueFormOpen&&<div className="ops-form issue-form"><div className="issue-type-buttons full">{(["issue","risk","collaboration"] as const).map(v=><button key={v} className={issueDraft.issueType===v?"active":""} onClick={()=>setIssueDraft({...issueDraft,issueType:v})}>{v==="issue"?<AlertTriangle size={13}/>:v==="risk"?<AlertTriangle size={13}/>:<Check size={13}/>} {typeLabel(v)}</button>)}</div><div className="issue-meta-auto">{editingIssueId?"기 등록 항목 수정 중":"등록자: 로그인 사용자 자동 · 처리 담당자는 별도 지정"}</div><input className="full" value={issueDraft.title} onChange={e=>setIssueDraft({...issueDraft,title:e.target.value})} placeholder="제목"/><textarea className="full" value={issueDraft.description} onChange={e=>setIssueDraft({...issueDraft,description:e.target.value})} placeholder="내용"/><select value={issueDraft.severity} onChange={e=>setIssueDraft({...issueDraft,severity:e.target.value})}><option value="low">낮음</option><option value="medium">보통</option><option value="high">높음</option><option value="critical">긴급</option></select><select value={issueDraft.ownerUserId} onChange={e=>setIssueDraft({...issueDraft,ownerUserId:e.target.value})}><option value="">처리 담당자 미지정</option>{members.map(m=><option key={m.userId} value={m.userId}>{m.name} · {m.projectRole}</option>)}</select><input type="date" value={issueDraft.dueDate} onChange={e=>setIssueDraft({...issueDraft,dueDate:e.target.value})}/><div className="issue-files full"><div className={`issue-drop-zone ${issueDragging?"dragging":""}`} onDragOver={e=>{e.preventDefault();setIssueDragging(true)}} onDragLeave={()=>setIssueDragging(false)} onDrop={e=>{e.preventDefault();setIssueDragging(false);setIssueFiles(Array.from(e.dataTransfer.files||[]))}} onClick={()=>document.getElementById("issue-file-input")?.click()}><Upload size={16}/><span>{issueFiles.length?`${issueFiles.length}개 파일 선택`:"선택된 파일 없음"}</span><small>드래그앤드롭 또는 클릭</small></div><input id="issue-file-input" hidden type="file" multiple onChange={e=>setIssueFiles(Array.from(e.target.files||[]))}/>{issueFiles.length>0&&<small className="issue-file-names">{issueFiles.map(f=>f.name).join(" · ")}</small>}{editingIssueId&&<small className="issue-file-names">기존 첨부파일은 유지되며 선택한 파일은 추가 첨부됩니다.</small>}</div><div className="issue-form-actions full"><button type="button" className="secondary" onClick={cancelIssueEdit}>취소</button><button className="primary" disabled={!issueDraft.title.trim()||saving||(issueDraft.issueType==="collaboration"&&!issueDraft.ownerUserId)} onClick={()=>void saveIssue()}>{editingIssueId?<Save size={14}/>:<Plus size={14}/>} {editingIssueId?"수정 저장":`${typeLabel(issueDraft.issueType)} 등록`}</button></div></div>}
        <div className="issue-list">{issues.length?issues.map(i=>{const kind=typeLabel(i.issueType) as "이슈"|"리스크"|"협업",aiKey=`issue:${i.id}`,picked=aiBasket.some(x=>x.key===aiKey);const aiItem:AiContextItem={key:aiKey,id:i.id,kind,title:i.title,taskId:activeTask.id,wbsCode:activeTask.wbsCode,meta:`WBS ${activeTask.wbsCode} · ${i.severity} · ${statusLabel(i.status)} · 처리 ${i.ownerName||"미지정"}${i.dueDate?` · ${i.dueDate}`:""}${i.description?` · ${i.description}`:""}`};return <div className={`issue-card ${editingIssueId===i.id?"editing":""} ${picked?"ai-picked":""}`} key={i.id}><button type="button" className={`ai-context-check issue-check ${picked?"checked":""}`} title="AI 문맥 선택" aria-pressed={picked} onClick={e=>{e.stopPropagation();toggleAiItem(aiItem)}}>{picked&&<Check size={12}/>}</button><div><b>{typeLabel(i.issueType)} · {i.severity}</b><strong>{i.title}</strong><small>등록자 {i.createdByName||"로그인 사용자"} · 처리 {i.ownerName||"미지정"}{i.dueDate?` · ${i.dueDate}`:""}</small>{i.description&&<small>{i.description}</small>}{i.attachments&&i.attachments.length>0&&<div className="attachment-row">{i.attachments.map(a=><a key={a.id} href={`/api/projects/${project?.id}/issues?attachmentId=${a.id}`} target="_blank" rel="noreferrer">📎 {a.fileName}</a>)}</div>}</div><span>{statusLabel(i.status)}</span><div className="issue-card-actions"><button onClick={()=>startIssueEdit(i)}><Pencil size={12}/> 수정</button><button onClick={()=>void setIssueStatus(i.id,i.status==="resolved"||i.status==="closed"?"open":"resolved")}>{i.status==="resolved"||i.status==="closed"?"재열기":"완료"}</button></div></div>}):<div className="empty-ops">현재 연결된 이슈·리스크·협업이 없습니다.</div>}</div>
      </div>}

      {mode==="history"&&<div className="context-body history-body"><div className="history-line"><i/><div><strong>최근 진척률 {actuals[activeTask.id]?.latestProgress??activeTask.progress}%</strong><span>{actuals[activeTask.id]?.latestActualDate||"실적 미입력"}</span><p>누적 공수 {actuals[activeTask.id]?.totalHours||0}시간</p></div></div><div className="history-line"><i/><div><strong>산출물 Revision</strong><span>{versions.length}건 등록</span></div></div><div className="history-line"><i/><div><strong>이슈·리스크·협업</strong><span>{issues.length}건 연결</span></div></div></div>}
      {mode==="ai"&&<div className="context-body ai-body"><CommonAiChatPanel
        items={(aiContextItems.length?aiContextItems:(activeTask?[{key:`task:${activeTask.id}`,id:activeTask.id,kind:"WBS" as const,title:`${activeTask.wbsCode} · ${activeTask.name}`,wbsCode:activeTask.wbsCode,taskId:activeTask.id,meta:`진행률 ${activeTask.progress}% · 산출물 ${activeTask.deliverables.length} · 이슈 ${actuals[activeTask.id]?.issueCount||0}`}]:[])).map(({id,kind,title,meta})=>({id,kind,title,meta}) as CommonAiContextItem)}
        projectName={project?.name||"현재 프로젝트"}
        source="일정 · WBS"
        contextType={aiContextItems.some(item=>item.kind!=="WBS")?"mixed":"wbs"}
        contextTitle={`${project?.name||"현재 프로젝트"} · WBS`}
        onRemove={item=>{const target=aiContextItems.find(x=>x.id===item.id&&x.kind===item.kind);if(target)removeAiItem(target)}}
        onClear={clearAiContext}
        emptyLabel={`${activeTask.name}을 기준으로 분석합니다.`}
      /></div>}
    </aside>,document.body)}
    {notice&&typeof document!=="undefined"&&createPortal(<div className="unified-toast">{notice}</div>,document.body)}
  </>;
}
