export const pbomColumns=[
 {key:'part',label:'품번',locked:true},
 {key:'status',label:'구분 / 변경'},
 {key:'procurement',label:'조달 구분'},
 {key:'section',label:'SECTION'},
 {key:'level',label:'LEVEL'},
 {key:'description',label:'Item Description'},
 {key:'position',label:'POS'},
 {key:'item',label:'Item No.'},
 {key:'drawing',label:'Drawing No.'},
 {key:'revision',label:'CompRev'},
 {key:'quantity',label:'Qty Per Unit'},
 {key:'unit',label:'수량 단위',locked:true},
 {key:'total',label:'Total Qty / Section'},
 {key:'weight',label:'Weight'},
 {key:'weightSource',label:'Weight Source / Calculation Basis'},
 {key:'availability',label:'Drawing Availability'},
 {key:'source',label:'출처 자료'},
 {key:'reviewDescription',label:'Item Description 검토'},
 {key:'reviewTotal',label:'Total Qty / Section 검토'},
 {key:'reviewDrawing',label:'Drawing No. 검토'},
 {key:'reviewPosition',label:'POS 검토'},
 {key:'reviewRevision',label:'CompRev 검토'},
 {key:'remark',label:'Remark'},
 {key:'customerReply',label:'고객 회신'},
] as const;
export type ColumnKey=typeof pbomColumns[number]['key'];
