import { getLegacyDbCompat } from "../../../db/postgres-d1-compat";
/* eslint-disable @typescript-eslint/no-explicit-any */
import {contextErrorResponse,resolveRequestContext} from "../../../db/request-context";

type D1={prepare:(sql:string)=>any;batch:(statements:any[])=>Promise<unknown>};
const ADMIN_ROLES=new Set(["SUPER_ADMIN","ADMIN","SYSTEM_ADMIN"]);
const GROUPS=new Set(["MATERIAL","EXPENSE","OUTSOURCE","OTHER"]);
const now=()=>Math.floor(Date.now()/1000);
async function runtimeDb():Promise<D1>{return getLegacyDbCompat() as D1;}
async function ensureTable(db:D1){await db.batch([
  db.prepare(`CREATE TABLE IF NOT EXISTS project_cost_categories (id TEXT PRIMARY KEY NOT NULL,company_id TEXT NOT NULL,code TEXT NOT NULL,group_code TEXT NOT NULL,name TEXT NOT NULL,source_type TEXT NOT NULL DEFAULT 'MANUAL',enabled INTEGER NOT NULL DEFAULT 1,sort_order INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)`),
  db.prepare("CREATE UNIQUE INDEX IF NOT EXISTS project_cost_categories_company_code_uq ON project_cost_categories(company_id,code)"),
]);}
async function adminContext(request:Request,db:D1){const context=await resolveRequestContext(request,db);if(!context.systemRoles.some(role=>ADMIN_ROLES.has(role)))throw new Error("FORBIDDEN");return context;}
export async function GET(request:Request){const db=await runtimeDb();await ensureTable(db);let context;try{context=await resolveRequestContext(request,db)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"로그인이 필요합니다."},{status:401})}const rows=await db.prepare("SELECT id,code,group_code AS groupCode,name,source_type AS sourceType,enabled,sort_order AS sortOrder FROM project_cost_categories WHERE company_id=? ORDER BY group_code,sort_order,name").bind(context.companyId).all();return Response.json({categories:rows.results??[]});}
export async function POST(request:Request){const db=await runtimeDb();await ensureTable(db);let context;try{context=await adminContext(request,db)}catch(reason){if(reason instanceof Error&&reason.message==="FORBIDDEN")return Response.json({error:"시스템 관리자만 비용 카테고리를 추가할 수 있습니다."},{status:403});return contextErrorResponse(reason)??Response.json({error:"권한을 확인하지 못했습니다."},{status:500})}const input=await request.json() as any;const code=String(input.code||"").trim().toUpperCase().replace(/\s+/g,"_");const groupCode=String(input.groupCode||"").trim().toUpperCase();const name=String(input.name||"").trim();if(!code||!name||!GROUPS.has(groupCode))return Response.json({error:"비용 카테고리 정보를 확인해 주세요."},{status:400});if(code==="MATERIAL_BOM")return Response.json({error:"BOM 재료비는 시스템 자동연계 항목입니다."},{status:409});const id=crypto.randomUUID(),t=now();try{await db.prepare("INSERT INTO project_cost_categories (id,company_id,code,group_code,name,source_type,enabled,sort_order,created_at,updated_at) VALUES (?,?,?,?,?,'MANUAL',1,?,?,?)").bind(id,context.companyId,code,groupCode,name,Number(input.sortOrder||0),t,t).run()}catch{return Response.json({error:"이미 사용 중인 비용 카테고리 코드입니다."},{status:409})}return Response.json({ok:true,id},{status:201});}
export async function PATCH(request:Request){const db=await runtimeDb();await ensureTable(db);let context;try{context=await adminContext(request,db)}catch(reason){if(reason instanceof Error&&reason.message==="FORBIDDEN")return Response.json({error:"시스템 관리자만 비용 카테고리를 수정할 수 있습니다."},{status:403});return contextErrorResponse(reason)??Response.json({error:"권한을 확인하지 못했습니다."},{status:500})}const input=await request.json() as any;const id=String(input.id||"");const row=await db.prepare("SELECT id,code,source_type AS sourceType FROM project_cost_categories WHERE id=? AND company_id=?").bind(id,context.companyId).first() as any;if(!row)return Response.json({error:"비용 카테고리를 찾을 수 없습니다."},{status:404});if(row.code==="MATERIAL_BOM"||row.sourceType==="BOM")return Response.json({error:"BOM 재료비 시스템 항목은 수정할 수 없습니다."},{status:409});const groupCode=String(input.groupCode||"").trim().toUpperCase(),name=String(input.name||"").trim();if(!name||!GROUPS.has(groupCode))return Response.json({error:"비용 카테고리 정보를 확인해 주세요."},{status:400});await db.prepare("UPDATE project_cost_categories SET group_code=?,name=?,enabled=?,sort_order=?,updated_at=? WHERE id=? AND company_id=?").bind(groupCode,name,input.enabled===false?0:1,Number(input.sortOrder||0),now(),id,context.companyId).run();return Response.json({ok:true});}
export async function DELETE(request:Request){const db=await runtimeDb();await ensureTable(db);let context;try{context=await adminContext(request,db)}catch(reason){if(reason instanceof Error&&reason.message==="FORBIDDEN")return Response.json({error:"시스템 관리자만 비용 카테고리를 삭제할 수 있습니다."},{status:403});return contextErrorResponse(reason)??Response.json({error:"권한을 확인하지 못했습니다."},{status:500})}const input=await request.json() as any;const id=String(input.id||"");const row=await db.prepare("SELECT id,code,source_type AS sourceType FROM project_cost_categories WHERE id=? AND company_id=?").bind(id,context.companyId).first() as any;if(!row)return Response.json({error:"비용 카테고리를 찾을 수 없습니다."},{status:404});if(row.code==="MATERIAL_BOM"||row.sourceType==="BOM")return Response.json({error:"BOM 재료비 시스템 항목은 삭제할 수 없습니다."},{status:409});const usedBudget=await db.prepare("SELECT 1 FROM project_cost_budgets WHERE company_id=? AND category_code=? LIMIT 1").bind(context.companyId,row.code).first().catch(()=>null);const usedEntry=await db.prepare("SELECT 1 FROM project_cost_entries WHERE company_id=? AND category_code=? LIMIT 1").bind(context.companyId,row.code).first().catch(()=>null);if(usedBudget||usedEntry)return Response.json({error:"이미 프로젝트 예산 또는 비용 실적에서 사용 중인 카테고리는 삭제할 수 없습니다. 사용 안 함으로 변경해 주세요."},{status:409});await db.prepare("DELETE FROM project_cost_categories WHERE id=? AND company_id=?").bind(id,context.companyId).run();return Response.json({ok:true});}
