/* eslint-disable @typescript-eslint/no-explicit-any */
import type {RuntimeD1} from "./project-data-foundation";

export type WorkflowDocumentAction="NONE"|"VIEW"|"NEW"|"REVISION"|"REVIEW"|"APPROVAL";
export type WorkflowStepDefinition={id?:string;name:string;actionType:"WRITE"|"PROCESS"|"REVIEW"|"AGREEMENT"|"APPROVAL"|"REFERENCE";roleCode?:string;assignmentRule?:string;dueDays?:number;commentRequired?:boolean;attachmentRequired?:boolean;documentAction?:WorkflowDocumentAction;documentRequired?:boolean};
export type WorkflowTemplateDefinition={description?:string;applicationType:string;projectRequired:boolean;taskLinkMode:"required"|"optional"|"disabled";registerCommonDocument:boolean;documentCategory?:string;steps:WorkflowStepDefinition[]};

const statements=[
`CREATE TABLE IF NOT EXISTS workflow_templates (id text PRIMARY KEY NOT NULL,company_id text NOT NULL,code text NOT NULL,name text NOT NULL,application_type text DEFAULT 'GENERAL' NOT NULL,description text,project_required integer DEFAULT 1 NOT NULL,task_link_mode text DEFAULT 'optional' NOT NULL,register_common_document integer DEFAULT 0 NOT NULL,document_category text,status text DEFAULT 'active' NOT NULL,current_version integer DEFAULT 1 NOT NULL,created_at integer NOT NULL,updated_at integer NOT NULL)`,
`CREATE UNIQUE INDEX IF NOT EXISTS workflow_templates_company_code_uq ON workflow_templates(company_id,code)`,
`CREATE TABLE IF NOT EXISTS workflow_template_versions (id text PRIMARY KEY NOT NULL,template_id text NOT NULL,version integer NOT NULL,definition text NOT NULL,status text DEFAULT 'published' NOT NULL,published_at integer,created_by text NOT NULL,created_at integer NOT NULL,updated_at integer NOT NULL)`,
`CREATE UNIQUE INDEX IF NOT EXISTS workflow_template_versions_template_version_uq ON workflow_template_versions(template_id,version)`,
`CREATE TABLE IF NOT EXISTS workflow_instances (id text PRIMARY KEY NOT NULL,company_id text NOT NULL,project_id text NOT NULL,task_id text,template_id text NOT NULL,template_version_id text NOT NULL,workflow_number text NOT NULL,title text NOT NULL,request_content text,source_type text DEFAULT 'GENERAL' NOT NULL,source_id text,priority text DEFAULT 'normal' NOT NULL,due_date text,status text DEFAULT 'draft' NOT NULL,current_step_order integer DEFAULT 0 NOT NULL,requester_user_id text NOT NULL,main_deliverable_id text,official_document_id text,created_at integer NOT NULL,updated_at integer NOT NULL)`,
`CREATE UNIQUE INDEX IF NOT EXISTS workflow_instances_company_number_uq ON workflow_instances(company_id,workflow_number)`,
`CREATE INDEX IF NOT EXISTS workflow_instances_project_status_idx ON workflow_instances(project_id,status,updated_at)`,
`CREATE TABLE IF NOT EXISTS workflow_instance_deliverables (workflow_id text NOT NULL,deliverable_id text NOT NULL,sort_order integer DEFAULT 0 NOT NULL,created_at integer NOT NULL,PRIMARY KEY(workflow_id,deliverable_id))`,
`CREATE INDEX IF NOT EXISTS workflow_instance_deliverables_workflow_idx ON workflow_instance_deliverables(workflow_id,sort_order)`,
`CREATE TABLE IF NOT EXISTS workflow_instance_steps (id text PRIMARY KEY NOT NULL,workflow_id text NOT NULL,step_order integer NOT NULL,name text NOT NULL,action_type text NOT NULL,role_code text,assignment_rule text,due_days integer DEFAULT 0 NOT NULL,comment_required integer DEFAULT 0 NOT NULL,attachment_required integer DEFAULT 0 NOT NULL,assignee_user_id text,status text DEFAULT 'waiting' NOT NULL,started_at integer,completed_at integer,comment text,created_at integer NOT NULL,updated_at integer NOT NULL)`,
`CREATE UNIQUE INDEX IF NOT EXISTS workflow_instance_steps_order_uq ON workflow_instance_steps(workflow_id,step_order)`,
`CREATE INDEX IF NOT EXISTS workflow_instance_steps_assignee_idx ON workflow_instance_steps(assignee_user_id,status,updated_at)`,
`CREATE TABLE IF NOT EXISTS workflow_history (id text PRIMARY KEY NOT NULL,workflow_id text NOT NULL,step_id text,actor_user_id text NOT NULL,action text NOT NULL,previous_status text,next_status text,comment text,attachments text,created_at integer NOT NULL)`,
`CREATE INDEX IF NOT EXISTS workflow_history_workflow_created_idx ON workflow_history(workflow_id,created_at)`,
`CREATE TABLE IF NOT EXISTS workflow_source_attachments (id text PRIMARY KEY NOT NULL,company_id text NOT NULL,project_id text NOT NULL,source_type text NOT NULL,source_id text NOT NULL,file_key text NOT NULL,file_name text NOT NULL,file_size integer DEFAULT 0 NOT NULL,content_type text,created_by text NOT NULL,created_at integer NOT NULL)`,
`CREATE INDEX IF NOT EXISTS workflow_source_attachments_source_idx ON workflow_source_attachments(source_type,source_id,created_at)`,
`CREATE TABLE IF NOT EXISTS project_documents (id text PRIMARY KEY NOT NULL,project_id text NOT NULL,task_id text,title text NOT NULL,category text,file_key text,version text,status text DEFAULT 'draft' NOT NULL,created_by text,created_at integer NOT NULL,updated_at integer NOT NULL)`,
`CREATE INDEX IF NOT EXISTS project_documents_project_idx ON project_documents(project_id,updated_at)`,
`CREATE TABLE IF NOT EXISTS deliverable_versions (id text PRIMARY KEY NOT NULL,project_id text NOT NULL,deliverable_id text NOT NULL,task_id text,revision integer NOT NULL,file_key text NOT NULL,file_name text NOT NULL,file_size integer DEFAULT 0 NOT NULL,content_type text,note text,created_by text,created_at integer NOT NULL,deleted_at integer,deleted_by text)`,
`CREATE UNIQUE INDEX IF NOT EXISTS deliverable_versions_deliverable_revision_uq ON deliverable_versions(deliverable_id,revision)`,
`CREATE INDEX IF NOT EXISTS deliverable_versions_project_idx ON deliverable_versions(project_id,created_at)`,
`CREATE TABLE IF NOT EXISTS workflow_step_document_rules (step_id text PRIMARY KEY NOT NULL,workflow_id text NOT NULL,document_action text DEFAULT 'NONE' NOT NULL,document_required integer DEFAULT 0 NOT NULL,created_at integer NOT NULL,updated_at integer NOT NULL)`,
`CREATE INDEX IF NOT EXISTS workflow_step_document_rules_workflow_idx ON workflow_step_document_rules(workflow_id)`,
`CREATE TABLE IF NOT EXISTS workflow_step_documents (id text PRIMARY KEY NOT NULL,workflow_id text NOT NULL,step_id text NOT NULL,deliverable_id text NOT NULL,version_id text NOT NULL,document_action text NOT NULL,change_reason text,created_by text NOT NULL,created_at integer NOT NULL)`,
`CREATE INDEX IF NOT EXISTS workflow_step_documents_workflow_step_idx ON workflow_step_documents(workflow_id,step_id,created_at)`,
`CREATE TABLE IF NOT EXISTS design_change_requests (id text PRIMARY KEY NOT NULL,company_id text NOT NULL,project_id text NOT NULL,task_id text,ecr_number text NOT NULL,title text NOT NULL,change_target text,before_content text,after_content text,reason text,impact_content text,priority text DEFAULT 'normal' NOT NULL,requester_user_id text NOT NULL,requested_at integer NOT NULL,workflow_id text,status text DEFAULT 'draft' NOT NULL,created_at integer NOT NULL,updated_at integer NOT NULL)`,
`CREATE UNIQUE INDEX IF NOT EXISTS design_change_requests_company_number_uq ON design_change_requests(company_id,ecr_number)`,
`CREATE TABLE IF NOT EXISTS quality_cases (id text PRIMARY KEY NOT NULL,company_id text NOT NULL,project_id text NOT NULL,task_id text,quality_number text NOT NULL,title text NOT NULL,occurred_on text,issue_type text,severity text DEFAULT 'medium' NOT NULL,description text,root_cause text,corrective_action text,effectiveness_check text,owner_user_id text,workflow_id text,status text DEFAULT 'draft' NOT NULL,created_at integer NOT NULL,updated_at integer NOT NULL)`,
`CREATE UNIQUE INDEX IF NOT EXISTS quality_cases_company_number_uq ON quality_cases(company_id,quality_number)`,
];

export async function ensureWorkflowFoundation(db:RuntimeD1){await db.batch(statements.map(sql=>db.prepare(sql)));try{await db.prepare("ALTER TABLE deliverables ADD COLUMN source TEXT NOT NULL DEFAULT 'planned'").run()}catch{}try{await db.prepare("ALTER TABLE deliverables ADD COLUMN created_by TEXT").run()}catch{}try{await db.prepare("UPDATE workflow_templates SET code='EC_ACTION' WHERE code='ECR' AND application_type='ECR'").run()}catch{}}

export const defaultWorkflowTemplates:Array<{code:string;name:string;type:string;registerDocument?:boolean;category?:string;steps:WorkflowStepDefinition[]}>= [
 {code:"PRODUCTION_TRANSFER",name:"양산이관 승인",type:"GENERAL",registerDocument:true,category:"양산이관",steps:[{name:"이관자료 작성",actionType:"WRITE",assignmentRule:"requester"},{name:"개발 검토",actionType:"REVIEW",roleCode:"DEV",assignmentRule:"project_role",dueDays:2},{name:"품질 검토",actionType:"REVIEW",roleCode:"QA",assignmentRule:"project_role",dueDays:2},{name:"생산 합의",actionType:"AGREEMENT",roleCode:"PROD",assignmentRule:"project_role",dueDays:2},{name:"최종 승인",actionType:"APPROVAL",roleCode:"PM",assignmentRule:"project_pm",dueDays:1}]},
 {code:"PILOT_REQUEST",name:"PILOT 대응 생산의뢰",type:"GENERAL",steps:[{name:"생산의뢰 작성",actionType:"WRITE",assignmentRule:"requester"},{name:"생산 검토",actionType:"PROCESS",roleCode:"PROD",assignmentRule:"project_role"},{name:"최종 승인",actionType:"APPROVAL",roleCode:"PM",assignmentRule:"project_pm"}]},
 {code:"DOCUMENT_REVISION",name:"문서 Revision 승인",type:"GENERAL",registerDocument:true,category:"승인문서",steps:[{name:"Revision 작성",actionType:"WRITE",assignmentRule:"requester"},{name:"담당 검토",actionType:"REVIEW",assignmentRule:"task_role"},{name:"최종 승인",actionType:"APPROVAL",roleCode:"PM",assignmentRule:"project_pm"}]},
 {code:"FABRIC_REQUEST",name:"원단 제작의뢰",type:"GENERAL",steps:[{name:"제작의뢰 작성",actionType:"WRITE",assignmentRule:"requester"},{name:"개발 처리",actionType:"PROCESS",roleCode:"DEV",assignmentRule:"project_role"},{name:"승인",actionType:"APPROVAL",roleCode:"PM",assignmentRule:"project_pm"}]},
 {code:"WEAVING_REQUEST",name:"제직 의뢰",type:"GENERAL",steps:[{name:"제직의뢰 작성",actionType:"WRITE",assignmentRule:"requester"},{name:"제직 처리",actionType:"PROCESS",roleCode:"PROD",assignmentRule:"project_role"},{name:"승인",actionType:"APPROVAL",roleCode:"PM",assignmentRule:"project_pm"}]},
 {code:"FINISHING_REQUEST",name:"후가공 의뢰",type:"GENERAL",steps:[{name:"후가공의뢰 작성",actionType:"WRITE",assignmentRule:"requester"},{name:"생산 합의",actionType:"AGREEMENT",roleCode:"PROD",assignmentRule:"project_role"},{name:"승인",actionType:"APPROVAL",roleCode:"PM",assignmentRule:"project_pm"}]},
 {code:"EC_ACTION",name:"설계변경 기본 워크플로우",type:"ECR",steps:[{name:"변경 요청 작성",actionType:"WRITE",assignmentRule:"requester"},{name:"설계 검토",actionType:"REVIEW",roleCode:"DESIGN",assignmentRule:"project_role"},{name:"품질 검토",actionType:"REVIEW",roleCode:"QA",assignmentRule:"project_role"},{name:"관련부서 합의",actionType:"AGREEMENT",assignmentRule:"manual"},{name:"최종 승인",actionType:"APPROVAL",roleCode:"PM",assignmentRule:"project_pm"}]},
 {code:"QUALITY_ACTION",name:"품질관리 기본 워크플로우",type:"QUALITY",steps:[{name:"문제 등록",actionType:"WRITE",assignmentRule:"requester"},{name:"원인분석",actionType:"PROCESS",roleCode:"QA",assignmentRule:"project_role"},{name:"개선조치",actionType:"PROCESS",assignmentRule:"manual"},{name:"효과검증",actionType:"REVIEW",roleCode:"QA",assignmentRule:"project_role"},{name:"종결 승인",actionType:"APPROVAL",roleCode:"PM",assignmentRule:"project_pm"}]},
 {code:"CONSULT_REPORT",name:"상담보고서 승인",type:"GENERAL",registerDocument:true,category:"상담보고서",steps:[{name:"상담보고서 작성",actionType:"WRITE",assignmentRule:"requester"},{name:"내용 검토",actionType:"REVIEW",roleCode:"PL",assignmentRule:"project_pl"},{name:"최종 승인",actionType:"APPROVAL",roleCode:"PM",assignmentRule:"project_pm"}]},
];

export function normalizedSteps(value:unknown):WorkflowStepDefinition[]{const source=Array.isArray(value)?value:[];return source.map((step:any)=>({name:String(step?.name||"").trim(),actionType:String(step?.actionType||"REVIEW").toUpperCase() as WorkflowStepDefinition["actionType"],roleCode:step?.roleCode?String(step.roleCode).trim():undefined,assignmentRule:step?.assignmentRule?String(step.assignmentRule):"manual",dueDays:Math.max(0,Number(step?.dueDays||0)),commentRequired:Boolean(step?.commentRequired),attachmentRequired:Boolean(step?.attachmentRequired),documentAction:String(step?.documentAction||"NONE").toUpperCase() as WorkflowDocumentAction,documentRequired:Boolean(step?.documentRequired)})).filter(step=>step.name)}
