/* eslint-disable @typescript-eslint/no-explicit-any */
import {contextErrorResponse,resolveRequestContext} from "../../../../db/request-context";
import {normalizedSteps} from "../../../../db/workflow-foundation";
import {isWorkflowManager,nowSeconds,parseJson,seedDefaultWorkflowTemplates,workflowDb} from "../shared";

const SYSTEM_DEFAULT_CODES=new Set(["EC_ACTION","QUALITY_ACTION"]);
function definitionOf(input:any){const steps=normalizedSteps(input.steps);if(!steps.length)throw new Error("Workflow 단계를 1개 이상 등록해 주세요.");if(steps[0].actionType!=="WRITE")throw new Error("첫 단계는 작성 단계여야 합니다.");if(Boolean(input.registerCommonDocument)&&!steps.some(step=>step.actionType==="APPROVAL"))throw new Error("공식문서 등록 템플릿에는 최종 승인 단계가 필요합니다.");return {description:String(input.description||"").trim(),applicationType:String(input.applicationType||"GENERAL").toUpperCase(),projectRequired:true,taskLinkMode:["required","optional","disabled"].includes(input.taskLinkMode)?input.taskLinkMode:"optional",registerCommonDocument:Boolean(input.registerCommonDocument),documentCategory:input.documentCategory?String(input.documentCategory):null,steps}}

export async function GET(request:Request){const db=await workflowDb();let context;try{context=await resolveRequestContext(request,db);await seedDefaultWorkflowTemplates(db,context)}catch(reason){console.error("[WORKFLOW_TEMPLATES_ERROR]",reason);return contextErrorResponse(reason)??Response.json({error:"Workflow 템플릿을 불러오지 못했습니다."},{status:500})}const result=await db.prepare(`SELECT t.*,v.id AS versionId,v.version,v.definition,v.published_at AS publishedAt,u.name AS createdByName FROM workflow_templates t JOIN workflow_template_versions v ON v.id=(SELECT v2.id FROM workflow_template_versions v2 WHERE v2.template_id=t.id ORDER BY v2.version DESC LIMIT 1) LEFT JOIN users u ON u.id=v.created_by WHERE t.company_id=? ORDER BY CASE WHEN t.status='inactive' THEN 1 ELSE 0 END ASC,t.updated_at DESC,t.name`).bind(context.companyId).all();return Response.json({templates:(result.results??[] as any[]).map(row=>({...row,definition:parseJson(row.definition,{}),canEdit:isWorkflowManager(context),systemDefault:SYSTEM_DEFAULT_CODES.has(String(row.code||"").toUpperCase())}))})}

export async function POST(request:Request){const db=await workflowDb();let context;try{context=await resolveRequestContext(request,db)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"사용자 정보를 확인하지 못했습니다."},{status:500})}if(!isWorkflowManager(context))return Response.json({error:"관리자 또는 PM만 Workflow 템플릿을 등록할 수 있습니다."},{status:403});const input=await request.json() as any;if(!input.name?.trim()||!input.code?.trim())return Response.json({error:"템플릿명과 코드를 입력해 주세요."},{status:400});let definition;try{definition=definitionOf(input)}catch(reason){return Response.json({error:reason instanceof Error?reason.message:"단계 구성을 확인해 주세요."},{status:400})}if(definition.applicationType!=="GENERAL")return Response.json({error:"설계변경·품질관리 Workflow는 시스템 기본 템플릿만 사용합니다. 추가 템플릿은 일반 Workflow로 등록해 주세요."},{status:400});const code=input.code.trim().toUpperCase();if(SYSTEM_DEFAULT_CODES.has(code))return Response.json({error:"시스템 기본 Workflow 템플릿 코드는 새로 등록할 수 없습니다."},{status:400});const duplicate=await db.prepare("SELECT id FROM workflow_templates WHERE company_id=? AND upper(code)=upper(?)").bind(context.companyId,code).first();if(duplicate)return Response.json({error:"이미 사용 중인 Workflow 템플릿 코드입니다."},{status:409});const now=nowSeconds(),id=crypto.randomUUID(),versionId=crypto.randomUUID();await db.batch([db.prepare("INSERT INTO workflow_templates (id,company_id,code,name,application_type,description,project_required,task_link_mode,register_common_document,document_category,status,current_version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,1,?,?)").bind(id,context.companyId,code,input.name.trim(),"GENERAL",definition.description,1,definition.taskLinkMode,definition.registerCommonDocument?1:0,definition.documentCategory,input.status==="inactive"?"inactive":"active",now,now),db.prepare("INSERT INTO workflow_template_versions (id,template_id,version,definition,status,published_at,created_by,created_at,updated_at) VALUES (?,?,1,?,'published',?,?,?,?)").bind(versionId,id,JSON.stringify({...definition,applicationType:"GENERAL"}),now,context.userId,now,now)]);return Response.json({id,versionId,version:1},{status:201})}

export async function PATCH(request:Request){const db=await workflowDb();let context;try{context=await resolveRequestContext(request,db)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"사용자 정보를 확인하지 못했습니다."},{status:500})}if(!isWorkflowManager(context))return Response.json({error:"관리자 또는 PM만 Workflow 템플릿을 수정할 수 있습니다."},{status:403});const input=await request.json() as any;const existing=await db.prepare("SELECT * FROM workflow_templates WHERE id=? AND company_id=?").bind(input.id,context.companyId).first<any>();if(!existing)return Response.json({error:"Workflow 템플릿을 찾을 수 없습니다."},{status:404});const systemDefault=SYSTEM_DEFAULT_CODES.has(String(existing.code||"").toUpperCase()),now=nowSeconds();if(input.mode==="status"){if(systemDefault&&input.status!=="active")return Response.json({error:"설계변경·품질관리 기본 Workflow는 사용 중지할 수 없습니다."},{status:400});await db.prepare("UPDATE workflow_templates SET status=?,updated_at=? WHERE id=?").bind(input.status==="active"?"active":"inactive",now,input.id).run();return Response.json({ok:true})}let definition;try{definition=definitionOf(input)}catch(reason){return Response.json({error:reason instanceof Error?reason.message:"단계 구성을 확인해 주세요."},{status:400})}if(systemDefault){const requiredType=String(existing.code).toUpperCase()==="EC_ACTION"?"ECR":"QUALITY";definition={...definition,applicationType:requiredType};}else if(definition.applicationType!=="GENERAL")return Response.json({error:"일반 Workflow 템플릿은 설계변경·품질관리 유형으로 변경할 수 없습니다."},{status:400});const version=Number(existing.current_version||1)+1,versionId=crypto.randomUUID(),nextStatus=systemDefault?"active":input.status==="inactive"?"inactive":"active";await db.batch([db.prepare("UPDATE workflow_templates SET name=?,application_type=?,description=?,task_link_mode=?,register_common_document=?,document_category=?,status=?,current_version=?,updated_at=? WHERE id=?").bind(input.name?.trim()||existing.name,definition.applicationType,definition.description,definition.taskLinkMode,definition.registerCommonDocument?1:0,definition.documentCategory,nextStatus,version,now,input.id),db.prepare("INSERT INTO workflow_template_versions (id,template_id,version,definition,status,published_at,created_by,created_at,updated_at) VALUES (?,?,?,?,'published',?,?,?,?)").bind(versionId,input.id,version,JSON.stringify(definition),now,context.userId,now,now)]);return Response.json({id:input.id,versionId,version})}
