import { getLegacyDbCompat } from "../../../../../db/postgres-d1-compat";
/* eslint-disable @typescript-eslint/no-explicit-any */
import {ensureProjectDataFoundation,type RuntimeD1} from "../../../../../db/project-data-foundation";
import {canManageProject,contextErrorResponse,requireProjectAccess,resolveRequestContext} from "../../../../../db/request-context";

type D1=RuntimeD1;
async function runtimeDb():Promise<D1>{return getLegacyDbCompat() as D1;}
async function ensureUserAvatarColumn(db:D1){const columns=await db.prepare("PRAGMA table_info(users)").all();if(!(columns.results??[]).some((column:any)=>column.name==="avatar_key"))await db.prepare("ALTER TABLE users ADD COLUMN avatar_key text DEFAULT 'avatar-01'").run();}
async function ensureRoleCatalog(db:D1,companyId:string){const now=Math.floor(Date.now()/1000);await db.batch([db.prepare(`CREATE TABLE IF NOT EXISTS project_role_catalog (id text PRIMARY KEY NOT NULL,company_id text NOT NULL,code text NOT NULL,name text NOT NULL,group_name text NOT NULL,required integer DEFAULT 0 NOT NULL,enabled integer DEFAULT 1 NOT NULL,sort_order integer DEFAULT 0 NOT NULL,created_at integer NOT NULL,updated_at integer NOT NULL)`),db.prepare("CREATE UNIQUE INDEX IF NOT EXISTS project_role_catalog_company_code_uq ON project_role_catalog(company_id,code)"),...[['project-role-pm','PM','PM','프로젝트 관리',1,0],['project-role-pl','PL','PL','프로젝트 관리',1,1],['project-role-member','MEMBER','참여자','프로젝트 참여',0,2],['project-role-plan','PLAN','기획','업무 수행',0,10],['project-role-sales','SALES','영업','업무 수행',0,20],['project-role-dev','DEV','개발','업무 수행',0,30],['project-role-design','DESIGN','설계','업무 수행',0,40],['project-role-purchase','PURCHASE','구매','업무 수행',0,50],['project-role-material','MATERIAL','자재','업무 수행',0,60],['project-role-production','PRODUCTION','생산','업무 수행',0,70],['project-role-quality','QUALITY','품질','업무 수행',0,80],['project-role-service','SERVICE','서비스','업무 수행',0,90],['project-role-sw','SW','SW','전문 분야',0,100],['project-role-mech','MECHANICAL','기구','전문 분야',0,110],['project-role-electric','ELECTRICAL','전장','전문 분야',0,120],['project-role-circuit','CIRCUIT','회로','전문 분야',0,130]].map(([id,code,name,group,required,sort])=>db.prepare("INSERT OR IGNORE INTO project_role_catalog (id,company_id,code,name,group_name,required,enabled,sort_order,created_at,updated_at) VALUES (?,?,?,?,?,?,1,?,?,?)").bind(id,companyId,code,name,group,required,sort,now,now))]);}

export async function GET(request:Request,{params}:{params:Promise<{projectId:string}>}){
  const {projectId}=await params;const db=await runtimeDb();await ensureProjectDataFoundation(db);await ensureUserAvatarColumn(db);let context;try{context=await resolveRequestContext(request,db);await requireProjectAccess(db,context,projectId)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"사용자 권한을 확인하지 못했습니다."},{status:500})}await ensureRoleCatalog(db,context.companyId);
  const project=await db.prepare("SELECT id FROM projects WHERE id=? AND company_id=?").bind(projectId,context.companyId).first();if(!project)return Response.json({error:"프로젝트를 찾을 수 없습니다."},{status:404});
  const [members,users,roles]=await Promise.all([
    db.prepare(`SELECT pm.user_id AS userId,u.name,u.email,COALESCE(u.avatar_key,'avatar-01') AS avatarKey,pm.project_role AS projectRole,COUNT(w.id) AS assignedTaskCount FROM project_members pm JOIN users u ON u.id=pm.user_id LEFT JOIN wbs_tasks w ON w.project_id=pm.project_id AND w.assignee_user_id=pm.user_id WHERE pm.project_id=? GROUP BY pm.user_id,u.name,u.email,pm.project_role ORDER BY CASE pm.project_role WHEN 'PM' THEN 0 WHEN 'PL' THEN 1 ELSE 2 END,u.name`).bind(projectId).all(),
    db.prepare("SELECT id AS userId,name,email,COALESCE(avatar_key,'avatar-01') AS avatarKey FROM users WHERE company_id=? AND status='active' ORDER BY name").bind(context.companyId).all(),
    db.prepare("SELECT code,name,group_name AS groupName,required,sort_order AS sortOrder FROM project_role_catalog WHERE company_id=? AND enabled=1 ORDER BY sort_order,name").bind(context.companyId).all(),
  ]);
  return Response.json({members:members.results??[],users:users.results??[],roles:roles.results??[]});
}

export async function PUT(request:Request,{params}:{params:Promise<{projectId:string}>}){
  const {projectId}=await params;const input=await request.json() as {members?:Array<{userId:string;projectRole:string}>};const members=input.members??[];
  if(new Set(members.map(item=>item.userId)).size!==members.length)return Response.json({error:"같은 참여자가 중복되었습니다."},{status:400});
  if(members.filter(item=>item.projectRole==="PM").length!==1)return Response.json({error:"프로젝트 PM은 반드시 1명이어야 합니다."},{status:400});
  const db=await runtimeDb();await ensureProjectDataFoundation(db);let context,access;try{context=await resolveRequestContext(request,db);access=await requireProjectAccess(db,context,projectId,true)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"사용자 권한을 확인하지 못했습니다."},{status:500})}if(!canManageProject(context,access.projectRole))return Response.json({error:"PM 또는 PL만 참여자를 변경할 수 있습니다."},{status:403});await ensureRoleCatalog(db,context.companyId);const project=await db.prepare("SELECT id,status FROM projects WHERE id=? AND company_id=?").bind(projectId,context.companyId).first() as {id:string;status:string}|null;if(!project)return Response.json({error:"프로젝트를 찾을 수 없습니다."},{status:404});
  const [validUsers,validRoles]=await Promise.all([db.prepare("SELECT id FROM users WHERE company_id=? AND status='active'").bind(context.companyId).all(),db.prepare("SELECT code FROM project_role_catalog WHERE company_id=? AND enabled=1").bind(context.companyId).all()]);const validIds=new Set((validUsers.results??[]).map((item:any)=>item.id)),roleCodes=new Set((validRoles.results??[]).map((item:any)=>item.code));if(members.some(item=>!validIds.has(item.userId)))return Response.json({error:"활성 상태가 아닌 사용자가 포함되어 있습니다."},{status:400});if(members.some(item=>!roleCodes.has(item.projectRole)))return Response.json({error:"시스템 설정에서 사용 중인 프로젝트 Role만 선택할 수 있습니다."},{status:400});
  const existing=await db.prepare("SELECT user_id AS userId FROM project_members WHERE project_id=?").bind(projectId).all();const nextIds=new Set(members.map(item=>item.userId));const removed=(existing.results??[]).map((item:any)=>item.userId).filter((id:string)=>!nextIds.has(id));if(removed.length){const placeholders=removed.map(()=>"?").join(",");const assigned=await db.prepare(`SELECT COUNT(*) AS count FROM wbs_tasks WHERE project_id=? AND assignee_user_id IN (${placeholders})`).bind(projectId,...removed).first<{count:number}>();if(Number(assigned?.count))return Response.json({error:"담당 업무가 남은 참여자는 다른 참여자에게 업무를 이관한 뒤 제거해 주세요."},{status:409});}
  const now=Math.floor(Date.now()/1000);const statements:any[]=[db.prepare("DELETE FROM project_members WHERE project_id=?").bind(projectId)];for(const member of members)statements.push(db.prepare("INSERT INTO project_members (project_id,user_id,project_role,created_at,updated_at) VALUES (?,?,?,?,?)").bind(projectId,member.userId,member.projectRole,now,now));statements.push(db.prepare("INSERT INTO audit_logs (id,company_id,actor_user_id,action,entity_type,entity_id,detail,created_at) VALUES (?,?,?,'PROJECT_MEMBERS_UPDATED','PROJECT',?,?,?)").bind(crypto.randomUUID(),context.companyId,context.userId,projectId,JSON.stringify({memberCount:members.length,pmUserId:members.find(item=>item.projectRole==="PM")?.userId}),now));await db.batch(statements);return Response.json({ok:true,memberCount:members.length});
}

