/* eslint-disable @typescript-eslint/no-explicit-any */
import type {RequestContext} from "../../../db/request-context";
import {clearSourceDrawings} from "../../../services/workflow-drawing-service";
import {clearSourceParts} from "../../../services/workflow-part-service";
import {nowSeconds,type D1,workflowDetail} from "./shared";
import {removeSourceFiles} from "./source-files";

export async function updateDraftWorkflow(db:D1,context:RequestContext,id:string,input:any){
 const detail=await workflowDetail(db,context,id);if(!detail)throw new Error("Workflow를 찾을 수 없습니다.");const w=detail.workflow,isAdmin=context.systemRoles.some(role=>["SUPER_ADMIN","ADMIN","SYSTEM_ADMIN"].includes(role));if(w.status!=="draft")throw new Error("임시저장 상태에서만 수정할 수 있습니다.");if(w.requester_user_id!==context.userId&&!isAdmin)throw new Error("요청자만 임시저장 Workflow를 수정할 수 있습니다.");
 const assignments=input.assignees&&typeof input.assignees==="object"?input.assignees:{},assignedIds=Array.from(new Set(Object.values(assignments).map(String).filter(Boolean)));if(assignedIds.length){const placeholders=assignedIds.map(()=>"?").join(","),valid=await db.prepare(`SELECT id FROM users WHERE company_id=? AND status='active' AND id IN (${placeholders})`).bind(context.companyId,...assignedIds).all();if((valid.results??[]).length!==assignedIds.length)throw new Error("담당자는 같은 회사의 활성 사용자만 선택할 수 있습니다.")}
 const deliverableIds=input.deliverableIds===undefined?null:Array.from(new Set((Array.isArray(input.deliverableIds)?input.deliverableIds:[]).map(String).filter(Boolean)));if(deliverableIds)for(const deliverableId of deliverableIds){const item=await db.prepare("SELECT id FROM deliverables WHERE id=? AND project_id=?").bind(deliverableId,w.project_id).first();if(!item)throw new Error("프로젝트에 속하지 않은 문서·산출물이 포함되어 있습니다.")}
 const title=String(input.title??w.title).trim();if(!title)throw new Error("Workflow 제목을 입력해 주세요.");const taskId=input.taskId===undefined?w.task_id:String(input.taskId||"")||null,now=nowSeconds(),statements:any[]=[db.prepare("UPDATE workflow_instances SET task_id=?,title=?,request_content=?,priority=?,due_date=?,main_deliverable_id=?,updated_at=? WHERE id=?").bind(taskId,title,input.requestContent===undefined?w.request_content:String(input.requestContent||"").trim()||null,input.priority??w.priority,input.dueDate===undefined?w.due_date:String(input.dueDate||"")||null,deliverableIds?deliverableIds[0]||null:w.main_deliverable_id,now,id)];
 for(const step of detail.steps as any[])if(assignments[String(step.step_order)]!==undefined)statements.push(db.prepare("UPDATE workflow_instance_steps SET assignee_user_id=?,updated_at=? WHERE id=?").bind(String(assignments[String(step.step_order)]||"")||null,now,step.id));if(deliverableIds){statements.push(db.prepare("DELETE FROM workflow_instance_deliverables WHERE workflow_id=?").bind(id));deliverableIds.forEach((deliverableId,index)=>statements.push(db.prepare("INSERT INTO workflow_instance_deliverables (workflow_id,deliverable_id,sort_order,created_at) VALUES (?,?,?,?)").bind(id,deliverableId,index,now)))}statements.push(db.prepare("INSERT INTO workflow_history (id,workflow_id,actor_user_id,action,previous_status,next_status,created_at) VALUES (?,?,?,'EDIT_DRAFT','draft','draft',?)").bind(crypto.randomUUID(),id,context.userId,now));await db.batch(statements);return {ok:true,id,status:"draft"};
}
export async function deleteDraftWorkflow(db:D1,context:RequestContext,id:string){
 const detail=await workflowDetail(db,context,id);if(!detail)throw new Error("Workflow를 찾을 수 없습니다.");const w=detail.workflow,isAdmin=context.systemRoles.some(role=>["SUPER_ADMIN","ADMIN","SYSTEM_ADMIN"].includes(role));if(w.status!=="draft")throw new Error("임시저장 상태에서만 삭제할 수 있습니다.");if(w.requester_user_id!==context.userId&&!isAdmin)throw new Error("요청자만 임시저장 Workflow를 삭제할 수 있습니다.");const sourceType=String(w.source_type||"").toUpperCase(),sourceId=String(w.source_id||""),now=nowSeconds();
 if(sourceId&&(sourceType==="ECR"||sourceType==="QUALITY"))await removeSourceFiles(db,context,sourceType,sourceId);
 const statements:any[]=[];if(sourceId&&sourceType==="ECR")statements.push(db.prepare("DELETE FROM design_change_requests WHERE id=? AND company_id=?").bind(sourceId,context.companyId));if(sourceId&&sourceType==="QUALITY")statements.push(db.prepare("DELETE FROM quality_cases WHERE id=? AND company_id=?").bind(sourceId,context.companyId));statements.push(db.prepare("DELETE FROM workflow_step_documents WHERE workflow_id=?").bind(id),db.prepare("DELETE FROM workflow_step_document_rules WHERE workflow_id=?").bind(id),db.prepare("DELETE FROM workflow_history WHERE workflow_id=?").bind(id),db.prepare("DELETE FROM workflow_instance_deliverables WHERE workflow_id=?").bind(id),db.prepare("DELETE FROM workflow_instance_steps WHERE workflow_id=?").bind(id),db.prepare("DELETE FROM workflow_instances WHERE id=?").bind(id));statements.push(db.prepare("INSERT INTO audit_logs (id,company_id,actor_user_id,action,entity_type,entity_id,detail,created_at) VALUES (?,?,?,'WORKFLOW_DRAFT_DELETED','WORKFLOW',?,?,?)").bind(crypto.randomUUID(),context.companyId,context.userId,id,JSON.stringify({sourceType,sourceId}),now));await db.batch(statements);if(sourceId&&(sourceType==="ECR"||sourceType==="QUALITY")){await clearSourceParts(context.companyId,sourceType,sourceId);await clearSourceDrawings(context.companyId,sourceType,sourceId)}return {ok:true};
}
