/* eslint-disable @typescript-eslint/no-explicit-any */
import {contextErrorResponse,requireProjectAccess,resolveRequestContext} from "../../../db/request-context";
import {createWorkflowInstance,seedDefaultWorkflowTemplates,workflowDb} from "./shared";

export async function GET(request:Request){
  const db=await workflowDb();let context;
  try{context=await resolveRequestContext(request,db);await seedDefaultWorkflowTemplates(db,context)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"Workflow를 불러오지 못했습니다."},{status:500})}
  const url=new URL(request.url),projectId=url.searchParams.get("projectId")||"",status=url.searchParams.get("status")||"",q=url.searchParams.get("q")?.trim()||"";const filters=["w.company_id=?"],binds:any[]=[context.companyId];
  if(projectId){filters.push("w.project_id=?");binds.push(projectId)}if(status){filters.push("w.status=?");binds.push(status)}if(q){filters.push("(lower(w.title) LIKE ? OR lower(w.workflow_number) LIKE ? OR lower(p.name) LIKE ?)");const like=`%${q.toLowerCase()}%`;binds.push(like,like,like)}
  const result=await db.prepare(`SELECT w.id,w.workflow_number AS workflowNumber,w.title,w.source_type AS sourceType,w.priority,w.due_date AS dueDate,w.status,w.current_step_order AS currentStepOrder,w.updated_at AS updatedAt,p.id AS projectId,p.code AS projectCode,p.name AS projectName,t.name AS templateName,tv.version AS templateVersion,u.name AS requesterName,s.name AS currentStepName,s.action_type AS currentActionType,COALESCE(dr.document_action,'NONE') AS currentDocumentAction,COALESCE(dr.document_required,0) AS currentDocumentRequired,CASE WHEN w.main_deliverable_id IS NOT NULL OR EXISTS(SELECT 1 FROM workflow_instance_deliverables wl WHERE wl.workflow_id=w.id) THEN 1 ELSE 0 END AS hasMainDocument,(SELECT COUNT(*) FROM workflow_instance_deliverables wl WHERE wl.workflow_id=w.id) AS documentCount,au.name AS currentAssigneeName,(SELECT COUNT(*) FROM workflow_instance_steps x WHERE x.workflow_id=w.id) AS stepCount,(SELECT string_agg(flow.name||'|'||flow.status,'~') FROM (SELECT name,status FROM workflow_instance_steps WHERE workflow_id=w.id ORDER BY step_order) flow) AS stepFlow,(SELECT COUNT(*) FROM workflow_history h WHERE h.workflow_id=w.id AND h.comment IS NOT NULL) AS commentCount FROM workflow_instances w JOIN projects p ON p.id=w.project_id JOIN workflow_templates t ON t.id=w.template_id JOIN workflow_template_versions tv ON tv.id=w.template_version_id JOIN users u ON u.id=w.requester_user_id LEFT JOIN workflow_instance_steps s ON s.workflow_id=w.id AND s.step_order=w.current_step_order LEFT JOIN workflow_step_document_rules dr ON dr.step_id=s.id LEFT JOIN users au ON au.id=s.assignee_user_id WHERE ${filters.join(" AND ")} ORDER BY CASE w.status WHEN 'in_progress' THEN 0 WHEN 'supplement' THEN 1 WHEN 'draft' THEN 2 ELSE 3 END,w.updated_at DESC`).bind(...binds).all();
  const projects=await db.prepare(`SELECT p.id,p.code,p.name FROM projects p WHERE p.company_id=? AND (EXISTS(SELECT 1 FROM project_members m WHERE m.project_id=p.id AND m.user_id=?) OR EXISTS(SELECT 1 FROM user_roles ur JOIN roles r ON r.id=ur.role_id WHERE ur.user_id=? AND r.code IN ('SUPER_ADMIN','ADMIN','SYSTEM_ADMIN'))) ORDER BY p.updated_at DESC`).bind(context.companyId,context.userId,context.userId).all();
  const templates=await db.prepare(`SELECT id,code,name,application_type AS applicationType,task_link_mode AS taskLinkMode,register_common_document AS registerCommonDocument,current_version AS currentVersion FROM workflow_templates WHERE company_id=? AND status='active' AND application_type='GENERAL' ORDER BY name`).bind(context.companyId).all();
  return Response.json({workflows:result.results??[],projects:projects.results??[],templates:templates.results??[]});
}

export async function POST(request:Request){const db=await workflowDb();let context;try{context=await resolveRequestContext(request,db)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"사용자 정보를 확인하지 못했습니다."},{status:500})}const input=await request.json() as any;if(!input.projectId||!input.templateId||!input.title?.trim())return Response.json({error:"프로젝트, 템플릿과 제목을 입력해 주세요."},{status:400});try{await requireProjectAccess(db,context,input.projectId,true);const template=await db.prepare("SELECT id FROM workflow_templates WHERE id=? AND company_id=? AND status='active' AND application_type='GENERAL'").bind(input.templateId,context.companyId).first();if(!template)return Response.json({error:"일반 Workflow 생성에서는 일반 템플릿만 사용할 수 있습니다. 설계변경과 품질관리는 전용 등록 화면을 이용해 주세요."},{status:400});const result=await createWorkflowInstance(db,context,{projectId:input.projectId,taskId:input.taskId||undefined,templateId:input.templateId,title:input.title,requestContent:input.requestContent,priority:input.priority,dueDate:input.dueDate,sourceType:"GENERAL",sourceId:input.sourceId,mainDeliverableId:input.mainDeliverableId,deliverableIds:Array.isArray(input.deliverableIds)?input.deliverableIds:[],assignees:input.assignees,submit:Boolean(input.submit)});return Response.json(result,{status:201})}catch(reason){return contextErrorResponse(reason)??Response.json({error:reason instanceof Error?reason.message:"Workflow를 생성하지 못했습니다."},{status:400})}}
