import { getLegacyDbCompat } from "../../../db/postgres-d1-compat";
/* eslint-disable @typescript-eslint/no-explicit-any */
import {ensureProjectDataFoundation,type RuntimeD1} from "../../../db/project-data-foundation";
import {defaultWorkflowTemplates,ensureWorkflowFoundation,normalizedSteps,type WorkflowStepDefinition} from "../../../db/workflow-foundation";
import type {RequestContext} from "../../../db/request-context";

type Prepared={bind:(...values:unknown[])=>Prepared;first:<T=Record<string,unknown>>()=>Promise<T|null>;all:<T=Record<string,unknown>>()=>Promise<{results:T[]}>;run:()=>Promise<unknown>};
export type D1={prepare:(sql:string)=>Prepared;batch:(statements:Prepared[])=>Promise<unknown>};
export async function workflowDb():Promise<D1>{const db=getLegacyDbCompat() as unknown as D1;await ensureProjectDataFoundation(db as RuntimeD1);await ensureWorkflowFoundation(db as RuntimeD1);return db}
export const parseJson=<T>(value:unknown,fallback:T):T=>{if(typeof value!=="string")return (value??fallback) as T;try{return JSON.parse(value) as T}catch{return fallback}};
export const nowSeconds=()=>Math.floor(Date.now()/1000);
export const isWorkflowManager=(context:RequestContext)=>context.systemRoles.some(role=>["SUPER_ADMIN","ADMIN","SYSTEM_ADMIN","PM"].includes(role));

export async function seedDefaultWorkflowTemplates(db:D1,context:RequestContext){
  const existing=await db.prepare("SELECT code FROM workflow_templates WHERE company_id=?").bind(context.companyId).all<{code:string}>();
  const existingCodes=new Set((existing.results??[]).map(row=>String(row.code||"").trim()).filter(Boolean));
  const now=nowSeconds(),statements:any[]=[];
  for(const item of defaultWorkflowTemplates){
    if(existingCodes.has(item.code))continue;
    const templateId=crypto.randomUUID(),versionId=crypto.randomUUID();
    const definition={description:`${item.name} 기본 템플릿`,applicationType:item.type,projectRequired:true,taskLinkMode:"optional",registerCommonDocument:Boolean(item.registerDocument),documentCategory:item.category||null,steps:item.steps};
    statements.push(db.prepare("INSERT INTO workflow_templates (id,company_id,code,name,application_type,description,project_required,task_link_mode,register_common_document,document_category,status,current_version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?, 'active',1,?,?)").bind(templateId,context.companyId,item.code,item.name,item.type,definition.description,1,"optional",item.registerDocument?1:0,item.category||null,now,now));
    statements.push(db.prepare("INSERT INTO workflow_template_versions (id,template_id,version,definition,status,published_at,created_by,created_at,updated_at) VALUES (?,?,1,?,'published',?,?,?,?)").bind(versionId,templateId,JSON.stringify(definition),now,context.userId,now,now));
  }
  if(statements.length)await db.batch(statements);
}

export async function resolveStepAssignee(db:D1,projectId:string,taskId:string|undefined,step:WorkflowStepDefinition,requesterUserId:string){
  const rule=step.assignmentRule||"manual";if(rule==="requester")return requesterUserId;
  if(rule==="project_pm"||rule==="project_pl"){const role=rule==="project_pm"?"PM":"PL";const row=await db.prepare("SELECT user_id AS userId FROM project_members WHERE project_id=? AND upper(project_role)=? ORDER BY created_at LIMIT 1").bind(projectId,role).first<{userId:string}>();return row?.userId||null}
  if(rule==="task_role"&&taskId){const task=await db.prepare("SELECT assignee_user_id AS assigneeUserId,role_code AS roleCode FROM wbs_tasks WHERE id=? AND project_id=?").bind(taskId,projectId).first<{assigneeUserId?:string;roleCode?:string}>();if(task?.assigneeUserId)return task.assigneeUserId;if(task?.roleCode){const row=await db.prepare("SELECT user_id AS userId FROM project_members WHERE project_id=? AND upper(project_role)=upper(?) ORDER BY created_at LIMIT 1").bind(projectId,task.roleCode).first<{userId:string}>();if(row?.userId)return row.userId}}
  if((rule==="project_role"||step.roleCode)&&step.roleCode){const row=await db.prepare("SELECT user_id AS userId FROM project_members WHERE project_id=? AND upper(project_role)=upper(?) ORDER BY created_at LIMIT 1").bind(projectId,step.roleCode).first<{userId:string}>();return row?.userId||null}
  return null;
}

export async function createWorkflowInstance(db:D1,context:RequestContext,input:{projectId:string;taskId?:string;templateId?:string;templateCode?:string;title:string;requestContent?:string;priority?:string;dueDate?:string;sourceType?:string;sourceId?:string;mainDeliverableId?:string;deliverableIds?:string[];assignees?:Record<string,string>;submit?:boolean}){
  const template=input.templateId?await db.prepare("SELECT * FROM workflow_templates WHERE id=? AND company_id=? AND status='active'").bind(input.templateId,context.companyId).first<any>():await db.prepare("SELECT * FROM workflow_templates WHERE code=? AND company_id=? AND status='active'").bind(input.templateCode,context.companyId).first<any>();
  if(!template)throw new Error("사용 가능한 Workflow 템플릿을 찾을 수 없습니다.");
  const version=await db.prepare("SELECT * FROM workflow_template_versions WHERE template_id=? ORDER BY version DESC LIMIT 1").bind(template.id).first<any>();if(!version)throw new Error("Workflow 템플릿 버전을 찾을 수 없습니다.");
  const definition=parseJson<any>(version.definition,{}),steps=normalizedSteps(definition.steps);if(!steps.length)throw new Error("Workflow 단계가 없습니다.");
  if(definition.taskLinkMode==="required"&&!input.taskId)throw new Error("이 Workflow는 관련 Task 연결이 필수입니다.");
  const deliverableIds=Array.from(new Set((input.deliverableIds??[]).map(String).filter(Boolean)));if(input.mainDeliverableId&&!deliverableIds.includes(input.mainDeliverableId))deliverableIds.unshift(input.mainDeliverableId);for(const deliverableId of deliverableIds){const linked=await db.prepare("SELECT id FROM deliverables WHERE id=? AND project_id=?").bind(deliverableId,input.projectId).first();if(!linked)throw new Error("선택한 문서·산출물 중 프로젝트에 속하지 않은 항목이 있습니다.")}const primaryDeliverableId=deliverableIds[0]||null;
  const now=nowSeconds(),id=crypto.randomUUID(),seq=await db.prepare("SELECT COUNT(*) AS count FROM workflow_instances WHERE company_id=?").bind(context.companyId).first<{count:number}>(),number=`WF-${new Date().toISOString().slice(0,4)}-${String(Number(seq?.count||0)+1).padStart(4,"0")}`;
  const assignments:Record<number,string|null>={};for(let index=0;index<steps.length;index++)assignments[index]=input.assignees?.[String(index)]||await resolveStepAssignee(db,input.projectId,input.taskId,steps[index],context.userId);
  const assignedUserIds=Array.from(new Set(Object.values(assignments).filter((value):value is string=>Boolean(value))));
  if(assignedUserIds.length){const placeholders=assignedUserIds.map(()=>"?").join(",");const validUsers=await db.prepare(`SELECT id FROM users WHERE company_id=? AND status='active' AND id IN (${placeholders})`).bind(context.companyId,...assignedUserIds).all<{id:string}>();if((validUsers.results??[]).length!==assignedUserIds.length)throw new Error("담당자는 같은 회사의 활성 사용자만 선택할 수 있습니다.")}
  const firstPending=steps.findIndex((step,index)=>index>0&&step.actionType!=="REFERENCE"),effectiveSubmit=Boolean(input.submit);if(effectiveSubmit&&steps.slice(Math.max(1,firstPending)).some((step,index)=>step.actionType!=="REFERENCE"&&!assignments[index+Math.max(1,firstPending)]))throw new Error("미배정 단계의 실제 담당자를 모두 지정해 주세요.");
  const status=effectiveSubmit?"in_progress":"draft",current=effectiveSubmit?Math.max(1,firstPending):0,statements:any[]=[db.prepare("INSERT INTO workflow_instances (id,company_id,project_id,task_id,template_id,template_version_id,workflow_number,title,request_content,source_type,source_id,priority,due_date,status,current_step_order,requester_user_id,main_deliverable_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,context.companyId,input.projectId,input.taskId||null,template.id,version.id,number,input.title.trim(),input.requestContent?.trim()||null,input.sourceType||template.application_type||"GENERAL",input.sourceId||null,input.priority||"normal",input.dueDate||null,status,current,context.userId,primaryDeliverableId,now,now)];
  for(let index=0;index<steps.length;index++){const step=steps[index],stepId=crypto.randomUUID(),stepStatus=index===0?"completed":effectiveSubmit&&index===current?"active":"waiting";statements.push(db.prepare("INSERT INTO workflow_instance_steps (id,workflow_id,step_order,name,action_type,role_code,assignment_rule,due_days,comment_required,attachment_required,assignee_user_id,status,started_at,completed_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(stepId,id,index,step.name,step.actionType,step.roleCode||null,step.assignmentRule||"manual",Number(step.dueDays||0),step.commentRequired?1:0,step.attachmentRequired?1:0,assignments[index],stepStatus,stepStatus==="active"?now:null,stepStatus==="completed"?now:null,now,now));statements.push(db.prepare("INSERT INTO workflow_step_document_rules (step_id,workflow_id,document_action,document_required,created_at,updated_at) VALUES (?,?,?,?,?,?)").bind(stepId,id,step.documentAction||"NONE",step.documentRequired?1:0,now,now))}
  deliverableIds.forEach((deliverableId,index)=>statements.push(db.prepare("INSERT INTO workflow_instance_deliverables (workflow_id,deliverable_id,sort_order,created_at) VALUES (?,?,?,?)").bind(id,deliverableId,index,now)));
  statements.push(db.prepare("INSERT INTO workflow_history (id,workflow_id,actor_user_id,action,previous_status,next_status,comment,created_at) VALUES (?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),id,context.userId,effectiveSubmit?"SUBMIT":"SAVE_DRAFT",null,status,input.requestContent?.trim()||null,now));await db.batch(statements);return {id,number,status,documentCount:deliverableIds.length};
}

export async function workflowDetail(db:D1,context:RequestContext,id:string){
  const workflow=await db.prepare(`SELECT w.*,p.code AS projectCode,p.name AS projectName,t.name AS templateName,t.document_category AS templateDocumentCategory,u.name AS requesterName,wt.name AS taskName,wt.wbs_code AS taskCode,d.name AS mainDocumentName,d.category AS mainDocumentCategory,d.version AS mainDocumentVersion,pd.title AS officialDocumentTitle FROM workflow_instances w JOIN projects p ON p.id=w.project_id JOIN workflow_templates t ON t.id=w.template_id JOIN users u ON u.id=w.requester_user_id LEFT JOIN wbs_tasks wt ON wt.id=w.task_id LEFT JOIN deliverables d ON d.id=w.main_deliverable_id LEFT JOIN project_documents pd ON pd.id=w.official_document_id WHERE w.id=? AND w.company_id=?`).bind(id,context.companyId).first<any>();if(!workflow)return null;
  const steps=await db.prepare(`SELECT s.*,COALESCE(r.document_action,'NONE') AS document_action,COALESCE(r.document_required,0) AS document_required,u.name AS assigneeName FROM workflow_instance_steps s LEFT JOIN workflow_step_document_rules r ON r.step_id=s.id LEFT JOIN users u ON u.id=s.assignee_user_id WHERE s.workflow_id=? ORDER BY s.step_order`).bind(id).all();
  const history=await db.prepare(`SELECT h.*,u.name AS actorName,s.name AS stepName FROM workflow_history h JOIN users u ON u.id=h.actor_user_id LEFT JOIN workflow_instance_steps s ON s.id=h.step_id WHERE h.workflow_id=? ORDER BY h.created_at,h.id`).bind(id).all();
  const documents=await db.prepare(`SELECT wd.id,wd.step_id AS stepId,wd.document_action AS documentAction,wd.change_reason AS changeReason,wd.created_at AS createdAt,d.id AS deliverableId,d.name,d.category,v.id AS versionId,v.revision,v.file_name AS fileName,v.file_size AS fileSize,u.name AS createdBy FROM workflow_step_documents wd JOIN deliverables d ON d.id=wd.deliverable_id JOIN deliverable_versions v ON v.id=wd.version_id LEFT JOIN users u ON u.id=wd.created_by WHERE wd.workflow_id=? ORDER BY wd.created_at DESC`).bind(id).all();
  let linkedDocuments=(await db.prepare(`SELECT d.id AS deliverableId,d.name,d.category,d.status,d.version,COALESCE(d.document_kind,'document') AS documentKind,d.drawing_code AS drawingCode,l.sort_order AS sortOrder,v.id AS latestVersionId,v.revision AS latestRevision,v.file_name AS latestFileName,v.file_size AS latestFileSize FROM workflow_instance_deliverables l JOIN deliverables d ON d.id=l.deliverable_id LEFT JOIN deliverable_versions v ON v.id=(SELECT x.id FROM deliverable_versions x WHERE x.deliverable_id=d.id AND x.deleted_at IS NULL ORDER BY x.revision DESC LIMIT 1) WHERE l.workflow_id=? ORDER BY l.sort_order`).bind(id).all()).results??[];if(!linkedDocuments.length&&workflow.main_deliverable_id){const legacy=await db.prepare(`SELECT d.id AS deliverableId,d.name,d.category,d.status,d.version,COALESCE(d.document_kind,'document') AS documentKind,d.drawing_code AS drawingCode,0 AS sortOrder,v.id AS latestVersionId,v.revision AS latestRevision,v.file_name AS latestFileName,v.file_size AS latestFileSize FROM deliverables d LEFT JOIN deliverable_versions v ON v.id=(SELECT x.id FROM deliverable_versions x WHERE x.deliverable_id=d.id AND x.deleted_at IS NULL ORDER BY x.revision DESC LIMIT 1) WHERE d.id=? AND d.project_id=?`).bind(workflow.main_deliverable_id,workflow.project_id).first<any>();if(legacy)linkedDocuments=[legacy]}
  const current=(steps.results??[]).find((step:any)=>Number(step.step_order)===Number(workflow.current_step_order));const isAdmin=context.systemRoles.some(role=>["SUPER_ADMIN","ADMIN","SYSTEM_ADMIN"].includes(role));
  return {workflow,steps:steps.results??[],history:history.results??[],documents:documents.results??[],linkedDocuments,permissions:{viewerUserId:context.userId,canAct:Boolean(isAdmin||(workflow.status==="in_progress"&&current?.assignee_user_id===context.userId)||(["draft","supplement","recalled"].includes(workflow.status)&&workflow.requester_user_id===context.userId)),isRequester:workflow.requester_user_id===context.userId,isAdmin}};
}
