import { getLegacyDbCompat } from "../../../../db/postgres-d1-compat";
import {ensureProjectDataFoundation,type RuntimeD1} from "../../../../db/project-data-foundation";
/* eslint-disable @typescript-eslint/no-explicit-any */
import {contextErrorResponse,resolveRequestContext} from "../../../../db/request-context";

async function runtimeDb():Promise<RuntimeD1>{return getLegacyDbCompat() as RuntimeD1;}
async function ensure(db:RuntimeD1){await ensureProjectDataFoundation(db);await db.batch([db.prepare("CREATE TABLE IF NOT EXISTS system_settings (company_id text NOT NULL,setting_key text NOT NULL,value text NOT NULL,updated_by text,updated_at integer NOT NULL,PRIMARY KEY(company_id,setting_key))"),db.prepare("CREATE INDEX IF NOT EXISTS audit_logs_company_created_idx ON audit_logs(company_id,created_at DESC)")]);}
const defaults:Record<string,unknown>={NOTIFICATION_POLICY:{delayedTask:true,approval:true,deliverable:true,issueSeverity:"high",dailyDigest:false,digestHour:"09:00"},AI_GOVERNANCE:{enabled:true,provider:"OPENAI",model:"configured-by-server",requireEvidence:true,requireApproval:true,allowOfficialDataWrite:false},FILE_INTEGRATION:{provider:"LOCAL",googleDriveEnabled:false,sharePointEnabled:false,conversionEnabled:true,maxUploadMb:100}};

export async function GET(request:Request){const db=await runtimeDb();await ensure(db);let context;try{context=await resolveRequestContext(request,db)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"사용자 정보를 확인하지 못했습니다."},{status:500})}const [company,settings,audit]=await Promise.all([db.prepare("SELECT id,name,code,status,created_at AS createdAt,updated_at AS updatedAt FROM companies WHERE id=?").bind(context.companyId).first(),db.prepare("SELECT setting_key AS settingKey,value,updated_by AS updatedBy,updated_at AS updatedAt FROM system_settings WHERE company_id=?").bind(context.companyId).all(),db.prepare("SELECT id,actor_user_id AS actorUserId,action,entity_type AS entityType,entity_id AS entityId,detail,created_at AS createdAt FROM audit_logs WHERE company_id=? ORDER BY created_at DESC LIMIT 100").bind(context.companyId).all()]);const values={...defaults};for(const row of (settings.results??[]) as any[]){try{values[row.settingKey]=JSON.parse(row.value)}catch{values[row.settingKey]=row.value}}return Response.json({company,settings:values,audit:(audit.results??[]).map((row:any)=>{try{return {...row,detail:row.detail?JSON.parse(row.detail):null}}catch{return row}})});}

export async function PUT(request:Request){const db=await runtimeDb();await ensure(db);let context;try{context=await resolveRequestContext(request,db)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"사용자 정보를 확인하지 못했습니다."},{status:500})}if(!context.systemRoles.some(role=>["SUPER_ADMIN","ADMIN","SYSTEM_ADMIN"].includes(role)))return Response.json({error:"시스템 관리자만 설정을 변경할 수 있습니다."},{status:403});const input=await request.json() as {section?:string;value?:Record<string,unknown>};const now=Math.floor(Date.now()/1000);if(!input.section||!input.value)return Response.json({error:"저장할 설정을 지정해 주세요."},{status:400});if(input.section==="COMPANY"){const name=String(input.value.name||"").trim(),code=String(input.value.code||"").trim();if(!name||!code)return Response.json({error:"회사명과 회사 코드는 필수입니다."},{status:400});await db.batch([db.prepare("UPDATE companies SET name=?,code=?,status=?,updated_at=? WHERE id=?").bind(name,code,String(input.value.status||"active"),now,context.companyId),db.prepare("INSERT INTO audit_logs (id,company_id,actor_user_id,action,entity_type,entity_id,detail,created_at) VALUES (?,?,?,'COMPANY_SETTINGS_UPDATED','COMPANY',?,?,?)").bind(crypto.randomUUID(),context.companyId,context.userId,context.companyId,JSON.stringify(input.value),now)]);return Response.json({ok:true,value:input.value});}if(!(input.section in defaults))return Response.json({error:"지원하지 않는 설정입니다."},{status:400});await db.batch([db.prepare("INSERT INTO system_settings (company_id,setting_key,value,updated_by,updated_at) VALUES (?,?,?,?,?) ON CONFLICT(company_id,setting_key) DO UPDATE SET value=excluded.value,updated_by=excluded.updated_by,updated_at=excluded.updated_at").bind(context.companyId,input.section,JSON.stringify(input.value),context.userId,now),db.prepare("INSERT INTO audit_logs (id,company_id,actor_user_id,action,entity_type,entity_id,detail,created_at) VALUES (?,?,?,'SYSTEM_SETTING_UPDATED','SETTING',?,?,?)").bind(crypto.randomUUID(),context.companyId,context.userId,input.section,JSON.stringify({section:input.section}),now)]);return Response.json({ok:true,value:input.value});}
