/* eslint-disable @typescript-eslint/no-explicit-any */
import {contextErrorResponse,requireProjectAccess,resolveRequestContext} from "../../../db/request-context";
import {clearSourceDrawings,getSourceDrawingsMap,getSourcePrimaryDrawing,requireWorkflowDrawing,setSourcePrimaryDrawing} from "../../../services/workflow-drawing-service";
import {clearSourceParts,getSourcePrimaryPart,getSourcePartsMap,requireWorkflowPart,setSourcePrimaryPart} from "../../../services/workflow-part-service";
import {deleteDraftWorkflow,updateDraftWorkflow} from "../workflows/draft-management";
import {readSourceUpload,reassignSourceAttachments,removeSourceFiles,syncSourceAttachments} from "../workflows/source-files";
import {createWorkflowInstance,nowSeconds,seedDefaultWorkflowTemplates,workflowDb} from "../workflows/shared";

const partFields=(part:any)=>part?{partId:part.id,partNumber:part.partNumber,partName:part.name,partRevision:part.revision,partType:part.partType,partSpec:part.spec}:{};
const drawingFields=(drawing:any)=>drawing?{drawingId:drawing.id,drawingCode:drawing.drawingCode,drawingName:drawing.name,drawingType:drawing.drawingType,drawingProjectId:drawing.projectId,drawingProjectCode:drawing.projectCode,drawingProjectName:drawing.projectName,drawingTaskId:drawing.taskId,drawingTaskCode:drawing.taskCode,drawingTaskName:drawing.taskName}:{};
const isAdmin=(context:any)=>context.systemRoles.some((role:string)=>["SUPER_ADMIN","ADMIN","SYSTEM_ADMIN"].includes(role));

export async function GET(request:Request){
 const db=await workflowDb();let context;try{context=await resolveRequestContext(request,db);await seedDefaultWorkflowTemplates(db,context)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"품질문제를 불러오지 못했습니다."},{status:500})}
 const url=new URL(request.url),id=url.searchParams.get("id")||"",projectId=url.searchParams.get("projectId")||"";
 if(id){const item=await db.prepare("SELECT q.id,q.project_id AS projectId,q.task_id AS taskId,q.quality_number AS qualityNumber,q.title,q.occurred_on AS occurredOn,q.issue_type AS issueType,q.severity,q.description,q.root_cause AS rootCause,q.corrective_action AS correctiveAction,q.effectiveness_check AS effectivenessCheck,q.status,q.workflow_id AS workflowId,q.owner_user_id AS ownerUserId,COALESCE(w.due_date,q.due_date) AS dueDate FROM quality_cases q LEFT JOIN workflow_instances w ON w.id=q.workflow_id WHERE q.id=? AND q.company_id=?").bind(id,context.companyId).first<any>();if(!item)return Response.json({error:"품질문제를 찾을 수 없습니다."},{status:404});if(item.projectId){try{await requireProjectAccess(db,context,item.projectId)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"품질문제 접근 권한이 없습니다."},{status:403})}}const [attachments,part,drawing]=await Promise.all([db.prepare("SELECT id,file_name AS fileName,file_size AS fileSize,content_type AS contentType FROM workflow_source_attachments WHERE company_id=? AND source_type='QUALITY' AND source_id=? ORDER BY created_at,id").bind(context.companyId,id).all(),getSourcePrimaryPart(context.companyId,"QUALITY",id),getSourcePrimaryDrawing(context.companyId,"QUALITY",id)]);return Response.json({item:{...item,...partFields(part),...drawingFields(drawing)},part,drawing,attachments:attachments.results??[]})}
 const rows=await db.prepare(`SELECT q.id,q.quality_number AS qualityNumber,q.title,q.occurred_on AS occurredOn,q.issue_type AS issueType,q.severity,q.status,q.workflow_id AS workflowId,p.id AS projectId,p.code AS projectCode,p.name AS projectName,w.status AS workflowStatus,w.current_step_order AS currentStepOrder,COALESCE(w.due_date,q.due_date) AS dueDate,cs.name AS currentStepName,cu.name AS currentAssigneeName,(SELECT COUNT(*) FROM workflow_instance_steps x WHERE x.workflow_id=w.id) AS stepCount,(SELECT string_agg(flow.name||'|'||flow.status,'~') FROM (SELECT name,status FROM workflow_instance_steps WHERE workflow_id=w.id ORDER BY step_order) flow) AS stepFlow FROM quality_cases q LEFT JOIN projects p ON p.id=q.project_id LEFT JOIN workflow_instances w ON w.id=q.workflow_id LEFT JOIN workflow_instance_steps cs ON cs.workflow_id=w.id AND cs.step_order=w.current_step_order LEFT JOIN users cu ON cu.id=cs.assignee_user_id WHERE q.company_id=? ${projectId?"AND q.project_id=?":""} ORDER BY q.updated_at DESC`).bind(context.companyId,...(projectId?[projectId]:[])).all();const items=(rows.results??[]) as any[],ids=items.map(item=>String(item.id)),[partsMap,drawingsMap]=await Promise.all([getSourcePartsMap(context.companyId,"QUALITY",ids),getSourceDrawingsMap(context.companyId,"QUALITY",ids)]);return Response.json({items:items.map(item=>({...item,...partFields(partsMap.get(String(item.id))?.[0]),...drawingFields(drawingsMap.get(String(item.id))?.[0])}))});
}

export async function POST(request:Request){
 const db=await workflowDb();let context;try{context=await resolveRequestContext(request,db);await seedDefaultWorkflowTemplates(db,context)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"사용자 정보를 확인하지 못했습니다."},{status:500})}
 let upload;try{upload=await readSourceUpload(request)}catch(reason){return Response.json({error:reason instanceof Error?reason.message:"등록 정보를 확인하지 못했습니다."},{status:400})}const {input,files}=upload;if(!input.title?.trim())return Response.json({error:"문제 제목을 입력해 주세요."},{status:400});const projectId=String(input.projectId||"").trim()||null;if(projectId){try{await requireProjectAccess(db,context,projectId,true)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"프로젝트 접근 권한이 없습니다."},{status:403})}}
 let part:any=null;if(input.partId){try{part=await requireWorkflowPart(context.companyId,String(input.partId))}catch(reason){return Response.json({error:reason instanceof Error?reason.message:"관련 PART를 확인하지 못했습니다."},{status:400})}}
 let drawing:any=null;if(input.drawingId){try{drawing=await requireWorkflowDrawing(context.companyId,String(input.drawingId))}catch(reason){return Response.json({error:reason instanceof Error?reason.message:"관련 도면을 확인하지 못했습니다."},{status:400})}}
 const taskId=projectId&&drawing?.projectId===projectId?drawing.taskId||null:null,now=nowSeconds(),id=crypto.randomUUID(),seq=await db.prepare("SELECT COUNT(*) AS count FROM quality_cases WHERE company_id=?").bind(context.companyId).first<{count:number}>(),number=`QMS-${new Date().toISOString().slice(0,4)}-${String(Number(seq?.count||0)+1).padStart(4,"0")}`;await db.prepare("INSERT INTO quality_cases (id,company_id,project_id,task_id,quality_number,title,occurred_on,issue_type,severity,description,root_cause,corrective_action,effectiveness_check,due_date,owner_user_id,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?, 'draft',?,?)").bind(id,context.companyId,projectId,taskId,number,input.title.trim(),input.occurredOn||null,input.issueType||null,input.severity||"medium",input.description||null,input.rootCause||null,input.correctiveAction||null,input.effectivenessCheck||null,input.dueDate||null,input.ownerUserId||context.userId,now,now).run();
 try{if(part)await setSourcePrimaryPart(context.companyId,"QUALITY",id,part.id);if(drawing)await setSourcePrimaryDrawing(context.companyId,"QUALITY",id,drawing)}catch(reason){await clearSourceParts(context.companyId,"QUALITY",id);await clearSourceDrawings(context.companyId,"QUALITY",id);await db.prepare("DELETE FROM quality_cases WHERE id=? AND company_id=?").bind(id,context.companyId).run();return Response.json({error:reason instanceof Error?reason.message:"관련 대상 연결을 저장하지 못했습니다."},{status:500})}
 let workflow:any=null;if(projectId){try{workflow=await createWorkflowInstance(db,context,{projectId,taskId:taskId||undefined,templateCode:"QUALITY_ACTION",title:`[${number}] ${input.title.trim()}`,requestContent:input.description,priority:input.severity==="critical"?"urgent":"normal",dueDate:input.dueDate||undefined,sourceType:"QUALITY",sourceId:id,assignees:input.assignees,submit:Boolean(input.submit)});await db.prepare("UPDATE quality_cases SET workflow_id=?,status=?,updated_at=? WHERE id=?").bind(workflow.id,workflow.status,now,id).run()}catch(reason){await clearSourceParts(context.companyId,"QUALITY",id);await clearSourceDrawings(context.companyId,"QUALITY",id);await db.prepare("DELETE FROM quality_cases WHERE id=? AND company_id=?").bind(id,context.companyId).run();return Response.json({error:reason instanceof Error?reason.message:"품질 Workflow를 생성하지 못했습니다."},{status:400})}}
 await syncSourceAttachments(db,context,{projectId,sourceType:"QUALITY",sourceId:id,files});return Response.json({id,qualityNumber:number,workflowId:workflow?.id||null,standalone:!projectId,part,drawing,workflow},{status:201});
}

export async function PATCH(request:Request){
 const db=await workflowDb();let context;try{context=await resolveRequestContext(request,db)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"사용자 정보를 확인하지 못했습니다."},{status:500})}
 let upload;try{upload=await readSourceUpload(request)}catch(reason){return Response.json({error:reason instanceof Error?reason.message:"수정 정보를 확인하지 못했습니다."},{status:400})}const {input,files}=upload;if(!input.id)return Response.json({error:"수정할 품질문제가 필요합니다."},{status:400});if(!String(input.title||"").trim())return Response.json({error:"문제 제목을 입력해 주세요."},{status:400});
 const current=await db.prepare("SELECT id,project_id AS projectId,quality_number AS qualityNumber,workflow_id AS workflowId,owner_user_id AS ownerUserId,status FROM quality_cases WHERE id=? AND company_id=?").bind(input.id,context.companyId).first<any>();if(!current)return Response.json({error:"품질문제를 찾을 수 없습니다."},{status:404});const projectId=String(input.projectId||"").trim()||null;if(current.workflowId&&projectId!==current.projectId)return Response.json({error:"Workflow가 생성된 품질문제는 프로젝트를 변경하거나 해제할 수 없습니다."},{status:409});if(projectId){try{await requireProjectAccess(db,context,projectId,true)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"품질문제 수정 권한이 없습니다."},{status:403})}}else if(current.ownerUserId!==context.userId&&!isAdmin(context))return Response.json({error:"등록자만 프로젝트 미연결 품질문제를 수정할 수 있습니다."},{status:403});
 let part:any=null;if(input.partId){try{part=await requireWorkflowPart(context.companyId,String(input.partId))}catch(reason){return Response.json({error:reason instanceof Error?reason.message:"관련 PART를 확인하지 못했습니다."},{status:400})}}
 let drawing:any=null;if(input.drawingId){try{drawing=await requireWorkflowDrawing(context.companyId,String(input.drawingId))}catch(reason){return Response.json({error:reason instanceof Error?reason.message:"관련 도면을 확인하지 못했습니다."},{status:400})}}
 const taskId=projectId&&drawing?.projectId===projectId?drawing.taskId||null:null,now=nowSeconds(),title=String(input.title||"").trim();let workflow:any=null;if(current.workflowId){await updateDraftWorkflow(db,context,current.workflowId,{title:`[${current.qualityNumber}] ${title}`,taskId:taskId||"",requestContent:input.description,priority:input.severity==="critical"?"urgent":"normal",dueDate:input.dueDate,assignees:input.assignees});workflow={id:current.workflowId,status:"draft"}}else if(projectId){workflow=await createWorkflowInstance(db,context,{projectId,taskId:taskId||undefined,templateCode:"QUALITY_ACTION",title:`[${current.qualityNumber}] ${title}`,requestContent:input.description,priority:input.severity==="critical"?"urgent":"normal",dueDate:input.dueDate||undefined,sourceType:"QUALITY",sourceId:input.id,assignees:input.assignees,submit:Boolean(input.submit)})}
 await db.prepare("UPDATE quality_cases SET project_id=?,task_id=?,workflow_id=COALESCE(?,workflow_id),status=?,title=?,occurred_on=?,issue_type=?,severity=?,description=?,root_cause=?,corrective_action=?,effectiveness_check=?,due_date=?,updated_at=? WHERE id=?").bind(projectId,taskId,workflow?.id||null,workflow?.status||current.status||"draft",title,input.occurredOn||null,input.issueType||null,input.severity||"medium",input.description||null,input.rootCause||null,input.correctiveAction||null,input.effectivenessCheck||null,input.dueDate||null,now,input.id).run();if(part)await setSourcePrimaryPart(context.companyId,"QUALITY",input.id,part.id);else await clearSourceParts(context.companyId,"QUALITY",input.id);if(drawing)await setSourcePrimaryDrawing(context.companyId,"QUALITY",input.id,drawing);else await clearSourceDrawings(context.companyId,"QUALITY",input.id);await reassignSourceAttachments(db,context,"QUALITY",input.id,projectId);await syncSourceAttachments(db,context,{projectId,sourceType:"QUALITY",sourceId:input.id,files,removeAttachmentIds:input.removeAttachmentIds});return Response.json({ok:true,id:input.id,workflowId:workflow?.id||current.workflowId||null,standalone:!projectId,part,drawing});
}

export async function DELETE(request:Request){const db=await workflowDb();let context;try{context=await resolveRequestContext(request,db);const id=new URL(request.url).searchParams.get("id")||"",item=await db.prepare("SELECT project_id AS projectId,workflow_id AS workflowId,owner_user_id AS ownerUserId FROM quality_cases WHERE id=? AND company_id=?").bind(id,context.companyId).first<any>();if(!item)return Response.json({error:"품질문제를 찾을 수 없습니다."},{status:404});if(item.workflowId)return Response.json(await deleteDraftWorkflow(db,context,item.workflowId));if(item.projectId){try{await requireProjectAccess(db,context,item.projectId,true)}catch(reason){return contextErrorResponse(reason)??Response.json({error:"품질문제 삭제 권한이 없습니다."},{status:403})}}else if(item.ownerUserId!==context.userId&&!isAdmin(context))return Response.json({error:"등록자만 프로젝트 미연결 품질문제를 삭제할 수 있습니다."},{status:403});await removeSourceFiles(db,context,"QUALITY",id);await clearSourceParts(context.companyId,"QUALITY",id);await clearSourceDrawings(context.companyId,"QUALITY",id);await db.prepare("DELETE FROM quality_cases WHERE id=? AND company_id=?").bind(id,context.companyId).run();return Response.json({ok:true})}catch(reason){return contextErrorResponse(reason)??Response.json({error:reason instanceof Error?reason.message:"품질문제를 삭제하지 못했습니다."},{status:400})}}
