import { getLegacyDbCompat } from "../../../../db/postgres-d1-compat";
/* eslint-disable @typescript-eslint/no-explicit-any */
import {contextErrorResponse,resolveRequestContext} from "../../../../db/request-context";

type D1={prepare:(sql:string)=>any;batch:(statements:any[])=>Promise<unknown>};
async function runtimeDb():Promise<D1>{return getLegacyDbCompat() as D1;}
const now=()=>Math.floor(Date.now()/1000);
const DEFAULT_CATEGORIES=[["PURCHASED","구매품"],["MACHINED","가공품"],["INJECTION","사출품"],["SHEET_METAL","판금품"],["ELECTRICAL","전장품"],["MECHANICAL","기구품"],["RAW_MATERIAL","원자재"],["CONSUMABLE","소모품"],["OTHER","기타"]] as const;

async function ensureTables(db:D1){await db.batch([
  db.prepare(`CREATE TABLE IF NOT EXISTS part_categories (id TEXT PRIMARY KEY NOT NULL,company_id TEXT NOT NULL,code TEXT NOT NULL,name TEXT NOT NULL,is_active INTEGER NOT NULL DEFAULT 1,sort_order INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)`),
  db.prepare("CREATE UNIQUE INDEX IF NOT EXISTS part_categories_company_code_uq ON part_categories(company_id,code)"),
  db.prepare(`CREATE TABLE IF NOT EXISTS part_category_links (company_id TEXT NOT NULL,part_id TEXT PRIMARY KEY NOT NULL,category_id TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)`),
  db.prepare(`CREATE TABLE IF NOT EXISTS part_number_settings (company_id TEXT PRIMARY KEY NOT NULL,prefix TEXT NOT NULL DEFAULT 'P',separator TEXT NOT NULL DEFAULT '-',digits INTEGER NOT NULL DEFAULT 6,next_sequence INTEGER NOT NULL DEFAULT 1,allow_manual INTEGER NOT NULL DEFAULT 1,updated_at INTEGER NOT NULL)`),
]);}
async function ensureDefaults(db:D1,companyId:string){const t=now();const count=await db.prepare("SELECT COUNT(*) AS count FROM part_categories WHERE company_id=?").bind(companyId).first<{count:number}>();if(Number(count?.count||0)===0)await db.batch(DEFAULT_CATEGORIES.map(([code,name],index)=>db.prepare("INSERT INTO part_categories (id,company_id,code,name,is_active,sort_order,created_at,updated_at) VALUES (?,?,?,?,1,?,?,?)").bind(crypto.randomUUID(),companyId,code,name,index,t,t)));const setting=await db.prepare("SELECT company_id FROM part_number_settings WHERE company_id=?").bind(companyId).first();if(!setting)await db.prepare("INSERT INTO part_number_settings (company_id,prefix,separator,digits,next_sequence,allow_manual,updated_at) VALUES (?,'P','-',6,1,1,?)").bind(companyId,t).run();}
async function contextFor(request:Request,db:D1){try{return await resolveRequestContext(request,db)}catch(reason){throw contextErrorResponse(reason)??Response.json({error:"로그인이 필요합니다."},{status:401})}}

export async function GET(request:Request){const db=await runtimeDb();await ensureTables(db);let context;try{context=await contextFor(request,db)}catch(response){return response as Response}await ensureDefaults(db,context.companyId);const [categories,setting]=await Promise.all([db.prepare("SELECT id,code,name,is_active AS isActive,sort_order AS sortOrder FROM part_categories WHERE company_id=? ORDER BY sort_order,name").bind(context.companyId).all(),db.prepare("SELECT prefix,separator,digits,next_sequence AS nextSequence,allow_manual AS allowManual FROM part_number_settings WHERE company_id=?").bind(context.companyId).first()]);return Response.json({categories:categories.results??[],numberSetting:setting});}

export async function POST(request:Request){const db=await runtimeDb();await ensureTables(db);let context;try{context=await contextFor(request,db)}catch(response){return response as Response}await ensureDefaults(db,context.companyId);const input=await request.json() as any;const code=String(input.code||"").trim().toUpperCase().replace(/\s+/g,"_");const name=String(input.name||"").trim();if(!code||!name)return Response.json({error:"부품 유형 코드와 이름을 입력해 주세요."},{status:400});try{await db.prepare("INSERT INTO part_categories (id,company_id,code,name,is_active,sort_order,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),context.companyId,code,name,input.isActive===false?0:1,Math.max(0,Number(input.sortOrder)||0),now(),now()).run()}catch{return Response.json({error:"이미 사용 중인 부품 유형 코드입니다."},{status:409})}return Response.json({ok:true},{status:201});}

export async function PATCH(request:Request){const db=await runtimeDb();await ensureTables(db);let context;try{context=await contextFor(request,db)}catch(response){return response as Response}await ensureDefaults(db,context.companyId);const input=await request.json() as any;if(input.entity==="number-setting"){const prefix=String(input.prefix??"P").trim(),separator=String(input.separator??"-").trim(),digits=Math.max(3,Math.min(12,Number(input.digits)||6)),nextSequence=Math.max(1,Number(input.nextSequence)||1),allowManual=input.allowManual===false||input.allowManual===0?0:1;await db.prepare("UPDATE part_number_settings SET prefix=?,separator=?,digits=?,next_sequence=?,allow_manual=?,updated_at=? WHERE company_id=?").bind(prefix,separator,digits,nextSequence,allowManual,now(),context.companyId).run();return Response.json({ok:true});}const id=String(input.id||"");if(!id)return Response.json({error:"수정할 부품 유형을 확인해 주세요."},{status:400});const code=String(input.code||"").trim().toUpperCase().replace(/\s+/g,"_"),name=String(input.name||"").trim();if(!code||!name)return Response.json({error:"부품 유형 코드와 이름을 입력해 주세요."},{status:400});try{await db.prepare("UPDATE part_categories SET code=?,name=?,is_active=?,sort_order=?,updated_at=? WHERE company_id=? AND id=?").bind(code,name,input.isActive===false||input.isActive===0?0:1,Math.max(0,Number(input.sortOrder)||0),now(),context.companyId,id).run()}catch{return Response.json({error:"이미 사용 중인 부품 유형 코드입니다."},{status:409})}return Response.json({ok:true});}

export async function DELETE(request:Request){const db=await runtimeDb();await ensureTables(db);let context;try{context=await contextFor(request,db)}catch(response){return response as Response}const input=await request.json() as any,id=String(input.id||"");if(!id)return Response.json({error:"삭제할 부품 유형을 확인해 주세요."},{status:400});const used=await db.prepare("SELECT COUNT(*) AS count FROM part_category_links WHERE company_id=? AND category_id=?").bind(context.companyId,id).first<{count:number}>();if(Number(used?.count||0)>0){await db.prepare("UPDATE part_categories SET is_active=0,updated_at=? WHERE company_id=? AND id=?").bind(now(),context.companyId,id).run();return Response.json({ok:true,deactivated:true});}await db.prepare("DELETE FROM part_categories WHERE company_id=? AND id=?").bind(context.companyId,id).run();return Response.json({ok:true,deleted:true});}
